(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	satellite4 - satellite
	instrument9 - instrument
	satellite5 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite6 - satellite
	instrument13 - instrument
	satellite7 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite8 - satellite
	instrument16 - instrument
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	infrared5 - mode
	thermograph2 - mode
	image1 - mode
	thermograph4 - mode
	thermograph0 - mode
	thermograph3 - mode
	GroundStation110 - direction
	GroundStation175 - direction
	GroundStation92 - direction
	GroundStation5 - direction
	GroundStation186 - direction
	GroundStation198 - direction
	GroundStation200 - direction
	GroundStation31 - direction
	Star56 - direction
	GroundStation60 - direction
	GroundStation195 - direction
	GroundStation104 - direction
	Star20 - direction
	Star136 - direction
	Star46 - direction
	Star180 - direction
	Star70 - direction
	Star121 - direction
	GroundStation42 - direction
	GroundStation41 - direction
	GroundStation123 - direction
	Star52 - direction
	Star95 - direction
	Star160 - direction
	GroundStation26 - direction
	GroundStation151 - direction
	Star90 - direction
	GroundStation57 - direction
	Star139 - direction
	GroundStation23 - direction
	GroundStation15 - direction
	GroundStation150 - direction
	Star137 - direction
	GroundStation111 - direction
	Star167 - direction
	GroundStation117 - direction
	Star8 - direction
	Star189 - direction
	GroundStation9 - direction
	GroundStation54 - direction
	GroundStation14 - direction
	GroundStation96 - direction
	GroundStation178 - direction
	Star84 - direction
	Star78 - direction
	GroundStation66 - direction
	Star182 - direction
	Star105 - direction
	GroundStation143 - direction
	GroundStation134 - direction
	GroundStation146 - direction
	Star68 - direction
	Star49 - direction
	GroundStation91 - direction
	Star0 - direction
	GroundStation199 - direction
	Star51 - direction
	GroundStation50 - direction
	Star141 - direction
	GroundStation147 - direction
	Star28 - direction
	Star109 - direction
	Star19 - direction
	GroundStation34 - direction
	Star67 - direction
	Star159 - direction
	Star176 - direction
	GroundStation128 - direction
	Star164 - direction
	Star48 - direction
	Star135 - direction
	GroundStation13 - direction
	GroundStation80 - direction
	GroundStation181 - direction
	GroundStation116 - direction
	Star156 - direction
	Star97 - direction
	Star62 - direction
	Star187 - direction
	Star77 - direction
	Star83 - direction
	GroundStation168 - direction
	Star89 - direction
	GroundStation171 - direction
	Star45 - direction
	Star61 - direction
	GroundStation155 - direction
	GroundStation153 - direction
	Star37 - direction
	GroundStation17 - direction
	GroundStation152 - direction
	GroundStation179 - direction
	Star59 - direction
	GroundStation138 - direction
	Star142 - direction
	GroundStation165 - direction
	GroundStation202 - direction
	GroundStation120 - direction
	GroundStation18 - direction
	Star170 - direction
	GroundStation119 - direction
	Star85 - direction
	GroundStation132 - direction
	Star158 - direction
	Star107 - direction
	GroundStation177 - direction
	Star201 - direction
	GroundStation173 - direction
	GroundStation93 - direction
	Star103 - direction
	Star38 - direction
	GroundStation140 - direction
	Star130 - direction
	Star113 - direction
	GroundStation22 - direction
	Star191 - direction
	GroundStation131 - direction
	GroundStation126 - direction
	Star29 - direction
	GroundStation196 - direction
	GroundStation75 - direction
	GroundStation72 - direction
	GroundStation63 - direction
	GroundStation11 - direction
	Star88 - direction
	Star125 - direction
	GroundStation188 - direction
	GroundStation106 - direction
	Star193 - direction
	GroundStation27 - direction
	GroundStation4 - direction
	Star94 - direction
	GroundStation6 - direction
	GroundStation129 - direction
	Star122 - direction
	GroundStation98 - direction
	GroundStation190 - direction
	GroundStation16 - direction
	Star184 - direction
	GroundStation108 - direction
	GroundStation149 - direction
	GroundStation112 - direction
	GroundStation102 - direction
	GroundStation145 - direction
	Star55 - direction
	GroundStation101 - direction
	Star76 - direction
	Star197 - direction
	GroundStation32 - direction
	GroundStation174 - direction
	Star43 - direction
	GroundStation12 - direction
	GroundStation87 - direction
	GroundStation133 - direction
	GroundStation99 - direction
	GroundStation58 - direction
	GroundStation35 - direction
	GroundStation114 - direction
	Star124 - direction
	GroundStation7 - direction
	GroundStation100 - direction
	Star185 - direction
	Star74 - direction
	Star25 - direction
	Star162 - direction
	GroundStation166 - direction
	GroundStation157 - direction
	Star169 - direction
	Star115 - direction
	GroundStation21 - direction
	Star161 - direction
	GroundStation81 - direction
	Star71 - direction
	Star127 - direction
	Star65 - direction
	GroundStation86 - direction
	Star3 - direction
	GroundStation203 - direction
	Star36 - direction
	GroundStation82 - direction
	GroundStation24 - direction
	Star33 - direction
	GroundStation1 - direction
	Star163 - direction
	GroundStation10 - direction
	GroundStation2 - direction
	Star118 - direction
	GroundStation53 - direction
	Star30 - direction
	Star192 - direction
	GroundStation148 - direction
	Star183 - direction
	GroundStation40 - direction
	Star144 - direction
	GroundStation47 - direction
	Star73 - direction
	GroundStation39 - direction
	Star194 - direction
	Star79 - direction
	Star64 - direction
	Star172 - direction
	GroundStation44 - direction
	Star154 - direction
	Star69 - direction
	Phenomenon204 - direction
	Star205 - direction
	Star206 - direction
	Star207 - direction
	Star208 - direction
	Phenomenon209 - direction
	Phenomenon210 - direction
	Planet211 - direction
	Star212 - direction
	Planet213 - direction
	Planet214 - direction
	Planet215 - direction
	Star216 - direction
	Star217 - direction
	Star218 - direction
	Star219 - direction
	Planet220 - direction
	Planet221 - direction
	Planet222 - direction
	Phenomenon223 - direction
	Star224 - direction
	Star225 - direction
	Phenomenon226 - direction
	Star227 - direction
	Star228 - direction
	Planet229 - direction
	Phenomenon230 - direction
	Phenomenon231 - direction
	Star232 - direction
	Star233 - direction
	Star234 - direction
	Planet235 - direction
	Phenomenon236 - direction
	Planet237 - direction
	Star238 - direction
	Star239 - direction
	Planet240 - direction
	Phenomenon241 - direction
	Phenomenon242 - direction
	Star243 - direction
	Star244 - direction
	Planet245 - direction
	Planet246 - direction
	Star247 - direction
	Planet248 - direction
	Planet249 - direction
	Star250 - direction
	Phenomenon251 - direction
	Planet252 - direction
	Star253 - direction
	Star254 - direction
	Phenomenon255 - direction
	Star256 - direction
	Star257 - direction
	Star258 - direction
	Planet259 - direction
	Star260 - direction
	Star261 - direction
	Phenomenon262 - direction
	Planet263 - direction
	Planet264 - direction
	Star265 - direction
	Star266 - direction
	Phenomenon267 - direction
	Planet268 - direction
	Planet269 - direction
	Planet270 - direction
	Star271 - direction
	Star272 - direction
	Planet273 - direction
	Planet274 - direction
	Planet275 - direction
	Star276 - direction
	Phenomenon277 - direction
	Star278 - direction
	Phenomenon279 - direction
	Phenomenon280 - direction
	Phenomenon281 - direction
	Phenomenon282 - direction
	Phenomenon283 - direction
	Planet284 - direction
	Phenomenon285 - direction
	Star286 - direction
	Planet287 - direction
	Planet288 - direction
	Planet289 - direction
	Planet290 - direction
	Phenomenon291 - direction
	Planet292 - direction
	Phenomenon293 - direction
	Star294 - direction
	Star295 - direction
	Planet296 - direction
	Phenomenon297 - direction
	Planet298 - direction
	Planet299 - direction
	Phenomenon300 - direction
	Planet301 - direction
	Star302 - direction
	Star303 - direction
	Planet304 - direction
	Planet305 - direction
	Planet306 - direction
	Star307 - direction
	Planet308 - direction
	Star309 - direction
	Phenomenon310 - direction
	Phenomenon311 - direction
	Planet312 - direction
	Planet313 - direction
	Star314 - direction
	Star315 - direction
	Star316 - direction
	Star317 - direction
	Phenomenon318 - direction
	Phenomenon319 - direction
	Planet320 - direction
	Star321 - direction
	Planet322 - direction
	Star323 - direction
	Star324 - direction
	Phenomenon325 - direction
	Star326 - direction
	Star327 - direction
	Planet328 - direction
	Planet329 - direction
	Star330 - direction
	Planet331 - direction
	Star332 - direction
	Phenomenon333 - direction
	Planet334 - direction
	Planet335 - direction
	Phenomenon336 - direction
	Phenomenon337 - direction
	Phenomenon338 - direction
	Star339 - direction
	Star340 - direction
	Star341 - direction
	Star342 - direction
	Planet343 - direction
	Phenomenon344 - direction
	Star345 - direction
	Planet346 - direction
	Planet347 - direction
	Planet348 - direction
	Planet349 - direction
	Star350 - direction
	Phenomenon351 - direction
	Phenomenon352 - direction
	Phenomenon353 - direction
	Star354 - direction
	Planet355 - direction
	Star356 - direction
	Star357 - direction
	Planet358 - direction
	Star359 - direction
	Star360 - direction
	Phenomenon361 - direction
	Star362 - direction
	Planet363 - direction
	Phenomenon364 - direction
	Phenomenon365 - direction
	Planet366 - direction
	Phenomenon367 - direction
	Phenomenon368 - direction
	Phenomenon369 - direction
	Phenomenon370 - direction
	Star371 - direction
	Star372 - direction
	Planet373 - direction
	Planet374 - direction
	Planet375 - direction
	Phenomenon376 - direction
	Star377 - direction
	Planet378 - direction
	Star379 - direction
	Star380 - direction
	Phenomenon381 - direction
	Phenomenon382 - direction
	Phenomenon383 - direction
	Star384 - direction
	Phenomenon385 - direction
	Phenomenon386 - direction
	Planet387 - direction
	Star388 - direction
	Star389 - direction
	Phenomenon390 - direction
	Planet391 - direction
	Planet392 - direction
	Phenomenon393 - direction
	Planet394 - direction
	Phenomenon395 - direction
	Phenomenon396 - direction
	Phenomenon397 - direction
	Phenomenon398 - direction
	Phenomenon399 - direction
	Phenomenon400 - direction
	Planet401 - direction
	Phenomenon402 - direction
	Planet403 - direction
	Planet404 - direction
	Star405 - direction
	Planet406 - direction
	Star407 - direction
)
(:init
	(supports instrument0 thermograph3)
	(calibration_target instrument0 Star105)
	(calibration_target instrument0 Star167)
	(calibration_target instrument0 Star193)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation16)
	(calibration_target instrument0 GroundStation87)
	(calibration_target instrument0 Star70)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 Star69)
	(calibration_target instrument0 GroundStation175)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star51)
	(supports instrument1 infrared5)
	(calibration_target instrument1 Star65)
	(calibration_target instrument1 GroundStation123)
	(calibration_target instrument1 GroundStation66)
	(calibration_target instrument1 GroundStation54)
	(calibration_target instrument1 GroundStation132)
	(calibration_target instrument1 Star84)
	(calibration_target instrument1 GroundStation148)
	(calibration_target instrument1 GroundStation175)
	(calibration_target instrument1 GroundStation92)
	(calibration_target instrument1 GroundStation4)
	(calibration_target instrument1 GroundStation174)
	(calibration_target instrument1 Star90)
	(calibration_target instrument1 GroundStation146)
	(calibration_target instrument1 GroundStation119)
	(calibration_target instrument1 Star187)
	(calibration_target instrument1 Star61)
	(calibration_target instrument1 Star163)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation177)
	(calibration_target instrument1 GroundStation34)
	(calibration_target instrument1 GroundStation126)
	(calibration_target instrument1 GroundStation1)
	(calibration_target instrument1 GroundStation166)
	(calibration_target instrument1 GroundStation100)
	(calibration_target instrument1 Star193)
	(calibration_target instrument1 GroundStation188)
	(calibration_target instrument1 GroundStation93)
	(calibration_target instrument1 Star73)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation106)
	(calibration_target instrument1 GroundStation179)
	(calibration_target instrument1 Star74)
	(calibration_target instrument1 GroundStation15)
	(calibration_target instrument1 GroundStation32)
	(supports instrument2 thermograph0)
	(supports instrument2 infrared5)
	(supports instrument2 thermograph2)
	(calibration_target instrument2 Star78)
	(calibration_target instrument2 Star43)
	(calibration_target instrument2 GroundStation174)
	(calibration_target instrument2 GroundStation138)
	(calibration_target instrument2 Star118)
	(calibration_target instrument2 Star180)
	(calibration_target instrument2 GroundStation190)
	(calibration_target instrument2 GroundStation147)
	(calibration_target instrument2 GroundStation155)
	(calibration_target instrument2 GroundStation131)
	(calibration_target instrument2 GroundStation181)
	(calibration_target instrument2 Star77)
	(calibration_target instrument2 GroundStation199)
	(calibration_target instrument2 GroundStation16)
	(calibration_target instrument2 GroundStation100)
	(calibration_target instrument2 Star113)
	(calibration_target instrument2 Star62)
	(calibration_target instrument2 Star127)
	(calibration_target instrument2 Star158)
	(calibration_target instrument2 Star142)
	(calibration_target instrument2 GroundStation116)
	(calibration_target instrument2 Star73)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 Star197)
	(calibration_target instrument2 GroundStation123)
	(calibration_target instrument2 Star163)
	(calibration_target instrument2 Star68)
	(calibration_target instrument2 Star61)
	(calibration_target instrument2 Star25)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 Star52)
	(calibration_target instrument2 GroundStation63)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 GroundStation195)
	(calibration_target instrument2 Star184)
	(calibration_target instrument2 GroundStation1)
	(calibration_target instrument2 Star124)
	(calibration_target instrument2 Star76)
	(calibration_target instrument2 GroundStation129)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation87)
	(calibration_target instrument2 GroundStation200)
	(calibration_target instrument2 Star70)
	(calibration_target instrument2 GroundStation171)
	(calibration_target instrument2 GroundStation53)
	(calibration_target instrument2 GroundStation23)
	(calibration_target instrument2 GroundStation47)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 Star160)
	(calibration_target instrument2 GroundStation165)
	(calibration_target instrument2 Star182)
	(calibration_target instrument2 Star161)
	(calibration_target instrument2 GroundStation178)
	(calibration_target instrument2 GroundStation117)
	(calibration_target instrument2 GroundStation157)
	(calibration_target instrument2 GroundStation153)
	(calibration_target instrument2 Star201)
	(calibration_target instrument2 Star139)
	(calibration_target instrument2 GroundStation186)
	(calibration_target instrument2 GroundStation10)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 Star65)
	(calibration_target instrument2 GroundStation50)
	(calibration_target instrument2 Star135)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation133)
	(supports instrument3 infrared5)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 Star125)
	(calibration_target instrument3 Star189)
	(calibration_target instrument3 Star49)
	(calibration_target instrument3 Star163)
	(calibration_target instrument3 Star45)
	(calibration_target instrument3 Star130)
	(calibration_target instrument3 GroundStation157)
	(calibration_target instrument3 Star139)
	(calibration_target instrument3 GroundStation17)
	(calibration_target instrument3 GroundStation175)
	(calibration_target instrument3 Star89)
	(calibration_target instrument3 GroundStation100)
	(calibration_target instrument3 GroundStation148)
	(calibration_target instrument3 GroundStation131)
	(calibration_target instrument3 Star187)
	(calibration_target instrument3 Star156)
	(calibration_target instrument3 GroundStation155)
	(calibration_target instrument3 GroundStation75)
	(calibration_target instrument3 GroundStation22)
	(calibration_target instrument3 GroundStation123)
	(calibration_target instrument3 Star201)
	(calibration_target instrument3 Star172)
	(calibration_target instrument3 Star55)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 GroundStation179)
	(calibration_target instrument3 Star158)
	(calibration_target instrument3 GroundStation81)
	(calibration_target instrument3 Star94)
	(calibration_target instrument3 Star169)
	(calibration_target instrument3 Star83)
	(calibration_target instrument3 GroundStation24)
	(calibration_target instrument3 Star184)
	(calibration_target instrument3 GroundStation153)
	(calibration_target instrument3 GroundStation72)
	(calibration_target instrument3 Star65)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 Star105)
	(supports instrument4 thermograph4)
	(supports instrument4 infrared5)
	(calibration_target instrument4 GroundStation99)
	(calibration_target instrument4 Star90)
	(calibration_target instrument4 GroundStation155)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 GroundStation114)
	(calibration_target instrument4 Star125)
	(calibration_target instrument4 GroundStation80)
	(calibration_target instrument4 GroundStation131)
	(calibration_target instrument4 GroundStation120)
	(calibration_target instrument4 Star46)
	(calibration_target instrument4 Star29)
	(calibration_target instrument4 GroundStation147)
	(calibration_target instrument4 Star107)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star49)
	(calibration_target instrument4 GroundStation87)
	(calibration_target instrument4 Star37)
	(calibration_target instrument4 Star137)
	(calibration_target instrument4 Star197)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star88)
	(calibration_target instrument4 GroundStation72)
	(calibration_target instrument4 GroundStation86)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star124)
	(calibration_target instrument4 Star183)
	(calibration_target instrument4 GroundStation40)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 GroundStation145)
	(calibration_target instrument4 GroundStation175)
	(calibration_target instrument4 GroundStation18)
	(calibration_target instrument4 Star65)
	(calibration_target instrument4 Star83)
	(calibration_target instrument4 GroundStation190)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 GroundStation153)
	(calibration_target instrument4 GroundStation157)
	(calibration_target instrument4 GroundStation21)
	(calibration_target instrument4 Star56)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 GroundStation39)
	(calibration_target instrument4 Star55)
	(calibration_target instrument4 GroundStation81)
	(calibration_target instrument4 GroundStation42)
	(calibration_target instrument4 GroundStation179)
	(calibration_target instrument4 GroundStation24)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 Star45)
	(calibration_target instrument4 GroundStation91)
	(calibration_target instrument4 Star167)
	(calibration_target instrument4 Star0)
	(calibration_target instrument4 Star154)
	(calibration_target instrument4 GroundStation140)
	(calibration_target instrument4 Star169)
	(calibration_target instrument4 Star156)
	(calibration_target instrument4 Star163)
	(calibration_target instrument4 Star121)
	(calibration_target instrument4 Star19)
	(supports instrument5 thermograph3)
	(calibration_target instrument5 GroundStation31)
	(calibration_target instrument5 Star69)
	(calibration_target instrument5 GroundStation195)
	(calibration_target instrument5 GroundStation116)
	(calibration_target instrument5 GroundStation39)
	(calibration_target instrument5 Star127)
	(calibration_target instrument5 GroundStation146)
	(calibration_target instrument5 GroundStation157)
	(calibration_target instrument5 Star170)
	(calibration_target instrument5 GroundStation199)
	(calibration_target instrument5 GroundStation92)
	(calibration_target instrument5 GroundStation153)
	(calibration_target instrument5 Star19)
	(calibration_target instrument5 Star187)
	(calibration_target instrument5 Star33)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 Star130)
	(calibration_target instrument5 Star88)
	(calibration_target instrument5 Star135)
	(calibration_target instrument5 GroundStation149)
	(calibration_target instrument5 Star191)
	(calibration_target instrument5 Star48)
	(supports instrument6 infrared5)
	(calibration_target instrument6 GroundStation120)
	(calibration_target instrument6 GroundStation200)
	(calibration_target instrument6 GroundStation82)
	(calibration_target instrument6 Star71)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 Star122)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 GroundStation145)
	(calibration_target instrument6 GroundStation104)
	(calibration_target instrument6 GroundStation63)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 Star144)
	(calibration_target instrument6 GroundStation111)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 Star172)
	(calibration_target instrument6 Star191)
	(calibration_target instrument6 Star176)
	(calibration_target instrument6 Star52)
	(calibration_target instrument6 Star115)
	(calibration_target instrument6 GroundStation181)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 Star29)
	(calibration_target instrument6 GroundStation75)
	(calibration_target instrument6 Star163)
	(calibration_target instrument6 Star64)
	(calibration_target instrument6 GroundStation58)
	(calibration_target instrument6 GroundStation128)
	(calibration_target instrument6 GroundStation35)
	(calibration_target instrument6 GroundStation168)
	(calibration_target instrument6 Star65)
	(calibration_target instrument6 Star56)
	(calibration_target instrument6 GroundStation60)
	(calibration_target instrument6 GroundStation151)
	(calibration_target instrument6 Star8)
	(calibration_target instrument6 GroundStation134)
	(calibration_target instrument6 GroundStation157)
	(calibration_target instrument6 Star69)
	(calibration_target instrument6 Star28)
	(calibration_target instrument6 Star55)
	(calibration_target instrument6 GroundStation108)
	(calibration_target instrument6 Star113)
	(calibration_target instrument6 GroundStation119)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 Star167)
	(calibration_target instrument6 GroundStation96)
	(calibration_target instrument6 Star130)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet308)
	(supports instrument7 infrared5)
	(calibration_target instrument7 GroundStation21)
	(calibration_target instrument7 GroundStation63)
	(calibration_target instrument7 Star68)
	(calibration_target instrument7 GroundStation31)
	(calibration_target instrument7 GroundStation101)
	(calibration_target instrument7 GroundStation200)
	(calibration_target instrument7 GroundStation24)
	(calibration_target instrument7 GroundStation40)
	(calibration_target instrument7 GroundStation120)
	(calibration_target instrument7 GroundStation27)
	(calibration_target instrument7 GroundStation7)
	(calibration_target instrument7 GroundStation117)
	(calibration_target instrument7 GroundStation98)
	(calibration_target instrument7 Star127)
	(calibration_target instrument7 GroundStation179)
	(calibration_target instrument7 Star113)
	(calibration_target instrument7 GroundStation133)
	(calibration_target instrument7 GroundStation58)
	(calibration_target instrument7 GroundStation188)
	(calibration_target instrument7 Star193)
	(calibration_target instrument7 Star67)
	(calibration_target instrument7 Star85)
	(calibration_target instrument7 GroundStation198)
	(calibration_target instrument7 GroundStation186)
	(calibration_target instrument7 Star164)
	(calibration_target instrument7 Star162)
	(calibration_target instrument7 Star121)
	(calibration_target instrument7 GroundStation100)
	(calibration_target instrument7 Star185)
	(calibration_target instrument7 GroundStation138)
	(calibration_target instrument7 GroundStation150)
	(calibration_target instrument7 Star33)
	(calibration_target instrument7 Star61)
	(calibration_target instrument7 Star45)
	(calibration_target instrument7 Star169)
	(calibration_target instrument7 Star201)
	(calibration_target instrument7 GroundStation91)
	(calibration_target instrument7 GroundStation13)
	(calibration_target instrument7 GroundStation26)
	(calibration_target instrument7 GroundStation14)
	(calibration_target instrument7 Star51)
	(calibration_target instrument7 GroundStation145)
	(calibration_target instrument7 GroundStation108)
	(calibration_target instrument7 GroundStation173)
	(calibration_target instrument7 GroundStation199)
	(calibration_target instrument7 Star76)
	(supports instrument8 thermograph2)
	(supports instrument8 infrared5)
	(calibration_target instrument8 GroundStation12)
	(calibration_target instrument8 GroundStation106)
	(calibration_target instrument8 GroundStation188)
	(calibration_target instrument8 GroundStation104)
	(calibration_target instrument8 GroundStation42)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star88)
	(calibration_target instrument8 GroundStation96)
	(calibration_target instrument8 GroundStation60)
	(calibration_target instrument8 GroundStation87)
	(calibration_target instrument8 Star48)
	(calibration_target instrument8 GroundStation171)
	(calibration_target instrument8 Star105)
	(calibration_target instrument8 GroundStation174)
	(calibration_target instrument8 GroundStation112)
	(calibration_target instrument8 Star89)
	(calibration_target instrument8 GroundStation166)
	(calibration_target instrument8 GroundStation66)
	(calibration_target instrument8 Star69)
	(calibration_target instrument8 GroundStation129)
	(calibration_target instrument8 GroundStation100)
	(calibration_target instrument8 GroundStation53)
	(calibration_target instrument8 Star122)
	(calibration_target instrument8 GroundStation195)
	(calibration_target instrument8 Star144)
	(calibration_target instrument8 GroundStation108)
	(calibration_target instrument8 Star191)
	(calibration_target instrument8 Star84)
	(calibration_target instrument8 Star95)
	(calibration_target instrument8 Star56)
	(calibration_target instrument8 GroundStation196)
	(calibration_target instrument8 GroundStation102)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star38)
	(calibration_target instrument8 Star201)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star124)
	(calibration_target instrument8 Star156)
	(calibration_target instrument8 GroundStation82)
	(calibration_target instrument8 Star103)
	(calibration_target instrument8 Star45)
	(calibration_target instrument8 Star118)
	(calibration_target instrument8 Star94)
	(calibration_target instrument8 GroundStation15)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation18)
	(calibration_target instrument8 Star125)
	(calibration_target instrument8 GroundStation1)
	(calibration_target instrument8 Star130)
	(calibration_target instrument8 GroundStation143)
	(calibration_target instrument8 Star68)
	(calibration_target instrument8 Star137)
	(calibration_target instrument8 GroundStation148)
	(calibration_target instrument8 GroundStation17)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 Star97)
	(calibration_target instrument8 GroundStation99)
	(calibration_target instrument8 Star176)
	(calibration_target instrument8 Star70)
	(calibration_target instrument8 Star170)
	(calibration_target instrument8 Star154)
	(calibration_target instrument8 GroundStation81)
	(calibration_target instrument8 Star8)
	(calibration_target instrument8 GroundStation93)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon398)
	(supports instrument9 image1)
	(supports instrument9 thermograph3)
	(supports instrument9 infrared5)
	(calibration_target instrument9 Star163)
	(calibration_target instrument9 Star185)
	(calibration_target instrument9 GroundStation145)
	(calibration_target instrument9 Star136)
	(calibration_target instrument9 GroundStation126)
	(calibration_target instrument9 Star105)
	(calibration_target instrument9 Star20)
	(calibration_target instrument9 GroundStation57)
	(calibration_target instrument9 GroundStation104)
	(calibration_target instrument9 Star201)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 Star144)
	(calibration_target instrument9 GroundStation202)
	(calibration_target instrument9 Star19)
	(calibration_target instrument9 GroundStation12)
	(calibration_target instrument9 GroundStation80)
	(calibration_target instrument9 GroundStation188)
	(calibration_target instrument9 Star154)
	(calibration_target instrument9 Star36)
	(calibration_target instrument9 GroundStation120)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 GroundStation195)
	(calibration_target instrument9 Star55)
	(calibration_target instrument9 GroundStation54)
	(calibration_target instrument9 GroundStation173)
	(calibration_target instrument9 GroundStation138)
	(calibration_target instrument9 Star130)
	(calibration_target instrument9 Star164)
	(calibration_target instrument9 Star141)
	(calibration_target instrument9 GroundStation155)
	(calibration_target instrument9 GroundStation190)
	(calibration_target instrument9 GroundStation111)
	(calibration_target instrument9 GroundStation129)
	(calibration_target instrument9 GroundStation143)
	(calibration_target instrument9 GroundStation91)
	(calibration_target instrument9 GroundStation2)
	(calibration_target instrument9 GroundStation81)
	(calibration_target instrument9 Star61)
	(calibration_target instrument9 Star73)
	(calibration_target instrument9 GroundStation63)
	(calibration_target instrument9 GroundStation146)
	(calibration_target instrument9 GroundStation133)
	(calibration_target instrument9 Star162)
	(calibration_target instrument9 GroundStation35)
	(calibration_target instrument9 GroundStation60)
	(calibration_target instrument9 Star121)
	(on_board instrument9 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet221)
	(supports instrument10 thermograph3)
	(supports instrument10 image1)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation21)
	(calibration_target instrument10 GroundStation39)
	(calibration_target instrument10 Star89)
	(calibration_target instrument10 GroundStation15)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 Star94)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation112)
	(calibration_target instrument10 Star160)
	(calibration_target instrument10 GroundStation47)
	(calibration_target instrument10 GroundStation41)
	(calibration_target instrument10 Star38)
	(calibration_target instrument10 Star194)
	(calibration_target instrument10 GroundStation7)
	(calibration_target instrument10 GroundStation42)
	(calibration_target instrument10 GroundStation111)
	(calibration_target instrument10 Star121)
	(calibration_target instrument10 Star127)
	(calibration_target instrument10 GroundStation12)
	(calibration_target instrument10 GroundStation132)
	(calibration_target instrument10 Star65)
	(calibration_target instrument10 Star183)
	(calibration_target instrument10 Star189)
	(calibration_target instrument10 GroundStation155)
	(calibration_target instrument10 Star95)
	(calibration_target instrument10 Star162)
	(calibration_target instrument10 Star70)
	(calibration_target instrument10 GroundStation117)
	(calibration_target instrument10 Star68)
	(calibration_target instrument10 GroundStation143)
	(calibration_target instrument10 Star187)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 Star180)
	(calibration_target instrument10 Star79)
	(calibration_target instrument10 Star74)
	(calibration_target instrument10 Star90)
	(calibration_target instrument10 Star156)
	(calibration_target instrument10 GroundStation17)
	(calibration_target instrument10 GroundStation145)
	(calibration_target instrument10 GroundStation87)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 Star185)
	(calibration_target instrument10 Star172)
	(calibration_target instrument10 GroundStation63)
	(calibration_target instrument10 GroundStation58)
	(calibration_target instrument10 Star78)
	(calibration_target instrument10 Star124)
	(calibration_target instrument10 Star46)
	(calibration_target instrument10 GroundStation82)
	(calibration_target instrument10 Star176)
	(calibration_target instrument10 GroundStation134)
	(calibration_target instrument10 GroundStation126)
	(calibration_target instrument10 GroundStation106)
	(calibration_target instrument10 GroundStation179)
	(supports instrument11 thermograph3)
	(supports instrument11 thermograph4)
	(supports instrument11 thermograph0)
	(calibration_target instrument11 Star170)
	(calibration_target instrument11 GroundStation26)
	(calibration_target instrument11 Star201)
	(calibration_target instrument11 GroundStation32)
	(calibration_target instrument11 Star94)
	(calibration_target instrument11 Star49)
	(calibration_target instrument11 GroundStation177)
	(calibration_target instrument11 GroundStation35)
	(calibration_target instrument11 Star48)
	(calibration_target instrument11 GroundStation181)
	(calibration_target instrument11 GroundStation99)
	(calibration_target instrument11 Star160)
	(calibration_target instrument11 Star68)
	(calibration_target instrument11 Star122)
	(calibration_target instrument11 GroundStation14)
	(calibration_target instrument11 Star182)
	(calibration_target instrument11 GroundStation53)
	(calibration_target instrument11 Star36)
	(calibration_target instrument11 Star95)
	(calibration_target instrument11 GroundStation140)
	(calibration_target instrument11 GroundStation168)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 GroundStation63)
	(calibration_target instrument11 Star142)
	(calibration_target instrument11 Star78)
	(calibration_target instrument11 GroundStation190)
	(calibration_target instrument11 Star172)
	(calibration_target instrument11 Star141)
	(calibration_target instrument11 GroundStation116)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 GroundStation123)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 Star167)
	(calibration_target instrument11 Star90)
	(calibration_target instrument11 GroundStation202)
	(supports instrument12 thermograph2)
	(calibration_target instrument12 Star130)
	(calibration_target instrument12 GroundStation53)
	(calibration_target instrument12 GroundStation132)
	(calibration_target instrument12 GroundStation91)
	(calibration_target instrument12 Star141)
	(on_board instrument10 satellite5)
	(on_board instrument11 satellite5)
	(on_board instrument12 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation190)
	(supports instrument13 thermograph4)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 GroundStation196)
	(calibration_target instrument13 Star193)
	(calibration_target instrument13 Star94)
	(calibration_target instrument13 GroundStation173)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 Star141)
	(calibration_target instrument13 Star103)
	(calibration_target instrument13 Star38)
	(calibration_target instrument13 Star109)
	(calibration_target instrument13 GroundStation171)
	(calibration_target instrument13 GroundStation150)
	(calibration_target instrument13 GroundStation99)
	(calibration_target instrument13 GroundStation157)
	(calibration_target instrument13 Star89)
	(calibration_target instrument13 GroundStation15)
	(calibration_target instrument13 GroundStation9)
	(calibration_target instrument13 GroundStation32)
	(calibration_target instrument13 Star61)
	(calibration_target instrument13 GroundStation108)
	(calibration_target instrument13 GroundStation152)
	(calibration_target instrument13 GroundStation98)
	(calibration_target instrument13 Star167)
	(calibration_target instrument13 GroundStation23)
	(calibration_target instrument13 GroundStation203)
	(calibration_target instrument13 GroundStation35)
	(calibration_target instrument13 GroundStation140)
	(calibration_target instrument13 Star71)
	(calibration_target instrument13 Star59)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 Star139)
	(calibration_target instrument13 Star74)
	(calibration_target instrument13 GroundStation11)
	(calibration_target instrument13 GroundStation102)
	(calibration_target instrument13 Star176)
	(calibration_target instrument13 GroundStation101)
	(calibration_target instrument13 GroundStation131)
	(calibration_target instrument13 GroundStation179)
	(calibration_target instrument13 Star189)
	(calibration_target instrument13 Star68)
	(calibration_target instrument13 GroundStation126)
	(calibration_target instrument13 Star28)
	(calibration_target instrument13 Star64)
	(calibration_target instrument13 GroundStation80)
	(calibration_target instrument13 Star84)
	(calibration_target instrument13 Star159)
	(calibration_target instrument13 Star97)
	(calibration_target instrument13 GroundStation57)
	(calibration_target instrument13 Star170)
	(calibration_target instrument13 GroundStation116)
	(calibration_target instrument13 Star30)
	(calibration_target instrument13 GroundStation53)
	(calibration_target instrument13 GroundStation114)
	(calibration_target instrument13 Star90)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 GroundStation151)
	(calibration_target instrument13 Star194)
	(calibration_target instrument13 Star49)
	(on_board instrument13 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet284)
	(supports instrument14 thermograph4)
	(supports instrument14 infrared5)
	(calibration_target instrument14 Star67)
	(calibration_target instrument14 GroundStation96)
	(calibration_target instrument14 Star161)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 Star159)
	(calibration_target instrument14 GroundStation134)
	(calibration_target instrument14 GroundStation168)
	(calibration_target instrument14 GroundStation14)
	(calibration_target instrument14 Star158)
	(calibration_target instrument14 GroundStation203)
	(calibration_target instrument14 GroundStation54)
	(calibration_target instrument14 GroundStation9)
	(calibration_target instrument14 GroundStation174)
	(calibration_target instrument14 Star156)
	(calibration_target instrument14 Star94)
	(calibration_target instrument14 Star189)
	(calibration_target instrument14 GroundStation17)
	(calibration_target instrument14 Star8)
	(calibration_target instrument14 Star162)
	(calibration_target instrument14 GroundStation53)
	(calibration_target instrument14 Star84)
	(calibration_target instrument14 Star142)
	(calibration_target instrument14 GroundStation117)
	(calibration_target instrument14 Star65)
	(calibration_target instrument14 GroundStation202)
	(calibration_target instrument14 Star197)
	(calibration_target instrument14 Star167)
	(calibration_target instrument14 GroundStation157)
	(calibration_target instrument14 GroundStation99)
	(calibration_target instrument14 Star141)
	(calibration_target instrument14 GroundStation111)
	(calibration_target instrument14 GroundStation128)
	(calibration_target instrument14 Star118)
	(calibration_target instrument14 GroundStation21)
	(calibration_target instrument14 Star19)
	(calibration_target instrument14 Star184)
	(calibration_target instrument14 GroundStation165)
	(calibration_target instrument14 Star43)
	(calibration_target instrument14 Star130)
	(calibration_target instrument14 Star107)
	(calibration_target instrument14 GroundStation32)
	(calibration_target instrument14 Star3)
	(calibration_target instrument14 Star192)
	(calibration_target instrument14 Star137)
	(supports instrument15 image1)
	(supports instrument15 infrared5)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 Star71)
	(calibration_target instrument15 GroundStation181)
	(calibration_target instrument15 GroundStation145)
	(calibration_target instrument15 GroundStation199)
	(calibration_target instrument15 Star144)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star97)
	(calibration_target instrument15 GroundStation165)
	(calibration_target instrument15 GroundStation27)
	(calibration_target instrument15 GroundStation50)
	(calibration_target instrument15 Star187)
	(calibration_target instrument15 GroundStation91)
	(calibration_target instrument15 GroundStation6)
	(calibration_target instrument15 Star49)
	(calibration_target instrument15 Star68)
	(calibration_target instrument15 Star185)
	(calibration_target instrument15 GroundStation146)
	(calibration_target instrument15 GroundStation203)
	(calibration_target instrument15 GroundStation35)
	(calibration_target instrument15 GroundStation138)
	(calibration_target instrument15 GroundStation129)
	(calibration_target instrument15 GroundStation1)
	(calibration_target instrument15 Star113)
	(calibration_target instrument15 Star45)
	(calibration_target instrument15 GroundStation16)
	(calibration_target instrument15 GroundStation134)
	(calibration_target instrument15 Star170)
	(calibration_target instrument15 GroundStation140)
	(calibration_target instrument15 Star176)
	(calibration_target instrument15 GroundStation143)
	(calibration_target instrument15 GroundStation22)
	(calibration_target instrument15 Star105)
	(calibration_target instrument15 Star156)
	(calibration_target instrument15 Star182)
	(calibration_target instrument15 Star55)
	(calibration_target instrument15 GroundStation66)
	(calibration_target instrument15 Star142)
	(calibration_target instrument15 GroundStation72)
	(calibration_target instrument15 Star37)
	(calibration_target instrument15 GroundStation106)
	(calibration_target instrument15 Star135)
	(calibration_target instrument15 Star78)
	(calibration_target instrument15 Star84)
	(calibration_target instrument15 GroundStation173)
	(calibration_target instrument15 Star62)
	(calibration_target instrument15 Star48)
	(calibration_target instrument15 Star169)
	(calibration_target instrument15 Star154)
	(calibration_target instrument15 Star172)
	(calibration_target instrument15 GroundStation21)
	(calibration_target instrument15 Star28)
	(calibration_target instrument15 GroundStation196)
	(calibration_target instrument15 GroundStation178)
	(calibration_target instrument15 Star3)
	(calibration_target instrument15 Star159)
	(on_board instrument14 satellite7)
	(on_board instrument15 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star227)
	(supports instrument16 thermograph2)
	(calibration_target instrument16 Star192)
	(calibration_target instrument16 GroundStation157)
	(calibration_target instrument16 GroundStation13)
	(calibration_target instrument16 Star135)
	(calibration_target instrument16 Star48)
	(calibration_target instrument16 Star163)
	(calibration_target instrument16 Star164)
	(calibration_target instrument16 Star115)
	(calibration_target instrument16 Star73)
	(calibration_target instrument16 GroundStation16)
	(calibration_target instrument16 GroundStation128)
	(calibration_target instrument16 GroundStation58)
	(calibration_target instrument16 Star176)
	(calibration_target instrument16 Star142)
	(calibration_target instrument16 GroundStation190)
	(calibration_target instrument16 GroundStation35)
	(calibration_target instrument16 Star159)
	(calibration_target instrument16 Star97)
	(calibration_target instrument16 Star125)
	(calibration_target instrument16 GroundStation17)
	(calibration_target instrument16 Star193)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 GroundStation120)
	(calibration_target instrument16 GroundStation6)
	(calibration_target instrument16 Star67)
	(calibration_target instrument16 GroundStation148)
	(calibration_target instrument16 GroundStation34)
	(calibration_target instrument16 Star94)
	(calibration_target instrument16 GroundStation81)
	(calibration_target instrument16 GroundStation177)
	(calibration_target instrument16 Star61)
	(calibration_target instrument16 GroundStation21)
	(calibration_target instrument16 Star71)
	(calibration_target instrument16 Star19)
	(calibration_target instrument16 Star109)
	(calibration_target instrument16 Star172)
	(calibration_target instrument16 GroundStation140)
	(calibration_target instrument16 Star28)
	(calibration_target instrument16 Star156)
	(calibration_target instrument16 GroundStation147)
	(calibration_target instrument16 Star141)
	(calibration_target instrument16 GroundStation116)
	(calibration_target instrument16 Star183)
	(calibration_target instrument16 GroundStation102)
	(calibration_target instrument16 GroundStation82)
	(calibration_target instrument16 GroundStation202)
	(calibration_target instrument16 Star122)
	(calibration_target instrument16 GroundStation181)
	(calibration_target instrument16 Star130)
	(calibration_target instrument16 GroundStation108)
	(calibration_target instrument16 Star162)
	(calibration_target instrument16 Star191)
	(calibration_target instrument16 GroundStation50)
	(calibration_target instrument16 Star113)
	(calibration_target instrument16 Star51)
	(calibration_target instrument16 GroundStation174)
	(calibration_target instrument16 Star83)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation40)
	(calibration_target instrument17 Star130)
	(calibration_target instrument17 GroundStation100)
	(calibration_target instrument17 GroundStation32)
	(calibration_target instrument17 Star64)
	(calibration_target instrument17 Star142)
	(calibration_target instrument17 GroundStation138)
	(calibration_target instrument17 GroundStation148)
	(calibration_target instrument17 Star127)
	(calibration_target instrument17 Star59)
	(calibration_target instrument17 Star115)
	(calibration_target instrument17 Star162)
	(calibration_target instrument17 Star184)
	(calibration_target instrument17 GroundStation179)
	(calibration_target instrument17 GroundStation152)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 GroundStation203)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star33)
	(calibration_target instrument17 GroundStation98)
	(calibration_target instrument17 Star43)
	(calibration_target instrument17 Star37)
	(calibration_target instrument17 Star30)
	(calibration_target instrument17 GroundStation18)
	(calibration_target instrument17 GroundStation153)
	(calibration_target instrument17 Star113)
	(calibration_target instrument17 GroundStation155)
	(calibration_target instrument17 GroundStation22)
	(calibration_target instrument17 Star61)
	(calibration_target instrument17 Star45)
	(calibration_target instrument17 GroundStation171)
	(calibration_target instrument17 GroundStation58)
	(calibration_target instrument17 Star89)
	(calibration_target instrument17 GroundStation168)
	(calibration_target instrument17 GroundStation131)
	(calibration_target instrument17 Star83)
	(calibration_target instrument17 GroundStation99)
	(calibration_target instrument17 Star77)
	(calibration_target instrument17 Star55)
	(calibration_target instrument17 Star187)
	(calibration_target instrument17 Star74)
	(calibration_target instrument17 Star62)
	(calibration_target instrument17 Star107)
	(calibration_target instrument17 Star172)
	(calibration_target instrument17 Star97)
	(calibration_target instrument17 Star156)
	(calibration_target instrument17 GroundStation47)
	(calibration_target instrument17 Star154)
	(calibration_target instrument17 GroundStation132)
	(calibration_target instrument17 GroundStation116)
	(calibration_target instrument17 GroundStation16)
	(calibration_target instrument17 GroundStation181)
	(calibration_target instrument17 GroundStation80)
	(calibration_target instrument17 Star71)
	(supports instrument18 thermograph0)
	(supports instrument18 thermograph2)
	(supports instrument18 infrared5)
	(calibration_target instrument18 Star29)
	(calibration_target instrument18 GroundStation126)
	(calibration_target instrument18 GroundStation131)
	(calibration_target instrument18 GroundStation72)
	(calibration_target instrument18 Star191)
	(calibration_target instrument18 Star73)
	(calibration_target instrument18 GroundStation22)
	(calibration_target instrument18 Star113)
	(calibration_target instrument18 Star130)
	(calibration_target instrument18 GroundStation86)
	(calibration_target instrument18 GroundStation140)
	(calibration_target instrument18 Star193)
	(calibration_target instrument18 Star38)
	(calibration_target instrument18 Star103)
	(calibration_target instrument18 GroundStation93)
	(calibration_target instrument18 GroundStation129)
	(calibration_target instrument18 GroundStation173)
	(calibration_target instrument18 Star201)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 GroundStation177)
	(calibration_target instrument18 GroundStation108)
	(calibration_target instrument18 Star107)
	(calibration_target instrument18 Star118)
	(calibration_target instrument18 GroundStation99)
	(calibration_target instrument18 Star158)
	(calibration_target instrument18 GroundStation53)
	(calibration_target instrument18 GroundStation132)
	(calibration_target instrument18 Star185)
	(calibration_target instrument18 Star85)
	(calibration_target instrument18 Star25)
	(calibration_target instrument18 GroundStation119)
	(calibration_target instrument18 GroundStation112)
	(calibration_target instrument18 Star170)
	(calibration_target instrument18 GroundStation18)
	(calibration_target instrument18 GroundStation120)
	(calibration_target instrument18 GroundStation44)
	(calibration_target instrument18 GroundStation202)
	(calibration_target instrument18 GroundStation165)
	(supports instrument19 thermograph2)
	(supports instrument19 thermograph0)
	(supports instrument19 image1)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 GroundStation27)
	(calibration_target instrument19 Star122)
	(calibration_target instrument19 Star193)
	(calibration_target instrument19 GroundStation106)
	(calibration_target instrument19 GroundStation188)
	(calibration_target instrument19 Star125)
	(calibration_target instrument19 Star88)
	(calibration_target instrument19 GroundStation11)
	(calibration_target instrument19 GroundStation63)
	(calibration_target instrument19 GroundStation72)
	(calibration_target instrument19 Star144)
	(calibration_target instrument19 GroundStation75)
	(calibration_target instrument19 GroundStation196)
	(on_board instrument16 satellite8)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation7)
	(supports instrument20 thermograph2)
	(supports instrument20 thermograph4)
	(calibration_target instrument20 GroundStation114)
	(calibration_target instrument20 Star154)
	(calibration_target instrument20 GroundStation35)
	(calibration_target instrument20 GroundStation58)
	(calibration_target instrument20 Star74)
	(calibration_target instrument20 GroundStation99)
	(calibration_target instrument20 GroundStation133)
	(calibration_target instrument20 GroundStation87)
	(calibration_target instrument20 Star192)
	(calibration_target instrument20 GroundStation12)
	(calibration_target instrument20 Star43)
	(calibration_target instrument20 Star163)
	(calibration_target instrument20 GroundStation174)
	(calibration_target instrument20 GroundStation32)
	(calibration_target instrument20 Star197)
	(calibration_target instrument20 Star76)
	(calibration_target instrument20 GroundStation101)
	(calibration_target instrument20 Star55)
	(calibration_target instrument20 GroundStation145)
	(calibration_target instrument20 GroundStation102)
	(calibration_target instrument20 GroundStation112)
	(calibration_target instrument20 GroundStation149)
	(calibration_target instrument20 GroundStation108)
	(calibration_target instrument20 Star162)
	(calibration_target instrument20 GroundStation166)
	(calibration_target instrument20 Star184)
	(calibration_target instrument20 GroundStation16)
	(calibration_target instrument20 GroundStation190)
	(calibration_target instrument20 GroundStation98)
	(calibration_target instrument20 Star144)
	(calibration_target instrument20 Star122)
	(calibration_target instrument20 GroundStation129)
	(calibration_target instrument20 GroundStation6)
	(calibration_target instrument20 GroundStation81)
	(calibration_target instrument20 Star94)
	(supports instrument21 thermograph2)
	(supports instrument21 thermograph0)
	(supports instrument21 thermograph3)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 GroundStation100)
	(calibration_target instrument21 GroundStation7)
	(calibration_target instrument21 Star124)
	(supports instrument22 image1)
	(calibration_target instrument22 Star163)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 Star33)
	(calibration_target instrument22 GroundStation24)
	(calibration_target instrument22 GroundStation82)
	(calibration_target instrument22 GroundStation53)
	(calibration_target instrument22 Star36)
	(calibration_target instrument22 GroundStation203)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation86)
	(calibration_target instrument22 Star65)
	(calibration_target instrument22 Star192)
	(calibration_target instrument22 Star127)
	(calibration_target instrument22 Star71)
	(calibration_target instrument22 GroundStation81)
	(calibration_target instrument22 Star161)
	(calibration_target instrument22 GroundStation21)
	(calibration_target instrument22 Star115)
	(calibration_target instrument22 Star169)
	(calibration_target instrument22 GroundStation157)
	(calibration_target instrument22 GroundStation166)
	(calibration_target instrument22 Star162)
	(calibration_target instrument22 Star25)
	(calibration_target instrument22 Star74)
	(calibration_target instrument22 Star185)
	(supports instrument23 thermograph3)
	(supports instrument23 thermograph0)
	(supports instrument23 thermograph4)
	(calibration_target instrument23 Star69)
	(calibration_target instrument23 Star154)
	(calibration_target instrument23 GroundStation44)
	(calibration_target instrument23 Star172)
	(calibration_target instrument23 Star64)
	(calibration_target instrument23 Star79)
	(calibration_target instrument23 Star194)
	(calibration_target instrument23 GroundStation39)
	(calibration_target instrument23 Star73)
	(calibration_target instrument23 GroundStation47)
	(calibration_target instrument23 Star144)
	(calibration_target instrument23 GroundStation40)
	(calibration_target instrument23 Star183)
	(calibration_target instrument23 GroundStation148)
	(calibration_target instrument23 Star192)
	(calibration_target instrument23 Star30)
	(calibration_target instrument23 GroundStation53)
	(calibration_target instrument23 Star118)
	(calibration_target instrument23 GroundStation2)
	(calibration_target instrument23 GroundStation10)
	(on_board instrument20 satellite9)
	(on_board instrument21 satellite9)
	(on_board instrument22 satellite9)
	(on_board instrument23 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star45)
)
(:goal (and
	(pointing satellite0 Planet301)
	(pointing satellite1 Phenomenon402)
	(pointing satellite2 GroundStation98)
	(pointing satellite4 Star356)
	(pointing satellite6 Star162)
	(pointing satellite9 Star191)
	(have_image Star205 thermograph0)
	(have_image Star206 infrared5)
	(have_image Star207 thermograph2)
	(have_image Star207 image1)
	(have_image Star208 image1)
	(have_image Star208 thermograph4)
	(have_image Phenomenon210 image1)
	(have_image Phenomenon210 thermograph4)
	(have_image Planet211 thermograph4)
	(have_image Star212 thermograph2)
	(have_image Star212 thermograph3)
	(have_image Planet213 infrared5)
	(have_image Planet214 infrared5)
	(have_image Planet215 thermograph3)
	(have_image Planet215 image1)
	(have_image Star216 thermograph2)
	(have_image Star216 image1)
	(have_image Star217 thermograph4)
	(have_image Star217 thermograph3)
	(have_image Star218 infrared5)
	(have_image Star219 thermograph2)
	(have_image Star219 thermograph0)
	(have_image Planet220 infrared5)
	(have_image Planet221 infrared5)
	(have_image Planet221 thermograph4)
	(have_image Planet222 thermograph0)
	(have_image Phenomenon223 infrared5)
	(have_image Star224 thermograph2)
	(have_image Star224 image1)
	(have_image Star225 thermograph4)
	(have_image Star225 thermograph2)
	(have_image Phenomenon226 image1)
	(have_image Star227 thermograph4)
	(have_image Star228 image1)
	(have_image Phenomenon230 image1)
	(have_image Phenomenon230 infrared5)
	(have_image Phenomenon231 thermograph2)
	(have_image Star232 thermograph3)
	(have_image Star233 thermograph3)
	(have_image Star234 infrared5)
	(have_image Planet235 thermograph3)
	(have_image Phenomenon236 image1)
	(have_image Planet237 thermograph4)
	(have_image Star238 image1)
	(have_image Star238 thermograph4)
	(have_image Star239 thermograph2)
	(have_image Star239 infrared5)
	(have_image Phenomenon241 thermograph3)
	(have_image Phenomenon242 image1)
	(have_image Phenomenon242 thermograph4)
	(have_image Star243 thermograph4)
	(have_image Star243 thermograph0)
	(have_image Star244 image1)
	(have_image Star244 thermograph2)
	(have_image Planet245 image1)
	(have_image Planet245 thermograph3)
	(have_image Planet246 image1)
	(have_image Star247 thermograph2)
	(have_image Planet248 image1)
	(have_image Planet248 thermograph0)
	(have_image Planet249 thermograph4)
	(have_image Planet249 infrared5)
	(have_image Star250 thermograph4)
	(have_image Star250 thermograph3)
	(have_image Planet252 thermograph3)
	(have_image Planet252 infrared5)
	(have_image Star253 thermograph4)
	(have_image Star253 thermograph2)
	(have_image Star254 thermograph0)
	(have_image Star254 infrared5)
	(have_image Phenomenon255 infrared5)
	(have_image Phenomenon255 image1)
	(have_image Star256 thermograph0)
	(have_image Star256 thermograph4)
	(have_image Star257 image1)
	(have_image Star258 image1)
	(have_image Planet259 thermograph2)
	(have_image Planet259 image1)
	(have_image Star260 image1)
	(have_image Star260 thermograph4)
	(have_image Star261 thermograph0)
	(have_image Phenomenon262 thermograph4)
	(have_image Phenomenon262 thermograph3)
	(have_image Planet263 infrared5)
	(have_image Planet263 thermograph0)
	(have_image Planet264 thermograph4)
	(have_image Star266 thermograph4)
	(have_image Planet268 thermograph3)
	(have_image Planet269 thermograph3)
	(have_image Planet270 thermograph3)
	(have_image Planet270 thermograph2)
	(have_image Star271 thermograph0)
	(have_image Star271 thermograph2)
	(have_image Star272 image1)
	(have_image Planet273 image1)
	(have_image Planet274 thermograph0)
	(have_image Planet275 thermograph4)
	(have_image Star276 thermograph3)
	(have_image Star276 infrared5)
	(have_image Phenomenon277 thermograph4)
	(have_image Phenomenon277 thermograph0)
	(have_image Star278 thermograph0)
	(have_image Star278 thermograph3)
	(have_image Phenomenon279 thermograph4)
	(have_image Phenomenon279 thermograph3)
	(have_image Phenomenon280 thermograph2)
	(have_image Phenomenon280 infrared5)
	(have_image Phenomenon281 infrared5)
	(have_image Phenomenon282 image1)
	(have_image Phenomenon282 thermograph3)
	(have_image Phenomenon283 image1)
	(have_image Planet284 thermograph4)
	(have_image Planet284 thermograph3)
	(have_image Star286 image1)
	(have_image Star286 thermograph2)
	(have_image Planet287 thermograph2)
	(have_image Planet288 thermograph3)
	(have_image Planet288 image1)
	(have_image Planet289 thermograph2)
	(have_image Planet289 image1)
	(have_image Planet290 thermograph0)
	(have_image Planet290 thermograph4)
	(have_image Phenomenon291 thermograph3)
	(have_image Planet292 thermograph4)
	(have_image Phenomenon293 thermograph2)
	(have_image Star294 thermograph0)
	(have_image Star294 image1)
	(have_image Star295 image1)
	(have_image Planet296 thermograph4)
	(have_image Planet298 image1)
	(have_image Planet299 thermograph3)
	(have_image Planet301 infrared5)
	(have_image Star302 image1)
	(have_image Star302 thermograph2)
	(have_image Star303 thermograph3)
	(have_image Star303 image1)
	(have_image Planet304 thermograph4)
	(have_image Planet304 image1)
	(have_image Planet305 thermograph0)
	(have_image Planet305 image1)
	(have_image Planet306 thermograph4)
	(have_image Star307 thermograph4)
	(have_image Planet308 thermograph2)
	(have_image Planet308 image1)
	(have_image Star309 thermograph3)
	(have_image Phenomenon310 image1)
	(have_image Phenomenon310 infrared5)
	(have_image Phenomenon311 thermograph3)
	(have_image Planet312 image1)
	(have_image Planet312 thermograph2)
	(have_image Planet313 infrared5)
	(have_image Planet313 thermograph0)
	(have_image Star314 thermograph0)
	(have_image Star315 image1)
	(have_image Star315 thermograph2)
	(have_image Star316 thermograph4)
	(have_image Star316 thermograph0)
	(have_image Phenomenon318 thermograph4)
	(have_image Phenomenon318 infrared5)
	(have_image Phenomenon319 thermograph0)
	(have_image Phenomenon319 thermograph2)
	(have_image Star321 thermograph4)
	(have_image Planet322 image1)
	(have_image Planet322 thermograph2)
	(have_image Star323 thermograph4)
	(have_image Star323 image1)
	(have_image Star324 thermograph0)
	(have_image Phenomenon325 thermograph3)
	(have_image Phenomenon325 thermograph0)
	(have_image Star326 image1)
	(have_image Star326 infrared5)
	(have_image Star327 thermograph3)
	(have_image Star327 thermograph4)
	(have_image Planet328 thermograph4)
	(have_image Planet329 thermograph3)
	(have_image Star330 thermograph2)
	(have_image Planet331 thermograph4)
	(have_image Star332 infrared5)
	(have_image Phenomenon333 infrared5)
	(have_image Phenomenon333 thermograph0)
	(have_image Planet334 thermograph2)
	(have_image Planet334 thermograph3)
	(have_image Planet335 thermograph3)
	(have_image Phenomenon337 thermograph3)
	(have_image Phenomenon337 thermograph0)
	(have_image Phenomenon338 thermograph4)
	(have_image Phenomenon338 thermograph3)
	(have_image Star340 thermograph3)
	(have_image Star340 infrared5)
	(have_image Star341 image1)
	(have_image Star341 thermograph4)
	(have_image Star342 thermograph3)
	(have_image Planet343 infrared5)
	(have_image Phenomenon344 thermograph3)
	(have_image Star345 thermograph3)
	(have_image Star345 infrared5)
	(have_image Planet346 infrared5)
	(have_image Planet347 thermograph2)
	(have_image Planet347 infrared5)
	(have_image Planet348 infrared5)
	(have_image Planet348 thermograph0)
	(have_image Planet349 infrared5)
	(have_image Phenomenon351 image1)
	(have_image Phenomenon352 image1)
	(have_image Phenomenon352 thermograph2)
	(have_image Star354 thermograph0)
	(have_image Star354 thermograph2)
	(have_image Planet355 image1)
	(have_image Planet355 thermograph2)
	(have_image Star356 thermograph0)
	(have_image Star357 infrared5)
	(have_image Star357 thermograph4)
	(have_image Planet358 thermograph3)
	(have_image Planet358 infrared5)
	(have_image Star359 thermograph2)
	(have_image Star359 thermograph4)
	(have_image Phenomenon361 thermograph4)
	(have_image Star362 thermograph4)
	(have_image Star362 thermograph2)
	(have_image Planet363 thermograph0)
	(have_image Planet363 thermograph2)
	(have_image Phenomenon364 thermograph2)
	(have_image Phenomenon365 thermograph3)
	(have_image Phenomenon365 thermograph4)
	(have_image Planet366 image1)
	(have_image Phenomenon367 image1)
	(have_image Phenomenon368 thermograph3)
	(have_image Phenomenon369 thermograph3)
	(have_image Phenomenon370 thermograph4)
	(have_image Star371 thermograph4)
	(have_image Star372 thermograph4)
	(have_image Star372 infrared5)
	(have_image Planet374 thermograph2)
	(have_image Planet374 thermograph4)
	(have_image Planet375 image1)
	(have_image Phenomenon376 thermograph2)
	(have_image Star377 infrared5)
	(have_image Planet378 thermograph0)
	(have_image Planet378 thermograph2)
	(have_image Star379 thermograph0)
	(have_image Star380 thermograph4)
	(have_image Phenomenon381 thermograph4)
	(have_image Phenomenon382 thermograph4)
	(have_image Phenomenon383 thermograph2)
	(have_image Star384 thermograph2)
	(have_image Star384 infrared5)
	(have_image Phenomenon385 thermograph0)
	(have_image Phenomenon385 thermograph3)
	(have_image Phenomenon386 infrared5)
	(have_image Star388 infrared5)
	(have_image Star389 infrared5)
	(have_image Star389 thermograph0)
	(have_image Planet391 image1)
	(have_image Planet392 infrared5)
	(have_image Planet394 thermograph3)
	(have_image Planet394 infrared5)
	(have_image Phenomenon395 thermograph4)
	(have_image Phenomenon396 image1)
	(have_image Phenomenon396 thermograph2)
	(have_image Phenomenon397 thermograph3)
	(have_image Phenomenon397 infrared5)
	(have_image Phenomenon398 thermograph4)
	(have_image Phenomenon398 image1)
	(have_image Phenomenon399 image1)
	(have_image Phenomenon399 infrared5)
	(have_image Phenomenon400 thermograph2)
	(have_image Phenomenon400 infrared5)
	(have_image Planet401 infrared5)
	(have_image Planet401 thermograph2)
	(have_image Phenomenon402 thermograph4)
	(have_image Phenomenon402 thermograph2)
	(have_image Planet403 thermograph0)
	(have_image Planet404 image1)
	(have_image Planet404 thermograph0)
	(have_image Star405 thermograph0)
	(have_image Star405 image1)
	(have_image Planet406 thermograph0)
	(have_image Planet406 image1)
	(have_image Star407 thermograph0)
))

)
