(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	satellite5 - satellite
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	satellite7 - satellite
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	instrument23 - instrument
	satellite8 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite9 - satellite
	instrument29 - instrument
	satellite10 - satellite
	instrument30 - instrument
	instrument31 - instrument
	satellite11 - satellite
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	spectrograph0 - mode
	thermograph1 - mode
	spectrograph6 - mode
	infrared3 - mode
	image5 - mode
	image4 - mode
	infrared2 - mode
	GroundStation50 - direction
	Star120 - direction
	Star21 - direction
	GroundStation1 - direction
	GroundStation180 - direction
	Star188 - direction
	Star161 - direction
	GroundStation141 - direction
	Star82 - direction
	GroundStation118 - direction
	Star138 - direction
	Star46 - direction
	Star172 - direction
	Star109 - direction
	Star19 - direction
	GroundStation197 - direction
	GroundStation142 - direction
	GroundStation9 - direction
	Star129 - direction
	GroundStation29 - direction
	GroundStation22 - direction
	GroundStation176 - direction
	Star76 - direction
	Star72 - direction
	Star79 - direction
	GroundStation171 - direction
	Star122 - direction
	Star52 - direction
	Star151 - direction
	Star78 - direction
	Star101 - direction
	GroundStation163 - direction
	Star196 - direction
	GroundStation27 - direction
	GroundStation57 - direction
	GroundStation114 - direction
	GroundStation59 - direction
	GroundStation66 - direction
	GroundStation38 - direction
	GroundStation43 - direction
	GroundStation175 - direction
	GroundStation117 - direction
	Star150 - direction
	GroundStation62 - direction
	GroundStation51 - direction
	GroundStation6 - direction
	Star156 - direction
	Star7 - direction
	GroundStation198 - direction
	Star97 - direction
	Star116 - direction
	Star88 - direction
	Star11 - direction
	GroundStation20 - direction
	GroundStation37 - direction
	Star113 - direction
	GroundStation186 - direction
	Star80 - direction
	Star74 - direction
	Star200 - direction
	Star135 - direction
	Star145 - direction
	GroundStation26 - direction
	Star55 - direction
	Star58 - direction
	Star165 - direction
	Star119 - direction
	Star184 - direction
	GroundStation12 - direction
	Star0 - direction
	Star125 - direction
	Star191 - direction
	Star166 - direction
	GroundStation115 - direction
	Star157 - direction
	GroundStation4 - direction
	Star84 - direction
	Star195 - direction
	Star168 - direction
	Star104 - direction
	GroundStation158 - direction
	GroundStation35 - direction
	GroundStation124 - direction
	Star56 - direction
	Star67 - direction
	Star41 - direction
	Star111 - direction
	Star133 - direction
	Star152 - direction
	Star89 - direction
	GroundStation16 - direction
	Star126 - direction
	GroundStation174 - direction
	GroundStation81 - direction
	Star102 - direction
	Star33 - direction
	GroundStation75 - direction
	GroundStation139 - direction
	GroundStation170 - direction
	GroundStation65 - direction
	GroundStation85 - direction
	Star203 - direction
	Star202 - direction
	Star192 - direction
	GroundStation90 - direction
	Star128 - direction
	Star61 - direction
	GroundStation10 - direction
	GroundStation92 - direction
	GroundStation173 - direction
	GroundStation25 - direction
	Star86 - direction
	GroundStation77 - direction
	GroundStation127 - direction
	Star178 - direction
	GroundStation130 - direction
	Star181 - direction
	Star100 - direction
	GroundStation132 - direction
	Star112 - direction
	GroundStation30 - direction
	Star60 - direction
	GroundStation169 - direction
	GroundStation17 - direction
	Star70 - direction
	Star31 - direction
	Star105 - direction
	Star187 - direction
	Star189 - direction
	Star182 - direction
	GroundStation177 - direction
	GroundStation71 - direction
	GroundStation162 - direction
	Star15 - direction
	Star48 - direction
	Star110 - direction
	Star123 - direction
	Star148 - direction
	Star42 - direction
	Star45 - direction
	Star93 - direction
	GroundStation98 - direction
	Star149 - direction
	Star24 - direction
	GroundStation95 - direction
	GroundStation147 - direction
	GroundStation134 - direction
	Star28 - direction
	GroundStation34 - direction
	GroundStation131 - direction
	GroundStation8 - direction
	GroundStation18 - direction
	GroundStation44 - direction
	GroundStation106 - direction
	GroundStation99 - direction
	GroundStation64 - direction
	Star2 - direction
	GroundStation201 - direction
	GroundStation54 - direction
	Star155 - direction
	GroundStation23 - direction
	GroundStation69 - direction
	GroundStation63 - direction
	Star5 - direction
	Star185 - direction
	GroundStation146 - direction
	GroundStation107 - direction
	GroundStation39 - direction
	GroundStation32 - direction
	GroundStation159 - direction
	GroundStation13 - direction
	Star199 - direction
	GroundStation94 - direction
	Star103 - direction
	GroundStation179 - direction
	GroundStation167 - direction
	Star193 - direction
	Star136 - direction
	GroundStation3 - direction
	GroundStation87 - direction
	Star83 - direction
	GroundStation153 - direction
	Star14 - direction
	Star91 - direction
	Star160 - direction
	Star144 - direction
	Star190 - direction
	GroundStation47 - direction
	Star121 - direction
	Star36 - direction
	GroundStation143 - direction
	Star140 - direction
	Star164 - direction
	GroundStation96 - direction
	GroundStation108 - direction
	Star137 - direction
	Star68 - direction
	GroundStation73 - direction
	Star183 - direction
	Star194 - direction
	GroundStation40 - direction
	GroundStation154 - direction
	GroundStation49 - direction
	GroundStation53 - direction
	Planet204 - direction
	Star205 - direction
	Star206 - direction
	Star207 - direction
	Phenomenon208 - direction
	Star209 - direction
	Phenomenon210 - direction
	Phenomenon211 - direction
	Phenomenon212 - direction
	Planet213 - direction
	Star214 - direction
	Planet215 - direction
	Planet216 - direction
	Planet217 - direction
	Phenomenon218 - direction
	Star219 - direction
	Planet220 - direction
	Planet221 - direction
	Star222 - direction
	Star223 - direction
	Star224 - direction
	Planet225 - direction
	Phenomenon226 - direction
	Phenomenon227 - direction
	Phenomenon228 - direction
	Phenomenon229 - direction
	Phenomenon230 - direction
	Star231 - direction
	Star232 - direction
	Star233 - direction
	Phenomenon234 - direction
	Planet235 - direction
	Phenomenon236 - direction
	Star237 - direction
	Star238 - direction
	Phenomenon239 - direction
	Planet240 - direction
	Phenomenon241 - direction
	Star242 - direction
	Planet243 - direction
	Star244 - direction
	Planet245 - direction
	Planet246 - direction
	Planet247 - direction
	Phenomenon248 - direction
	Phenomenon249 - direction
	Phenomenon250 - direction
	Planet251 - direction
	Phenomenon252 - direction
	Star253 - direction
	Star254 - direction
	Planet255 - direction
	Planet256 - direction
	Planet257 - direction
	Star258 - direction
	Phenomenon259 - direction
	Planet260 - direction
	Phenomenon261 - direction
	Planet262 - direction
	Star263 - direction
	Phenomenon264 - direction
	Star265 - direction
	Phenomenon266 - direction
	Star267 - direction
	Planet268 - direction
	Phenomenon269 - direction
	Phenomenon270 - direction
	Phenomenon271 - direction
	Phenomenon272 - direction
	Phenomenon273 - direction
	Phenomenon274 - direction
	Phenomenon275 - direction
	Planet276 - direction
	Phenomenon277 - direction
	Planet278 - direction
	Planet279 - direction
	Star280 - direction
	Star281 - direction
	Planet282 - direction
	Planet283 - direction
	Phenomenon284 - direction
	Planet285 - direction
	Star286 - direction
	Planet287 - direction
	Phenomenon288 - direction
	Star289 - direction
	Phenomenon290 - direction
	Star291 - direction
	Planet292 - direction
	Phenomenon293 - direction
	Star294 - direction
	Phenomenon295 - direction
	Phenomenon296 - direction
	Planet297 - direction
	Star298 - direction
	Planet299 - direction
	Star300 - direction
	Phenomenon301 - direction
	Star302 - direction
	Planet303 - direction
	Phenomenon304 - direction
	Star305 - direction
	Star306 - direction
	Planet307 - direction
	Planet308 - direction
	Star309 - direction
	Phenomenon310 - direction
	Planet311 - direction
	Star312 - direction
	Star313 - direction
	Phenomenon314 - direction
	Star315 - direction
	Planet316 - direction
	Planet317 - direction
	Planet318 - direction
	Phenomenon319 - direction
	Star320 - direction
	Planet321 - direction
	Star322 - direction
	Planet323 - direction
	Star324 - direction
	Phenomenon325 - direction
	Star326 - direction
	Phenomenon327 - direction
	Star328 - direction
	Phenomenon329 - direction
	Planet330 - direction
	Phenomenon331 - direction
	Planet332 - direction
	Phenomenon333 - direction
	Phenomenon334 - direction
	Planet335 - direction
	Planet336 - direction
	Planet337 - direction
	Phenomenon338 - direction
	Phenomenon339 - direction
	Planet340 - direction
	Planet341 - direction
	Phenomenon342 - direction
	Planet343 - direction
	Phenomenon344 - direction
	Planet345 - direction
	Phenomenon346 - direction
	Phenomenon347 - direction
	Planet348 - direction
	Phenomenon349 - direction
	Phenomenon350 - direction
	Phenomenon351 - direction
	Phenomenon352 - direction
	Planet353 - direction
	Phenomenon354 - direction
	Star355 - direction
	Phenomenon356 - direction
	Planet357 - direction
	Planet358 - direction
	Planet359 - direction
	Phenomenon360 - direction
	Star361 - direction
	Planet362 - direction
	Phenomenon363 - direction
	Planet364 - direction
	Planet365 - direction
	Star366 - direction
	Phenomenon367 - direction
	Planet368 - direction
	Star369 - direction
	Planet370 - direction
	Planet371 - direction
	Star372 - direction
	Planet373 - direction
	Planet374 - direction
	Phenomenon375 - direction
	Planet376 - direction
	Star377 - direction
	Star378 - direction
	Phenomenon379 - direction
	Planet380 - direction
	Planet381 - direction
	Phenomenon382 - direction
	Star383 - direction
	Star384 - direction
	Phenomenon385 - direction
	Phenomenon386 - direction
	Planet387 - direction
	Phenomenon388 - direction
	Planet389 - direction
	Planet390 - direction
	Phenomenon391 - direction
	Star392 - direction
	Phenomenon393 - direction
	Phenomenon394 - direction
	Star395 - direction
	Phenomenon396 - direction
	Planet397 - direction
	Star398 - direction
	Star399 - direction
	Planet400 - direction
	Phenomenon401 - direction
	Planet402 - direction
	Star403 - direction
	Star404 - direction
	Phenomenon405 - direction
	Planet406 - direction
	Phenomenon407 - direction
)
(:init
	(supports instrument0 image5)
	(supports instrument0 image4)
	(supports instrument0 infrared3)
	(calibration_target instrument0 GroundStation8)
	(calibration_target instrument0 Star33)
	(calibration_target instrument0 GroundStation75)
	(calibration_target instrument0 Star83)
	(calibration_target instrument0 Star202)
	(calibration_target instrument0 Star11)
	(calibration_target instrument0 Star88)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 GroundStation139)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star68)
	(supports instrument1 image5)
	(calibration_target instrument1 GroundStation16)
	(calibration_target instrument1 GroundStation26)
	(calibration_target instrument1 GroundStation98)
	(calibration_target instrument1 Star28)
	(calibration_target instrument1 Star61)
	(calibration_target instrument1 GroundStation173)
	(calibration_target instrument1 GroundStation114)
	(calibration_target instrument1 Star58)
	(calibration_target instrument1 Star184)
	(calibration_target instrument1 Star200)
	(calibration_target instrument1 Star74)
	(calibration_target instrument1 Star119)
	(calibration_target instrument1 GroundStation163)
	(calibration_target instrument1 Star172)
	(calibration_target instrument1 Star165)
	(calibration_target instrument1 Star15)
	(calibration_target instrument1 GroundStation90)
	(calibration_target instrument1 Star148)
	(calibration_target instrument1 GroundStation85)
	(calibration_target instrument1 Star48)
	(calibration_target instrument1 GroundStation108)
	(calibration_target instrument1 Star42)
	(supports instrument2 spectrograph6)
	(calibration_target instrument2 Star150)
	(calibration_target instrument2 Star0)
	(calibration_target instrument2 GroundStation173)
	(calibration_target instrument2 GroundStation201)
	(calibration_target instrument2 Star121)
	(calibration_target instrument2 GroundStation40)
	(calibration_target instrument2 Star61)
	(calibration_target instrument2 GroundStation30)
	(calibration_target instrument2 Star45)
	(calibration_target instrument2 GroundStation10)
	(calibration_target instrument2 Star155)
	(calibration_target instrument2 Star178)
	(calibration_target instrument2 GroundStation38)
	(calibration_target instrument2 GroundStation20)
	(calibration_target instrument2 GroundStation147)
	(calibration_target instrument2 Star80)
	(calibration_target instrument2 Star145)
	(calibration_target instrument2 Star165)
	(calibration_target instrument2 GroundStation143)
	(calibration_target instrument2 Star103)
	(calibration_target instrument2 GroundStation18)
	(calibration_target instrument2 Star102)
	(calibration_target instrument2 Star120)
	(calibration_target instrument2 Star14)
	(calibration_target instrument2 GroundStation43)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 GroundStation142)
	(calibration_target instrument2 Star161)
	(calibration_target instrument2 Star31)
	(calibration_target instrument2 GroundStation108)
	(calibration_target instrument2 GroundStation64)
	(calibration_target instrument2 GroundStation179)
	(calibration_target instrument2 Star42)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 Star137)
	(calibration_target instrument2 GroundStation99)
	(calibration_target instrument2 Star93)
	(calibration_target instrument2 Star133)
	(calibration_target instrument2 Star126)
	(calibration_target instrument2 GroundStation131)
	(supports instrument3 image4)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 GroundStation118)
	(calibration_target instrument3 Star7)
	(calibration_target instrument3 Star31)
	(calibration_target instrument3 GroundStation1)
	(calibration_target instrument3 GroundStation174)
	(calibration_target instrument3 Star48)
	(calibration_target instrument3 GroundStation85)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 Star133)
	(calibration_target instrument3 GroundStation59)
	(calibration_target instrument3 Star100)
	(calibration_target instrument3 Star46)
	(calibration_target instrument3 GroundStation66)
	(calibration_target instrument3 Star19)
	(calibration_target instrument3 GroundStation16)
	(calibration_target instrument3 Star74)
	(calibration_target instrument3 GroundStation87)
	(calibration_target instrument3 Star5)
	(calibration_target instrument3 GroundStation147)
	(calibration_target instrument3 Star194)
	(calibration_target instrument3 Star156)
	(calibration_target instrument3 GroundStation99)
	(calibration_target instrument3 GroundStation81)
	(calibration_target instrument3 Star14)
	(calibration_target instrument3 Star119)
	(calibration_target instrument3 GroundStation198)
	(calibration_target instrument3 GroundStation32)
	(calibration_target instrument3 GroundStation115)
	(calibration_target instrument3 Star111)
	(calibration_target instrument3 GroundStation57)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 GroundStation90)
	(calibration_target instrument3 Star68)
	(calibration_target instrument3 GroundStation43)
	(calibration_target instrument3 Star15)
	(calibration_target instrument3 GroundStation163)
	(calibration_target instrument3 GroundStation180)
	(calibration_target instrument3 Star144)
	(calibration_target instrument3 Star172)
	(calibration_target instrument3 Star128)
	(calibration_target instrument3 Star189)
	(calibration_target instrument3 GroundStation29)
	(calibration_target instrument3 Star164)
	(calibration_target instrument3 GroundStation64)
	(calibration_target instrument3 GroundStation47)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet390)
	(supports instrument4 thermograph1)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 Star101)
	(calibration_target instrument4 Star79)
	(calibration_target instrument4 GroundStation108)
	(calibration_target instrument4 GroundStation77)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 GroundStation17)
	(calibration_target instrument4 Star182)
	(calibration_target instrument4 Star157)
	(calibration_target instrument4 GroundStation90)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 Star136)
	(calibration_target instrument4 Star78)
	(calibration_target instrument4 GroundStation26)
	(calibration_target instrument4 GroundStation179)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 Star111)
	(supports instrument5 spectrograph6)
	(supports instrument5 thermograph1)
	(supports instrument5 infrared3)
	(calibration_target instrument5 Star135)
	(calibration_target instrument5 Star149)
	(calibration_target instrument5 Star91)
	(calibration_target instrument5 Star155)
	(calibration_target instrument5 Star33)
	(calibration_target instrument5 Star156)
	(supports instrument6 image5)
	(supports instrument6 infrared3)
	(calibration_target instrument6 GroundStation43)
	(calibration_target instrument6 GroundStation99)
	(calibration_target instrument6 Star110)
	(calibration_target instrument6 Star168)
	(calibration_target instrument6 Star86)
	(calibration_target instrument6 GroundStation186)
	(calibration_target instrument6 GroundStation53)
	(calibration_target instrument6 Star199)
	(calibration_target instrument6 Star133)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 Star181)
	(calibration_target instrument6 Star196)
	(calibration_target instrument6 Star79)
	(calibration_target instrument6 Star78)
	(calibration_target instrument6 GroundStation131)
	(calibration_target instrument6 Star123)
	(calibration_target instrument6 Star112)
	(calibration_target instrument6 GroundStation163)
	(calibration_target instrument6 GroundStation77)
	(calibration_target instrument6 GroundStation198)
	(calibration_target instrument6 Star93)
	(calibration_target instrument6 GroundStation117)
	(calibration_target instrument6 Star67)
	(calibration_target instrument6 GroundStation106)
	(calibration_target instrument6 Star121)
	(calibration_target instrument6 GroundStation3)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 GroundStation54)
	(calibration_target instrument6 GroundStation153)
	(calibration_target instrument6 Star185)
	(calibration_target instrument6 GroundStation23)
	(calibration_target instrument6 GroundStation107)
	(calibration_target instrument6 GroundStation96)
	(calibration_target instrument6 GroundStation134)
	(calibration_target instrument6 Star145)
	(calibration_target instrument6 Star183)
	(calibration_target instrument6 Star128)
	(calibration_target instrument6 GroundStation180)
	(calibration_target instrument6 Star31)
	(calibration_target instrument6 Star42)
	(calibration_target instrument6 GroundStation32)
	(calibration_target instrument6 GroundStation130)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 Star189)
	(calibration_target instrument6 GroundStation92)
	(calibration_target instrument6 GroundStation142)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 GroundStation197)
	(calibration_target instrument6 Star152)
	(calibration_target instrument6 Star101)
	(calibration_target instrument6 Star113)
	(calibration_target instrument6 GroundStation179)
	(calibration_target instrument6 Star97)
	(calibration_target instrument6 GroundStation176)
	(calibration_target instrument6 GroundStation62)
	(calibration_target instrument6 Star136)
	(calibration_target instrument6 Star187)
	(calibration_target instrument6 Star155)
	(calibration_target instrument6 GroundStation12)
	(calibration_target instrument6 Star144)
	(calibration_target instrument6 GroundStation175)
	(calibration_target instrument6 Star36)
	(calibration_target instrument6 Star156)
	(supports instrument7 spectrograph6)
	(supports instrument7 infrared2)
	(supports instrument7 image4)
	(calibration_target instrument7 GroundStation118)
	(calibration_target instrument7 Star148)
	(calibration_target instrument7 Star187)
	(calibration_target instrument7 GroundStation169)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 Star70)
	(calibration_target instrument7 Star193)
	(calibration_target instrument7 GroundStation198)
	(calibration_target instrument7 Star191)
	(calibration_target instrument7 Star116)
	(calibration_target instrument7 Star137)
	(supports instrument8 infrared3)
	(supports instrument8 thermograph1)
	(supports instrument8 image4)
	(calibration_target instrument8 Star193)
	(calibration_target instrument8 Star149)
	(calibration_target instrument8 GroundStation62)
	(calibration_target instrument8 Star89)
	(calibration_target instrument8 Star190)
	(calibration_target instrument8 GroundStation35)
	(calibration_target instrument8 Star93)
	(calibration_target instrument8 GroundStation87)
	(calibration_target instrument8 GroundStation37)
	(calibration_target instrument8 GroundStation43)
	(calibration_target instrument8 Star185)
	(calibration_target instrument8 Star168)
	(calibration_target instrument8 GroundStation162)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 GroundStation75)
	(calibration_target instrument8 GroundStation64)
	(calibration_target instrument8 GroundStation71)
	(calibration_target instrument8 GroundStation26)
	(calibration_target instrument8 Star7)
	(calibration_target instrument8 Star135)
	(calibration_target instrument8 GroundStation143)
	(calibration_target instrument8 Star111)
	(calibration_target instrument8 GroundStation115)
	(calibration_target instrument8 GroundStation171)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star214)
	(supports instrument9 infrared2)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 Star93)
	(calibration_target instrument9 GroundStation62)
	(calibration_target instrument9 GroundStation98)
	(calibration_target instrument9 Star52)
	(calibration_target instrument9 Star88)
	(calibration_target instrument9 Star190)
	(calibration_target instrument9 Star160)
	(calibration_target instrument9 Star78)
	(calibration_target instrument9 Star128)
	(calibration_target instrument9 Star121)
	(calibration_target instrument9 GroundStation99)
	(calibration_target instrument9 Star68)
	(calibration_target instrument9 GroundStation167)
	(calibration_target instrument9 GroundStation96)
	(calibration_target instrument9 GroundStation94)
	(calibration_target instrument9 GroundStation71)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star76)
	(calibration_target instrument9 GroundStation69)
	(calibration_target instrument9 GroundStation59)
	(calibration_target instrument9 GroundStation32)
	(calibration_target instrument9 GroundStation169)
	(supports instrument10 spectrograph6)
	(supports instrument10 spectrograph0)
	(supports instrument10 image4)
	(calibration_target instrument10 Star83)
	(calibration_target instrument10 GroundStation162)
	(calibration_target instrument10 GroundStation12)
	(calibration_target instrument10 Star105)
	(calibration_target instrument10 GroundStation94)
	(calibration_target instrument10 GroundStation141)
	(calibration_target instrument10 GroundStation173)
	(calibration_target instrument10 Star84)
	(calibration_target instrument10 Star93)
	(calibration_target instrument10 Star56)
	(calibration_target instrument10 GroundStation54)
	(calibration_target instrument10 GroundStation177)
	(calibration_target instrument10 Star157)
	(calibration_target instrument10 GroundStation154)
	(calibration_target instrument10 Star172)
	(calibration_target instrument10 GroundStation62)
	(calibration_target instrument10 GroundStation139)
	(calibration_target instrument10 Star111)
	(calibration_target instrument10 Star91)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation39)
	(calibration_target instrument10 Star112)
	(calibration_target instrument10 GroundStation174)
	(calibration_target instrument10 Star104)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 GroundStation131)
	(calibration_target instrument10 Star193)
	(calibration_target instrument10 GroundStation63)
	(calibration_target instrument10 GroundStation75)
	(calibration_target instrument10 Star58)
	(calibration_target instrument10 GroundStation71)
	(calibration_target instrument10 GroundStation65)
	(calibration_target instrument10 Star72)
	(calibration_target instrument10 GroundStation90)
	(calibration_target instrument10 Star188)
	(calibration_target instrument10 Star21)
	(calibration_target instrument10 GroundStation134)
	(calibration_target instrument10 Star152)
	(calibration_target instrument10 GroundStation124)
	(calibration_target instrument10 GroundStation107)
	(calibration_target instrument10 GroundStation143)
	(calibration_target instrument10 Star116)
	(calibration_target instrument10 Star135)
	(calibration_target instrument10 Star80)
	(calibration_target instrument10 GroundStation96)
	(calibration_target instrument10 Star192)
	(calibration_target instrument10 Star165)
	(calibration_target instrument10 Star140)
	(calibration_target instrument10 GroundStation98)
	(calibration_target instrument10 GroundStation198)
	(calibration_target instrument10 Star31)
	(calibration_target instrument10 GroundStation34)
	(calibration_target instrument10 GroundStation17)
	(calibration_target instrument10 GroundStation73)
	(calibration_target instrument10 GroundStation146)
	(calibration_target instrument10 Star148)
	(calibration_target instrument10 Star137)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation37)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon363)
	(supports instrument11 thermograph1)
	(supports instrument11 image4)
	(calibration_target instrument11 Star31)
	(calibration_target instrument11 GroundStation139)
	(calibration_target instrument11 Star202)
	(calibration_target instrument11 GroundStation71)
	(supports instrument12 infrared3)
	(supports instrument12 infrared2)
	(supports instrument12 image4)
	(calibration_target instrument12 GroundStation99)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 GroundStation130)
	(calibration_target instrument12 Star138)
	(calibration_target instrument12 Star104)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 Star33)
	(calibration_target instrument12 GroundStation201)
	(calibration_target instrument12 Star103)
	(calibration_target instrument12 GroundStation147)
	(calibration_target instrument12 GroundStation54)
	(calibration_target instrument12 Star36)
	(calibration_target instrument12 Star78)
	(calibration_target instrument12 GroundStation167)
	(calibration_target instrument12 Star192)
	(calibration_target instrument12 Star188)
	(calibration_target instrument12 Star5)
	(calibration_target instrument12 GroundStation134)
	(calibration_target instrument12 GroundStation171)
	(calibration_target instrument12 GroundStation38)
	(calibration_target instrument12 GroundStation141)
	(calibration_target instrument12 Star42)
	(calibration_target instrument12 GroundStation169)
	(calibration_target instrument12 GroundStation197)
	(calibration_target instrument12 Star128)
	(calibration_target instrument12 GroundStation158)
	(calibration_target instrument12 Star194)
	(calibration_target instrument12 GroundStation65)
	(calibration_target instrument12 Star101)
	(calibration_target instrument12 Star91)
	(calibration_target instrument12 Star155)
	(calibration_target instrument12 Star82)
	(calibration_target instrument12 GroundStation114)
	(calibration_target instrument12 Star135)
	(calibration_target instrument12 Star184)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 GroundStation198)
	(supports instrument13 infrared2)
	(calibration_target instrument13 GroundStation37)
	(calibration_target instrument13 Star192)
	(calibration_target instrument13 GroundStation177)
	(calibration_target instrument13 Star79)
	(calibration_target instrument13 Star100)
	(calibration_target instrument13 Star190)
	(calibration_target instrument13 GroundStation124)
	(calibration_target instrument13 Star15)
	(calibration_target instrument13 GroundStation173)
	(calibration_target instrument13 Star137)
	(calibration_target instrument13 Star156)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 GroundStation153)
	(calibration_target instrument13 Star111)
	(calibration_target instrument13 Star165)
	(calibration_target instrument13 GroundStation26)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 Star102)
	(calibration_target instrument13 Star123)
	(calibration_target instrument13 GroundStation171)
	(calibration_target instrument13 GroundStation174)
	(calibration_target instrument13 Star109)
	(calibration_target instrument13 GroundStation95)
	(calibration_target instrument13 GroundStation87)
	(calibration_target instrument13 Star152)
	(calibration_target instrument13 GroundStation147)
	(calibration_target instrument13 GroundStation115)
	(calibration_target instrument13 Star149)
	(calibration_target instrument13 GroundStation175)
	(calibration_target instrument13 GroundStation176)
	(calibration_target instrument13 GroundStation53)
	(calibration_target instrument13 Star101)
	(calibration_target instrument13 GroundStation29)
	(calibration_target instrument13 Star61)
	(calibration_target instrument13 Star182)
	(calibration_target instrument13 GroundStation64)
	(calibration_target instrument13 GroundStation94)
	(calibration_target instrument13 Star188)
	(calibration_target instrument13 GroundStation75)
	(calibration_target instrument13 GroundStation69)
	(calibration_target instrument13 GroundStation35)
	(calibration_target instrument13 Star103)
	(calibration_target instrument13 Star83)
	(calibration_target instrument13 Star194)
	(calibration_target instrument13 Star58)
	(calibration_target instrument13 GroundStation163)
	(calibration_target instrument13 GroundStation180)
	(calibration_target instrument13 GroundStation167)
	(calibration_target instrument13 Star160)
	(calibration_target instrument13 GroundStation154)
	(calibration_target instrument13 Star135)
	(calibration_target instrument13 GroundStation85)
	(calibration_target instrument13 Star202)
	(calibration_target instrument13 GroundStation197)
	(calibration_target instrument13 Star84)
	(calibration_target instrument13 GroundStation186)
	(calibration_target instrument13 Star184)
	(calibration_target instrument13 Star119)
	(calibration_target instrument13 GroundStation130)
	(calibration_target instrument13 Star166)
	(calibration_target instrument13 GroundStation32)
	(calibration_target instrument13 Star67)
	(supports instrument14 infrared2)
	(calibration_target instrument14 Star168)
	(calibration_target instrument14 Star76)
	(calibration_target instrument14 Star135)
	(calibration_target instrument14 Star101)
	(calibration_target instrument14 Star83)
	(calibration_target instrument14 GroundStation147)
	(calibration_target instrument14 GroundStation177)
	(calibration_target instrument14 GroundStation132)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star78)
	(calibration_target instrument14 Star152)
	(calibration_target instrument14 GroundStation131)
	(calibration_target instrument14 Star144)
	(calibration_target instrument14 GroundStation30)
	(calibration_target instrument14 GroundStation49)
	(calibration_target instrument14 Star68)
	(calibration_target instrument14 Star184)
	(calibration_target instrument14 GroundStation96)
	(calibration_target instrument14 Star24)
	(calibration_target instrument14 Star193)
	(calibration_target instrument14 GroundStation114)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 GroundStation106)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation115)
	(calibration_target instrument14 GroundStation108)
	(calibration_target instrument14 GroundStation117)
	(calibration_target instrument14 GroundStation39)
	(calibration_target instrument14 Star2)
	(calibration_target instrument14 Star150)
	(calibration_target instrument14 Star55)
	(calibration_target instrument14 GroundStation65)
	(calibration_target instrument14 Star105)
	(calibration_target instrument14 Star103)
	(calibration_target instrument14 GroundStation17)
	(calibration_target instrument14 Star70)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star61)
	(supports instrument15 image4)
	(supports instrument15 infrared2)
	(calibration_target instrument15 GroundStation65)
	(calibration_target instrument15 GroundStation39)
	(calibration_target instrument15 Star103)
	(calibration_target instrument15 Star68)
	(calibration_target instrument15 Star125)
	(calibration_target instrument15 GroundStation175)
	(calibration_target instrument15 GroundStation169)
	(calibration_target instrument15 Star157)
	(calibration_target instrument15 Star102)
	(calibration_target instrument15 GroundStation47)
	(calibration_target instrument15 Star56)
	(calibration_target instrument15 Star88)
	(calibration_target instrument15 Star33)
	(calibration_target instrument15 GroundStation106)
	(calibration_target instrument15 GroundStation22)
	(calibration_target instrument15 Star202)
	(calibration_target instrument15 Star19)
	(calibration_target instrument15 GroundStation130)
	(supports instrument16 infrared2)
	(supports instrument16 infrared3)
	(calibration_target instrument16 GroundStation22)
	(calibration_target instrument16 GroundStation92)
	(calibration_target instrument16 Star67)
	(calibration_target instrument16 Star42)
	(calibration_target instrument16 Star28)
	(calibration_target instrument16 Star2)
	(calibration_target instrument16 Star126)
	(calibration_target instrument16 Star184)
	(calibration_target instrument16 GroundStation90)
	(calibration_target instrument16 Star203)
	(calibration_target instrument16 Star119)
	(calibration_target instrument16 Star194)
	(calibration_target instrument16 Star187)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Planet245)
	(supports instrument17 image4)
	(supports instrument17 spectrograph0)
	(supports instrument17 infrared3)
	(calibration_target instrument17 GroundStation179)
	(calibration_target instrument17 Star60)
	(calibration_target instrument17 Star202)
	(calibration_target instrument17 Star100)
	(calibration_target instrument17 GroundStation87)
	(calibration_target instrument17 Star74)
	(calibration_target instrument17 Star183)
	(calibration_target instrument17 GroundStation54)
	(calibration_target instrument17 GroundStation26)
	(calibration_target instrument17 GroundStation167)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 GroundStation139)
	(calibration_target instrument17 Star58)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star123)
	(calibration_target instrument17 GroundStation163)
	(calibration_target instrument17 GroundStation38)
	(calibration_target instrument17 Star136)
	(calibration_target instrument17 GroundStation106)
	(calibration_target instrument17 GroundStation176)
	(calibration_target instrument17 GroundStation141)
	(calibration_target instrument17 Star68)
	(calibration_target instrument17 Star119)
	(calibration_target instrument17 Star79)
	(calibration_target instrument17 Star48)
	(calibration_target instrument17 Star152)
	(calibration_target instrument17 Star172)
	(calibration_target instrument17 Star36)
	(calibration_target instrument17 Star155)
	(calibration_target instrument17 Star46)
	(calibration_target instrument17 GroundStation171)
	(calibration_target instrument17 GroundStation201)
	(calibration_target instrument17 GroundStation170)
	(calibration_target instrument17 GroundStation73)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 GroundStation23)
	(calibration_target instrument17 GroundStation186)
	(calibration_target instrument17 GroundStation75)
	(calibration_target instrument17 Star101)
	(calibration_target instrument17 Star122)
	(calibration_target instrument17 GroundStation143)
	(calibration_target instrument17 Star61)
	(calibration_target instrument17 Star82)
	(calibration_target instrument17 GroundStation175)
	(calibration_target instrument17 GroundStation34)
	(calibration_target instrument17 Star161)
	(calibration_target instrument17 GroundStation134)
	(calibration_target instrument17 GroundStation131)
	(calibration_target instrument17 Star110)
	(calibration_target instrument17 Star148)
	(calibration_target instrument17 Star93)
	(calibration_target instrument17 GroundStation17)
	(calibration_target instrument17 Star133)
	(supports instrument18 infrared2)
	(supports instrument18 spectrograph0)
	(supports instrument18 image4)
	(calibration_target instrument18 Star46)
	(calibration_target instrument18 GroundStation47)
	(calibration_target instrument18 GroundStation59)
	(calibration_target instrument18 Star138)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 Star55)
	(calibration_target instrument18 Star74)
	(calibration_target instrument18 GroundStation143)
	(calibration_target instrument18 GroundStation39)
	(calibration_target instrument18 GroundStation118)
	(calibration_target instrument18 GroundStation131)
	(calibration_target instrument18 GroundStation198)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 Star82)
	(calibration_target instrument18 GroundStation17)
	(calibration_target instrument18 Star136)
	(calibration_target instrument18 Star11)
	(calibration_target instrument18 Star192)
	(calibration_target instrument18 GroundStation159)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star48)
	(supports instrument19 spectrograph0)
	(supports instrument19 infrared2)
	(supports instrument19 image5)
	(calibration_target instrument19 GroundStation64)
	(calibration_target instrument19 Star119)
	(calibration_target instrument19 GroundStation44)
	(calibration_target instrument19 Star101)
	(calibration_target instrument19 GroundStation158)
	(calibration_target instrument19 GroundStation95)
	(calibration_target instrument19 Star151)
	(calibration_target instrument19 GroundStation147)
	(calibration_target instrument19 GroundStation197)
	(calibration_target instrument19 Star129)
	(calibration_target instrument19 Star184)
	(calibration_target instrument19 Star83)
	(calibration_target instrument19 Star183)
	(calibration_target instrument19 Star182)
	(calibration_target instrument19 GroundStation143)
	(calibration_target instrument19 Star45)
	(calibration_target instrument19 GroundStation198)
	(calibration_target instrument19 Star202)
	(calibration_target instrument19 Star140)
	(calibration_target instrument19 GroundStation99)
	(calibration_target instrument19 GroundStation96)
	(calibration_target instrument19 Star19)
	(calibration_target instrument19 Star70)
	(calibration_target instrument19 Star137)
	(calibration_target instrument19 GroundStation29)
	(calibration_target instrument19 Star109)
	(calibration_target instrument19 GroundStation142)
	(calibration_target instrument19 GroundStation13)
	(calibration_target instrument19 GroundStation174)
	(calibration_target instrument19 Star128)
	(calibration_target instrument19 Star100)
	(calibration_target instrument19 Star172)
	(calibration_target instrument19 Star113)
	(calibration_target instrument19 GroundStation159)
	(calibration_target instrument19 Star144)
	(calibration_target instrument19 Star111)
	(calibration_target instrument19 Star41)
	(calibration_target instrument19 GroundStation130)
	(calibration_target instrument19 GroundStation131)
	(calibration_target instrument19 Star2)
	(calibration_target instrument19 Star102)
	(calibration_target instrument19 Star125)
	(calibration_target instrument19 GroundStation4)
	(calibration_target instrument19 Star190)
	(calibration_target instrument19 Star74)
	(calibration_target instrument19 GroundStation77)
	(calibration_target instrument19 GroundStation30)
	(calibration_target instrument19 GroundStation179)
	(calibration_target instrument19 GroundStation127)
	(calibration_target instrument19 GroundStation186)
	(calibration_target instrument19 GroundStation98)
	(calibration_target instrument19 Star76)
	(calibration_target instrument19 Star31)
	(supports instrument20 image4)
	(supports instrument20 spectrograph6)
	(supports instrument20 thermograph1)
	(calibration_target instrument20 GroundStation47)
	(calibration_target instrument20 Star60)
	(calibration_target instrument20 Star102)
	(calibration_target instrument20 Star79)
	(calibration_target instrument20 GroundStation29)
	(calibration_target instrument20 GroundStation146)
	(calibration_target instrument20 GroundStation43)
	(calibration_target instrument20 Star116)
	(calibration_target instrument20 GroundStation163)
	(calibration_target instrument20 Star67)
	(calibration_target instrument20 Star129)
	(calibration_target instrument20 Star194)
	(calibration_target instrument20 Star110)
	(calibration_target instrument20 GroundStation44)
	(calibration_target instrument20 GroundStation77)
	(calibration_target instrument20 Star199)
	(calibration_target instrument20 Star125)
	(calibration_target instrument20 GroundStation9)
	(calibration_target instrument20 GroundStation106)
	(calibration_target instrument20 GroundStation198)
	(calibration_target instrument20 Star164)
	(calibration_target instrument20 Star123)
	(calibration_target instrument20 Star45)
	(calibration_target instrument20 GroundStation175)
	(calibration_target instrument20 GroundStation124)
	(calibration_target instrument20 GroundStation85)
	(calibration_target instrument20 GroundStation177)
	(calibration_target instrument20 GroundStation142)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation176)
	(calibration_target instrument21 GroundStation98)
	(calibration_target instrument21 GroundStation159)
	(calibration_target instrument21 Star74)
	(calibration_target instrument21 Star45)
	(calibration_target instrument21 Star182)
	(calibration_target instrument21 Star42)
	(calibration_target instrument21 Star60)
	(calibration_target instrument21 GroundStation57)
	(calibration_target instrument21 GroundStation117)
	(calibration_target instrument21 GroundStation53)
	(calibration_target instrument21 Star125)
	(calibration_target instrument21 GroundStation127)
	(calibration_target instrument21 GroundStation23)
	(calibration_target instrument21 Star160)
	(calibration_target instrument21 GroundStation6)
	(calibration_target instrument21 GroundStation131)
	(calibration_target instrument21 Star24)
	(calibration_target instrument21 Star68)
	(calibration_target instrument21 Star111)
	(calibration_target instrument21 GroundStation22)
	(calibration_target instrument21 Star121)
	(calibration_target instrument21 GroundStation59)
	(calibration_target instrument21 Star11)
	(calibration_target instrument21 Star33)
	(calibration_target instrument21 GroundStation201)
	(calibration_target instrument21 GroundStation173)
	(calibration_target instrument21 Star194)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 Star103)
	(calibration_target instrument21 Star56)
	(supports instrument22 infrared2)
	(calibration_target instrument22 GroundStation173)
	(calibration_target instrument22 GroundStation154)
	(calibration_target instrument22 GroundStation35)
	(calibration_target instrument22 GroundStation107)
	(calibration_target instrument22 Star72)
	(calibration_target instrument22 GroundStation32)
	(calibration_target instrument22 Star119)
	(calibration_target instrument22 Star126)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 Star74)
	(calibration_target instrument22 GroundStation20)
	(calibration_target instrument22 GroundStation94)
	(calibration_target instrument22 GroundStation44)
	(calibration_target instrument22 Star48)
	(calibration_target instrument22 Star184)
	(calibration_target instrument22 Star80)
	(calibration_target instrument22 Star76)
	(calibration_target instrument22 Star113)
	(calibration_target instrument22 GroundStation13)
	(calibration_target instrument22 Star168)
	(calibration_target instrument22 Star185)
	(supports instrument23 infrared2)
	(supports instrument23 spectrograph6)
	(calibration_target instrument23 GroundStation63)
	(calibration_target instrument23 GroundStation162)
	(calibration_target instrument23 GroundStation201)
	(calibration_target instrument23 Star79)
	(calibration_target instrument23 Star136)
	(calibration_target instrument23 GroundStation98)
	(calibration_target instrument23 Star150)
	(calibration_target instrument23 GroundStation51)
	(calibration_target instrument23 Star68)
	(calibration_target instrument23 Star190)
	(calibration_target instrument23 GroundStation39)
	(calibration_target instrument23 GroundStation20)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(on_board instrument23 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star125)
	(supports instrument24 spectrograph6)
	(calibration_target instrument24 Star196)
	(calibration_target instrument24 Star105)
	(calibration_target instrument24 Star137)
	(calibration_target instrument24 Star133)
	(calibration_target instrument24 GroundStation115)
	(calibration_target instrument24 GroundStation170)
	(calibration_target instrument24 GroundStation53)
	(calibration_target instrument24 GroundStation163)
	(calibration_target instrument24 GroundStation90)
	(calibration_target instrument24 GroundStation6)
	(calibration_target instrument24 GroundStation124)
	(calibration_target instrument24 Star123)
	(calibration_target instrument24 GroundStation174)
	(calibration_target instrument24 GroundStation35)
	(calibration_target instrument24 Star101)
	(calibration_target instrument24 Star88)
	(calibration_target instrument24 Star0)
	(calibration_target instrument24 Star155)
	(calibration_target instrument24 Star149)
	(calibration_target instrument24 GroundStation59)
	(calibration_target instrument24 GroundStation37)
	(calibration_target instrument24 GroundStation26)
	(calibration_target instrument24 Star68)
	(calibration_target instrument24 Star78)
	(calibration_target instrument24 Star86)
	(calibration_target instrument24 GroundStation12)
	(calibration_target instrument24 Star80)
	(calibration_target instrument24 Star190)
	(calibration_target instrument24 Star2)
	(calibration_target instrument24 GroundStation85)
	(calibration_target instrument24 Star151)
	(calibration_target instrument24 Star140)
	(calibration_target instrument24 Star45)
	(calibration_target instrument24 Star52)
	(calibration_target instrument24 Star168)
	(calibration_target instrument24 Star178)
	(calibration_target instrument24 GroundStation8)
	(calibration_target instrument24 GroundStation106)
	(calibration_target instrument24 Star56)
	(calibration_target instrument24 Star194)
	(calibration_target instrument24 GroundStation54)
	(calibration_target instrument24 Star122)
	(calibration_target instrument24 GroundStation171)
	(calibration_target instrument24 GroundStation154)
	(supports instrument25 infrared3)
	(calibration_target instrument25 Star202)
	(calibration_target instrument25 Star145)
	(calibration_target instrument25 Star150)
	(calibration_target instrument25 Star199)
	(calibration_target instrument25 Star33)
	(calibration_target instrument25 GroundStation143)
	(calibration_target instrument25 GroundStation117)
	(calibration_target instrument25 Star110)
	(calibration_target instrument25 GroundStation154)
	(calibration_target instrument25 GroundStation96)
	(calibration_target instrument25 GroundStation132)
	(calibration_target instrument25 Star67)
	(calibration_target instrument25 Star160)
	(calibration_target instrument25 Star187)
	(calibration_target instrument25 GroundStation49)
	(calibration_target instrument25 Star195)
	(calibration_target instrument25 Star157)
	(calibration_target instrument25 Star189)
	(calibration_target instrument25 Star100)
	(calibration_target instrument25 GroundStation175)
	(calibration_target instrument25 GroundStation139)
	(calibration_target instrument25 GroundStation43)
	(calibration_target instrument25 GroundStation38)
	(calibration_target instrument25 Star5)
	(calibration_target instrument25 GroundStation10)
	(calibration_target instrument25 GroundStation12)
	(calibration_target instrument25 Star165)
	(calibration_target instrument25 Star149)
	(calibration_target instrument25 GroundStation66)
	(calibration_target instrument25 Star140)
	(calibration_target instrument25 Star56)
	(calibration_target instrument25 GroundStation198)
	(calibration_target instrument25 GroundStation59)
	(calibration_target instrument25 Star103)
	(calibration_target instrument25 GroundStation25)
	(calibration_target instrument25 GroundStation95)
	(calibration_target instrument25 Star137)
	(calibration_target instrument25 GroundStation159)
	(calibration_target instrument25 Star133)
	(calibration_target instrument25 GroundStation201)
	(calibration_target instrument25 Star7)
	(calibration_target instrument25 GroundStation114)
	(calibration_target instrument25 Star58)
	(calibration_target instrument25 Star48)
	(calibration_target instrument25 Star144)
	(calibration_target instrument25 Star164)
	(calibration_target instrument25 Star74)
	(calibration_target instrument25 GroundStation57)
	(calibration_target instrument25 Star11)
	(calibration_target instrument25 GroundStation27)
	(calibration_target instrument25 Star112)
	(calibration_target instrument25 GroundStation85)
	(calibration_target instrument25 Star60)
	(calibration_target instrument25 GroundStation179)
	(calibration_target instrument25 GroundStation69)
	(calibration_target instrument25 Star155)
	(calibration_target instrument25 Star148)
	(calibration_target instrument25 GroundStation87)
	(calibration_target instrument25 Star194)
	(calibration_target instrument25 Star36)
	(calibration_target instrument25 Star166)
	(calibration_target instrument25 GroundStation127)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star31)
	(calibration_target instrument26 GroundStation81)
	(calibration_target instrument26 GroundStation162)
	(calibration_target instrument26 Star7)
	(calibration_target instrument26 GroundStation26)
	(calibration_target instrument26 Star125)
	(calibration_target instrument26 Star137)
	(calibration_target instrument26 GroundStation198)
	(calibration_target instrument26 GroundStation94)
	(calibration_target instrument26 GroundStation154)
	(calibration_target instrument26 Star156)
	(calibration_target instrument26 Star61)
	(calibration_target instrument26 GroundStation139)
	(calibration_target instrument26 GroundStation40)
	(calibration_target instrument26 GroundStation153)
	(calibration_target instrument26 GroundStation87)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 GroundStation71)
	(calibration_target instrument26 Star181)
	(calibration_target instrument26 GroundStation23)
	(calibration_target instrument26 GroundStation186)
	(calibration_target instrument26 GroundStation69)
	(calibration_target instrument26 GroundStation107)
	(calibration_target instrument26 GroundStation12)
	(calibration_target instrument26 Star86)
	(calibration_target instrument26 GroundStation75)
	(calibration_target instrument26 Star28)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 Star128)
	(calibration_target instrument26 Star191)
	(calibration_target instrument26 Star11)
	(calibration_target instrument26 GroundStation51)
	(calibration_target instrument26 GroundStation62)
	(calibration_target instrument26 Star83)
	(calibration_target instrument26 GroundStation158)
	(calibration_target instrument26 GroundStation115)
	(supports instrument27 image4)
	(supports instrument27 infrared2)
	(calibration_target instrument27 GroundStation71)
	(calibration_target instrument27 GroundStation30)
	(calibration_target instrument27 Star60)
	(calibration_target instrument27 GroundStation63)
	(calibration_target instrument27 GroundStation186)
	(calibration_target instrument27 Star111)
	(calibration_target instrument27 GroundStation167)
	(calibration_target instrument27 Star113)
	(calibration_target instrument27 GroundStation37)
	(calibration_target instrument27 Star187)
	(calibration_target instrument27 GroundStation20)
	(calibration_target instrument27 Star11)
	(calibration_target instrument27 Star88)
	(calibration_target instrument27 GroundStation25)
	(calibration_target instrument27 Star45)
	(calibration_target instrument27 Star116)
	(calibration_target instrument27 Star5)
	(calibration_target instrument27 Star166)
	(calibration_target instrument27 Star93)
	(calibration_target instrument27 Star97)
	(calibration_target instrument27 GroundStation198)
	(supports instrument28 thermograph1)
	(supports instrument28 image5)
	(supports instrument28 spectrograph6)
	(calibration_target instrument28 GroundStation115)
	(calibration_target instrument28 Star166)
	(calibration_target instrument28 GroundStation23)
	(calibration_target instrument28 Star191)
	(calibration_target instrument28 Star125)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 GroundStation12)
	(calibration_target instrument28 Star184)
	(calibration_target instrument28 Star152)
	(calibration_target instrument28 Star60)
	(calibration_target instrument28 Star119)
	(calibration_target instrument28 GroundStation35)
	(calibration_target instrument28 Star165)
	(calibration_target instrument28 Star137)
	(calibration_target instrument28 Star193)
	(calibration_target instrument28 GroundStation147)
	(calibration_target instrument28 Star58)
	(calibration_target instrument28 Star182)
	(calibration_target instrument28 Star183)
	(calibration_target instrument28 Star70)
	(calibration_target instrument28 GroundStation139)
	(calibration_target instrument28 GroundStation98)
	(calibration_target instrument28 Star55)
	(calibration_target instrument28 GroundStation26)
	(calibration_target instrument28 GroundStation47)
	(calibration_target instrument28 Star194)
	(calibration_target instrument28 Star145)
	(calibration_target instrument28 Star189)
	(calibration_target instrument28 Star112)
	(calibration_target instrument28 Star135)
	(calibration_target instrument28 Star136)
	(calibration_target instrument28 GroundStation131)
	(calibration_target instrument28 Star200)
	(calibration_target instrument28 Star41)
	(calibration_target instrument28 Star84)
	(calibration_target instrument28 GroundStation81)
	(calibration_target instrument28 GroundStation10)
	(calibration_target instrument28 GroundStation94)
	(calibration_target instrument28 GroundStation64)
	(calibration_target instrument28 Star128)
	(calibration_target instrument28 Star61)
	(calibration_target instrument28 Star74)
	(calibration_target instrument28 GroundStation77)
	(calibration_target instrument28 Star105)
	(calibration_target instrument28 Star80)
	(calibration_target instrument28 GroundStation3)
	(calibration_target instrument28 GroundStation143)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(power_avail satellite8)
	(pointing satellite8 GroundStation108)
	(supports instrument29 spectrograph0)
	(supports instrument29 thermograph1)
	(supports instrument29 infrared2)
	(calibration_target instrument29 Star126)
	(calibration_target instrument29 GroundStation177)
	(calibration_target instrument29 Star84)
	(calibration_target instrument29 Star199)
	(calibration_target instrument29 GroundStation4)
	(calibration_target instrument29 Star157)
	(on_board instrument29 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet257)
	(supports instrument30 infrared2)
	(supports instrument30 infrared3)
	(calibration_target instrument30 GroundStation170)
	(calibration_target instrument30 Star181)
	(calibration_target instrument30 GroundStation106)
	(calibration_target instrument30 Star168)
	(calibration_target instrument30 Star93)
	(calibration_target instrument30 GroundStation32)
	(calibration_target instrument30 Star187)
	(calibration_target instrument30 GroundStation143)
	(calibration_target instrument30 Star195)
	(calibration_target instrument30 Star183)
	(calibration_target instrument30 Star83)
	(calibration_target instrument30 GroundStation108)
	(supports instrument31 image4)
	(supports instrument31 thermograph1)
	(calibration_target instrument31 Star105)
	(calibration_target instrument31 Star202)
	(calibration_target instrument31 GroundStation108)
	(calibration_target instrument31 Star203)
	(calibration_target instrument31 GroundStation130)
	(calibration_target instrument31 GroundStation44)
	(calibration_target instrument31 GroundStation85)
	(calibration_target instrument31 GroundStation47)
	(calibration_target instrument31 Star160)
	(calibration_target instrument31 GroundStation65)
	(calibration_target instrument31 Star28)
	(calibration_target instrument31 GroundStation170)
	(calibration_target instrument31 Star83)
	(calibration_target instrument31 Star192)
	(calibration_target instrument31 Star15)
	(calibration_target instrument31 GroundStation95)
	(calibration_target instrument31 Star24)
	(calibration_target instrument31 GroundStation39)
	(calibration_target instrument31 Star48)
	(calibration_target instrument31 GroundStation139)
	(calibration_target instrument31 Star140)
	(calibration_target instrument31 GroundStation17)
	(calibration_target instrument31 GroundStation75)
	(calibration_target instrument31 Star33)
	(calibration_target instrument31 GroundStation23)
	(calibration_target instrument31 Star102)
	(calibration_target instrument31 GroundStation81)
	(calibration_target instrument31 GroundStation174)
	(calibration_target instrument31 GroundStation173)
	(calibration_target instrument31 Star42)
	(calibration_target instrument31 GroundStation92)
	(calibration_target instrument31 Star126)
	(calibration_target instrument31 GroundStation94)
	(calibration_target instrument31 GroundStation16)
	(calibration_target instrument31 Star89)
	(calibration_target instrument31 Star152)
	(calibration_target instrument31 Star178)
	(calibration_target instrument31 Star133)
	(calibration_target instrument31 Star111)
	(calibration_target instrument31 Star41)
	(calibration_target instrument31 Star67)
	(calibration_target instrument31 Star185)
	(calibration_target instrument31 GroundStation10)
	(calibration_target instrument31 Star56)
	(calibration_target instrument31 GroundStation124)
	(calibration_target instrument31 Star70)
	(calibration_target instrument31 GroundStation35)
	(calibration_target instrument31 GroundStation158)
	(calibration_target instrument31 Star104)
	(calibration_target instrument31 GroundStation54)
	(calibration_target instrument31 GroundStation53)
	(calibration_target instrument31 Star110)
	(calibration_target instrument31 Star155)
	(on_board instrument30 satellite10)
	(on_board instrument31 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Planet220)
	(supports instrument32 infrared3)
	(supports instrument32 spectrograph6)
	(calibration_target instrument32 GroundStation177)
	(calibration_target instrument32 Star61)
	(calibration_target instrument32 Star128)
	(calibration_target instrument32 GroundStation63)
	(calibration_target instrument32 GroundStation90)
	(calibration_target instrument32 Star192)
	(supports instrument33 image5)
	(calibration_target instrument33 GroundStation17)
	(calibration_target instrument33 GroundStation169)
	(calibration_target instrument33 Star60)
	(calibration_target instrument33 GroundStation177)
	(calibration_target instrument33 GroundStation30)
	(calibration_target instrument33 Star112)
	(calibration_target instrument33 GroundStation132)
	(calibration_target instrument33 Star100)
	(calibration_target instrument33 Star181)
	(calibration_target instrument33 GroundStation130)
	(calibration_target instrument33 Star178)
	(calibration_target instrument33 GroundStation154)
	(calibration_target instrument33 GroundStation201)
	(calibration_target instrument33 GroundStation127)
	(calibration_target instrument33 GroundStation77)
	(calibration_target instrument33 Star86)
	(calibration_target instrument33 GroundStation44)
	(calibration_target instrument33 GroundStation134)
	(calibration_target instrument33 Star15)
	(calibration_target instrument33 GroundStation25)
	(calibration_target instrument33 Star164)
	(calibration_target instrument33 GroundStation173)
	(calibration_target instrument33 GroundStation162)
	(calibration_target instrument33 Star45)
	(calibration_target instrument33 GroundStation92)
	(calibration_target instrument33 GroundStation64)
	(calibration_target instrument33 GroundStation10)
	(calibration_target instrument33 Star31)
	(supports instrument34 infrared2)
	(calibration_target instrument34 GroundStation63)
	(calibration_target instrument34 GroundStation99)
	(calibration_target instrument34 GroundStation87)
	(calibration_target instrument34 Star5)
	(calibration_target instrument34 GroundStation34)
	(calibration_target instrument34 Star28)
	(calibration_target instrument34 GroundStation134)
	(calibration_target instrument34 GroundStation147)
	(calibration_target instrument34 GroundStation95)
	(calibration_target instrument34 Star24)
	(calibration_target instrument34 Star149)
	(calibration_target instrument34 GroundStation98)
	(calibration_target instrument34 Star93)
	(calibration_target instrument34 Star45)
	(calibration_target instrument34 GroundStation32)
	(calibration_target instrument34 Star42)
	(calibration_target instrument34 GroundStation94)
	(calibration_target instrument34 Star148)
	(calibration_target instrument34 Star123)
	(calibration_target instrument34 Star137)
	(calibration_target instrument34 GroundStation154)
	(calibration_target instrument34 Star110)
	(calibration_target instrument34 Star48)
	(calibration_target instrument34 Star15)
	(calibration_target instrument34 GroundStation162)
	(calibration_target instrument34 GroundStation71)
	(calibration_target instrument34 GroundStation96)
	(calibration_target instrument34 GroundStation177)
	(calibration_target instrument34 GroundStation106)
	(calibration_target instrument34 Star182)
	(calibration_target instrument34 Star189)
	(calibration_target instrument34 Star136)
	(calibration_target instrument34 Star187)
	(calibration_target instrument34 Star105)
	(calibration_target instrument34 Star31)
	(calibration_target instrument34 Star70)
	(supports instrument35 infrared2)
	(supports instrument35 image4)
	(calibration_target instrument35 GroundStation53)
	(calibration_target instrument35 GroundStation49)
	(calibration_target instrument35 GroundStation154)
	(calibration_target instrument35 GroundStation40)
	(calibration_target instrument35 Star194)
	(calibration_target instrument35 Star183)
	(calibration_target instrument35 GroundStation73)
	(calibration_target instrument35 Star68)
	(calibration_target instrument35 Star137)
	(calibration_target instrument35 GroundStation108)
	(calibration_target instrument35 GroundStation96)
	(calibration_target instrument35 Star164)
	(calibration_target instrument35 Star140)
	(calibration_target instrument35 GroundStation143)
	(calibration_target instrument35 Star36)
	(calibration_target instrument35 Star121)
	(calibration_target instrument35 GroundStation47)
	(calibration_target instrument35 Star190)
	(calibration_target instrument35 Star144)
	(calibration_target instrument35 Star160)
	(calibration_target instrument35 Star91)
	(calibration_target instrument35 Star14)
	(calibration_target instrument35 GroundStation153)
	(calibration_target instrument35 Star83)
	(calibration_target instrument35 GroundStation87)
	(calibration_target instrument35 GroundStation3)
	(calibration_target instrument35 Star136)
	(calibration_target instrument35 Star193)
	(calibration_target instrument35 GroundStation167)
	(calibration_target instrument35 GroundStation179)
	(calibration_target instrument35 Star103)
	(calibration_target instrument35 GroundStation94)
	(calibration_target instrument35 Star199)
	(calibration_target instrument35 GroundStation13)
	(calibration_target instrument35 GroundStation159)
	(calibration_target instrument35 GroundStation32)
	(calibration_target instrument35 GroundStation39)
	(calibration_target instrument35 GroundStation107)
	(calibration_target instrument35 GroundStation146)
	(calibration_target instrument35 Star185)
	(calibration_target instrument35 Star5)
	(calibration_target instrument35 GroundStation63)
	(calibration_target instrument35 GroundStation69)
	(calibration_target instrument35 GroundStation23)
	(calibration_target instrument35 Star155)
	(calibration_target instrument35 GroundStation54)
	(calibration_target instrument35 GroundStation201)
	(calibration_target instrument35 Star2)
	(calibration_target instrument35 GroundStation64)
	(calibration_target instrument35 GroundStation99)
	(calibration_target instrument35 GroundStation106)
	(calibration_target instrument35 GroundStation44)
	(calibration_target instrument35 GroundStation18)
	(calibration_target instrument35 GroundStation8)
	(calibration_target instrument35 GroundStation131)
	(on_board instrument32 satellite11)
	(on_board instrument33 satellite11)
	(on_board instrument34 satellite11)
	(on_board instrument35 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Phenomenon274)
)
(:goal (and
	(pointing satellite2 Star41)
	(pointing satellite3 Star398)
	(pointing satellite4 Phenomenon347)
	(pointing satellite5 GroundStation159)
	(pointing satellite6 GroundStation159)
	(pointing satellite8 GroundStation43)
	(have_image Planet204 thermograph1)
	(have_image Star205 spectrograph6)
	(have_image Star205 spectrograph0)
	(have_image Star206 image4)
	(have_image Star206 spectrograph6)
	(have_image Star207 image5)
	(have_image Phenomenon208 spectrograph0)
	(have_image Star209 image5)
	(have_image Phenomenon211 spectrograph0)
	(have_image Planet213 infrared2)
	(have_image Star214 image4)
	(have_image Star214 image5)
	(have_image Planet215 image5)
	(have_image Planet215 infrared3)
	(have_image Planet216 spectrograph6)
	(have_image Star219 spectrograph6)
	(have_image Star219 image5)
	(have_image Planet220 infrared3)
	(have_image Planet221 thermograph1)
	(have_image Planet221 infrared3)
	(have_image Star222 image5)
	(have_image Star222 image4)
	(have_image Star223 spectrograph6)
	(have_image Star223 image4)
	(have_image Star224 spectrograph6)
	(have_image Planet225 infrared2)
	(have_image Phenomenon227 spectrograph0)
	(have_image Phenomenon228 infrared2)
	(have_image Phenomenon229 spectrograph0)
	(have_image Phenomenon230 image5)
	(have_image Phenomenon230 image4)
	(have_image Star231 infrared3)
	(have_image Star232 thermograph1)
	(have_image Star233 image5)
	(have_image Star233 infrared2)
	(have_image Phenomenon234 infrared3)
	(have_image Planet235 infrared2)
	(have_image Planet235 spectrograph0)
	(have_image Phenomenon236 spectrograph0)
	(have_image Phenomenon236 spectrograph6)
	(have_image Star237 thermograph1)
	(have_image Star237 infrared2)
	(have_image Phenomenon239 image4)
	(have_image Planet240 infrared2)
	(have_image Planet240 infrared3)
	(have_image Phenomenon241 thermograph1)
	(have_image Star242 image4)
	(have_image Planet243 spectrograph0)
	(have_image Planet243 thermograph1)
	(have_image Star244 image4)
	(have_image Star244 infrared2)
	(have_image Planet245 infrared2)
	(have_image Planet245 spectrograph0)
	(have_image Planet247 image5)
	(have_image Phenomenon248 infrared2)
	(have_image Phenomenon249 spectrograph6)
	(have_image Phenomenon250 image5)
	(have_image Phenomenon250 image4)
	(have_image Planet251 infrared3)
	(have_image Phenomenon252 spectrograph0)
	(have_image Phenomenon252 thermograph1)
	(have_image Star253 image5)
	(have_image Star253 infrared3)
	(have_image Star254 spectrograph6)
	(have_image Planet255 spectrograph6)
	(have_image Planet255 thermograph1)
	(have_image Planet256 infrared3)
	(have_image Planet256 image5)
	(have_image Planet257 infrared3)
	(have_image Planet257 image4)
	(have_image Star258 infrared3)
	(have_image Star258 infrared2)
	(have_image Phenomenon259 spectrograph6)
	(have_image Phenomenon259 infrared3)
	(have_image Planet260 infrared3)
	(have_image Phenomenon261 spectrograph6)
	(have_image Planet262 infrared2)
	(have_image Planet262 spectrograph6)
	(have_image Star263 image5)
	(have_image Phenomenon264 spectrograph6)
	(have_image Phenomenon264 image5)
	(have_image Star265 spectrograph0)
	(have_image Star265 image5)
	(have_image Phenomenon266 spectrograph0)
	(have_image Phenomenon266 image4)
	(have_image Star267 spectrograph6)
	(have_image Star267 thermograph1)
	(have_image Planet268 infrared2)
	(have_image Phenomenon269 spectrograph6)
	(have_image Phenomenon269 thermograph1)
	(have_image Phenomenon270 spectrograph6)
	(have_image Phenomenon270 infrared2)
	(have_image Phenomenon271 infrared2)
	(have_image Phenomenon271 spectrograph0)
	(have_image Phenomenon272 infrared2)
	(have_image Phenomenon272 spectrograph0)
	(have_image Phenomenon273 spectrograph6)
	(have_image Phenomenon274 thermograph1)
	(have_image Phenomenon275 infrared3)
	(have_image Planet276 image5)
	(have_image Planet276 spectrograph6)
	(have_image Phenomenon277 spectrograph0)
	(have_image Phenomenon277 infrared2)
	(have_image Planet279 spectrograph6)
	(have_image Planet279 image5)
	(have_image Star280 infrared2)
	(have_image Star280 spectrograph6)
	(have_image Star281 image5)
	(have_image Star281 image4)
	(have_image Phenomenon284 image4)
	(have_image Phenomenon284 infrared2)
	(have_image Planet285 spectrograph0)
	(have_image Planet285 infrared2)
	(have_image Star286 thermograph1)
	(have_image Planet287 thermograph1)
	(have_image Planet287 spectrograph6)
	(have_image Phenomenon288 infrared2)
	(have_image Star289 spectrograph0)
	(have_image Star289 thermograph1)
	(have_image Phenomenon290 thermograph1)
	(have_image Star291 infrared3)
	(have_image Phenomenon293 image4)
	(have_image Phenomenon293 spectrograph0)
	(have_image Star294 image5)
	(have_image Star294 infrared3)
	(have_image Phenomenon295 image4)
	(have_image Phenomenon295 thermograph1)
	(have_image Phenomenon296 image4)
	(have_image Star298 spectrograph6)
	(have_image Planet299 spectrograph6)
	(have_image Planet299 infrared3)
	(have_image Star300 image5)
	(have_image Star300 thermograph1)
	(have_image Phenomenon301 spectrograph0)
	(have_image Star302 infrared3)
	(have_image Planet303 spectrograph0)
	(have_image Planet303 image5)
	(have_image Phenomenon304 spectrograph6)
	(have_image Phenomenon304 spectrograph0)
	(have_image Star305 image4)
	(have_image Star306 image5)
	(have_image Planet307 image4)
	(have_image Planet308 infrared3)
	(have_image Planet308 image5)
	(have_image Star309 image4)
	(have_image Phenomenon310 infrared3)
	(have_image Planet311 thermograph1)
	(have_image Star312 infrared3)
	(have_image Star313 thermograph1)
	(have_image Phenomenon314 spectrograph0)
	(have_image Star315 image5)
	(have_image Star315 infrared2)
	(have_image Planet316 spectrograph6)
	(have_image Planet316 spectrograph0)
	(have_image Planet317 spectrograph0)
	(have_image Planet318 spectrograph6)
	(have_image Planet318 thermograph1)
	(have_image Phenomenon319 infrared3)
	(have_image Phenomenon319 thermograph1)
	(have_image Star320 spectrograph6)
	(have_image Star320 image5)
	(have_image Planet321 spectrograph6)
	(have_image Star322 infrared3)
	(have_image Star322 spectrograph0)
	(have_image Planet323 spectrograph0)
	(have_image Star324 thermograph1)
	(have_image Star324 image4)
	(have_image Phenomenon325 infrared3)
	(have_image Phenomenon325 spectrograph6)
	(have_image Star326 spectrograph0)
	(have_image Star326 image4)
	(have_image Phenomenon327 thermograph1)
	(have_image Phenomenon327 image4)
	(have_image Star328 infrared2)
	(have_image Star328 image5)
	(have_image Phenomenon329 spectrograph0)
	(have_image Planet330 spectrograph6)
	(have_image Phenomenon331 image5)
	(have_image Phenomenon331 infrared3)
	(have_image Planet332 spectrograph0)
	(have_image Planet332 infrared2)
	(have_image Phenomenon334 infrared2)
	(have_image Planet335 spectrograph0)
	(have_image Planet336 spectrograph6)
	(have_image Planet336 image5)
	(have_image Planet337 spectrograph6)
	(have_image Planet337 spectrograph0)
	(have_image Phenomenon339 thermograph1)
	(have_image Phenomenon339 spectrograph6)
	(have_image Planet340 thermograph1)
	(have_image Planet341 image4)
	(have_image Planet341 infrared3)
	(have_image Phenomenon342 infrared2)
	(have_image Planet343 infrared2)
	(have_image Planet343 thermograph1)
	(have_image Phenomenon344 image5)
	(have_image Phenomenon344 thermograph1)
	(have_image Planet345 infrared2)
	(have_image Planet345 thermograph1)
	(have_image Phenomenon346 image5)
	(have_image Phenomenon346 infrared3)
	(have_image Phenomenon347 image4)
	(have_image Phenomenon347 infrared2)
	(have_image Planet348 infrared2)
	(have_image Planet348 spectrograph6)
	(have_image Phenomenon349 infrared3)
	(have_image Phenomenon349 image5)
	(have_image Phenomenon350 thermograph1)
	(have_image Phenomenon350 spectrograph6)
	(have_image Phenomenon351 thermograph1)
	(have_image Phenomenon352 image5)
	(have_image Phenomenon352 thermograph1)
	(have_image Planet353 image5)
	(have_image Planet353 spectrograph6)
	(have_image Phenomenon354 spectrograph6)
	(have_image Phenomenon354 image5)
	(have_image Star355 image4)
	(have_image Phenomenon356 thermograph1)
	(have_image Planet357 spectrograph0)
	(have_image Planet358 infrared3)
	(have_image Planet358 thermograph1)
	(have_image Planet359 infrared2)
	(have_image Planet359 spectrograph0)
	(have_image Phenomenon360 spectrograph0)
	(have_image Star361 image4)
	(have_image Planet362 infrared2)
	(have_image Planet362 image5)
	(have_image Phenomenon363 image5)
	(have_image Planet365 image4)
	(have_image Star366 image5)
	(have_image Phenomenon367 thermograph1)
	(have_image Phenomenon367 image5)
	(have_image Planet368 infrared3)
	(have_image Star369 spectrograph0)
	(have_image Planet370 spectrograph0)
	(have_image Planet371 infrared3)
	(have_image Star372 thermograph1)
	(have_image Planet373 spectrograph0)
	(have_image Planet374 thermograph1)
	(have_image Planet374 image4)
	(have_image Phenomenon375 spectrograph6)
	(have_image Planet376 image5)
	(have_image Planet376 spectrograph6)
	(have_image Star377 image5)
	(have_image Star378 thermograph1)
	(have_image Star378 spectrograph6)
	(have_image Phenomenon379 image5)
	(have_image Phenomenon379 spectrograph6)
	(have_image Planet380 spectrograph0)
	(have_image Planet380 spectrograph6)
	(have_image Planet381 infrared3)
	(have_image Phenomenon382 infrared2)
	(have_image Phenomenon382 thermograph1)
	(have_image Star384 image5)
	(have_image Star384 spectrograph0)
	(have_image Phenomenon385 image4)
	(have_image Phenomenon385 spectrograph0)
	(have_image Phenomenon386 image5)
	(have_image Planet387 thermograph1)
	(have_image Planet387 spectrograph6)
	(have_image Phenomenon388 infrared3)
	(have_image Phenomenon388 image4)
	(have_image Planet389 spectrograph0)
	(have_image Planet389 infrared2)
	(have_image Planet390 infrared2)
	(have_image Planet390 image5)
	(have_image Phenomenon391 spectrograph0)
	(have_image Phenomenon391 infrared2)
	(have_image Star392 thermograph1)
	(have_image Star392 image4)
	(have_image Phenomenon393 infrared3)
	(have_image Phenomenon393 thermograph1)
	(have_image Phenomenon394 image4)
	(have_image Phenomenon394 infrared2)
	(have_image Phenomenon396 spectrograph0)
	(have_image Planet397 spectrograph0)
	(have_image Planet397 thermograph1)
	(have_image Star398 spectrograph6)
	(have_image Star398 thermograph1)
	(have_image Star399 spectrograph0)
	(have_image Star399 infrared2)
	(have_image Planet400 thermograph1)
	(have_image Phenomenon401 spectrograph6)
	(have_image Planet402 image5)
	(have_image Planet402 infrared3)
	(have_image Star403 spectrograph0)
	(have_image Star403 infrared3)
	(have_image Star404 infrared2)
	(have_image Phenomenon405 spectrograph6)
	(have_image Planet406 image5)
	(have_image Planet406 spectrograph6)
	(have_image Phenomenon407 spectrograph0)
))

)
