(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	satellite2 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	satellite4 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite5 - satellite
	instrument11 - instrument
	satellite6 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite7 - satellite
	instrument16 - instrument
	satellite8 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite9 - satellite
	instrument20 - instrument
	spectrograph0 - mode
	image3 - mode
	image4 - mode
	infrared5 - mode
	infrared1 - mode
	image2 - mode
	Star14 - direction
	Star107 - direction
	Star136 - direction
	Star140 - direction
	Star154 - direction
	GroundStation44 - direction
	GroundStation50 - direction
	GroundStation110 - direction
	GroundStation71 - direction
	GroundStation142 - direction
	Star174 - direction
	GroundStation53 - direction
	Star175 - direction
	GroundStation201 - direction
	Star200 - direction
	Star150 - direction
	Star132 - direction
	GroundStation80 - direction
	Star15 - direction
	GroundStation66 - direction
	Star130 - direction
	Star102 - direction
	Star92 - direction
	GroundStation126 - direction
	Star209 - direction
	Star120 - direction
	GroundStation125 - direction
	Star184 - direction
	Star27 - direction
	Star199 - direction
	Star88 - direction
	GroundStation152 - direction
	Star65 - direction
	GroundStation204 - direction
	Star138 - direction
	Star177 - direction
	Star28 - direction
	GroundStation21 - direction
	Star182 - direction
	Star195 - direction
	GroundStation76 - direction
	Star87 - direction
	GroundStation63 - direction
	GroundStation98 - direction
	GroundStation43 - direction
	GroundStation74 - direction
	GroundStation202 - direction
	GroundStation131 - direction
	Star56 - direction
	Star77 - direction
	GroundStation164 - direction
	Star111 - direction
	GroundStation123 - direction
	Star180 - direction
	GroundStation118 - direction
	GroundStation165 - direction
	GroundStation91 - direction
	Star143 - direction
	Star156 - direction
	Star35 - direction
	Star115 - direction
	GroundStation207 - direction
	GroundStation157 - direction
	GroundStation109 - direction
	GroundStation55 - direction
	Star190 - direction
	Star19 - direction
	GroundStation134 - direction
	Star122 - direction
	GroundStation149 - direction
	GroundStation159 - direction
	Star25 - direction
	Star166 - direction
	GroundStation203 - direction
	GroundStation75 - direction
	Star113 - direction
	GroundStation79 - direction
	GroundStation78 - direction
	GroundStation94 - direction
	GroundStation69 - direction
	Star104 - direction
	Star12 - direction
	GroundStation137 - direction
	GroundStation37 - direction
	GroundStation181 - direction
	GroundStation23 - direction
	GroundStation68 - direction
	Star60 - direction
	Star48 - direction
	Star32 - direction
	Star178 - direction
	GroundStation116 - direction
	GroundStation198 - direction
	Star114 - direction
	GroundStation197 - direction
	Star59 - direction
	GroundStation192 - direction
	Star188 - direction
	Star17 - direction
	Star208 - direction
	Star72 - direction
	GroundStation0 - direction
	GroundStation99 - direction
	Star73 - direction
	GroundStation151 - direction
	GroundStation54 - direction
	Star64 - direction
	Star51 - direction
	Star183 - direction
	Star100 - direction
	GroundStation112 - direction
	GroundStation173 - direction
	Star171 - direction
	Star121 - direction
	GroundStation179 - direction
	Star129 - direction
	GroundStation141 - direction
	GroundStation158 - direction
	Star161 - direction
	GroundStation4 - direction
	Star168 - direction
	Star185 - direction
	GroundStation95 - direction
	GroundStation97 - direction
	Star49 - direction
	Star1 - direction
	GroundStation57 - direction
	Star85 - direction
	Star70 - direction
	Star89 - direction
	Star211 - direction
	Star3 - direction
	GroundStation33 - direction
	Star36 - direction
	Star206 - direction
	Star5 - direction
	Star135 - direction
	Star119 - direction
	GroundStation13 - direction
	Star67 - direction
	Star167 - direction
	Star47 - direction
	GroundStation18 - direction
	Star194 - direction
	Star62 - direction
	Star38 - direction
	Star24 - direction
	GroundStation2 - direction
	GroundStation145 - direction
	Star84 - direction
	Star82 - direction
	Star26 - direction
	Star124 - direction
	Star155 - direction
	GroundStation162 - direction
	GroundStation144 - direction
	Star83 - direction
	GroundStation187 - direction
	GroundStation40 - direction
	GroundStation52 - direction
	GroundStation61 - direction
	GroundStation9 - direction
	Star193 - direction
	Star127 - direction
	GroundStation163 - direction
	Star186 - direction
	GroundStation117 - direction
	Star46 - direction
	GroundStation170 - direction
	GroundStation90 - direction
	GroundStation29 - direction
	Star105 - direction
	GroundStation20 - direction
	Star196 - direction
	GroundStation128 - direction
	GroundStation22 - direction
	Star160 - direction
	GroundStation8 - direction
	GroundStation169 - direction
	Star41 - direction
	GroundStation172 - direction
	Star31 - direction
	Star16 - direction
	GroundStation6 - direction
	Star96 - direction
	Star103 - direction
	Star176 - direction
	Star81 - direction
	GroundStation153 - direction
	GroundStation148 - direction
	GroundStation210 - direction
	Star205 - direction
	GroundStation30 - direction
	GroundStation39 - direction
	Star147 - direction
	GroundStation93 - direction
	Star86 - direction
	Star191 - direction
	Star58 - direction
	GroundStation7 - direction
	GroundStation45 - direction
	GroundStation10 - direction
	Star189 - direction
	GroundStation101 - direction
	Star34 - direction
	GroundStation108 - direction
	Star139 - direction
	GroundStation133 - direction
	Star146 - direction
	GroundStation42 - direction
	GroundStation11 - direction
	GroundStation106 - direction
	Star212 - direction
	Phenomenon213 - direction
	Phenomenon214 - direction
	Planet215 - direction
	Planet216 - direction
	Planet217 - direction
	Phenomenon218 - direction
	Phenomenon219 - direction
	Phenomenon220 - direction
	Planet221 - direction
	Phenomenon222 - direction
	Star223 - direction
	Star224 - direction
	Star225 - direction
	Planet226 - direction
	Star227 - direction
	Planet228 - direction
	Star229 - direction
	Planet230 - direction
	Phenomenon231 - direction
	Star232 - direction
	Planet233 - direction
	Star234 - direction
	Phenomenon235 - direction
	Phenomenon236 - direction
	Star237 - direction
	Phenomenon238 - direction
	Phenomenon239 - direction
	Planet240 - direction
	Phenomenon241 - direction
	Star242 - direction
	Star243 - direction
	Star244 - direction
	Star245 - direction
	Planet246 - direction
	Phenomenon247 - direction
	Star248 - direction
	Phenomenon249 - direction
	Star250 - direction
	Planet251 - direction
	Phenomenon252 - direction
	Star253 - direction
	Star254 - direction
	Phenomenon255 - direction
	Star256 - direction
	Phenomenon257 - direction
	Star258 - direction
	Planet259 - direction
	Star260 - direction
	Planet261 - direction
	Star262 - direction
	Phenomenon263 - direction
	Phenomenon264 - direction
	Planet265 - direction
	Planet266 - direction
	Phenomenon267 - direction
	Phenomenon268 - direction
	Phenomenon269 - direction
	Planet270 - direction
	Planet271 - direction
	Planet272 - direction
	Phenomenon273 - direction
	Planet274 - direction
	Phenomenon275 - direction
	Planet276 - direction
	Planet277 - direction
	Planet278 - direction
	Planet279 - direction
	Planet280 - direction
	Planet281 - direction
	Phenomenon282 - direction
	Star283 - direction
	Planet284 - direction
	Planet285 - direction
	Phenomenon286 - direction
	Phenomenon287 - direction
	Phenomenon288 - direction
	Planet289 - direction
	Phenomenon290 - direction
	Phenomenon291 - direction
	Star292 - direction
	Phenomenon293 - direction
	Planet294 - direction
	Phenomenon295 - direction
	Planet296 - direction
	Planet297 - direction
	Phenomenon298 - direction
	Phenomenon299 - direction
	Planet300 - direction
	Phenomenon301 - direction
	Phenomenon302 - direction
	Planet303 - direction
	Planet304 - direction
	Phenomenon305 - direction
	Star306 - direction
	Planet307 - direction
	Phenomenon308 - direction
	Phenomenon309 - direction
	Phenomenon310 - direction
	Phenomenon311 - direction
	Star312 - direction
	Phenomenon313 - direction
	Phenomenon314 - direction
	Star315 - direction
	Star316 - direction
	Planet317 - direction
	Phenomenon318 - direction
	Star319 - direction
	Phenomenon320 - direction
	Planet321 - direction
	Star322 - direction
	Star323 - direction
	Phenomenon324 - direction
	Planet325 - direction
	Star326 - direction
	Phenomenon327 - direction
	Planet328 - direction
	Phenomenon329 - direction
	Phenomenon330 - direction
	Planet331 - direction
	Phenomenon332 - direction
	Phenomenon333 - direction
	Phenomenon334 - direction
	Star335 - direction
	Phenomenon336 - direction
	Planet337 - direction
	Star338 - direction
	Planet339 - direction
	Planet340 - direction
	Phenomenon341 - direction
	Phenomenon342 - direction
	Phenomenon343 - direction
	Planet344 - direction
	Planet345 - direction
	Planet346 - direction
	Phenomenon347 - direction
	Star348 - direction
	Phenomenon349 - direction
	Star350 - direction
	Planet351 - direction
	Planet352 - direction
	Phenomenon353 - direction
	Star354 - direction
	Planet355 - direction
	Star356 - direction
	Phenomenon357 - direction
	Phenomenon358 - direction
	Star359 - direction
	Phenomenon360 - direction
	Planet361 - direction
	Phenomenon362 - direction
	Planet363 - direction
	Star364 - direction
	Star365 - direction
	Phenomenon366 - direction
	Star367 - direction
	Planet368 - direction
	Star369 - direction
	Star370 - direction
	Planet371 - direction
	Planet372 - direction
	Planet373 - direction
	Planet374 - direction
	Star375 - direction
	Phenomenon376 - direction
	Star377 - direction
	Planet378 - direction
	Planet379 - direction
	Star380 - direction
	Phenomenon381 - direction
	Planet382 - direction
	Phenomenon383 - direction
	Star384 - direction
	Phenomenon385 - direction
	Phenomenon386 - direction
	Planet387 - direction
	Planet388 - direction
	Planet389 - direction
	Star390 - direction
	Planet391 - direction
	Star392 - direction
	Planet393 - direction
	Star394 - direction
	Star395 - direction
	Phenomenon396 - direction
	Planet397 - direction
	Planet398 - direction
	Planet399 - direction
	Star400 - direction
	Planet401 - direction
	Star402 - direction
	Planet403 - direction
	Phenomenon404 - direction
	Planet405 - direction
	Star406 - direction
	Phenomenon407 - direction
	Planet408 - direction
	Phenomenon409 - direction
	Star410 - direction
	Phenomenon411 - direction
	Phenomenon412 - direction
	Planet413 - direction
	Planet414 - direction
	Planet415 - direction
	Planet416 - direction
	Planet417 - direction
	Planet418 - direction
	Phenomenon419 - direction
	Planet420 - direction
	Star421 - direction
	Phenomenon422 - direction
	Star423 - direction
)
(:init
	(supports instrument0 image3)
	(supports instrument0 infrared1)
	(supports instrument0 spectrograph0)
	(calibration_target instrument0 GroundStation110)
	(calibration_target instrument0 Star15)
	(calibration_target instrument0 Star88)
	(calibration_target instrument0 Star183)
	(calibration_target instrument0 GroundStation157)
	(calibration_target instrument0 Star59)
	(calibration_target instrument0 GroundStation137)
	(calibration_target instrument0 GroundStation20)
	(calibration_target instrument0 Star87)
	(calibration_target instrument0 Star171)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star180)
	(calibration_target instrument0 GroundStation164)
	(calibration_target instrument0 Star176)
	(supports instrument1 spectrograph0)
	(supports instrument1 image3)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation90)
	(calibration_target instrument1 GroundStation61)
	(calibration_target instrument1 Star84)
	(calibration_target instrument1 GroundStation153)
	(calibration_target instrument1 Star209)
	(calibration_target instrument1 GroundStation106)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 GroundStation163)
	(calibration_target instrument1 Star114)
	(calibration_target instrument1 Star180)
	(calibration_target instrument1 Star113)
	(calibration_target instrument1 Star72)
	(calibration_target instrument1 Star105)
	(calibration_target instrument1 Star28)
	(calibration_target instrument1 GroundStation57)
	(calibration_target instrument1 GroundStation7)
	(calibration_target instrument1 Star171)
	(calibration_target instrument1 GroundStation197)
	(calibration_target instrument1 GroundStation50)
	(calibration_target instrument1 GroundStation53)
	(calibration_target instrument1 GroundStation162)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 Star24)
	(calibration_target instrument1 Star208)
	(calibration_target instrument1 GroundStation44)
	(calibration_target instrument1 Star200)
	(calibration_target instrument1 Star185)
	(calibration_target instrument1 GroundStation170)
	(calibration_target instrument1 Star195)
	(calibration_target instrument1 Star49)
	(calibration_target instrument1 Star92)
	(calibration_target instrument1 Star62)
	(calibration_target instrument1 GroundStation116)
	(calibration_target instrument1 Star174)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star96)
	(calibration_target instrument1 GroundStation54)
	(calibration_target instrument1 GroundStation9)
	(calibration_target instrument1 GroundStation33)
	(calibration_target instrument1 Star167)
	(calibration_target instrument1 Star88)
	(calibration_target instrument1 GroundStation144)
	(calibration_target instrument1 Star17)
	(calibration_target instrument1 Star104)
	(calibration_target instrument1 GroundStation173)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Phenomenon347)
	(supports instrument2 infrared5)
	(supports instrument2 image4)
	(calibration_target instrument2 GroundStation91)
	(calibration_target instrument2 Star70)
	(calibration_target instrument2 Star12)
	(calibration_target instrument2 Star166)
	(calibration_target instrument2 GroundStation157)
	(calibration_target instrument2 Star127)
	(calibration_target instrument2 Star60)
	(calibration_target instrument2 GroundStation173)
	(calibration_target instrument2 Star156)
	(calibration_target instrument2 GroundStation10)
	(calibration_target instrument2 GroundStation145)
	(calibration_target instrument2 Star189)
	(calibration_target instrument2 Star167)
	(calibration_target instrument2 Star86)
	(calibration_target instrument2 GroundStation54)
	(calibration_target instrument2 GroundStation125)
	(calibration_target instrument2 Star102)
	(calibration_target instrument2 Star105)
	(calibration_target instrument2 Star176)
	(calibration_target instrument2 GroundStation123)
	(calibration_target instrument2 Star24)
	(calibration_target instrument2 GroundStation163)
	(calibration_target instrument2 GroundStation197)
	(calibration_target instrument2 GroundStation57)
	(calibration_target instrument2 GroundStation158)
	(calibration_target instrument2 Star168)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 GroundStation6)
	(calibration_target instrument2 GroundStation204)
	(calibration_target instrument2 GroundStation52)
	(on_board instrument2 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon257)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation78)
	(calibration_target instrument3 Star65)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 Star105)
	(calibration_target instrument3 GroundStation52)
	(calibration_target instrument3 GroundStation204)
	(calibration_target instrument3 GroundStation6)
	(calibration_target instrument3 Star60)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 Star195)
	(calibration_target instrument3 Star28)
	(calibration_target instrument3 Star193)
	(calibration_target instrument3 Star178)
	(calibration_target instrument3 GroundStation201)
	(calibration_target instrument3 Star36)
	(calibration_target instrument3 Star85)
	(calibration_target instrument3 GroundStation2)
	(calibration_target instrument3 GroundStation69)
	(calibration_target instrument3 Star1)
	(calibration_target instrument3 Star138)
	(calibration_target instrument3 Star16)
	(calibration_target instrument3 Star189)
	(calibration_target instrument3 Star100)
	(calibration_target instrument3 GroundStation197)
	(calibration_target instrument3 GroundStation109)
	(calibration_target instrument3 GroundStation210)
	(calibration_target instrument3 Star130)
	(calibration_target instrument3 GroundStation158)
	(calibration_target instrument3 GroundStation125)
	(calibration_target instrument3 GroundStation144)
	(calibration_target instrument3 Star143)
	(calibration_target instrument3 GroundStation110)
	(calibration_target instrument3 GroundStation163)
	(calibration_target instrument3 Star161)
	(calibration_target instrument3 Star196)
	(calibration_target instrument3 Star49)
	(calibration_target instrument3 Star124)
	(calibration_target instrument3 Star150)
	(calibration_target instrument3 Star96)
	(calibration_target instrument3 Star129)
	(supports instrument4 image3)
	(supports instrument4 image2)
	(calibration_target instrument4 GroundStation71)
	(calibration_target instrument4 GroundStation30)
	(calibration_target instrument4 Star130)
	(calibration_target instrument4 Star168)
	(calibration_target instrument4 Star209)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 GroundStation79)
	(calibration_target instrument4 Star27)
	(calibration_target instrument4 Star12)
	(calibration_target instrument4 GroundStation142)
	(calibration_target instrument4 Star121)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation66)
	(calibration_target instrument4 Star132)
	(calibration_target instrument4 Star62)
	(calibration_target instrument4 Star177)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 GroundStation170)
	(calibration_target instrument4 Star60)
	(calibration_target instrument4 Star147)
	(calibration_target instrument4 Star208)
	(calibration_target instrument4 Star120)
	(calibration_target instrument4 Star161)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 GroundStation57)
	(calibration_target instrument4 GroundStation198)
	(calibration_target instrument4 GroundStation93)
	(calibration_target instrument4 Star89)
	(calibration_target instrument4 Star156)
	(calibration_target instrument4 Star19)
	(calibration_target instrument4 Star86)
	(calibration_target instrument4 Star193)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 Star200)
	(calibration_target instrument4 Star72)
	(calibration_target instrument4 Star70)
	(calibration_target instrument4 GroundStation123)
	(calibration_target instrument4 GroundStation158)
	(supports instrument5 image3)
	(supports instrument5 spectrograph0)
	(calibration_target instrument5 GroundStation157)
	(calibration_target instrument5 GroundStation75)
	(calibration_target instrument5 Star183)
	(calibration_target instrument5 Star100)
	(calibration_target instrument5 GroundStation57)
	(calibration_target instrument5 Star102)
	(calibration_target instrument5 Star5)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star394)
	(supports instrument6 spectrograph0)
	(supports instrument6 infrared5)
	(calibration_target instrument6 Star86)
	(calibration_target instrument6 GroundStation134)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 Star189)
	(calibration_target instrument6 GroundStation53)
	(calibration_target instrument6 Star51)
	(calibration_target instrument6 GroundStation172)
	(calibration_target instrument6 GroundStation144)
	(calibration_target instrument6 GroundStation61)
	(calibration_target instrument6 GroundStation39)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 GroundStation101)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 Star143)
	(calibration_target instrument6 GroundStation98)
	(calibration_target instrument6 Star56)
	(calibration_target instrument6 Star105)
	(calibration_target instrument6 GroundStation90)
	(calibration_target instrument6 GroundStation192)
	(calibration_target instrument6 Star70)
	(calibration_target instrument6 GroundStation137)
	(calibration_target instrument6 GroundStation45)
	(calibration_target instrument6 GroundStation203)
	(calibration_target instrument6 Star129)
	(calibration_target instrument6 Star132)
	(calibration_target instrument6 Star174)
	(calibration_target instrument6 Star121)
	(calibration_target instrument6 Star175)
	(calibration_target instrument6 GroundStation131)
	(calibration_target instrument6 Star87)
	(calibration_target instrument6 GroundStation21)
	(calibration_target instrument6 Star48)
	(calibration_target instrument6 Star178)
	(calibration_target instrument6 Star26)
	(calibration_target instrument6 Star200)
	(calibration_target instrument6 GroundStation128)
	(calibration_target instrument6 GroundStation76)
	(calibration_target instrument6 GroundStation80)
	(calibration_target instrument6 GroundStation79)
	(calibration_target instrument6 GroundStation2)
	(calibration_target instrument6 GroundStation112)
	(calibration_target instrument6 GroundStation9)
	(calibration_target instrument6 GroundStation142)
	(calibration_target instrument6 GroundStation158)
	(calibration_target instrument6 Star81)
	(calibration_target instrument6 Star58)
	(calibration_target instrument6 Star177)
	(supports instrument7 infrared5)
	(supports instrument7 image3)
	(supports instrument7 spectrograph0)
	(calibration_target instrument7 Star138)
	(calibration_target instrument7 GroundStation76)
	(calibration_target instrument7 GroundStation18)
	(calibration_target instrument7 Star161)
	(calibration_target instrument7 Star206)
	(calibration_target instrument7 Star24)
	(calibration_target instrument7 GroundStation201)
	(calibration_target instrument7 Star51)
	(calibration_target instrument7 GroundStation53)
	(calibration_target instrument7 Star59)
	(calibration_target instrument7 GroundStation210)
	(calibration_target instrument7 Star119)
	(calibration_target instrument7 GroundStation153)
	(calibration_target instrument7 Star81)
	(calibration_target instrument7 GroundStation163)
	(calibration_target instrument7 GroundStation203)
	(calibration_target instrument7 GroundStation118)
	(calibration_target instrument7 GroundStation123)
	(calibration_target instrument7 GroundStation78)
	(calibration_target instrument7 Star122)
	(calibration_target instrument7 Star17)
	(calibration_target instrument7 GroundStation22)
	(calibration_target instrument7 Star46)
	(calibration_target instrument7 GroundStation159)
	(calibration_target instrument7 GroundStation101)
	(calibration_target instrument7 GroundStation90)
	(calibration_target instrument7 GroundStation144)
	(calibration_target instrument7 Star193)
	(calibration_target instrument7 GroundStation69)
	(calibration_target instrument7 GroundStation75)
	(calibration_target instrument7 Star83)
	(calibration_target instrument7 GroundStation74)
	(calibration_target instrument7 Star65)
	(calibration_target instrument7 Star103)
	(calibration_target instrument7 Star100)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon357)
	(supports instrument8 image3)
	(calibration_target instrument8 Star83)
	(calibration_target instrument8 Star127)
	(calibration_target instrument8 Star200)
	(calibration_target instrument8 GroundStation109)
	(calibration_target instrument8 GroundStation55)
	(calibration_target instrument8 GroundStation152)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation157)
	(calibration_target instrument8 Star58)
	(calibration_target instrument8 GroundStation151)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star122)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 GroundStation40)
	(calibration_target instrument8 Star129)
	(calibration_target instrument8 GroundStation153)
	(calibration_target instrument8 GroundStation68)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 Star24)
	(calibration_target instrument8 Star150)
	(calibration_target instrument8 Star194)
	(calibration_target instrument8 Star60)
	(calibration_target instrument8 Star28)
	(calibration_target instrument8 Star166)
	(calibration_target instrument8 Star17)
	(calibration_target instrument8 GroundStation9)
	(calibration_target instrument8 Star189)
	(calibration_target instrument8 GroundStation204)
	(calibration_target instrument8 GroundStation159)
	(calibration_target instrument8 Star130)
	(calibration_target instrument8 GroundStation201)
	(calibration_target instrument8 Star175)
	(calibration_target instrument8 GroundStation37)
	(supports instrument9 image4)
	(calibration_target instrument9 GroundStation118)
	(calibration_target instrument9 GroundStation76)
	(calibration_target instrument9 Star103)
	(calibration_target instrument9 Star180)
	(calibration_target instrument9 Star15)
	(calibration_target instrument9 Star48)
	(calibration_target instrument9 GroundStation40)
	(calibration_target instrument9 Star156)
	(calibration_target instrument9 Star72)
	(calibration_target instrument9 GroundStation80)
	(calibration_target instrument9 Star182)
	(calibration_target instrument9 GroundStation207)
	(calibration_target instrument9 GroundStation134)
	(calibration_target instrument9 Star184)
	(calibration_target instrument9 GroundStation131)
	(calibration_target instrument9 Star185)
	(calibration_target instrument9 Star132)
	(calibration_target instrument9 Star150)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 Star17)
	(calibration_target instrument9 Star143)
	(calibration_target instrument9 Star100)
	(calibration_target instrument9 Star46)
	(supports instrument10 image3)
	(supports instrument10 infrared5)
	(calibration_target instrument10 GroundStation123)
	(calibration_target instrument10 GroundStation145)
	(calibration_target instrument10 GroundStation172)
	(calibration_target instrument10 Star147)
	(calibration_target instrument10 GroundStation204)
	(calibration_target instrument10 GroundStation20)
	(calibration_target instrument10 GroundStation133)
	(calibration_target instrument10 Star65)
	(calibration_target instrument10 Star103)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 GroundStation10)
	(calibration_target instrument10 Star47)
	(calibration_target instrument10 Star84)
	(calibration_target instrument10 Star129)
	(calibration_target instrument10 GroundStation4)
	(calibration_target instrument10 Star139)
	(calibration_target instrument10 Star115)
	(calibration_target instrument10 GroundStation164)
	(calibration_target instrument10 Star100)
	(calibration_target instrument10 GroundStation152)
	(calibration_target instrument10 GroundStation108)
	(calibration_target instrument10 Star88)
	(calibration_target instrument10 Star24)
	(calibration_target instrument10 Star199)
	(calibration_target instrument10 GroundStation54)
	(calibration_target instrument10 GroundStation76)
	(calibration_target instrument10 Star156)
	(calibration_target instrument10 GroundStation75)
	(calibration_target instrument10 Star189)
	(calibration_target instrument10 Star70)
	(calibration_target instrument10 Star26)
	(calibration_target instrument10 Star27)
	(calibration_target instrument10 GroundStation207)
	(calibration_target instrument10 Star186)
	(calibration_target instrument10 Star184)
	(calibration_target instrument10 Star81)
	(calibration_target instrument10 Star208)
	(calibration_target instrument10 Star77)
	(calibration_target instrument10 GroundStation125)
	(calibration_target instrument10 Star120)
	(calibration_target instrument10 Star143)
	(calibration_target instrument10 Star160)
	(calibration_target instrument10 Star209)
	(calibration_target instrument10 Star191)
	(calibration_target instrument10 GroundStation23)
	(calibration_target instrument10 GroundStation91)
	(calibration_target instrument10 GroundStation197)
	(calibration_target instrument10 GroundStation126)
	(calibration_target instrument10 Star87)
	(calibration_target instrument10 Star92)
	(calibration_target instrument10 Star180)
	(calibration_target instrument10 GroundStation101)
	(calibration_target instrument10 Star102)
	(calibration_target instrument10 Star166)
	(calibration_target instrument10 Star46)
	(calibration_target instrument10 Star28)
	(calibration_target instrument10 Star130)
	(calibration_target instrument10 GroundStation55)
	(calibration_target instrument10 GroundStation66)
	(calibration_target instrument10 GroundStation45)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 Star67)
	(calibration_target instrument10 GroundStation99)
	(calibration_target instrument10 GroundStation93)
	(calibration_target instrument10 GroundStation162)
	(on_board instrument8 satellite4)
	(on_board instrument9 satellite4)
	(on_board instrument10 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star223)
	(supports instrument11 image4)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 Star189)
	(calibration_target instrument11 Star127)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 GroundStation78)
	(calibration_target instrument11 Star114)
	(calibration_target instrument11 Star64)
	(calibration_target instrument11 GroundStation198)
	(calibration_target instrument11 GroundStation42)
	(calibration_target instrument11 GroundStation116)
	(calibration_target instrument11 Star96)
	(calibration_target instrument11 Star194)
	(calibration_target instrument11 GroundStation192)
	(calibration_target instrument11 Star28)
	(calibration_target instrument11 GroundStation75)
	(calibration_target instrument11 Star208)
	(calibration_target instrument11 Star85)
	(calibration_target instrument11 GroundStation7)
	(calibration_target instrument11 Star119)
	(calibration_target instrument11 Star32)
	(calibration_target instrument11 Star177)
	(calibration_target instrument11 Star138)
	(calibration_target instrument11 Star60)
	(calibration_target instrument11 GroundStation210)
	(calibration_target instrument11 GroundStation133)
	(calibration_target instrument11 GroundStation157)
	(calibration_target instrument11 GroundStation170)
	(calibration_target instrument11 Star135)
	(calibration_target instrument11 Star156)
	(calibration_target instrument11 Star26)
	(on_board instrument11 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star206)
	(supports instrument12 spectrograph0)
	(calibration_target instrument12 Star72)
	(calibration_target instrument12 GroundStation43)
	(calibration_target instrument12 Star25)
	(calibration_target instrument12 Star83)
	(calibration_target instrument12 GroundStation93)
	(calibration_target instrument12 GroundStation76)
	(calibration_target instrument12 GroundStation79)
	(calibration_target instrument12 Star81)
	(calibration_target instrument12 GroundStation153)
	(calibration_target instrument12 Star121)
	(calibration_target instrument12 GroundStation158)
	(calibration_target instrument12 GroundStation52)
	(calibration_target instrument12 GroundStation207)
	(calibration_target instrument12 GroundStation18)
	(calibration_target instrument12 Star67)
	(calibration_target instrument12 GroundStation162)
	(calibration_target instrument12 GroundStation131)
	(calibration_target instrument12 GroundStation151)
	(calibration_target instrument12 Star115)
	(calibration_target instrument12 GroundStation54)
	(calibration_target instrument12 Star195)
	(calibration_target instrument12 GroundStation8)
	(calibration_target instrument12 GroundStation90)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 Star182)
	(calibration_target instrument12 Star196)
	(calibration_target instrument12 Star127)
	(calibration_target instrument12 Star17)
	(calibration_target instrument12 GroundStation144)
	(calibration_target instrument12 GroundStation61)
	(calibration_target instrument12 GroundStation29)
	(calibration_target instrument12 GroundStation78)
	(calibration_target instrument12 Star191)
	(calibration_target instrument12 Star36)
	(calibration_target instrument12 Star58)
	(supports instrument13 image3)
	(supports instrument13 spectrograph0)
	(supports instrument13 infrared5)
	(calibration_target instrument13 Star84)
	(calibration_target instrument13 Star25)
	(calibration_target instrument13 Star196)
	(calibration_target instrument13 GroundStation131)
	(calibration_target instrument13 Star114)
	(calibration_target instrument13 GroundStation169)
	(calibration_target instrument13 Star115)
	(calibration_target instrument13 GroundStation162)
	(calibration_target instrument13 GroundStation202)
	(calibration_target instrument13 GroundStation74)
	(calibration_target instrument13 Star86)
	(calibration_target instrument13 Star156)
	(calibration_target instrument13 GroundStation43)
	(calibration_target instrument13 GroundStation123)
	(calibration_target instrument13 GroundStation42)
	(calibration_target instrument13 Star111)
	(calibration_target instrument13 GroundStation99)
	(calibration_target instrument13 GroundStation18)
	(calibration_target instrument13 GroundStation179)
	(calibration_target instrument13 GroundStation151)
	(calibration_target instrument13 GroundStation98)
	(calibration_target instrument13 GroundStation164)
	(calibration_target instrument13 Star70)
	(calibration_target instrument13 Star147)
	(calibration_target instrument13 GroundStation63)
	(calibration_target instrument13 Star183)
	(calibration_target instrument13 Star143)
	(calibration_target instrument13 Star87)
	(calibration_target instrument13 Star49)
	(calibration_target instrument13 Star19)
	(supports instrument14 image4)
	(supports instrument14 infrared5)
	(calibration_target instrument14 Star193)
	(calibration_target instrument14 GroundStation57)
	(calibration_target instrument14 GroundStation61)
	(calibration_target instrument14 Star105)
	(calibration_target instrument14 Star156)
	(calibration_target instrument14 Star36)
	(calibration_target instrument14 Star5)
	(calibration_target instrument14 Star196)
	(calibration_target instrument14 GroundStation117)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 Star38)
	(calibration_target instrument14 GroundStation181)
	(calibration_target instrument14 Star143)
	(calibration_target instrument14 Star104)
	(calibration_target instrument14 GroundStation157)
	(calibration_target instrument14 GroundStation91)
	(calibration_target instrument14 GroundStation159)
	(calibration_target instrument14 GroundStation165)
	(calibration_target instrument14 GroundStation118)
	(calibration_target instrument14 Star168)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation95)
	(calibration_target instrument14 Star205)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 GroundStation163)
	(calibration_target instrument14 Star103)
	(calibration_target instrument14 Star176)
	(calibration_target instrument14 Star17)
	(calibration_target instrument14 Star84)
	(calibration_target instrument14 GroundStation145)
	(calibration_target instrument14 Star180)
	(calibration_target instrument14 Star51)
	(calibration_target instrument14 Star81)
	(calibration_target instrument14 GroundStation30)
	(calibration_target instrument14 GroundStation4)
	(calibration_target instrument14 GroundStation90)
	(calibration_target instrument14 GroundStation123)
	(calibration_target instrument14 Star111)
	(calibration_target instrument14 GroundStation29)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 GroundStation106)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 GroundStation187)
	(calibration_target instrument14 Star82)
	(calibration_target instrument14 GroundStation164)
	(calibration_target instrument14 GroundStation2)
	(calibration_target instrument14 Star77)
	(calibration_target instrument14 Star56)
	(calibration_target instrument14 Star121)
	(supports instrument15 infrared1)
	(calibration_target instrument15 Star82)
	(calibration_target instrument15 Star1)
	(calibration_target instrument15 GroundStation61)
	(calibration_target instrument15 GroundStation172)
	(calibration_target instrument15 GroundStation203)
	(calibration_target instrument15 Star166)
	(calibration_target instrument15 Star51)
	(calibration_target instrument15 Star25)
	(calibration_target instrument15 GroundStation159)
	(calibration_target instrument15 GroundStation149)
	(calibration_target instrument15 Star122)
	(calibration_target instrument15 GroundStation117)
	(calibration_target instrument15 GroundStation134)
	(calibration_target instrument15 Star19)
	(calibration_target instrument15 Star96)
	(calibration_target instrument15 Star190)
	(calibration_target instrument15 GroundStation55)
	(calibration_target instrument15 GroundStation109)
	(calibration_target instrument15 Star127)
	(calibration_target instrument15 GroundStation157)
	(calibration_target instrument15 GroundStation33)
	(calibration_target instrument15 Star100)
	(calibration_target instrument15 Star36)
	(calibration_target instrument15 Star46)
	(calibration_target instrument15 Star186)
	(calibration_target instrument15 GroundStation79)
	(calibration_target instrument15 GroundStation75)
	(calibration_target instrument15 GroundStation13)
	(calibration_target instrument15 GroundStation145)
	(calibration_target instrument15 GroundStation207)
	(calibration_target instrument15 GroundStation187)
	(calibration_target instrument15 Star49)
	(calibration_target instrument15 Star115)
	(calibration_target instrument15 GroundStation2)
	(calibration_target instrument15 Star124)
	(calibration_target instrument15 Star35)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 Star5)
	(on_board instrument12 satellite6)
	(on_board instrument13 satellite6)
	(on_board instrument14 satellite6)
	(on_board instrument15 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star160)
	(supports instrument16 spectrograph0)
	(calibration_target instrument16 Star167)
	(calibration_target instrument16 GroundStation181)
	(calibration_target instrument16 GroundStation37)
	(calibration_target instrument16 GroundStation137)
	(calibration_target instrument16 Star161)
	(calibration_target instrument16 GroundStation151)
	(calibration_target instrument16 Star34)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 GroundStation163)
	(calibration_target instrument16 GroundStation106)
	(calibration_target instrument16 Star119)
	(calibration_target instrument16 Star49)
	(calibration_target instrument16 GroundStation198)
	(calibration_target instrument16 Star70)
	(calibration_target instrument16 GroundStation4)
	(calibration_target instrument16 Star160)
	(calibration_target instrument16 Star104)
	(calibration_target instrument16 GroundStation52)
	(calibration_target instrument16 GroundStation69)
	(calibration_target instrument16 GroundStation197)
	(calibration_target instrument16 GroundStation94)
	(calibration_target instrument16 Star86)
	(calibration_target instrument16 GroundStation9)
	(calibration_target instrument16 GroundStation78)
	(calibration_target instrument16 GroundStation79)
	(calibration_target instrument16 Star113)
	(calibration_target instrument16 GroundStation75)
	(calibration_target instrument16 Star146)
	(calibration_target instrument16 GroundStation210)
	(calibration_target instrument16 GroundStation112)
	(on_board instrument16 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation157)
	(supports instrument17 spectrograph0)
	(calibration_target instrument17 GroundStation128)
	(calibration_target instrument17 Star185)
	(calibration_target instrument17 Star168)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 GroundStation106)
	(calibration_target instrument17 Star161)
	(calibration_target instrument17 GroundStation158)
	(calibration_target instrument17 GroundStation141)
	(calibration_target instrument17 Star89)
	(calibration_target instrument17 Star147)
	(calibration_target instrument17 Star129)
	(calibration_target instrument17 GroundStation179)
	(calibration_target instrument17 Star121)
	(calibration_target instrument17 Star206)
	(calibration_target instrument17 Star171)
	(calibration_target instrument17 GroundStation173)
	(calibration_target instrument17 GroundStation112)
	(calibration_target instrument17 Star100)
	(calibration_target instrument17 Star183)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star51)
	(calibration_target instrument17 Star167)
	(calibration_target instrument17 GroundStation210)
	(calibration_target instrument17 Star64)
	(calibration_target instrument17 GroundStation54)
	(calibration_target instrument17 GroundStation33)
	(calibration_target instrument17 GroundStation30)
	(calibration_target instrument17 GroundStation151)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 Star67)
	(calibration_target instrument17 GroundStation61)
	(calibration_target instrument17 Star73)
	(calibration_target instrument17 Star176)
	(calibration_target instrument17 GroundStation99)
	(calibration_target instrument17 Star70)
	(calibration_target instrument17 GroundStation0)
	(calibration_target instrument17 Star72)
	(calibration_target instrument17 Star208)
	(calibration_target instrument17 Star17)
	(calibration_target instrument17 GroundStation8)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star86)
	(calibration_target instrument17 Star188)
	(calibration_target instrument17 GroundStation192)
	(calibration_target instrument17 Star155)
	(calibration_target instrument17 Star59)
	(calibration_target instrument17 Star83)
	(calibration_target instrument17 GroundStation197)
	(calibration_target instrument17 Star82)
	(calibration_target instrument17 Star49)
	(calibration_target instrument17 Star114)
	(calibration_target instrument17 Star5)
	(calibration_target instrument17 GroundStation198)
	(calibration_target instrument17 GroundStation116)
	(calibration_target instrument17 Star178)
	(calibration_target instrument17 Star32)
	(calibration_target instrument17 Star48)
	(calibration_target instrument17 GroundStation57)
	(calibration_target instrument17 Star60)
	(calibration_target instrument17 Star62)
	(calibration_target instrument17 GroundStation68)
	(calibration_target instrument17 GroundStation23)
	(supports instrument18 image2)
	(supports instrument18 image4)
	(supports instrument18 image3)
	(calibration_target instrument18 GroundStation187)
	(calibration_target instrument18 Star83)
	(calibration_target instrument18 GroundStation144)
	(calibration_target instrument18 GroundStation162)
	(calibration_target instrument18 Star155)
	(calibration_target instrument18 GroundStation8)
	(calibration_target instrument18 GroundStation11)
	(calibration_target instrument18 Star124)
	(calibration_target instrument18 Star26)
	(calibration_target instrument18 Star82)
	(calibration_target instrument18 Star84)
	(calibration_target instrument18 GroundStation145)
	(calibration_target instrument18 GroundStation93)
	(calibration_target instrument18 GroundStation2)
	(calibration_target instrument18 Star24)
	(calibration_target instrument18 Star38)
	(calibration_target instrument18 Star34)
	(calibration_target instrument18 Star62)
	(calibration_target instrument18 Star194)
	(calibration_target instrument18 GroundStation18)
	(calibration_target instrument18 Star47)
	(calibration_target instrument18 Star16)
	(calibration_target instrument18 Star167)
	(calibration_target instrument18 Star67)
	(calibration_target instrument18 GroundStation108)
	(calibration_target instrument18 GroundStation13)
	(calibration_target instrument18 Star119)
	(calibration_target instrument18 Star135)
	(calibration_target instrument18 GroundStation106)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star206)
	(calibration_target instrument18 Star105)
	(calibration_target instrument18 Star36)
	(calibration_target instrument18 Star139)
	(calibration_target instrument18 GroundStation33)
	(calibration_target instrument18 Star3)
	(calibration_target instrument18 Star211)
	(calibration_target instrument18 Star89)
	(calibration_target instrument18 Star70)
	(calibration_target instrument18 Star85)
	(calibration_target instrument18 GroundStation57)
	(calibration_target instrument18 GroundStation133)
	(calibration_target instrument18 Star1)
	(calibration_target instrument18 Star41)
	(calibration_target instrument18 Star49)
	(calibration_target instrument18 GroundStation97)
	(calibration_target instrument18 Star127)
	(calibration_target instrument18 GroundStation95)
	(supports instrument19 infrared1)
	(supports instrument19 infrared5)
	(calibration_target instrument19 GroundStation170)
	(calibration_target instrument19 Star46)
	(calibration_target instrument19 GroundStation117)
	(calibration_target instrument19 Star186)
	(calibration_target instrument19 GroundStation163)
	(calibration_target instrument19 Star127)
	(calibration_target instrument19 Star193)
	(calibration_target instrument19 GroundStation9)
	(calibration_target instrument19 GroundStation61)
	(calibration_target instrument19 Star105)
	(calibration_target instrument19 GroundStation52)
	(calibration_target instrument19 GroundStation10)
	(calibration_target instrument19 GroundStation40)
	(on_board instrument17 satellite8)
	(on_board instrument18 satellite8)
	(on_board instrument19 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet261)
	(supports instrument20 image2)
	(calibration_target instrument20 GroundStation106)
	(calibration_target instrument20 GroundStation11)
	(calibration_target instrument20 GroundStation42)
	(calibration_target instrument20 Star146)
	(calibration_target instrument20 GroundStation133)
	(calibration_target instrument20 Star139)
	(calibration_target instrument20 GroundStation108)
	(calibration_target instrument20 Star34)
	(calibration_target instrument20 GroundStation101)
	(calibration_target instrument20 Star189)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 GroundStation45)
	(calibration_target instrument20 GroundStation7)
	(calibration_target instrument20 Star58)
	(calibration_target instrument20 Star191)
	(calibration_target instrument20 Star86)
	(calibration_target instrument20 GroundStation93)
	(calibration_target instrument20 Star147)
	(calibration_target instrument20 GroundStation39)
	(calibration_target instrument20 GroundStation30)
	(calibration_target instrument20 Star205)
	(calibration_target instrument20 GroundStation210)
	(calibration_target instrument20 GroundStation148)
	(calibration_target instrument20 GroundStation153)
	(calibration_target instrument20 Star81)
	(calibration_target instrument20 Star176)
	(calibration_target instrument20 Star103)
	(calibration_target instrument20 Star96)
	(calibration_target instrument20 GroundStation6)
	(calibration_target instrument20 Star16)
	(calibration_target instrument20 Star31)
	(calibration_target instrument20 GroundStation172)
	(calibration_target instrument20 Star41)
	(calibration_target instrument20 GroundStation169)
	(calibration_target instrument20 GroundStation8)
	(calibration_target instrument20 Star160)
	(calibration_target instrument20 GroundStation22)
	(calibration_target instrument20 GroundStation128)
	(calibration_target instrument20 Star196)
	(calibration_target instrument20 GroundStation20)
	(calibration_target instrument20 Star105)
	(calibration_target instrument20 GroundStation29)
	(calibration_target instrument20 GroundStation90)
	(on_board instrument20 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet296)
)
(:goal (and
	(pointing satellite2 Phenomenon290)
	(pointing satellite4 GroundStation44)
	(pointing satellite5 GroundStation61)
	(have_image Star212 infrared1)
	(have_image Phenomenon214 image2)
	(have_image Phenomenon214 infrared1)
	(have_image Planet215 spectrograph0)
	(have_image Planet215 infrared1)
	(have_image Planet216 image3)
	(have_image Planet217 infrared5)
	(have_image Planet217 image4)
	(have_image Phenomenon218 image2)
	(have_image Phenomenon218 image3)
	(have_image Phenomenon219 infrared5)
	(have_image Phenomenon219 image2)
	(have_image Phenomenon220 infrared1)
	(have_image Phenomenon220 image4)
	(have_image Planet221 spectrograph0)
	(have_image Phenomenon222 infrared1)
	(have_image Star223 spectrograph0)
	(have_image Star224 image3)
	(have_image Star225 infrared5)
	(have_image Star225 image4)
	(have_image Planet226 image3)
	(have_image Star227 image3)
	(have_image Star227 infrared1)
	(have_image Planet228 image3)
	(have_image Planet228 infrared5)
	(have_image Star229 image4)
	(have_image Star229 image2)
	(have_image Phenomenon231 spectrograph0)
	(have_image Star232 infrared1)
	(have_image Star232 image2)
	(have_image Planet233 image4)
	(have_image Planet233 infrared1)
	(have_image Star234 image2)
	(have_image Star234 infrared1)
	(have_image Phenomenon235 infrared5)
	(have_image Phenomenon235 image4)
	(have_image Phenomenon236 infrared5)
	(have_image Star237 infrared1)
	(have_image Star237 infrared5)
	(have_image Phenomenon238 infrared5)
	(have_image Phenomenon239 infrared5)
	(have_image Planet240 infrared1)
	(have_image Phenomenon241 image2)
	(have_image Star242 spectrograph0)
	(have_image Star243 infrared5)
	(have_image Star243 spectrograph0)
	(have_image Star244 image2)
	(have_image Star245 image2)
	(have_image Planet246 image2)
	(have_image Planet246 spectrograph0)
	(have_image Phenomenon247 infrared1)
	(have_image Phenomenon247 image2)
	(have_image Star248 image3)
	(have_image Phenomenon249 image3)
	(have_image Star250 infrared1)
	(have_image Planet251 image2)
	(have_image Planet251 image4)
	(have_image Phenomenon252 infrared1)
	(have_image Phenomenon252 infrared5)
	(have_image Star253 spectrograph0)
	(have_image Star253 image3)
	(have_image Star254 image3)
	(have_image Star254 spectrograph0)
	(have_image Phenomenon255 infrared5)
	(have_image Phenomenon255 image4)
	(have_image Star256 infrared1)
	(have_image Phenomenon257 image3)
	(have_image Phenomenon257 infrared1)
	(have_image Star258 image2)
	(have_image Planet259 image3)
	(have_image Star260 spectrograph0)
	(have_image Planet261 image2)
	(have_image Star262 image2)
	(have_image Phenomenon263 image3)
	(have_image Phenomenon263 spectrograph0)
	(have_image Phenomenon264 image3)
	(have_image Phenomenon264 image4)
	(have_image Planet265 image3)
	(have_image Phenomenon267 spectrograph0)
	(have_image Phenomenon267 image4)
	(have_image Phenomenon269 image3)
	(have_image Planet270 image4)
	(have_image Planet271 image3)
	(have_image Planet271 infrared1)
	(have_image Planet272 infrared5)
	(have_image Planet272 image3)
	(have_image Phenomenon273 image2)
	(have_image Planet274 image4)
	(have_image Planet274 spectrograph0)
	(have_image Phenomenon275 image3)
	(have_image Phenomenon275 image2)
	(have_image Planet276 image4)
	(have_image Planet276 infrared5)
	(have_image Planet277 image3)
	(have_image Planet278 spectrograph0)
	(have_image Planet278 image2)
	(have_image Planet279 image2)
	(have_image Planet280 image2)
	(have_image Planet281 spectrograph0)
	(have_image Planet281 image3)
	(have_image Phenomenon282 infrared5)
	(have_image Planet284 spectrograph0)
	(have_image Planet285 spectrograph0)
	(have_image Planet285 infrared5)
	(have_image Phenomenon286 image4)
	(have_image Phenomenon286 spectrograph0)
	(have_image Phenomenon287 image4)
	(have_image Phenomenon287 infrared1)
	(have_image Phenomenon288 image4)
	(have_image Planet289 image3)
	(have_image Phenomenon290 image4)
	(have_image Phenomenon291 spectrograph0)
	(have_image Star292 image2)
	(have_image Star292 infrared1)
	(have_image Phenomenon293 spectrograph0)
	(have_image Phenomenon293 infrared1)
	(have_image Phenomenon295 infrared1)
	(have_image Phenomenon295 image3)
	(have_image Planet296 image4)
	(have_image Planet296 image2)
	(have_image Planet297 image4)
	(have_image Planet297 image3)
	(have_image Phenomenon298 image2)
	(have_image Phenomenon299 image2)
	(have_image Phenomenon299 image3)
	(have_image Planet300 infrared5)
	(have_image Planet300 image4)
	(have_image Phenomenon301 infrared5)
	(have_image Phenomenon302 infrared1)
	(have_image Phenomenon302 image4)
	(have_image Planet304 image2)
	(have_image Planet304 image4)
	(have_image Phenomenon305 image4)
	(have_image Star306 image2)
	(have_image Planet307 image3)
	(have_image Planet307 image4)
	(have_image Phenomenon308 spectrograph0)
	(have_image Phenomenon308 image3)
	(have_image Phenomenon309 infrared1)
	(have_image Phenomenon309 image4)
	(have_image Phenomenon311 spectrograph0)
	(have_image Star312 infrared5)
	(have_image Phenomenon313 infrared1)
	(have_image Phenomenon314 image3)
	(have_image Phenomenon314 spectrograph0)
	(have_image Star315 image4)
	(have_image Star316 image2)
	(have_image Star316 infrared5)
	(have_image Planet317 image3)
	(have_image Planet317 infrared5)
	(have_image Phenomenon318 spectrograph0)
	(have_image Star319 infrared1)
	(have_image Star319 image4)
	(have_image Phenomenon320 image2)
	(have_image Planet321 image2)
	(have_image Star322 infrared5)
	(have_image Star322 image2)
	(have_image Star323 image4)
	(have_image Star323 infrared5)
	(have_image Phenomenon324 image2)
	(have_image Phenomenon324 image3)
	(have_image Planet325 spectrograph0)
	(have_image Planet325 image3)
	(have_image Star326 infrared5)
	(have_image Star326 image2)
	(have_image Phenomenon327 spectrograph0)
	(have_image Phenomenon327 image4)
	(have_image Planet328 spectrograph0)
	(have_image Phenomenon329 image3)
	(have_image Phenomenon330 spectrograph0)
	(have_image Phenomenon330 infrared1)
	(have_image Planet331 image3)
	(have_image Phenomenon333 image3)
	(have_image Phenomenon333 image4)
	(have_image Phenomenon334 infrared1)
	(have_image Phenomenon334 image4)
	(have_image Star335 image2)
	(have_image Phenomenon336 infrared1)
	(have_image Planet337 spectrograph0)
	(have_image Planet337 image3)
	(have_image Planet339 infrared5)
	(have_image Planet339 image3)
	(have_image Planet340 infrared1)
	(have_image Planet340 infrared5)
	(have_image Phenomenon342 image2)
	(have_image Planet344 infrared1)
	(have_image Planet345 image4)
	(have_image Planet345 infrared5)
	(have_image Planet346 infrared5)
	(have_image Planet346 infrared1)
	(have_image Phenomenon349 image2)
	(have_image Star350 image3)
	(have_image Planet351 infrared5)
	(have_image Phenomenon353 spectrograph0)
	(have_image Phenomenon353 infrared1)
	(have_image Star354 image3)
	(have_image Star354 image4)
	(have_image Planet355 image4)
	(have_image Star356 infrared5)
	(have_image Star356 spectrograph0)
	(have_image Phenomenon357 spectrograph0)
	(have_image Phenomenon357 image4)
	(have_image Phenomenon358 spectrograph0)
	(have_image Star359 image4)
	(have_image Star359 image3)
	(have_image Phenomenon360 image2)
	(have_image Planet361 image2)
	(have_image Phenomenon362 image2)
	(have_image Phenomenon362 image3)
	(have_image Planet363 spectrograph0)
	(have_image Planet363 infrared1)
	(have_image Star364 infrared5)
	(have_image Phenomenon366 image3)
	(have_image Phenomenon366 image2)
	(have_image Star367 image2)
	(have_image Planet368 image4)
	(have_image Star369 infrared5)
	(have_image Star370 image3)
	(have_image Star370 spectrograph0)
	(have_image Planet371 image3)
	(have_image Planet371 image4)
	(have_image Planet372 infrared5)
	(have_image Planet372 image4)
	(have_image Planet374 image4)
	(have_image Planet374 infrared1)
	(have_image Star375 infrared1)
	(have_image Phenomenon376 image2)
	(have_image Phenomenon376 infrared5)
	(have_image Star377 image3)
	(have_image Star377 image4)
	(have_image Planet379 infrared1)
	(have_image Star380 infrared5)
	(have_image Star380 image2)
	(have_image Phenomenon381 spectrograph0)
	(have_image Star384 infrared5)
	(have_image Star384 image2)
	(have_image Phenomenon385 infrared1)
	(have_image Phenomenon385 image3)
	(have_image Phenomenon386 infrared5)
	(have_image Planet387 image4)
	(have_image Planet387 image3)
	(have_image Planet388 image4)
	(have_image Planet389 image4)
	(have_image Planet389 infrared5)
	(have_image Star390 image2)
	(have_image Planet391 image3)
	(have_image Star392 image3)
	(have_image Planet393 infrared1)
	(have_image Star395 image4)
	(have_image Phenomenon396 infrared5)
	(have_image Planet398 image4)
	(have_image Planet399 spectrograph0)
	(have_image Planet399 image3)
	(have_image Star400 infrared1)
	(have_image Star400 spectrograph0)
	(have_image Planet401 image2)
	(have_image Planet401 infrared5)
	(have_image Star402 image2)
	(have_image Star402 infrared5)
	(have_image Planet403 image3)
	(have_image Planet403 image2)
	(have_image Phenomenon404 spectrograph0)
	(have_image Phenomenon404 infrared1)
	(have_image Planet405 image2)
	(have_image Star406 spectrograph0)
	(have_image Phenomenon407 spectrograph0)
	(have_image Planet408 infrared1)
	(have_image Phenomenon409 image4)
	(have_image Phenomenon409 infrared1)
	(have_image Star410 infrared5)
	(have_image Star410 spectrograph0)
	(have_image Phenomenon411 image2)
	(have_image Phenomenon412 image4)
	(have_image Planet413 image4)
	(have_image Planet414 image3)
	(have_image Planet414 image4)
	(have_image Planet415 image4)
	(have_image Planet415 infrared1)
	(have_image Planet416 image2)
	(have_image Planet416 spectrograph0)
	(have_image Planet417 image3)
	(have_image Planet418 infrared1)
	(have_image Planet418 image4)
	(have_image Phenomenon419 infrared1)
	(have_image Phenomenon419 image3)
	(have_image Planet420 spectrograph0)
	(have_image Star421 infrared1)
	(have_image Star421 spectrograph0)
	(have_image Phenomenon422 image4)
	(have_image Star423 image3)
	(have_image Star423 image4)
))

)
