(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	satellite6 - satellite
	instrument16 - instrument
	instrument17 - instrument
	satellite7 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	satellite8 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	instrument25 - instrument
	satellite9 - satellite
	instrument26 - instrument
	satellite10 - satellite
	instrument27 - instrument
	instrument28 - instrument
	infrared4 - mode
	infrared1 - mode
	image0 - mode
	infrared3 - mode
	infrared5 - mode
	thermograph2 - mode
	GroundStation51 - direction
	Star7 - direction
	GroundStation10 - direction
	Star134 - direction
	Star185 - direction
	Star117 - direction
	Star150 - direction
	GroundStation53 - direction
	GroundStation151 - direction
	Star213 - direction
	Star159 - direction
	GroundStation181 - direction
	GroundStation217 - direction
	Star62 - direction
	GroundStation169 - direction
	Star109 - direction
	GroundStation113 - direction
	Star165 - direction
	GroundStation21 - direction
	GroundStation65 - direction
	Star35 - direction
	GroundStation130 - direction
	GroundStation129 - direction
	Star26 - direction
	Star147 - direction
	GroundStation18 - direction
	Star50 - direction
	GroundStation197 - direction
	GroundStation12 - direction
	GroundStation78 - direction
	GroundStation171 - direction
	Star214 - direction
	GroundStation107 - direction
	GroundStation103 - direction
	GroundStation206 - direction
	GroundStation106 - direction
	Star195 - direction
	GroundStation40 - direction
	Star66 - direction
	GroundStation192 - direction
	GroundStation166 - direction
	Star20 - direction
	GroundStation15 - direction
	Star48 - direction
	Star22 - direction
	Star201 - direction
	GroundStation198 - direction
	Star16 - direction
	Star69 - direction
	Star188 - direction
	Star140 - direction
	GroundStation63 - direction
	Star218 - direction
	Star212 - direction
	GroundStation99 - direction
	GroundStation43 - direction
	Star8 - direction
	GroundStation102 - direction
	GroundStation202 - direction
	Star45 - direction
	Star2 - direction
	GroundStation156 - direction
	Star211 - direction
	GroundStation143 - direction
	GroundStation1 - direction
	GroundStation190 - direction
	Star205 - direction
	GroundStation137 - direction
	GroundStation14 - direction
	Star172 - direction
	GroundStation49 - direction
	Star131 - direction
	Star56 - direction
	Star176 - direction
	GroundStation199 - direction
	GroundStation216 - direction
	Star158 - direction
	Star38 - direction
	Star135 - direction
	Star34 - direction
	Star174 - direction
	Star32 - direction
	Star82 - direction
	Star41 - direction
	GroundStation85 - direction
	GroundStation55 - direction
	GroundStation167 - direction
	Star136 - direction
	GroundStation209 - direction
	GroundStation124 - direction
	GroundStation132 - direction
	GroundStation110 - direction
	Star30 - direction
	GroundStation184 - direction
	GroundStation122 - direction
	Star133 - direction
	GroundStation75 - direction
	GroundStation33 - direction
	Star168 - direction
	GroundStation93 - direction
	Star163 - direction
	GroundStation219 - direction
	Star3 - direction
	Star108 - direction
	GroundStation83 - direction
	GroundStation114 - direction
	Star116 - direction
	GroundStation96 - direction
	GroundStation157 - direction
	GroundStation164 - direction
	GroundStation125 - direction
	Star155 - direction
	GroundStation71 - direction
	Star186 - direction
	Star13 - direction
	GroundStation180 - direction
	Star61 - direction
	GroundStation25 - direction
	Star91 - direction
	GroundStation92 - direction
	GroundStation173 - direction
	GroundStation37 - direction
	GroundStation101 - direction
	GroundStation90 - direction
	Star31 - direction
	GroundStation115 - direction
	Star119 - direction
	GroundStation142 - direction
	Star97 - direction
	Star80 - direction
	GroundStation144 - direction
	GroundStation175 - direction
	Star138 - direction
	GroundStation5 - direction
	GroundStation94 - direction
	GroundStation123 - direction
	Star120 - direction
	GroundStation52 - direction
	Star23 - direction
	Star89 - direction
	Star39 - direction
	GroundStation121 - direction
	Star57 - direction
	GroundStation9 - direction
	Star128 - direction
	GroundStation68 - direction
	GroundStation88 - direction
	GroundStation178 - direction
	Star98 - direction
	GroundStation11 - direction
	Star145 - direction
	Star36 - direction
	Star76 - direction
	GroundStation149 - direction
	Star193 - direction
	Star179 - direction
	GroundStation72 - direction
	Star28 - direction
	GroundStation161 - direction
	GroundStation210 - direction
	GroundStation126 - direction
	GroundStation60 - direction
	Star47 - direction
	Star154 - direction
	Star105 - direction
	GroundStation59 - direction
	Star87 - direction
	Star182 - direction
	Star46 - direction
	Star81 - direction
	GroundStation146 - direction
	Star189 - direction
	Star79 - direction
	Star70 - direction
	GroundStation170 - direction
	Star187 - direction
	GroundStation100 - direction
	Star200 - direction
	Star86 - direction
	Star4 - direction
	GroundStation152 - direction
	GroundStation77 - direction
	GroundStation127 - direction
	GroundStation191 - direction
	GroundStation204 - direction
	Star215 - direction
	GroundStation183 - direction
	Star42 - direction
	Star148 - direction
	Star194 - direction
	GroundStation153 - direction
	GroundStation84 - direction
	GroundStation73 - direction
	Star118 - direction
	Star111 - direction
	Star67 - direction
	Star112 - direction
	GroundStation17 - direction
	GroundStation58 - direction
	GroundStation207 - direction
	Star104 - direction
	Star141 - direction
	GroundStation160 - direction
	Star0 - direction
	GroundStation29 - direction
	GroundStation208 - direction
	GroundStation44 - direction
	GroundStation27 - direction
	GroundStation24 - direction
	Star196 - direction
	Star19 - direction
	GroundStation74 - direction
	GroundStation6 - direction
	Star64 - direction
	Star139 - direction
	GroundStation203 - direction
	Star54 - direction
	GroundStation95 - direction
	Star162 - direction
	GroundStation177 - direction
	Star220 - direction
	Phenomenon221 - direction
	Phenomenon222 - direction
	Planet223 - direction
	Phenomenon224 - direction
	Planet225 - direction
	Star226 - direction
	Planet227 - direction
	Planet228 - direction
	Phenomenon229 - direction
	Star230 - direction
	Planet231 - direction
	Phenomenon232 - direction
	Phenomenon233 - direction
	Phenomenon234 - direction
	Phenomenon235 - direction
	Star236 - direction
	Planet237 - direction
	Planet238 - direction
	Star239 - direction
	Planet240 - direction
	Planet241 - direction
	Planet242 - direction
	Phenomenon243 - direction
	Planet244 - direction
	Star245 - direction
	Planet246 - direction
	Phenomenon247 - direction
	Phenomenon248 - direction
	Star249 - direction
	Star250 - direction
	Planet251 - direction
	Planet252 - direction
	Phenomenon253 - direction
	Planet254 - direction
	Planet255 - direction
	Star256 - direction
	Star257 - direction
	Phenomenon258 - direction
	Planet259 - direction
	Phenomenon260 - direction
	Star261 - direction
	Planet262 - direction
	Phenomenon263 - direction
	Star264 - direction
	Phenomenon265 - direction
	Phenomenon266 - direction
	Planet267 - direction
	Phenomenon268 - direction
	Star269 - direction
	Star270 - direction
	Phenomenon271 - direction
	Planet272 - direction
	Planet273 - direction
	Planet274 - direction
	Star275 - direction
	Planet276 - direction
	Star277 - direction
	Phenomenon278 - direction
	Star279 - direction
	Star280 - direction
	Star281 - direction
	Planet282 - direction
	Phenomenon283 - direction
	Planet284 - direction
	Planet285 - direction
	Planet286 - direction
	Phenomenon287 - direction
	Phenomenon288 - direction
	Star289 - direction
	Phenomenon290 - direction
	Planet291 - direction
	Phenomenon292 - direction
	Star293 - direction
	Planet294 - direction
	Phenomenon295 - direction
	Planet296 - direction
	Planet297 - direction
	Star298 - direction
	Star299 - direction
	Phenomenon300 - direction
	Star301 - direction
	Planet302 - direction
	Star303 - direction
	Phenomenon304 - direction
	Phenomenon305 - direction
	Star306 - direction
	Planet307 - direction
	Phenomenon308 - direction
	Planet309 - direction
	Phenomenon310 - direction
	Phenomenon311 - direction
	Phenomenon312 - direction
	Planet313 - direction
	Phenomenon314 - direction
	Phenomenon315 - direction
	Phenomenon316 - direction
	Planet317 - direction
	Phenomenon318 - direction
	Phenomenon319 - direction
	Phenomenon320 - direction
	Planet321 - direction
	Phenomenon322 - direction
	Phenomenon323 - direction
	Star324 - direction
	Phenomenon325 - direction
	Star326 - direction
	Planet327 - direction
	Star328 - direction
	Star329 - direction
	Star330 - direction
	Phenomenon331 - direction
	Star332 - direction
	Planet333 - direction
	Planet334 - direction
	Star335 - direction
	Planet336 - direction
	Phenomenon337 - direction
	Star338 - direction
	Phenomenon339 - direction
	Planet340 - direction
	Star341 - direction
	Planet342 - direction
	Planet343 - direction
	Phenomenon344 - direction
	Phenomenon345 - direction
	Star346 - direction
	Planet347 - direction
	Planet348 - direction
	Phenomenon349 - direction
	Star350 - direction
	Star351 - direction
	Phenomenon352 - direction
	Planet353 - direction
	Planet354 - direction
	Star355 - direction
	Planet356 - direction
	Phenomenon357 - direction
	Phenomenon358 - direction
	Phenomenon359 - direction
	Star360 - direction
	Phenomenon361 - direction
	Planet362 - direction
	Star363 - direction
	Phenomenon364 - direction
	Planet365 - direction
	Star366 - direction
	Star367 - direction
	Star368 - direction
	Planet369 - direction
	Star370 - direction
	Phenomenon371 - direction
	Planet372 - direction
	Phenomenon373 - direction
	Planet374 - direction
	Phenomenon375 - direction
	Phenomenon376 - direction
	Planet377 - direction
	Planet378 - direction
	Phenomenon379 - direction
	Star380 - direction
	Planet381 - direction
	Star382 - direction
	Star383 - direction
	Phenomenon384 - direction
	Phenomenon385 - direction
	Star386 - direction
	Star387 - direction
	Star388 - direction
	Star389 - direction
	Planet390 - direction
	Star391 - direction
	Phenomenon392 - direction
	Planet393 - direction
	Planet394 - direction
	Star395 - direction
	Planet396 - direction
	Star397 - direction
	Planet398 - direction
	Star399 - direction
	Planet400 - direction
	Planet401 - direction
	Planet402 - direction
	Planet403 - direction
	Phenomenon404 - direction
	Phenomenon405 - direction
	Phenomenon406 - direction
	Phenomenon407 - direction
	Planet408 - direction
	Star409 - direction
	Star410 - direction
	Star411 - direction
	Planet412 - direction
	Planet413 - direction
	Star414 - direction
	Phenomenon415 - direction
	Phenomenon416 - direction
	Star417 - direction
	Phenomenon418 - direction
	Star419 - direction
	Star420 - direction
	Planet421 - direction
	Planet422 - direction
	Phenomenon423 - direction
	Star424 - direction
	Planet425 - direction
	Phenomenon426 - direction
	Phenomenon427 - direction
	Star428 - direction
	Star429 - direction
	Planet430 - direction
	Phenomenon431 - direction
	Star432 - direction
	Planet433 - direction
	Phenomenon434 - direction
	Phenomenon435 - direction
	Star436 - direction
	Phenomenon437 - direction
	Planet438 - direction
	Planet439 - direction
)
(:init
	(supports instrument0 infrared3)
	(supports instrument0 infrared4)
	(supports instrument0 infrared5)
	(calibration_target instrument0 GroundStation170)
	(calibration_target instrument0 GroundStation88)
	(calibration_target instrument0 GroundStation169)
	(calibration_target instrument0 Star193)
	(calibration_target instrument0 Star98)
	(calibration_target instrument0 GroundStation167)
	(calibration_target instrument0 Star179)
	(calibration_target instrument0 GroundStation94)
	(calibration_target instrument0 Star116)
	(calibration_target instrument0 Star159)
	(calibration_target instrument0 GroundStation113)
	(calibration_target instrument0 Star168)
	(calibration_target instrument0 Star34)
	(calibration_target instrument0 GroundStation126)
	(calibration_target instrument0 GroundStation203)
	(calibration_target instrument0 Star218)
	(calibration_target instrument0 Star158)
	(calibration_target instrument0 GroundStation102)
	(calibration_target instrument0 GroundStation175)
	(calibration_target instrument0 Star41)
	(calibration_target instrument0 Star147)
	(calibration_target instrument0 Star91)
	(calibration_target instrument0 GroundStation53)
	(calibration_target instrument0 Star87)
	(calibration_target instrument0 GroundStation43)
	(calibration_target instrument0 GroundStation33)
	(calibration_target instrument0 Star50)
	(calibration_target instrument0 GroundStation216)
	(calibration_target instrument0 Star35)
	(calibration_target instrument0 GroundStation6)
	(calibration_target instrument0 GroundStation123)
	(calibration_target instrument0 GroundStation208)
	(calibration_target instrument0 GroundStation93)
	(calibration_target instrument0 GroundStation71)
	(calibration_target instrument0 GroundStation183)
	(calibration_target instrument0 Star195)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 Star139)
	(calibration_target instrument0 GroundStation68)
	(calibration_target instrument0 Star138)
	(calibration_target instrument0 Star80)
	(calibration_target instrument0 Star187)
	(calibration_target instrument0 Star86)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation88)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 Star22)
	(calibration_target instrument1 Star145)
	(calibration_target instrument1 GroundStation14)
	(calibration_target instrument1 Star205)
	(calibration_target instrument1 Star117)
	(calibration_target instrument1 GroundStation68)
	(calibration_target instrument1 Star76)
	(calibration_target instrument1 Star118)
	(calibration_target instrument1 GroundStation60)
	(calibration_target instrument1 Star45)
	(calibration_target instrument1 Star19)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star87)
	(calibration_target instrument1 GroundStation40)
	(calibration_target instrument1 GroundStation103)
	(calibration_target instrument1 GroundStation12)
	(calibration_target instrument1 GroundStation153)
	(calibration_target instrument1 Star69)
	(calibration_target instrument1 Star108)
	(calibration_target instrument1 Star215)
	(calibration_target instrument1 Star133)
	(calibration_target instrument1 GroundStation24)
	(calibration_target instrument1 GroundStation149)
	(calibration_target instrument1 Star136)
	(calibration_target instrument1 GroundStation121)
	(calibration_target instrument1 Star61)
	(calibration_target instrument1 Star141)
	(calibration_target instrument1 GroundStation164)
	(calibration_target instrument1 Star26)
	(calibration_target instrument1 GroundStation137)
	(calibration_target instrument1 GroundStation199)
	(calibration_target instrument1 Star54)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation217)
	(calibration_target instrument1 Star34)
	(calibration_target instrument1 GroundStation129)
	(calibration_target instrument1 Star172)
	(calibration_target instrument1 GroundStation65)
	(calibration_target instrument1 Star147)
	(calibration_target instrument1 GroundStation71)
	(calibration_target instrument1 GroundStation110)
	(calibration_target instrument1 Star98)
	(calibration_target instrument1 GroundStation123)
	(calibration_target instrument1 Star79)
	(calibration_target instrument1 Star36)
	(calibration_target instrument1 Star62)
	(calibration_target instrument1 Star97)
	(calibration_target instrument1 GroundStation191)
	(calibration_target instrument1 GroundStation132)
	(calibration_target instrument1 GroundStation202)
	(calibration_target instrument1 GroundStation130)
	(calibration_target instrument1 GroundStation113)
	(calibration_target instrument1 Star138)
	(calibration_target instrument1 Star0)
	(calibration_target instrument1 Star120)
	(calibration_target instrument1 Star67)
	(calibration_target instrument1 GroundStation59)
	(calibration_target instrument1 GroundStation203)
	(calibration_target instrument1 Star195)
	(calibration_target instrument1 GroundStation85)
	(calibration_target instrument1 GroundStation115)
	(calibration_target instrument1 Star155)
	(supports instrument2 infrared5)
	(calibration_target instrument2 GroundStation100)
	(calibration_target instrument2 GroundStation183)
	(calibration_target instrument2 Star128)
	(calibration_target instrument2 GroundStation55)
	(calibration_target instrument2 Star87)
	(calibration_target instrument2 Star135)
	(calibration_target instrument2 GroundStation102)
	(calibration_target instrument2 GroundStation175)
	(supports instrument3 image0)
	(calibration_target instrument3 Star98)
	(calibration_target instrument3 GroundStation44)
	(calibration_target instrument3 Star89)
	(calibration_target instrument3 Star147)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star45)
	(supports instrument4 infrared3)
	(calibration_target instrument4 GroundStation153)
	(calibration_target instrument4 GroundStation1)
	(calibration_target instrument4 Star66)
	(calibration_target instrument4 Star136)
	(calibration_target instrument4 GroundStation29)
	(calibration_target instrument4 GroundStation55)
	(calibration_target instrument4 Star185)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 Star165)
	(calibration_target instrument4 Star205)
	(calibration_target instrument4 GroundStation58)
	(calibration_target instrument4 GroundStation207)
	(calibration_target instrument4 Star87)
	(calibration_target instrument4 Star118)
	(calibration_target instrument4 Star158)
	(calibration_target instrument4 GroundStation78)
	(calibration_target instrument4 GroundStation203)
	(calibration_target instrument4 Star154)
	(calibration_target instrument4 Star218)
	(calibration_target instrument4 Star163)
	(calibration_target instrument4 GroundStation24)
	(calibration_target instrument4 Star79)
	(calibration_target instrument4 Star81)
	(calibration_target instrument4 GroundStation85)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 Star112)
	(calibration_target instrument4 Star46)
	(calibration_target instrument4 GroundStation6)
	(calibration_target instrument4 GroundStation198)
	(calibration_target instrument4 Star194)
	(calibration_target instrument4 GroundStation197)
	(calibration_target instrument4 Star150)
	(calibration_target instrument4 Star196)
	(calibration_target instrument4 Star179)
	(calibration_target instrument4 GroundStation75)
	(calibration_target instrument4 Star139)
	(calibration_target instrument4 Star41)
	(calibration_target instrument4 Star116)
	(calibration_target instrument4 GroundStation33)
	(calibration_target instrument4 GroundStation44)
	(calibration_target instrument4 Star187)
	(calibration_target instrument4 Star97)
	(calibration_target instrument4 Star201)
	(calibration_target instrument4 GroundStation210)
	(calibration_target instrument4 GroundStation169)
	(calibration_target instrument4 Star39)
	(calibration_target instrument4 GroundStation130)
	(calibration_target instrument4 GroundStation142)
	(calibration_target instrument4 Star186)
	(calibration_target instrument4 Star131)
	(calibration_target instrument4 Star62)
	(calibration_target instrument4 GroundStation127)
	(calibration_target instrument4 Star28)
	(calibration_target instrument4 GroundStation14)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 Star38)
	(calibration_target instrument4 GroundStation77)
	(calibration_target instrument4 GroundStation49)
	(calibration_target instrument4 Star120)
	(calibration_target instrument4 GroundStation59)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 Star64)
	(calibration_target instrument4 GroundStation9)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 GroundStation164)
	(calibration_target instrument4 GroundStation95)
	(supports instrument5 infrared5)
	(supports instrument5 infrared1)
	(calibration_target instrument5 GroundStation173)
	(calibration_target instrument5 Star182)
	(calibration_target instrument5 GroundStation123)
	(calibration_target instrument5 Star145)
	(calibration_target instrument5 GroundStation63)
	(supports instrument6 infrared3)
	(supports instrument6 infrared1)
	(calibration_target instrument6 Star48)
	(calibration_target instrument6 GroundStation207)
	(calibration_target instrument6 GroundStation208)
	(calibration_target instrument6 GroundStation17)
	(calibration_target instrument6 Star82)
	(calibration_target instrument6 Star185)
	(calibration_target instrument6 Star215)
	(calibration_target instrument6 GroundStation25)
	(calibration_target instrument6 GroundStation106)
	(calibration_target instrument6 GroundStation181)
	(calibration_target instrument6 GroundStation92)
	(calibration_target instrument6 Star139)
	(calibration_target instrument6 Star91)
	(calibration_target instrument6 GroundStation127)
	(calibration_target instrument6 Star213)
	(calibration_target instrument6 GroundStation33)
	(calibration_target instrument6 GroundStation44)
	(calibration_target instrument6 GroundStation68)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star26)
	(supports instrument7 thermograph2)
	(supports instrument7 infrared4)
	(supports instrument7 infrared1)
	(calibration_target instrument7 Star41)
	(calibration_target instrument7 Star186)
	(calibration_target instrument7 GroundStation122)
	(calibration_target instrument7 GroundStation207)
	(calibration_target instrument7 Star145)
	(calibration_target instrument7 GroundStation15)
	(calibration_target instrument7 Star140)
	(calibration_target instrument7 GroundStation164)
	(calibration_target instrument7 Star62)
	(calibration_target instrument7 GroundStation183)
	(calibration_target instrument7 GroundStation1)
	(calibration_target instrument7 Star111)
	(calibration_target instrument7 Star187)
	(calibration_target instrument7 GroundStation94)
	(calibration_target instrument7 Star38)
	(calibration_target instrument7 Star46)
	(calibration_target instrument7 GroundStation177)
	(calibration_target instrument7 Star174)
	(calibration_target instrument7 Star139)
	(calibration_target instrument7 GroundStation52)
	(calibration_target instrument7 Star168)
	(calibration_target instrument7 GroundStation107)
	(calibration_target instrument7 Star31)
	(calibration_target instrument7 GroundStation198)
	(calibration_target instrument7 GroundStation129)
	(calibration_target instrument7 GroundStation203)
	(calibration_target instrument7 Star45)
	(calibration_target instrument7 Star133)
	(calibration_target instrument7 GroundStation106)
	(calibration_target instrument7 Star119)
	(calibration_target instrument7 Star155)
	(calibration_target instrument7 Star28)
	(calibration_target instrument7 GroundStation58)
	(calibration_target instrument7 GroundStation40)
	(calibration_target instrument7 GroundStation5)
	(calibration_target instrument7 Star196)
	(calibration_target instrument7 Star138)
	(calibration_target instrument7 GroundStation29)
	(calibration_target instrument7 Star193)
	(calibration_target instrument7 GroundStation99)
	(calibration_target instrument7 Star7)
	(calibration_target instrument7 GroundStation192)
	(calibration_target instrument7 GroundStation190)
	(calibration_target instrument7 GroundStation161)
	(calibration_target instrument7 Star120)
	(calibration_target instrument7 Star185)
	(calibration_target instrument7 GroundStation11)
	(calibration_target instrument7 Star213)
	(calibration_target instrument7 GroundStation157)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 GroundStation10)
	(calibration_target instrument7 Star30)
	(calibration_target instrument7 GroundStation84)
	(calibration_target instrument7 Star47)
	(calibration_target instrument7 GroundStation126)
	(calibration_target instrument7 Star22)
	(calibration_target instrument7 Star66)
	(calibration_target instrument7 GroundStation33)
	(calibration_target instrument7 GroundStation90)
	(calibration_target instrument7 GroundStation78)
	(calibration_target instrument7 GroundStation74)
	(calibration_target instrument7 Star26)
	(calibration_target instrument7 GroundStation103)
	(calibration_target instrument7 GroundStation181)
	(supports instrument8 infrared5)
	(calibration_target instrument8 Star176)
	(calibration_target instrument8 GroundStation68)
	(calibration_target instrument8 GroundStation52)
	(calibration_target instrument8 Star179)
	(calibration_target instrument8 GroundStation183)
	(calibration_target instrument8 Star189)
	(calibration_target instrument8 Star32)
	(calibration_target instrument8 GroundStation152)
	(calibration_target instrument8 GroundStation199)
	(calibration_target instrument8 GroundStation6)
	(calibration_target instrument8 Star98)
	(calibration_target instrument8 Star141)
	(calibration_target instrument8 GroundStation156)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star172)
	(calibration_target instrument8 GroundStation40)
	(calibration_target instrument8 Star87)
	(calibration_target instrument8 Star28)
	(calibration_target instrument8 Star194)
	(calibration_target instrument8 GroundStation10)
	(calibration_target instrument8 Star20)
	(calibration_target instrument8 GroundStation146)
	(calibration_target instrument8 Star70)
	(calibration_target instrument8 GroundStation149)
	(calibration_target instrument8 GroundStation151)
	(calibration_target instrument8 Star89)
	(calibration_target instrument8 GroundStation94)
	(calibration_target instrument8 GroundStation192)
	(calibration_target instrument8 GroundStation173)
	(calibration_target instrument8 GroundStation21)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 Star193)
	(calibration_target instrument8 GroundStation107)
	(calibration_target instrument8 Star211)
	(calibration_target instrument8 Star69)
	(calibration_target instrument8 Star155)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star13)
	(calibration_target instrument9 GroundStation15)
	(calibration_target instrument9 GroundStation178)
	(calibration_target instrument9 GroundStation92)
	(calibration_target instrument9 GroundStation144)
	(calibration_target instrument9 GroundStation157)
	(calibration_target instrument9 GroundStation151)
	(calibration_target instrument9 Star201)
	(calibration_target instrument9 GroundStation121)
	(calibration_target instrument9 Star36)
	(calibration_target instrument9 GroundStation180)
	(calibration_target instrument9 GroundStation124)
	(calibration_target instrument9 Star109)
	(supports instrument10 thermograph2)
	(supports instrument10 infrared5)
	(calibration_target instrument10 GroundStation173)
	(calibration_target instrument10 GroundStation177)
	(calibration_target instrument10 Star47)
	(calibration_target instrument10 GroundStation180)
	(calibration_target instrument10 Star4)
	(calibration_target instrument10 GroundStation198)
	(calibration_target instrument10 GroundStation84)
	(calibration_target instrument10 GroundStation93)
	(calibration_target instrument10 GroundStation209)
	(calibration_target instrument10 Star32)
	(calibration_target instrument10 GroundStation85)
	(calibration_target instrument10 Star108)
	(calibration_target instrument10 Star2)
	(calibration_target instrument10 Star91)
	(calibration_target instrument10 GroundStation72)
	(calibration_target instrument10 Star31)
	(calibration_target instrument10 GroundStation125)
	(calibration_target instrument10 Star133)
	(calibration_target instrument10 GroundStation60)
	(calibration_target instrument10 GroundStation68)
	(calibration_target instrument10 Star134)
	(calibration_target instrument10 GroundStation157)
	(calibration_target instrument10 Star163)
	(calibration_target instrument10 Star162)
	(calibration_target instrument10 Star80)
	(calibration_target instrument10 GroundStation73)
	(calibration_target instrument10 Star62)
	(calibration_target instrument10 Star66)
	(calibration_target instrument10 Star168)
	(calibration_target instrument10 Star218)
	(calibration_target instrument10 Star131)
	(calibration_target instrument10 GroundStation127)
	(calibration_target instrument10 Star159)
	(calibration_target instrument10 GroundStation151)
	(calibration_target instrument10 Star205)
	(calibration_target instrument10 Star118)
	(calibration_target instrument10 GroundStation106)
	(calibration_target instrument10 Star105)
	(calibration_target instrument10 GroundStation29)
	(calibration_target instrument10 Star89)
	(calibration_target instrument10 GroundStation178)
	(calibration_target instrument10 Star148)
	(calibration_target instrument10 GroundStation184)
	(calibration_target instrument10 GroundStation92)
	(calibration_target instrument10 Star213)
	(calibration_target instrument10 Star35)
	(calibration_target instrument10 GroundStation203)
	(calibration_target instrument10 Star139)
	(calibration_target instrument10 GroundStation149)
	(calibration_target instrument10 GroundStation121)
	(calibration_target instrument10 GroundStation11)
	(calibration_target instrument10 Star98)
	(calibration_target instrument10 Star179)
	(calibration_target instrument10 GroundStation114)
	(calibration_target instrument10 GroundStation18)
	(calibration_target instrument10 Star188)
	(calibration_target instrument10 GroundStation219)
	(calibration_target instrument10 Star140)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon247)
	(supports instrument11 infrared3)
	(supports instrument11 infrared4)
	(supports instrument11 infrared1)
	(calibration_target instrument11 Star133)
	(calibration_target instrument11 GroundStation77)
	(calibration_target instrument11 GroundStation5)
	(calibration_target instrument11 Star195)
	(calibration_target instrument11 GroundStation92)
	(calibration_target instrument11 GroundStation180)
	(calibration_target instrument11 GroundStation125)
	(calibration_target instrument11 GroundStation85)
	(calibration_target instrument11 Star150)
	(calibration_target instrument11 Star163)
	(calibration_target instrument11 Star131)
	(calibration_target instrument11 GroundStation12)
	(calibration_target instrument11 GroundStation11)
	(calibration_target instrument11 GroundStation17)
	(calibration_target instrument11 Star69)
	(calibration_target instrument11 Star34)
	(calibration_target instrument11 GroundStation33)
	(calibration_target instrument11 Star22)
	(calibration_target instrument11 GroundStation110)
	(calibration_target instrument11 GroundStation37)
	(calibration_target instrument11 Star159)
	(calibration_target instrument11 Star168)
	(calibration_target instrument11 Star205)
	(calibration_target instrument11 Star45)
	(calibration_target instrument11 GroundStation132)
	(calibration_target instrument11 Star117)
	(calibration_target instrument11 Star185)
	(calibration_target instrument11 Star81)
	(calibration_target instrument11 Star82)
	(calibration_target instrument11 Star36)
	(calibration_target instrument11 Star128)
	(calibration_target instrument11 Star112)
	(calibration_target instrument11 Star8)
	(calibration_target instrument11 GroundStation144)
	(calibration_target instrument11 GroundStation25)
	(calibration_target instrument11 Star35)
	(calibration_target instrument11 GroundStation52)
	(calibration_target instrument11 GroundStation63)
	(calibration_target instrument11 GroundStation18)
	(calibration_target instrument11 GroundStation83)
	(calibration_target instrument11 Star39)
	(calibration_target instrument11 Star194)
	(calibration_target instrument11 GroundStation100)
	(calibration_target instrument11 GroundStation204)
	(calibration_target instrument11 Star104)
	(calibration_target instrument11 Star89)
	(calibration_target instrument11 GroundStation59)
	(calibration_target instrument11 GroundStation129)
	(calibration_target instrument11 GroundStation130)
	(calibration_target instrument11 GroundStation90)
	(calibration_target instrument11 Star187)
	(calibration_target instrument11 GroundStation113)
	(calibration_target instrument11 GroundStation197)
	(calibration_target instrument11 Star215)
	(calibration_target instrument11 Star141)
	(calibration_target instrument11 GroundStation99)
	(calibration_target instrument11 Star0)
	(calibration_target instrument11 GroundStation170)
	(calibration_target instrument11 Star213)
	(calibration_target instrument11 Star47)
	(calibration_target instrument11 Star66)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 GroundStation75)
	(calibration_target instrument11 Star62)
	(calibration_target instrument11 Star188)
	(calibration_target instrument11 GroundStation114)
	(supports instrument12 image0)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star111)
	(calibration_target instrument12 Star104)
	(calibration_target instrument12 GroundStation198)
	(calibration_target instrument12 GroundStation94)
	(calibration_target instrument12 GroundStation78)
	(calibration_target instrument12 Star155)
	(calibration_target instrument12 Star188)
	(calibration_target instrument12 GroundStation125)
	(calibration_target instrument12 GroundStation71)
	(calibration_target instrument12 GroundStation183)
	(calibration_target instrument12 Star135)
	(calibration_target instrument12 GroundStation152)
	(calibration_target instrument12 GroundStation123)
	(calibration_target instrument12 GroundStation199)
	(calibration_target instrument12 Star91)
	(calibration_target instrument12 GroundStation63)
	(calibration_target instrument12 Star168)
	(calibration_target instrument12 GroundStation40)
	(calibration_target instrument12 Star23)
	(calibration_target instrument12 Star213)
	(calibration_target instrument12 Star194)
	(calibration_target instrument12 GroundStation115)
	(calibration_target instrument12 GroundStation170)
	(calibration_target instrument12 GroundStation58)
	(calibration_target instrument12 GroundStation206)
	(calibration_target instrument12 Star212)
	(calibration_target instrument12 Star139)
	(calibration_target instrument12 GroundStation106)
	(calibration_target instrument12 GroundStation175)
	(calibration_target instrument12 GroundStation156)
	(calibration_target instrument12 Star41)
	(calibration_target instrument12 GroundStation219)
	(calibration_target instrument12 GroundStation44)
	(calibration_target instrument12 Star50)
	(calibration_target instrument12 Star131)
	(calibration_target instrument12 GroundStation151)
	(calibration_target instrument12 Star176)
	(calibration_target instrument12 Star32)
	(calibration_target instrument12 GroundStation184)
	(calibration_target instrument12 Star162)
	(calibration_target instrument12 Star76)
	(calibration_target instrument12 Star0)
	(calibration_target instrument12 GroundStation53)
	(calibration_target instrument12 GroundStation107)
	(calibration_target instrument12 GroundStation169)
	(calibration_target instrument12 GroundStation197)
	(calibration_target instrument12 Star154)
	(calibration_target instrument12 Star67)
	(calibration_target instrument12 Star97)
	(calibration_target instrument12 GroundStation21)
	(calibration_target instrument12 Star8)
	(calibration_target instrument12 GroundStation27)
	(calibration_target instrument12 Star179)
	(calibration_target instrument12 Star105)
	(calibration_target instrument12 Star38)
	(calibration_target instrument12 GroundStation73)
	(calibration_target instrument12 Star2)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation95)
	(calibration_target instrument12 GroundStation100)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon311)
	(supports instrument13 infrared1)
	(supports instrument13 infrared3)
	(calibration_target instrument13 GroundStation130)
	(calibration_target instrument13 GroundStation208)
	(calibration_target instrument13 Star56)
	(calibration_target instrument13 Star136)
	(calibration_target instrument13 GroundStation84)
	(calibration_target instrument13 Star214)
	(calibration_target instrument13 Star215)
	(calibration_target instrument13 Star20)
	(calibration_target instrument13 Star211)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 Star168)
	(calibration_target instrument13 Star159)
	(calibration_target instrument13 Star218)
	(calibration_target instrument13 GroundStation122)
	(calibration_target instrument13 Star36)
	(calibration_target instrument13 Star140)
	(calibration_target instrument13 Star0)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 GroundStation43)
	(calibration_target instrument13 Star189)
	(calibration_target instrument13 GroundStation164)
	(calibration_target instrument13 Star62)
	(calibration_target instrument13 Star172)
	(calibration_target instrument13 GroundStation73)
	(calibration_target instrument13 Star2)
	(calibration_target instrument13 GroundStation127)
	(calibration_target instrument13 Star97)
	(calibration_target instrument13 GroundStation88)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 Star47)
	(calibration_target instrument13 GroundStation129)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet297)
	(supports instrument14 infrared5)
	(calibration_target instrument14 GroundStation204)
	(calibration_target instrument14 Star116)
	(calibration_target instrument14 GroundStation177)
	(calibration_target instrument14 GroundStation181)
	(calibration_target instrument14 Star194)
	(calibration_target instrument14 Star215)
	(calibration_target instrument14 Star162)
	(calibration_target instrument14 Star165)
	(calibration_target instrument14 Star67)
	(calibration_target instrument14 Star22)
	(calibration_target instrument14 GroundStation78)
	(calibration_target instrument14 GroundStation94)
	(calibration_target instrument14 GroundStation206)
	(calibration_target instrument14 Star46)
	(calibration_target instrument14 Star212)
	(calibration_target instrument14 GroundStation157)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation40)
	(supports instrument15 image0)
	(calibration_target instrument15 GroundStation43)
	(calibration_target instrument15 Star215)
	(calibration_target instrument15 Star131)
	(calibration_target instrument15 Star41)
	(calibration_target instrument15 GroundStation199)
	(calibration_target instrument15 GroundStation208)
	(calibration_target instrument15 Star187)
	(calibration_target instrument15 Star147)
	(calibration_target instrument15 GroundStation203)
	(calibration_target instrument15 Star138)
	(calibration_target instrument15 GroundStation206)
	(calibration_target instrument15 GroundStation90)
	(calibration_target instrument15 GroundStation92)
	(calibration_target instrument15 GroundStation27)
	(calibration_target instrument15 Star214)
	(calibration_target instrument15 GroundStation37)
	(calibration_target instrument15 GroundStation175)
	(calibration_target instrument15 GroundStation157)
	(calibration_target instrument15 GroundStation74)
	(calibration_target instrument15 GroundStation207)
	(calibration_target instrument15 Star57)
	(calibration_target instrument15 Star165)
	(calibration_target instrument15 GroundStation171)
	(calibration_target instrument15 Star195)
	(calibration_target instrument15 GroundStation122)
	(calibration_target instrument15 Star193)
	(calibration_target instrument15 Star201)
	(calibration_target instrument15 Star163)
	(calibration_target instrument15 GroundStation113)
	(calibration_target instrument15 GroundStation63)
	(calibration_target instrument15 Star108)
	(calibration_target instrument15 GroundStation146)
	(calibration_target instrument15 GroundStation58)
	(calibration_target instrument15 GroundStation216)
	(calibration_target instrument15 Star46)
	(calibration_target instrument15 Star89)
	(calibration_target instrument15 Star162)
	(calibration_target instrument15 Star31)
	(calibration_target instrument15 GroundStation12)
	(calibration_target instrument15 Star109)
	(calibration_target instrument15 GroundStation33)
	(calibration_target instrument15 Star82)
	(calibration_target instrument15 GroundStation123)
	(calibration_target instrument15 GroundStation24)
	(calibration_target instrument15 Star19)
	(calibration_target instrument15 GroundStation169)
	(calibration_target instrument15 GroundStation156)
	(calibration_target instrument15 GroundStation44)
	(calibration_target instrument15 GroundStation85)
	(calibration_target instrument15 Star218)
	(calibration_target instrument15 GroundStation166)
	(calibration_target instrument15 GroundStation77)
	(calibration_target instrument15 Star62)
	(calibration_target instrument15 GroundStation217)
	(calibration_target instrument15 Star158)
	(calibration_target instrument15 Star23)
	(calibration_target instrument15 GroundStation149)
	(calibration_target instrument15 GroundStation83)
	(calibration_target instrument15 Star70)
	(calibration_target instrument15 Star155)
	(calibration_target instrument15 Star48)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star303)
	(supports instrument16 image0)
	(supports instrument16 infrared1)
	(supports instrument16 infrared3)
	(calibration_target instrument16 GroundStation132)
	(calibration_target instrument16 Star158)
	(calibration_target instrument16 GroundStation170)
	(calibration_target instrument16 Star105)
	(calibration_target instrument16 Star35)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 GroundStation149)
	(calibration_target instrument16 Star162)
	(calibration_target instrument16 Star38)
	(calibration_target instrument16 GroundStation59)
	(calibration_target instrument16 Star82)
	(calibration_target instrument16 GroundStation14)
	(calibration_target instrument16 GroundStation72)
	(calibration_target instrument16 Star133)
	(calibration_target instrument16 GroundStation192)
	(calibration_target instrument16 GroundStation92)
	(calibration_target instrument16 GroundStation142)
	(calibration_target instrument16 Star56)
	(calibration_target instrument16 GroundStation65)
	(calibration_target instrument16 Star200)
	(calibration_target instrument16 Star80)
	(calibration_target instrument16 GroundStation94)
	(calibration_target instrument16 GroundStation210)
	(calibration_target instrument16 Star194)
	(calibration_target instrument16 GroundStation77)
	(calibration_target instrument16 GroundStation127)
	(calibration_target instrument16 Star212)
	(calibration_target instrument16 Star211)
	(calibration_target instrument16 GroundStation144)
	(calibration_target instrument16 Star186)
	(calibration_target instrument16 GroundStation75)
	(calibration_target instrument16 GroundStation204)
	(calibration_target instrument16 GroundStation90)
	(calibration_target instrument16 GroundStation33)
	(calibration_target instrument16 Star120)
	(calibration_target instrument16 GroundStation93)
	(calibration_target instrument16 GroundStation206)
	(calibration_target instrument16 GroundStation122)
	(calibration_target instrument16 Star79)
	(calibration_target instrument16 Star69)
	(calibration_target instrument16 GroundStation124)
	(calibration_target instrument16 GroundStation74)
	(calibration_target instrument16 GroundStation73)
	(calibration_target instrument16 GroundStation106)
	(calibration_target instrument16 GroundStation25)
	(calibration_target instrument16 Star19)
	(calibration_target instrument16 Star154)
	(calibration_target instrument16 GroundStation21)
	(supports instrument17 image0)
	(supports instrument17 infrared5)
	(calibration_target instrument17 Star36)
	(calibration_target instrument17 GroundStation78)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 GroundStation170)
	(calibration_target instrument17 GroundStation153)
	(calibration_target instrument17 GroundStation33)
	(calibration_target instrument17 GroundStation74)
	(calibration_target instrument17 Star47)
	(calibration_target instrument17 GroundStation15)
	(calibration_target instrument17 GroundStation9)
	(calibration_target instrument17 GroundStation52)
	(calibration_target instrument17 Star105)
	(calibration_target instrument17 GroundStation43)
	(calibration_target instrument17 Star138)
	(calibration_target instrument17 GroundStation14)
	(calibration_target instrument17 GroundStation137)
	(calibration_target instrument17 GroundStation12)
	(calibration_target instrument17 GroundStation93)
	(calibration_target instrument17 Star2)
	(calibration_target instrument17 Star218)
	(calibration_target instrument17 Star34)
	(calibration_target instrument17 GroundStation197)
	(calibration_target instrument17 Star69)
	(calibration_target instrument17 GroundStation166)
	(calibration_target instrument17 Star50)
	(calibration_target instrument17 Star141)
	(calibration_target instrument17 Star116)
	(calibration_target instrument17 Star214)
	(calibration_target instrument17 Star145)
	(calibration_target instrument17 GroundStation190)
	(calibration_target instrument17 GroundStation110)
	(calibration_target instrument17 Star89)
	(calibration_target instrument17 GroundStation216)
	(calibration_target instrument17 GroundStation18)
	(calibration_target instrument17 GroundStation123)
	(calibration_target instrument17 Star147)
	(calibration_target instrument17 Star26)
	(calibration_target instrument17 GroundStation129)
	(calibration_target instrument17 GroundStation29)
	(calibration_target instrument17 Star45)
	(calibration_target instrument17 GroundStation130)
	(on_board instrument16 satellite6)
	(on_board instrument17 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star350)
	(supports instrument18 infrared5)
	(supports instrument18 infrared3)
	(calibration_target instrument18 GroundStation126)
	(calibration_target instrument18 Star30)
	(calibration_target instrument18 GroundStation170)
	(calibration_target instrument18 Star54)
	(calibration_target instrument18 Star145)
	(calibration_target instrument18 GroundStation52)
	(calibration_target instrument18 Star70)
	(calibration_target instrument18 Star148)
	(calibration_target instrument18 Star128)
	(supports instrument19 infrared5)
	(supports instrument19 infrared1)
	(supports instrument19 infrared4)
	(calibration_target instrument19 Star45)
	(calibration_target instrument19 Star215)
	(calibration_target instrument19 Star23)
	(calibration_target instrument19 GroundStation27)
	(calibration_target instrument19 Star87)
	(calibration_target instrument19 Star205)
	(calibration_target instrument19 GroundStation167)
	(calibration_target instrument19 GroundStation107)
	(calibration_target instrument19 Star135)
	(calibration_target instrument19 Star214)
	(calibration_target instrument19 GroundStation5)
	(calibration_target instrument19 Star8)
	(calibration_target instrument19 Star80)
	(calibration_target instrument19 Star66)
	(calibration_target instrument19 GroundStation110)
	(calibration_target instrument19 Star34)
	(calibration_target instrument19 GroundStation84)
	(calibration_target instrument19 GroundStation100)
	(calibration_target instrument19 GroundStation72)
	(calibration_target instrument19 Star13)
	(calibration_target instrument19 GroundStation14)
	(calibration_target instrument19 GroundStation203)
	(calibration_target instrument19 GroundStation124)
	(calibration_target instrument19 GroundStation60)
	(calibration_target instrument19 GroundStation99)
	(calibration_target instrument19 GroundStation52)
	(calibration_target instrument19 GroundStation15)
	(calibration_target instrument19 GroundStation202)
	(calibration_target instrument19 GroundStation171)
	(supports instrument20 infrared3)
	(supports instrument20 thermograph2)
	(supports instrument20 infrared4)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star139)
	(calibration_target instrument20 Star162)
	(calibration_target instrument20 GroundStation121)
	(calibration_target instrument20 Star20)
	(calibration_target instrument20 Star200)
	(calibration_target instrument20 Star46)
	(calibration_target instrument20 GroundStation166)
	(calibration_target instrument20 GroundStation24)
	(calibration_target instrument20 Star135)
	(calibration_target instrument20 GroundStation208)
	(calibration_target instrument20 GroundStation72)
	(calibration_target instrument20 GroundStation132)
	(calibration_target instrument20 Star174)
	(calibration_target instrument20 Star104)
	(calibration_target instrument20 Star47)
	(calibration_target instrument20 Star34)
	(calibration_target instrument20 GroundStation85)
	(calibration_target instrument20 GroundStation102)
	(calibration_target instrument20 GroundStation192)
	(calibration_target instrument20 Star119)
	(calibration_target instrument20 Star66)
	(calibration_target instrument20 GroundStation25)
	(calibration_target instrument20 Star205)
	(calibration_target instrument20 GroundStation43)
	(calibration_target instrument20 GroundStation40)
	(calibration_target instrument20 GroundStation15)
	(calibration_target instrument20 GroundStation95)
	(calibration_target instrument20 GroundStation207)
	(calibration_target instrument20 GroundStation219)
	(calibration_target instrument20 Star80)
	(calibration_target instrument20 Star79)
	(calibration_target instrument20 Star195)
	(calibration_target instrument20 GroundStation127)
	(calibration_target instrument20 GroundStation149)
	(calibration_target instrument20 GroundStation74)
	(calibration_target instrument20 GroundStation184)
	(calibration_target instrument20 Star196)
	(calibration_target instrument20 GroundStation106)
	(calibration_target instrument20 Star56)
	(calibration_target instrument20 Star61)
	(calibration_target instrument20 GroundStation191)
	(calibration_target instrument20 GroundStation206)
	(calibration_target instrument20 Star141)
	(calibration_target instrument20 GroundStation173)
	(calibration_target instrument20 Star70)
	(calibration_target instrument20 Star131)
	(calibration_target instrument20 GroundStation103)
	(calibration_target instrument20 GroundStation152)
	(calibration_target instrument20 Star186)
	(calibration_target instrument20 Star89)
	(calibration_target instrument20 GroundStation17)
	(calibration_target instrument20 GroundStation199)
	(calibration_target instrument20 GroundStation71)
	(calibration_target instrument20 Star189)
	(supports instrument21 infrared5)
	(supports instrument21 infrared1)
	(supports instrument21 infrared3)
	(calibration_target instrument21 GroundStation184)
	(calibration_target instrument21 Star200)
	(calibration_target instrument21 GroundStation175)
	(calibration_target instrument21 Star135)
	(calibration_target instrument21 Star154)
	(calibration_target instrument21 GroundStation161)
	(calibration_target instrument21 Star91)
	(calibration_target instrument21 Star22)
	(calibration_target instrument21 Star188)
	(calibration_target instrument21 GroundStation1)
	(calibration_target instrument21 Star64)
	(calibration_target instrument21 GroundStation204)
	(calibration_target instrument21 Star48)
	(calibration_target instrument21 Star69)
	(calibration_target instrument21 Star119)
	(calibration_target instrument21 GroundStation15)
	(on_board instrument18 satellite7)
	(on_board instrument19 satellite7)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation25)
	(supports instrument22 thermograph2)
	(supports instrument22 infrared1)
	(calibration_target instrument22 Star13)
	(calibration_target instrument22 Star57)
	(calibration_target instrument22 Star104)
	(calibration_target instrument22 GroundStation93)
	(calibration_target instrument22 GroundStation100)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 GroundStation190)
	(calibration_target instrument22 GroundStation160)
	(calibration_target instrument22 GroundStation216)
	(calibration_target instrument22 Star196)
	(calibration_target instrument22 GroundStation1)
	(calibration_target instrument22 GroundStation143)
	(calibration_target instrument22 GroundStation114)
	(calibration_target instrument22 Star64)
	(calibration_target instrument22 Star211)
	(calibration_target instrument22 GroundStation149)
	(calibration_target instrument22 GroundStation156)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 Star45)
	(calibration_target instrument22 GroundStation92)
	(calibration_target instrument22 GroundStation202)
	(calibration_target instrument22 Star135)
	(calibration_target instrument22 GroundStation153)
	(calibration_target instrument22 Star112)
	(calibration_target instrument22 Star193)
	(calibration_target instrument22 Star34)
	(calibration_target instrument22 GroundStation102)
	(calibration_target instrument22 GroundStation72)
	(calibration_target instrument22 Star136)
	(calibration_target instrument22 Star8)
	(calibration_target instrument22 GroundStation43)
	(calibration_target instrument22 Star174)
	(calibration_target instrument22 Star200)
	(calibration_target instrument22 Star189)
	(calibration_target instrument22 GroundStation90)
	(calibration_target instrument22 GroundStation99)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 GroundStation24)
	(calibration_target instrument22 GroundStation84)
	(calibration_target instrument22 Star212)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation170)
	(calibration_target instrument22 GroundStation94)
	(calibration_target instrument22 Star141)
	(calibration_target instrument22 GroundStation9)
	(calibration_target instrument22 GroundStation95)
	(calibration_target instrument22 Star218)
	(calibration_target instrument22 Star205)
	(calibration_target instrument22 GroundStation63)
	(calibration_target instrument22 Star140)
	(calibration_target instrument22 GroundStation83)
	(calibration_target instrument22 Star188)
	(calibration_target instrument22 Star97)
	(calibration_target instrument22 GroundStation207)
	(calibration_target instrument22 Star28)
	(calibration_target instrument22 Star138)
	(calibration_target instrument22 Star23)
	(calibration_target instrument22 Star139)
	(calibration_target instrument22 Star194)
	(calibration_target instrument22 Star69)
	(calibration_target instrument22 GroundStation33)
	(calibration_target instrument22 Star155)
	(calibration_target instrument22 GroundStation74)
	(calibration_target instrument22 GroundStation137)
	(calibration_target instrument22 Star16)
	(calibration_target instrument22 GroundStation198)
	(calibration_target instrument22 GroundStation125)
	(calibration_target instrument22 Star162)
	(calibration_target instrument22 Star81)
	(calibration_target instrument22 GroundStation85)
	(calibration_target instrument22 Star201)
	(supports instrument23 image0)
	(supports instrument23 thermograph2)
	(supports instrument23 infrared4)
	(calibration_target instrument23 Star186)
	(calibration_target instrument23 GroundStation161)
	(calibration_target instrument23 GroundStation149)
	(calibration_target instrument23 GroundStation180)
	(calibration_target instrument23 Star205)
	(calibration_target instrument23 GroundStation27)
	(calibration_target instrument23 Star163)
	(calibration_target instrument23 GroundStation5)
	(supports instrument24 thermograph2)
	(supports instrument24 infrared1)
	(calibration_target instrument24 GroundStation60)
	(calibration_target instrument24 GroundStation170)
	(calibration_target instrument24 Star32)
	(calibration_target instrument24 GroundStation173)
	(calibration_target instrument24 Star135)
	(calibration_target instrument24 Star38)
	(calibration_target instrument24 Star158)
	(calibration_target instrument24 GroundStation216)
	(calibration_target instrument24 Star19)
	(calibration_target instrument24 GroundStation199)
	(calibration_target instrument24 Star86)
	(calibration_target instrument24 Star141)
	(calibration_target instrument24 Star111)
	(calibration_target instrument24 Star57)
	(calibration_target instrument24 GroundStation92)
	(calibration_target instrument24 GroundStation160)
	(calibration_target instrument24 GroundStation203)
	(calibration_target instrument24 Star176)
	(calibration_target instrument24 Star28)
	(calibration_target instrument24 GroundStation6)
	(calibration_target instrument24 GroundStation121)
	(calibration_target instrument24 Star89)
	(calibration_target instrument24 Star56)
	(calibration_target instrument24 Star155)
	(calibration_target instrument24 GroundStation101)
	(calibration_target instrument24 GroundStation84)
	(calibration_target instrument24 Star46)
	(calibration_target instrument24 GroundStation191)
	(calibration_target instrument24 Star131)
	(calibration_target instrument24 Star98)
	(calibration_target instrument24 GroundStation49)
	(calibration_target instrument24 GroundStation93)
	(calibration_target instrument24 Star174)
	(calibration_target instrument24 Star172)
	(calibration_target instrument24 GroundStation14)
	(calibration_target instrument24 GroundStation137)
	(supports instrument25 infrared3)
	(calibration_target instrument25 Star155)
	(calibration_target instrument25 GroundStation125)
	(calibration_target instrument25 GroundStation164)
	(calibration_target instrument25 GroundStation160)
	(calibration_target instrument25 Star67)
	(calibration_target instrument25 GroundStation157)
	(calibration_target instrument25 GroundStation96)
	(calibration_target instrument25 Star116)
	(calibration_target instrument25 GroundStation114)
	(calibration_target instrument25 GroundStation83)
	(calibration_target instrument25 Star108)
	(calibration_target instrument25 Star54)
	(calibration_target instrument25 GroundStation178)
	(calibration_target instrument25 Star3)
	(calibration_target instrument25 GroundStation219)
	(calibration_target instrument25 Star141)
	(calibration_target instrument25 GroundStation37)
	(calibration_target instrument25 Star194)
	(calibration_target instrument25 Star163)
	(calibration_target instrument25 GroundStation175)
	(calibration_target instrument25 GroundStation93)
	(calibration_target instrument25 Star168)
	(calibration_target instrument25 GroundStation33)
	(calibration_target instrument25 GroundStation95)
	(calibration_target instrument25 GroundStation75)
	(calibration_target instrument25 Star133)
	(calibration_target instrument25 GroundStation122)
	(calibration_target instrument25 Star139)
	(calibration_target instrument25 GroundStation184)
	(calibration_target instrument25 Star30)
	(calibration_target instrument25 GroundStation110)
	(calibration_target instrument25 GroundStation127)
	(calibration_target instrument25 GroundStation203)
	(calibration_target instrument25 GroundStation132)
	(calibration_target instrument25 GroundStation124)
	(calibration_target instrument25 GroundStation209)
	(calibration_target instrument25 Star136)
	(calibration_target instrument25 GroundStation167)
	(calibration_target instrument25 GroundStation126)
	(calibration_target instrument25 Star79)
	(calibration_target instrument25 GroundStation55)
	(calibration_target instrument25 GroundStation85)
	(calibration_target instrument25 GroundStation5)
	(calibration_target instrument25 GroundStation68)
	(calibration_target instrument25 Star41)
	(calibration_target instrument25 Star82)
	(calibration_target instrument25 Star32)
	(calibration_target instrument25 GroundStation71)
	(calibration_target instrument25 Star174)
	(calibration_target instrument25 Star13)
	(calibration_target instrument25 Star57)
	(calibration_target instrument25 Star34)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 GroundStation204)
	(calibration_target instrument25 Star36)
	(calibration_target instrument25 GroundStation177)
	(calibration_target instrument25 Star196)
	(on_board instrument22 satellite8)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star31)
	(supports instrument26 infrared3)
	(supports instrument26 image0)
	(supports instrument26 infrared1)
	(calibration_target instrument26 Star105)
	(calibration_target instrument26 Star154)
	(calibration_target instrument26 GroundStation177)
	(calibration_target instrument26 Star47)
	(calibration_target instrument26 GroundStation60)
	(calibration_target instrument26 GroundStation126)
	(calibration_target instrument26 GroundStation210)
	(calibration_target instrument26 GroundStation161)
	(calibration_target instrument26 Star28)
	(calibration_target instrument26 GroundStation72)
	(calibration_target instrument26 Star179)
	(calibration_target instrument26 Star193)
	(calibration_target instrument26 GroundStation149)
	(calibration_target instrument26 Star76)
	(calibration_target instrument26 Star36)
	(calibration_target instrument26 GroundStation152)
	(calibration_target instrument26 GroundStation74)
	(calibration_target instrument26 Star145)
	(calibration_target instrument26 GroundStation17)
	(calibration_target instrument26 GroundStation11)
	(calibration_target instrument26 Star98)
	(calibration_target instrument26 GroundStation178)
	(calibration_target instrument26 GroundStation88)
	(calibration_target instrument26 Star104)
	(calibration_target instrument26 GroundStation68)
	(calibration_target instrument26 Star128)
	(calibration_target instrument26 GroundStation9)
	(calibration_target instrument26 Star57)
	(calibration_target instrument26 GroundStation121)
	(calibration_target instrument26 Star39)
	(calibration_target instrument26 Star89)
	(calibration_target instrument26 Star141)
	(calibration_target instrument26 Star23)
	(calibration_target instrument26 Star81)
	(calibration_target instrument26 GroundStation52)
	(calibration_target instrument26 Star120)
	(calibration_target instrument26 GroundStation123)
	(calibration_target instrument26 GroundStation94)
	(calibration_target instrument26 GroundStation5)
	(calibration_target instrument26 Star194)
	(calibration_target instrument26 GroundStation160)
	(calibration_target instrument26 GroundStation203)
	(calibration_target instrument26 Star138)
	(calibration_target instrument26 GroundStation100)
	(calibration_target instrument26 GroundStation175)
	(calibration_target instrument26 GroundStation144)
	(calibration_target instrument26 GroundStation95)
	(calibration_target instrument26 Star80)
	(calibration_target instrument26 Star97)
	(calibration_target instrument26 GroundStation142)
	(calibration_target instrument26 Star119)
	(calibration_target instrument26 GroundStation115)
	(calibration_target instrument26 Star31)
	(calibration_target instrument26 GroundStation90)
	(calibration_target instrument26 GroundStation101)
	(calibration_target instrument26 GroundStation37)
	(calibration_target instrument26 GroundStation173)
	(calibration_target instrument26 GroundStation44)
	(calibration_target instrument26 GroundStation92)
	(calibration_target instrument26 Star91)
	(calibration_target instrument26 Star187)
	(calibration_target instrument26 GroundStation25)
	(calibration_target instrument26 Star61)
	(calibration_target instrument26 GroundStation180)
	(calibration_target instrument26 Star13)
	(calibration_target instrument26 Star186)
	(calibration_target instrument26 GroundStation71)
	(on_board instrument26 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star298)
	(supports instrument27 infrared5)
	(calibration_target instrument27 Star19)
	(calibration_target instrument27 Star196)
	(calibration_target instrument27 GroundStation24)
	(calibration_target instrument27 GroundStation27)
	(calibration_target instrument27 GroundStation44)
	(calibration_target instrument27 GroundStation208)
	(calibration_target instrument27 GroundStation29)
	(calibration_target instrument27 Star0)
	(calibration_target instrument27 GroundStation160)
	(calibration_target instrument27 Star141)
	(calibration_target instrument27 Star104)
	(calibration_target instrument27 GroundStation207)
	(calibration_target instrument27 GroundStation58)
	(calibration_target instrument27 GroundStation17)
	(calibration_target instrument27 Star112)
	(calibration_target instrument27 Star67)
	(calibration_target instrument27 Star111)
	(calibration_target instrument27 Star118)
	(calibration_target instrument27 GroundStation73)
	(calibration_target instrument27 GroundStation84)
	(calibration_target instrument27 GroundStation153)
	(calibration_target instrument27 Star194)
	(calibration_target instrument27 Star148)
	(calibration_target instrument27 Star42)
	(calibration_target instrument27 GroundStation183)
	(calibration_target instrument27 Star215)
	(calibration_target instrument27 GroundStation6)
	(calibration_target instrument27 GroundStation204)
	(calibration_target instrument27 GroundStation191)
	(calibration_target instrument27 GroundStation127)
	(calibration_target instrument27 GroundStation77)
	(calibration_target instrument27 GroundStation152)
	(calibration_target instrument27 Star4)
	(calibration_target instrument27 Star86)
	(calibration_target instrument27 Star200)
	(calibration_target instrument27 GroundStation100)
	(calibration_target instrument27 Star187)
	(calibration_target instrument27 GroundStation170)
	(calibration_target instrument27 Star70)
	(calibration_target instrument27 Star79)
	(calibration_target instrument27 Star189)
	(calibration_target instrument27 GroundStation146)
	(calibration_target instrument27 Star81)
	(calibration_target instrument27 Star46)
	(calibration_target instrument27 Star182)
	(calibration_target instrument27 Star87)
	(calibration_target instrument27 GroundStation59)
	(supports instrument28 thermograph2)
	(calibration_target instrument28 GroundStation177)
	(calibration_target instrument28 Star162)
	(calibration_target instrument28 GroundStation95)
	(calibration_target instrument28 Star54)
	(calibration_target instrument28 GroundStation203)
	(calibration_target instrument28 Star139)
	(calibration_target instrument28 Star64)
	(calibration_target instrument28 GroundStation6)
	(calibration_target instrument28 GroundStation74)
	(on_board instrument27 satellite10)
	(on_board instrument28 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star383)
)
(:goal (and
	(pointing satellite1 Planet274)
	(pointing satellite4 Phenomenon319)
	(pointing satellite7 Star269)
	(pointing satellite8 GroundStation190)
	(pointing satellite10 Planet273)
	(have_image Star220 infrared3)
	(have_image Star220 image0)
	(have_image Phenomenon221 infrared3)
	(have_image Phenomenon222 infrared1)
	(have_image Planet223 thermograph2)
	(have_image Phenomenon224 infrared5)
	(have_image Planet225 infrared5)
	(have_image Star226 image0)
	(have_image Star226 infrared5)
	(have_image Planet227 infrared1)
	(have_image Planet227 infrared3)
	(have_image Planet228 image0)
	(have_image Planet228 infrared4)
	(have_image Phenomenon229 infrared4)
	(have_image Star230 infrared1)
	(have_image Star230 infrared5)
	(have_image Planet231 infrared3)
	(have_image Planet231 infrared1)
	(have_image Phenomenon232 infrared5)
	(have_image Phenomenon233 thermograph2)
	(have_image Phenomenon233 image0)
	(have_image Phenomenon234 infrared1)
	(have_image Phenomenon234 thermograph2)
	(have_image Phenomenon235 infrared5)
	(have_image Planet237 infrared1)
	(have_image Planet238 infrared4)
	(have_image Planet238 thermograph2)
	(have_image Star239 image0)
	(have_image Planet240 thermograph2)
	(have_image Planet240 image0)
	(have_image Planet241 thermograph2)
	(have_image Planet241 infrared3)
	(have_image Planet242 infrared5)
	(have_image Planet242 image0)
	(have_image Phenomenon243 thermograph2)
	(have_image Planet244 thermograph2)
	(have_image Planet244 infrared4)
	(have_image Planet246 infrared3)
	(have_image Planet246 infrared4)
	(have_image Phenomenon247 thermograph2)
	(have_image Phenomenon248 infrared5)
	(have_image Phenomenon248 image0)
	(have_image Star249 image0)
	(have_image Star249 thermograph2)
	(have_image Star250 infrared3)
	(have_image Star250 image0)
	(have_image Planet251 infrared3)
	(have_image Planet252 infrared5)
	(have_image Planet252 infrared1)
	(have_image Phenomenon253 infrared5)
	(have_image Phenomenon253 thermograph2)
	(have_image Planet254 infrared4)
	(have_image Planet255 infrared4)
	(have_image Planet255 infrared1)
	(have_image Star256 infrared4)
	(have_image Star257 infrared5)
	(have_image Star257 infrared4)
	(have_image Phenomenon258 infrared1)
	(have_image Planet259 image0)
	(have_image Phenomenon260 infrared1)
	(have_image Star261 infrared1)
	(have_image Planet262 infrared4)
	(have_image Star264 infrared5)
	(have_image Star264 infrared1)
	(have_image Phenomenon265 infrared3)
	(have_image Phenomenon265 infrared4)
	(have_image Phenomenon266 thermograph2)
	(have_image Phenomenon266 infrared1)
	(have_image Planet267 infrared3)
	(have_image Planet267 infrared5)
	(have_image Phenomenon268 image0)
	(have_image Phenomenon268 infrared1)
	(have_image Star269 infrared4)
	(have_image Star270 infrared3)
	(have_image Phenomenon271 infrared1)
	(have_image Phenomenon271 infrared4)
	(have_image Planet272 thermograph2)
	(have_image Planet273 infrared3)
	(have_image Star275 infrared5)
	(have_image Star275 infrared4)
	(have_image Planet276 infrared1)
	(have_image Star277 infrared1)
	(have_image Star277 infrared4)
	(have_image Phenomenon278 infrared1)
	(have_image Star279 infrared4)
	(have_image Star280 infrared5)
	(have_image Star280 infrared1)
	(have_image Star281 infrared4)
	(have_image Star281 infrared1)
	(have_image Planet282 infrared5)
	(have_image Planet282 infrared3)
	(have_image Phenomenon283 infrared1)
	(have_image Planet284 thermograph2)
	(have_image Planet285 infrared1)
	(have_image Planet286 image0)
	(have_image Planet286 infrared4)
	(have_image Phenomenon287 infrared5)
	(have_image Phenomenon287 infrared3)
	(have_image Phenomenon288 infrared5)
	(have_image Phenomenon288 image0)
	(have_image Star289 infrared5)
	(have_image Star289 image0)
	(have_image Phenomenon292 infrared5)
	(have_image Phenomenon292 infrared4)
	(have_image Phenomenon295 image0)
	(have_image Phenomenon295 infrared3)
	(have_image Planet296 thermograph2)
	(have_image Planet296 image0)
	(have_image Planet297 image0)
	(have_image Star298 infrared1)
	(have_image Star299 infrared3)
	(have_image Star299 infrared4)
	(have_image Phenomenon300 infrared1)
	(have_image Phenomenon300 infrared3)
	(have_image Star301 image0)
	(have_image Star301 thermograph2)
	(have_image Planet302 infrared5)
	(have_image Planet302 infrared1)
	(have_image Star303 infrared4)
	(have_image Star303 infrared5)
	(have_image Phenomenon304 infrared3)
	(have_image Phenomenon304 infrared1)
	(have_image Phenomenon305 infrared5)
	(have_image Star306 image0)
	(have_image Planet307 infrared3)
	(have_image Planet307 thermograph2)
	(have_image Phenomenon308 infrared1)
	(have_image Phenomenon308 image0)
	(have_image Planet309 thermograph2)
	(have_image Planet309 image0)
	(have_image Phenomenon310 thermograph2)
	(have_image Phenomenon311 infrared3)
	(have_image Phenomenon312 infrared4)
	(have_image Planet313 infrared3)
	(have_image Planet313 infrared1)
	(have_image Phenomenon314 infrared4)
	(have_image Phenomenon314 infrared5)
	(have_image Phenomenon315 thermograph2)
	(have_image Phenomenon316 thermograph2)
	(have_image Planet317 infrared4)
	(have_image Phenomenon318 thermograph2)
	(have_image Phenomenon319 infrared3)
	(have_image Phenomenon319 infrared1)
	(have_image Phenomenon320 infrared1)
	(have_image Phenomenon320 thermograph2)
	(have_image Planet321 image0)
	(have_image Planet321 infrared5)
	(have_image Phenomenon322 infrared1)
	(have_image Phenomenon323 infrared1)
	(have_image Phenomenon323 image0)
	(have_image Star326 infrared5)
	(have_image Star326 image0)
	(have_image Planet327 infrared4)
	(have_image Star328 thermograph2)
	(have_image Star328 image0)
	(have_image Star329 infrared3)
	(have_image Star329 image0)
	(have_image Star330 infrared4)
	(have_image Star330 infrared3)
	(have_image Phenomenon331 infrared1)
	(have_image Star332 image0)
	(have_image Star332 infrared3)
	(have_image Planet333 image0)
	(have_image Planet334 thermograph2)
	(have_image Star335 infrared5)
	(have_image Star335 thermograph2)
	(have_image Planet336 infrared3)
	(have_image Planet336 infrared5)
	(have_image Phenomenon337 infrared4)
	(have_image Phenomenon337 thermograph2)
	(have_image Star338 image0)
	(have_image Phenomenon339 image0)
	(have_image Phenomenon339 infrared3)
	(have_image Planet340 thermograph2)
	(have_image Planet340 infrared3)
	(have_image Star341 infrared1)
	(have_image Planet342 thermograph2)
	(have_image Planet343 infrared4)
	(have_image Phenomenon345 infrared5)
	(have_image Phenomenon345 infrared4)
	(have_image Star346 infrared3)
	(have_image Star346 thermograph2)
	(have_image Planet348 infrared1)
	(have_image Phenomenon349 infrared4)
	(have_image Star350 infrared1)
	(have_image Star351 thermograph2)
	(have_image Star351 infrared3)
	(have_image Planet353 thermograph2)
	(have_image Planet354 thermograph2)
	(have_image Planet354 infrared3)
	(have_image Star355 thermograph2)
	(have_image Planet356 infrared1)
	(have_image Phenomenon357 infrared4)
	(have_image Phenomenon357 thermograph2)
	(have_image Phenomenon358 infrared5)
	(have_image Phenomenon359 thermograph2)
	(have_image Phenomenon359 infrared5)
	(have_image Star360 infrared1)
	(have_image Star360 image0)
	(have_image Phenomenon361 infrared4)
	(have_image Planet362 infrared5)
	(have_image Star363 infrared1)
	(have_image Star363 infrared3)
	(have_image Phenomenon364 infrared5)
	(have_image Planet365 image0)
	(have_image Planet365 infrared4)
	(have_image Star366 infrared4)
	(have_image Star366 image0)
	(have_image Star367 infrared5)
	(have_image Star367 thermograph2)
	(have_image Star368 infrared1)
	(have_image Planet369 thermograph2)
	(have_image Planet369 infrared5)
	(have_image Star370 thermograph2)
	(have_image Star370 infrared5)
	(have_image Phenomenon371 infrared5)
	(have_image Phenomenon371 image0)
	(have_image Planet372 infrared5)
	(have_image Planet372 thermograph2)
	(have_image Phenomenon373 infrared4)
	(have_image Phenomenon373 infrared5)
	(have_image Planet374 infrared3)
	(have_image Planet374 thermograph2)
	(have_image Phenomenon375 infrared3)
	(have_image Phenomenon375 thermograph2)
	(have_image Phenomenon376 infrared5)
	(have_image Planet377 infrared1)
	(have_image Planet377 thermograph2)
	(have_image Planet378 thermograph2)
	(have_image Phenomenon379 image0)
	(have_image Star380 infrared4)
	(have_image Planet381 thermograph2)
	(have_image Star382 infrared4)
	(have_image Star382 image0)
	(have_image Star383 infrared5)
	(have_image Phenomenon384 infrared5)
	(have_image Phenomenon384 thermograph2)
	(have_image Phenomenon385 infrared1)
	(have_image Phenomenon385 infrared4)
	(have_image Star386 infrared3)
	(have_image Star387 infrared4)
	(have_image Star388 infrared5)
	(have_image Star389 image0)
	(have_image Planet390 infrared5)
	(have_image Planet390 infrared1)
	(have_image Star391 infrared4)
	(have_image Phenomenon392 thermograph2)
	(have_image Planet394 infrared4)
	(have_image Planet394 image0)
	(have_image Star395 infrared1)
	(have_image Planet396 infrared4)
	(have_image Star397 infrared1)
	(have_image Star397 infrared3)
	(have_image Planet398 infrared3)
	(have_image Star399 image0)
	(have_image Star399 infrared4)
	(have_image Planet400 infrared3)
	(have_image Planet400 infrared4)
	(have_image Planet401 infrared3)
	(have_image Planet402 infrared4)
	(have_image Planet402 thermograph2)
	(have_image Planet403 infrared5)
	(have_image Phenomenon406 infrared3)
	(have_image Phenomenon407 image0)
	(have_image Planet408 infrared5)
	(have_image Planet408 infrared3)
	(have_image Star409 infrared5)
	(have_image Star409 infrared1)
	(have_image Star410 image0)
	(have_image Star411 infrared5)
	(have_image Star411 infrared4)
	(have_image Planet412 infrared1)
	(have_image Planet412 infrared3)
	(have_image Star414 infrared1)
	(have_image Star414 infrared3)
	(have_image Phenomenon415 infrared4)
	(have_image Phenomenon415 image0)
	(have_image Star417 infrared3)
	(have_image Star419 thermograph2)
	(have_image Star420 thermograph2)
	(have_image Planet421 image0)
	(have_image Planet421 infrared5)
	(have_image Planet422 infrared3)
	(have_image Phenomenon423 infrared1)
	(have_image Star424 infrared1)
	(have_image Planet425 infrared3)
	(have_image Phenomenon426 infrared4)
	(have_image Phenomenon426 image0)
	(have_image Star428 infrared3)
	(have_image Star428 infrared4)
	(have_image Star429 infrared1)
	(have_image Phenomenon431 infrared5)
	(have_image Phenomenon431 infrared1)
	(have_image Star432 thermograph2)
	(have_image Star432 infrared3)
	(have_image Planet433 infrared3)
	(have_image Phenomenon434 image0)
	(have_image Phenomenon435 thermograph2)
	(have_image Phenomenon435 image0)
	(have_image Star436 image0)
	(have_image Phenomenon437 thermograph2)
	(have_image Planet438 infrared3)
	(have_image Planet439 infrared5)
))

)
