(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	satellite1 - satellite
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	satellite4 - satellite
	instrument12 - instrument
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite5 - satellite
	instrument17 - instrument
	instrument18 - instrument
	satellite6 - satellite
	instrument19 - instrument
	instrument20 - instrument
	satellite7 - satellite
	instrument21 - instrument
	satellite8 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite9 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite10 - satellite
	instrument27 - instrument
	instrument28 - instrument
	instrument29 - instrument
	satellite11 - satellite
	instrument30 - instrument
	instrument31 - instrument
	instrument32 - instrument
	satellite12 - satellite
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	instrument36 - instrument
	instrument37 - instrument
	thermograph2 - mode
	thermograph1 - mode
	thermograph5 - mode
	image3 - mode
	spectrograph6 - mode
	infrared0 - mode
	infrared4 - mode
	infrared7 - mode
	Star203 - direction
	Star103 - direction
	GroundStation104 - direction
	Star205 - direction
	GroundStation131 - direction
	GroundStation58 - direction
	Star219 - direction
	GroundStation99 - direction
	Star92 - direction
	Star114 - direction
	GroundStation167 - direction
	GroundStation172 - direction
	Star190 - direction
	Star157 - direction
	GroundStation77 - direction
	GroundStation64 - direction
	GroundStation72 - direction
	GroundStation34 - direction
	Star210 - direction
	GroundStation212 - direction
	GroundStation169 - direction
	GroundStation100 - direction
	Star196 - direction
	Star74 - direction
	GroundStation2 - direction
	Star152 - direction
	Star208 - direction
	Star19 - direction
	Star180 - direction
	Star134 - direction
	GroundStation39 - direction
	GroundStation218 - direction
	GroundStation126 - direction
	Star76 - direction
	Star95 - direction
	Star171 - direction
	GroundStation200 - direction
	GroundStation33 - direction
	GroundStation213 - direction
	GroundStation38 - direction
	GroundStation96 - direction
	GroundStation166 - direction
	GroundStation123 - direction
	Star112 - direction
	Star154 - direction
	Star184 - direction
	GroundStation125 - direction
	GroundStation83 - direction
	GroundStation185 - direction
	Star94 - direction
	Star14 - direction
	GroundStation148 - direction
	Star93 - direction
	Star7 - direction
	Star144 - direction
	Star117 - direction
	Star97 - direction
	Star35 - direction
	Star60 - direction
	Star161 - direction
	GroundStation13 - direction
	GroundStation209 - direction
	GroundStation1 - direction
	Star31 - direction
	GroundStation78 - direction
	GroundStation57 - direction
	GroundStation133 - direction
	Star146 - direction
	Star55 - direction
	Star128 - direction
	GroundStation137 - direction
	Star81 - direction
	GroundStation217 - direction
	GroundStation111 - direction
	Star8 - direction
	Star25 - direction
	Star130 - direction
	Star206 - direction
	Star174 - direction
	GroundStation91 - direction
	GroundStation162 - direction
	GroundStation179 - direction
	GroundStation178 - direction
	GroundStation198 - direction
	Star192 - direction
	Star186 - direction
	Star132 - direction
	Star67 - direction
	Star118 - direction
	GroundStation108 - direction
	Star89 - direction
	Star120 - direction
	GroundStation173 - direction
	GroundStation21 - direction
	Star116 - direction
	GroundStation149 - direction
	GroundStation121 - direction
	GroundStation199 - direction
	Star156 - direction
	GroundStation163 - direction
	GroundStation42 - direction
	Star68 - direction
	Star207 - direction
	GroundStation197 - direction
	Star5 - direction
	GroundStation98 - direction
	Star54 - direction
	GroundStation124 - direction
	GroundStation136 - direction
	GroundStation16 - direction
	Star183 - direction
	GroundStation119 - direction
	Star32 - direction
	GroundStation175 - direction
	Star151 - direction
	GroundStation88 - direction
	Star181 - direction
	Star3 - direction
	Star23 - direction
	GroundStation113 - direction
	Star17 - direction
	Star45 - direction
	GroundStation105 - direction
	GroundStation49 - direction
	Star47 - direction
	GroundStation75 - direction
	GroundStation195 - direction
	Star44 - direction
	GroundStation150 - direction
	Star177 - direction
	Star59 - direction
	Star216 - direction
	Star71 - direction
	Star52 - direction
	GroundStation110 - direction
	Star6 - direction
	GroundStation70 - direction
	GroundStation22 - direction
	Star214 - direction
	Star107 - direction
	Star122 - direction
	GroundStation102 - direction
	Star37 - direction
	Star135 - direction
	Star106 - direction
	Star62 - direction
	Star143 - direction
	Star193 - direction
	GroundStation188 - direction
	Star29 - direction
	Star147 - direction
	GroundStation170 - direction
	GroundStation87 - direction
	GroundStation24 - direction
	Star0 - direction
	GroundStation164 - direction
	GroundStation41 - direction
	Star48 - direction
	GroundStation138 - direction
	Star202 - direction
	GroundStation27 - direction
	Star165 - direction
	GroundStation176 - direction
	Star61 - direction
	Star63 - direction
	GroundStation56 - direction
	GroundStation73 - direction
	GroundStation80 - direction
	Star215 - direction
	GroundStation141 - direction
	Star53 - direction
	GroundStation10 - direction
	Star15 - direction
	Star46 - direction
	GroundStation84 - direction
	GroundStation211 - direction
	GroundStation40 - direction
	GroundStation160 - direction
	Star9 - direction
	Star28 - direction
	Star65 - direction
	GroundStation85 - direction
	GroundStation36 - direction
	Star142 - direction
	Star43 - direction
	GroundStation191 - direction
	Star86 - direction
	Star50 - direction
	GroundStation159 - direction
	GroundStation204 - direction
	GroundStation20 - direction
	Star153 - direction
	Star187 - direction
	Star101 - direction
	Star139 - direction
	GroundStation11 - direction
	Star18 - direction
	Star201 - direction
	Star140 - direction
	GroundStation168 - direction
	GroundStation127 - direction
	GroundStation158 - direction
	Star82 - direction
	GroundStation155 - direction
	GroundStation66 - direction
	GroundStation4 - direction
	Star12 - direction
	GroundStation145 - direction
	GroundStation189 - direction
	Star26 - direction
	Star30 - direction
	GroundStation109 - direction
	Star79 - direction
	GroundStation129 - direction
	Star182 - direction
	Star115 - direction
	Star69 - direction
	Star90 - direction
	Star194 - direction
	Star51 - direction
	Planet220 - direction
	Star221 - direction
	Phenomenon222 - direction
	Planet223 - direction
	Planet224 - direction
	Phenomenon225 - direction
	Phenomenon226 - direction
	Planet227 - direction
	Planet228 - direction
	Phenomenon229 - direction
	Star230 - direction
	Phenomenon231 - direction
	Star232 - direction
	Star233 - direction
	Star234 - direction
	Phenomenon235 - direction
	Phenomenon236 - direction
	Planet237 - direction
	Phenomenon238 - direction
	Planet239 - direction
	Phenomenon240 - direction
	Star241 - direction
	Phenomenon242 - direction
	Star243 - direction
	Phenomenon244 - direction
	Planet245 - direction
	Star246 - direction
	Star247 - direction
	Phenomenon248 - direction
	Planet249 - direction
	Phenomenon250 - direction
	Phenomenon251 - direction
	Phenomenon252 - direction
	Planet253 - direction
	Planet254 - direction
	Planet255 - direction
	Planet256 - direction
	Star257 - direction
	Phenomenon258 - direction
	Planet259 - direction
	Star260 - direction
	Star261 - direction
	Star262 - direction
	Phenomenon263 - direction
	Star264 - direction
	Phenomenon265 - direction
	Planet266 - direction
	Phenomenon267 - direction
	Phenomenon268 - direction
	Planet269 - direction
	Planet270 - direction
	Phenomenon271 - direction
	Planet272 - direction
	Phenomenon273 - direction
	Star274 - direction
	Planet275 - direction
	Phenomenon276 - direction
	Star277 - direction
	Planet278 - direction
	Phenomenon279 - direction
	Phenomenon280 - direction
	Planet281 - direction
	Star282 - direction
	Planet283 - direction
	Star284 - direction
	Phenomenon285 - direction
	Star286 - direction
	Phenomenon287 - direction
	Star288 - direction
	Star289 - direction
	Star290 - direction
	Planet291 - direction
	Phenomenon292 - direction
	Phenomenon293 - direction
	Planet294 - direction
	Star295 - direction
	Star296 - direction
	Phenomenon297 - direction
	Phenomenon298 - direction
	Phenomenon299 - direction
	Planet300 - direction
	Planet301 - direction
	Phenomenon302 - direction
	Star303 - direction
	Planet304 - direction
	Planet305 - direction
	Planet306 - direction
	Phenomenon307 - direction
	Star308 - direction
	Phenomenon309 - direction
	Phenomenon310 - direction
	Star311 - direction
	Phenomenon312 - direction
	Phenomenon313 - direction
	Planet314 - direction
	Star315 - direction
	Phenomenon316 - direction
	Phenomenon317 - direction
	Star318 - direction
	Phenomenon319 - direction
	Phenomenon320 - direction
	Planet321 - direction
	Phenomenon322 - direction
	Phenomenon323 - direction
	Planet324 - direction
	Planet325 - direction
	Star326 - direction
	Star327 - direction
	Star328 - direction
	Planet329 - direction
	Planet330 - direction
	Planet331 - direction
	Star332 - direction
	Star333 - direction
	Star334 - direction
	Star335 - direction
	Phenomenon336 - direction
	Phenomenon337 - direction
	Phenomenon338 - direction
	Planet339 - direction
	Planet340 - direction
	Star341 - direction
	Star342 - direction
	Star343 - direction
	Star344 - direction
	Phenomenon345 - direction
	Planet346 - direction
	Phenomenon347 - direction
	Planet348 - direction
	Star349 - direction
	Planet350 - direction
	Phenomenon351 - direction
	Planet352 - direction
	Phenomenon353 - direction
	Planet354 - direction
	Planet355 - direction
	Star356 - direction
	Planet357 - direction
	Star358 - direction
	Phenomenon359 - direction
	Planet360 - direction
	Planet361 - direction
	Star362 - direction
	Star363 - direction
	Star364 - direction
	Planet365 - direction
	Planet366 - direction
	Phenomenon367 - direction
	Phenomenon368 - direction
	Phenomenon369 - direction
	Planet370 - direction
	Planet371 - direction
	Star372 - direction
	Phenomenon373 - direction
	Star374 - direction
	Star375 - direction
	Planet376 - direction
	Planet377 - direction
	Phenomenon378 - direction
	Star379 - direction
	Star380 - direction
	Phenomenon381 - direction
	Planet382 - direction
	Planet383 - direction
	Phenomenon384 - direction
	Planet385 - direction
	Phenomenon386 - direction
	Phenomenon387 - direction
	Phenomenon388 - direction
	Phenomenon389 - direction
	Planet390 - direction
	Phenomenon391 - direction
	Star392 - direction
	Star393 - direction
	Planet394 - direction
	Planet395 - direction
	Star396 - direction
	Star397 - direction
	Phenomenon398 - direction
	Star399 - direction
	Star400 - direction
	Phenomenon401 - direction
	Phenomenon402 - direction
	Star403 - direction
	Phenomenon404 - direction
	Star405 - direction
	Star406 - direction
	Planet407 - direction
	Planet408 - direction
	Star409 - direction
	Phenomenon410 - direction
	Star411 - direction
	Planet412 - direction
	Star413 - direction
	Star414 - direction
	Star415 - direction
	Phenomenon416 - direction
	Planet417 - direction
	Planet418 - direction
	Planet419 - direction
	Planet420 - direction
	Phenomenon421 - direction
	Star422 - direction
	Star423 - direction
	Phenomenon424 - direction
	Planet425 - direction
	Planet426 - direction
	Star427 - direction
	Phenomenon428 - direction
	Planet429 - direction
	Phenomenon430 - direction
	Planet431 - direction
	Star432 - direction
	Phenomenon433 - direction
	Phenomenon434 - direction
	Phenomenon435 - direction
	Star436 - direction
	Star437 - direction
	Planet438 - direction
	Star439 - direction
)
(:init
	(supports instrument0 spectrograph6)
	(calibration_target instrument0 GroundStation211)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 GroundStation124)
	(calibration_target instrument0 GroundStation217)
	(supports instrument1 spectrograph6)
	(supports instrument1 infrared0)
	(calibration_target instrument1 GroundStation191)
	(calibration_target instrument1 Star184)
	(calibration_target instrument1 Star17)
	(calibration_target instrument1 Star151)
	(calibration_target instrument1 GroundStation175)
	(calibration_target instrument1 GroundStation218)
	(calibration_target instrument1 Star76)
	(calibration_target instrument1 Star120)
	(calibration_target instrument1 Star61)
	(calibration_target instrument1 GroundStation77)
	(calibration_target instrument1 Star51)
	(calibration_target instrument1 GroundStation141)
	(calibration_target instrument1 GroundStation124)
	(calibration_target instrument1 Star128)
	(calibration_target instrument1 GroundStation204)
	(calibration_target instrument1 Star157)
	(calibration_target instrument1 GroundStation155)
	(calibration_target instrument1 Star134)
	(calibration_target instrument1 GroundStation168)
	(calibration_target instrument1 Star146)
	(calibration_target instrument1 GroundStation138)
	(calibration_target instrument1 GroundStation70)
	(calibration_target instrument1 Star143)
	(calibration_target instrument1 GroundStation20)
	(calibration_target instrument1 Star181)
	(calibration_target instrument1 Star68)
	(calibration_target instrument1 Star115)
	(calibration_target instrument1 GroundStation99)
	(calibration_target instrument1 Star62)
	(calibration_target instrument1 GroundStation173)
	(calibration_target instrument1 GroundStation22)
	(calibration_target instrument1 GroundStation34)
	(calibration_target instrument1 Star132)
	(calibration_target instrument1 GroundStation38)
	(calibration_target instrument1 GroundStation188)
	(calibration_target instrument1 GroundStation88)
	(calibration_target instrument1 Star32)
	(calibration_target instrument1 GroundStation42)
	(calibration_target instrument1 Star214)
	(calibration_target instrument1 Star94)
	(calibration_target instrument1 Star114)
	(calibration_target instrument1 Star43)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star112)
	(calibration_target instrument1 Star174)
	(calibration_target instrument1 GroundStation211)
	(calibration_target instrument1 Star52)
	(supports instrument2 thermograph2)
	(supports instrument2 infrared0)
	(calibration_target instrument2 Star216)
	(calibration_target instrument2 GroundStation121)
	(calibration_target instrument2 GroundStation191)
	(calibration_target instrument2 GroundStation73)
	(calibration_target instrument2 Star177)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 GroundStation42)
	(calibration_target instrument2 GroundStation91)
	(calibration_target instrument2 Star142)
	(calibration_target instrument2 GroundStation105)
	(calibration_target instrument2 GroundStation75)
	(calibration_target instrument2 GroundStation185)
	(calibration_target instrument2 GroundStation159)
	(calibration_target instrument2 GroundStation58)
	(calibration_target instrument2 GroundStation77)
	(calibration_target instrument2 GroundStation175)
	(calibration_target instrument2 Star139)
	(calibration_target instrument2 Star23)
	(calibration_target instrument2 GroundStation209)
	(calibration_target instrument2 Star128)
	(calibration_target instrument2 GroundStation100)
	(calibration_target instrument2 GroundStation110)
	(calibration_target instrument2 GroundStation2)
	(calibration_target instrument2 GroundStation27)
	(calibration_target instrument2 Star210)
	(supports instrument3 infrared4)
	(supports instrument3 infrared7)
	(calibration_target instrument3 Star81)
	(calibration_target instrument3 GroundStation78)
	(calibration_target instrument3 Star135)
	(calibration_target instrument3 Star174)
	(calibration_target instrument3 GroundStation200)
	(calibration_target instrument3 GroundStation159)
	(calibration_target instrument3 GroundStation75)
	(calibration_target instrument3 GroundStation108)
	(calibration_target instrument3 GroundStation66)
	(calibration_target instrument3 GroundStation198)
	(calibration_target instrument3 Star19)
	(calibration_target instrument3 Star115)
	(calibration_target instrument3 GroundStation58)
	(calibration_target instrument3 Star203)
	(calibration_target instrument3 Star48)
	(calibration_target instrument3 Star183)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 GroundStation77)
	(calibration_target instrument3 GroundStation158)
	(calibration_target instrument3 GroundStation150)
	(calibration_target instrument3 GroundStation85)
	(calibration_target instrument3 Star205)
	(calibration_target instrument3 Star50)
	(calibration_target instrument3 Star190)
	(calibration_target instrument3 Star95)
	(calibration_target instrument3 GroundStation42)
	(calibration_target instrument3 Star219)
	(calibration_target instrument3 GroundStation100)
	(calibration_target instrument3 GroundStation33)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 GroundStation166)
	(calibration_target instrument3 Star118)
	(calibration_target instrument3 GroundStation131)
	(calibration_target instrument3 GroundStation91)
	(calibration_target instrument3 Star25)
	(calibration_target instrument3 GroundStation16)
	(calibration_target instrument3 GroundStation27)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 GroundStation133)
	(calibration_target instrument3 GroundStation41)
	(calibration_target instrument3 Star215)
	(calibration_target instrument3 Star161)
	(calibration_target instrument3 GroundStation110)
	(calibration_target instrument3 GroundStation195)
	(calibration_target instrument3 Star46)
	(calibration_target instrument3 Star26)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(on_board instrument3 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet370)
	(supports instrument4 thermograph1)
	(supports instrument4 infrared0)
	(supports instrument4 thermograph2)
	(calibration_target instrument4 Star134)
	(calibration_target instrument4 Star54)
	(calibration_target instrument4 Star157)
	(calibration_target instrument4 GroundStation10)
	(calibration_target instrument4 GroundStation27)
	(calibration_target instrument4 Star115)
	(calibration_target instrument4 Star7)
	(calibration_target instrument4 Star101)
	(calibration_target instrument4 GroundStation34)
	(calibration_target instrument4 GroundStation212)
	(calibration_target instrument4 Star18)
	(calibration_target instrument4 GroundStation91)
	(calibration_target instrument4 GroundStation159)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 Star132)
	(calibration_target instrument4 Star3)
	(calibration_target instrument4 GroundStation155)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation16)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 GroundStation189)
	(supports instrument5 spectrograph6)
	(supports instrument5 infrared7)
	(calibration_target instrument5 GroundStation137)
	(calibration_target instrument5 GroundStation4)
	(calibration_target instrument5 GroundStation113)
	(calibration_target instrument5 GroundStation72)
	(calibration_target instrument5 Star5)
	(calibration_target instrument5 GroundStation41)
	(calibration_target instrument5 GroundStation24)
	(calibration_target instrument5 Star107)
	(calibration_target instrument5 Star203)
	(calibration_target instrument5 Star122)
	(calibration_target instrument5 GroundStation34)
	(calibration_target instrument5 GroundStation121)
	(calibration_target instrument5 GroundStation173)
	(calibration_target instrument5 Star103)
	(calibration_target instrument5 Star106)
	(calibration_target instrument5 GroundStation57)
	(calibration_target instrument5 GroundStation83)
	(calibration_target instrument5 Star135)
	(supports instrument6 spectrograph6)
	(calibration_target instrument6 GroundStation21)
	(calibration_target instrument6 Star90)
	(calibration_target instrument6 GroundStation197)
	(calibration_target instrument6 GroundStation150)
	(calibration_target instrument6 Star219)
	(calibration_target instrument6 Star177)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 Star132)
	(calibration_target instrument6 GroundStation189)
	(calibration_target instrument6 Star157)
	(calibration_target instrument6 GroundStation98)
	(calibration_target instrument6 GroundStation77)
	(calibration_target instrument6 GroundStation145)
	(calibration_target instrument6 Star118)
	(calibration_target instrument6 Star68)
	(calibration_target instrument6 Star187)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 Star17)
	(calibration_target instrument6 Star154)
	(calibration_target instrument6 Star203)
	(calibration_target instrument6 GroundStation72)
	(calibration_target instrument6 GroundStation124)
	(calibration_target instrument6 GroundStation64)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 Star32)
	(calibration_target instrument6 Star146)
	(calibration_target instrument6 Star143)
	(calibration_target instrument6 Star31)
	(calibration_target instrument6 Star95)
	(calibration_target instrument6 Star208)
	(calibration_target instrument6 Star214)
	(calibration_target instrument6 GroundStation58)
	(calibration_target instrument6 Star139)
	(calibration_target instrument6 Star134)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star182)
	(supports instrument7 image3)
	(supports instrument7 infrared7)
	(supports instrument7 spectrograph6)
	(calibration_target instrument7 Star130)
	(calibration_target instrument7 GroundStation39)
	(calibration_target instrument7 Star81)
	(calibration_target instrument7 GroundStation148)
	(calibration_target instrument7 Star171)
	(calibration_target instrument7 Star48)
	(calibration_target instrument7 Star63)
	(calibration_target instrument7 Star71)
	(calibration_target instrument7 Star97)
	(calibration_target instrument7 GroundStation21)
	(calibration_target instrument7 GroundStation198)
	(calibration_target instrument7 GroundStation80)
	(calibration_target instrument7 Star112)
	(calibration_target instrument7 Star6)
	(calibration_target instrument7 GroundStation91)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 GroundStation72)
	(calibration_target instrument7 GroundStation108)
	(calibration_target instrument7 Star216)
	(calibration_target instrument7 Star196)
	(calibration_target instrument7 Star95)
	(calibration_target instrument7 GroundStation137)
	(calibration_target instrument7 Star156)
	(calibration_target instrument7 GroundStation141)
	(calibration_target instrument7 GroundStation164)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 GroundStation136)
	(calibration_target instrument7 Star94)
	(calibration_target instrument7 GroundStation155)
	(calibration_target instrument7 Star93)
	(calibration_target instrument7 Star139)
	(calibration_target instrument7 GroundStation77)
	(supports instrument8 thermograph1)
	(supports instrument8 thermograph2)
	(supports instrument8 thermograph5)
	(calibration_target instrument8 GroundStation36)
	(calibration_target instrument8 GroundStation110)
	(calibration_target instrument8 Star140)
	(calibration_target instrument8 Star43)
	(calibration_target instrument8 GroundStation11)
	(calibration_target instrument8 GroundStation164)
	(calibration_target instrument8 GroundStation57)
	(calibration_target instrument8 Star165)
	(calibration_target instrument8 Star186)
	(calibration_target instrument8 GroundStation141)
	(calibration_target instrument8 GroundStation96)
	(calibration_target instrument8 GroundStation172)
	(calibration_target instrument8 GroundStation105)
	(calibration_target instrument8 GroundStation108)
	(calibration_target instrument8 Star47)
	(calibration_target instrument8 Star206)
	(calibration_target instrument8 Star117)
	(calibration_target instrument8 GroundStation111)
	(calibration_target instrument8 GroundStation56)
	(calibration_target instrument8 Star135)
	(calibration_target instrument8 GroundStation173)
	(calibration_target instrument8 Star190)
	(calibration_target instrument8 Star202)
	(calibration_target instrument8 Star30)
	(calibration_target instrument8 Star71)
	(calibration_target instrument8 GroundStation125)
	(calibration_target instrument8 GroundStation80)
	(calibration_target instrument8 GroundStation66)
	(calibration_target instrument8 Star19)
	(calibration_target instrument8 Star59)
	(calibration_target instrument8 GroundStation191)
	(calibration_target instrument8 GroundStation212)
	(calibration_target instrument8 GroundStation200)
	(calibration_target instrument8 Star107)
	(calibration_target instrument8 Star97)
	(calibration_target instrument8 Star174)
	(calibration_target instrument8 GroundStation85)
	(calibration_target instrument8 Star115)
	(calibration_target instrument8 Star132)
	(calibration_target instrument8 GroundStation197)
	(calibration_target instrument8 Star215)
	(calibration_target instrument8 Star63)
	(calibration_target instrument8 Star74)
	(calibration_target instrument8 GroundStation148)
	(calibration_target instrument8 Star93)
	(calibration_target instrument8 Star116)
	(calibration_target instrument8 Star194)
	(calibration_target instrument8 Star35)
	(calibration_target instrument8 Star52)
	(calibration_target instrument8 GroundStation99)
	(calibration_target instrument8 GroundStation24)
	(calibration_target instrument8 Star81)
	(calibration_target instrument8 Star12)
	(calibration_target instrument8 Star171)
	(calibration_target instrument8 Star14)
	(calibration_target instrument8 Star177)
	(calibration_target instrument8 GroundStation119)
	(calibration_target instrument8 Star6)
	(calibration_target instrument8 GroundStation218)
	(calibration_target instrument8 GroundStation4)
	(calibration_target instrument8 Star29)
	(calibration_target instrument8 GroundStation136)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation75)
	(calibration_target instrument8 Star205)
	(calibration_target instrument8 Star193)
	(calibration_target instrument8 Star147)
	(supports instrument9 spectrograph6)
	(calibration_target instrument9 Star101)
	(calibration_target instrument9 Star94)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 Star143)
	(calibration_target instrument9 GroundStation10)
	(calibration_target instrument9 GroundStation77)
	(calibration_target instrument9 Star180)
	(calibration_target instrument9 GroundStation85)
	(calibration_target instrument9 Star182)
	(calibration_target instrument9 GroundStation78)
	(calibration_target instrument9 Star35)
	(calibration_target instrument9 GroundStation189)
	(calibration_target instrument9 GroundStation195)
	(calibration_target instrument9 GroundStation20)
	(calibration_target instrument9 GroundStation38)
	(calibration_target instrument9 Star171)
	(calibration_target instrument9 Star76)
	(calibration_target instrument9 Star69)
	(calibration_target instrument9 Star135)
	(calibration_target instrument9 GroundStation113)
	(calibration_target instrument9 Star95)
	(calibration_target instrument9 GroundStation127)
	(calibration_target instrument9 GroundStation49)
	(calibration_target instrument9 GroundStation104)
	(calibration_target instrument9 GroundStation185)
	(calibration_target instrument9 GroundStation96)
	(calibration_target instrument9 Star122)
	(calibration_target instrument9 GroundStation172)
	(calibration_target instrument9 Star192)
	(calibration_target instrument9 Star107)
	(calibration_target instrument9 GroundStation158)
	(calibration_target instrument9 Star196)
	(calibration_target instrument9 GroundStation34)
	(calibration_target instrument9 Star50)
	(supports instrument10 infrared7)
	(supports instrument10 infrared0)
	(supports instrument10 thermograph2)
	(calibration_target instrument10 Star101)
	(calibration_target instrument10 GroundStation125)
	(calibration_target instrument10 GroundStation75)
	(calibration_target instrument10 Star55)
	(calibration_target instrument10 GroundStation119)
	(calibration_target instrument10 Star74)
	(calibration_target instrument10 GroundStation167)
	(calibration_target instrument10 GroundStation41)
	(calibration_target instrument10 Star151)
	(calibration_target instrument10 Star107)
	(calibration_target instrument10 Star161)
	(calibration_target instrument10 GroundStation34)
	(calibration_target instrument10 Star132)
	(calibration_target instrument10 GroundStation155)
	(calibration_target instrument10 Star5)
	(calibration_target instrument10 Star0)
	(calibration_target instrument10 GroundStation197)
	(calibration_target instrument10 GroundStation169)
	(calibration_target instrument10 GroundStation160)
	(calibration_target instrument10 GroundStation2)
	(calibration_target instrument10 Star90)
	(calibration_target instrument10 Star71)
	(calibration_target instrument10 GroundStation204)
	(calibration_target instrument10 Star45)
	(calibration_target instrument10 GroundStation175)
	(calibration_target instrument10 GroundStation168)
	(calibration_target instrument10 GroundStation127)
	(calibration_target instrument10 GroundStation198)
	(calibration_target instrument10 Star32)
	(calibration_target instrument10 GroundStation137)
	(calibration_target instrument10 Star18)
	(calibration_target instrument10 Star146)
	(calibration_target instrument10 Star128)
	(calibration_target instrument10 Star35)
	(calibration_target instrument10 Star187)
	(calibration_target instrument10 GroundStation96)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 Star29)
	(calibration_target instrument10 Star142)
	(calibration_target instrument10 GroundStation172)
	(calibration_target instrument10 Star17)
	(calibration_target instrument10 GroundStation13)
	(calibration_target instrument10 GroundStation66)
	(calibration_target instrument10 GroundStation170)
	(calibration_target instrument10 GroundStation126)
	(calibration_target instrument10 Star152)
	(calibration_target instrument10 GroundStation176)
	(calibration_target instrument10 Star165)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 Star26)
	(calibration_target instrument10 GroundStation84)
	(calibration_target instrument10 GroundStation108)
	(calibration_target instrument10 GroundStation40)
	(calibration_target instrument10 Star53)
	(calibration_target instrument10 Star43)
	(calibration_target instrument10 GroundStation166)
	(calibration_target instrument10 Star112)
	(calibration_target instrument10 Star19)
	(calibration_target instrument10 Star196)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation104)
	(supports instrument11 thermograph5)
	(supports instrument11 thermograph1)
	(calibration_target instrument11 Star207)
	(calibration_target instrument11 GroundStation109)
	(calibration_target instrument11 GroundStation158)
	(calibration_target instrument11 Star140)
	(calibration_target instrument11 Star182)
	(calibration_target instrument11 GroundStation170)
	(calibration_target instrument11 GroundStation99)
	(calibration_target instrument11 Star216)
	(calibration_target instrument11 GroundStation145)
	(calibration_target instrument11 Star146)
	(calibration_target instrument11 Star103)
	(calibration_target instrument11 GroundStation102)
	(calibration_target instrument11 Star44)
	(calibration_target instrument11 GroundStation195)
	(calibration_target instrument11 Star86)
	(calibration_target instrument11 Star26)
	(calibration_target instrument11 GroundStation164)
	(calibration_target instrument11 Star117)
	(calibration_target instrument11 GroundStation169)
	(calibration_target instrument11 Star118)
	(calibration_target instrument11 Star184)
	(calibration_target instrument11 Star51)
	(calibration_target instrument11 Star43)
	(calibration_target instrument11 Star187)
	(calibration_target instrument11 Star165)
	(calibration_target instrument11 Star37)
	(calibration_target instrument11 GroundStation197)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star154)
	(calibration_target instrument11 Star106)
	(calibration_target instrument11 Star161)
	(calibration_target instrument11 Star81)
	(calibration_target instrument11 Star157)
	(calibration_target instrument11 GroundStation111)
	(calibration_target instrument11 Star92)
	(calibration_target instrument11 Star79)
	(calibration_target instrument11 GroundStation72)
	(calibration_target instrument11 GroundStation80)
	(calibration_target instrument11 GroundStation136)
	(calibration_target instrument11 GroundStation77)
	(calibration_target instrument11 GroundStation91)
	(calibration_target instrument11 Star180)
	(calibration_target instrument11 GroundStation176)
	(calibration_target instrument11 Star130)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 Star12)
	(calibration_target instrument11 GroundStation138)
	(calibration_target instrument11 Star55)
	(calibration_target instrument11 GroundStation39)
	(calibration_target instrument11 Star153)
	(calibration_target instrument11 GroundStation64)
	(calibration_target instrument11 GroundStation141)
	(on_board instrument11 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon276)
	(supports instrument12 infrared7)
	(supports instrument12 image3)
	(calibration_target instrument12 Star135)
	(calibration_target instrument12 GroundStation129)
	(calibration_target instrument12 Star26)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 GroundStation33)
	(calibration_target instrument12 GroundStation102)
	(calibration_target instrument12 GroundStation155)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 GroundStation42)
	(calibration_target instrument12 Star165)
	(calibration_target instrument12 Star171)
	(calibration_target instrument12 Star183)
	(calibration_target instrument12 GroundStation158)
	(calibration_target instrument12 GroundStation211)
	(supports instrument13 infrared7)
	(calibration_target instrument13 Star132)
	(calibration_target instrument13 Star89)
	(calibration_target instrument13 GroundStation162)
	(calibration_target instrument13 GroundStation213)
	(calibration_target instrument13 Star46)
	(calibration_target instrument13 Star8)
	(calibration_target instrument13 Star79)
	(calibration_target instrument13 Star62)
	(calibration_target instrument13 GroundStation121)
	(supports instrument14 image3)
	(calibration_target instrument14 GroundStation175)
	(calibration_target instrument14 GroundStation113)
	(calibration_target instrument14 GroundStation136)
	(calibration_target instrument14 GroundStation188)
	(calibration_target instrument14 GroundStation33)
	(calibration_target instrument14 Star19)
	(calibration_target instrument14 Star82)
	(calibration_target instrument14 GroundStation133)
	(calibration_target instrument14 Star196)
	(calibration_target instrument14 GroundStation27)
	(calibration_target instrument14 Star37)
	(calibration_target instrument14 GroundStation126)
	(calibration_target instrument14 GroundStation1)
	(calibration_target instrument14 GroundStation170)
	(calibration_target instrument14 Star180)
	(calibration_target instrument14 GroundStation98)
	(calibration_target instrument14 Star74)
	(calibration_target instrument14 Star117)
	(calibration_target instrument14 GroundStation105)
	(calibration_target instrument14 Star30)
	(calibration_target instrument14 GroundStation49)
	(calibration_target instrument14 GroundStation91)
	(calibration_target instrument14 Star65)
	(calibration_target instrument14 GroundStation131)
	(calibration_target instrument14 Star122)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation158)
	(calibration_target instrument14 Star186)
	(calibration_target instrument14 Star97)
	(calibration_target instrument14 Star92)
	(calibration_target instrument14 Star156)
	(calibration_target instrument14 Star59)
	(calibration_target instrument14 Star31)
	(calibration_target instrument14 Star79)
	(calibration_target instrument14 Star67)
	(calibration_target instrument14 Star25)
	(calibration_target instrument14 GroundStation10)
	(calibration_target instrument14 GroundStation178)
	(calibration_target instrument14 Star177)
	(calibration_target instrument14 GroundStation102)
	(calibration_target instrument14 Star68)
	(calibration_target instrument14 GroundStation163)
	(calibration_target instrument14 GroundStation166)
	(calibration_target instrument14 GroundStation104)
	(calibration_target instrument14 Star165)
	(calibration_target instrument14 GroundStation150)
	(calibration_target instrument14 Star90)
	(calibration_target instrument14 GroundStation168)
	(calibration_target instrument14 GroundStation123)
	(calibration_target instrument14 GroundStation213)
	(calibration_target instrument14 GroundStation42)
	(calibration_target instrument14 Star143)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 Star26)
	(calibration_target instrument14 GroundStation127)
	(calibration_target instrument14 GroundStation16)
	(calibration_target instrument14 GroundStation58)
	(calibration_target instrument14 GroundStation108)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 GroundStation84)
	(calibration_target instrument14 GroundStation218)
	(calibration_target instrument14 GroundStation176)
	(supports instrument15 thermograph1)
	(calibration_target instrument15 Star9)
	(calibration_target instrument15 GroundStation87)
	(calibration_target instrument15 GroundStation131)
	(calibration_target instrument15 GroundStation22)
	(calibration_target instrument15 GroundStation38)
	(calibration_target instrument15 Star154)
	(calibration_target instrument15 GroundStation126)
	(calibration_target instrument15 Star5)
	(calibration_target instrument15 GroundStation213)
	(calibration_target instrument15 GroundStation158)
	(calibration_target instrument15 Star94)
	(calibration_target instrument15 GroundStation108)
	(calibration_target instrument15 GroundStation39)
	(calibration_target instrument15 Star106)
	(calibration_target instrument15 GroundStation125)
	(calibration_target instrument15 Star143)
	(calibration_target instrument15 GroundStation88)
	(calibration_target instrument15 Star0)
	(calibration_target instrument15 Star18)
	(calibration_target instrument15 GroundStation84)
	(calibration_target instrument15 Star115)
	(calibration_target instrument15 Star157)
	(calibration_target instrument15 GroundStation150)
	(supports instrument16 infrared4)
	(supports instrument16 image3)
	(supports instrument16 infrared0)
	(calibration_target instrument16 GroundStation199)
	(calibration_target instrument16 Star115)
	(calibration_target instrument16 Star8)
	(calibration_target instrument16 Star53)
	(calibration_target instrument16 Star183)
	(calibration_target instrument16 Star152)
	(calibration_target instrument16 Star93)
	(calibration_target instrument16 Star52)
	(calibration_target instrument16 Star174)
	(calibration_target instrument16 Star182)
	(calibration_target instrument16 Star61)
	(calibration_target instrument16 Star94)
	(calibration_target instrument16 Star154)
	(calibration_target instrument16 Star74)
	(calibration_target instrument16 Star92)
	(calibration_target instrument16 Star26)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 Star146)
	(calibration_target instrument16 Star180)
	(calibration_target instrument16 Star69)
	(calibration_target instrument16 Star47)
	(calibration_target instrument16 Star17)
	(calibration_target instrument16 Star147)
	(calibration_target instrument16 GroundStation167)
	(calibration_target instrument16 GroundStation204)
	(calibration_target instrument16 Star187)
	(calibration_target instrument16 Star32)
	(calibration_target instrument16 GroundStation72)
	(calibration_target instrument16 GroundStation85)
	(calibration_target instrument16 GroundStation102)
	(calibration_target instrument16 Star23)
	(calibration_target instrument16 Star29)
	(calibration_target instrument16 Star89)
	(calibration_target instrument16 GroundStation108)
	(calibration_target instrument16 GroundStation13)
	(calibration_target instrument16 Star202)
	(calibration_target instrument16 GroundStation185)
	(calibration_target instrument16 Star37)
	(calibration_target instrument16 Star151)
	(calibration_target instrument16 Star81)
	(calibration_target instrument16 GroundStation119)
	(calibration_target instrument16 GroundStation21)
	(calibration_target instrument16 GroundStation64)
	(calibration_target instrument16 Star71)
	(calibration_target instrument16 GroundStation36)
	(calibration_target instrument16 Star215)
	(calibration_target instrument16 GroundStation70)
	(calibration_target instrument16 GroundStation77)
	(calibration_target instrument16 Star122)
	(calibration_target instrument16 Star157)
	(calibration_target instrument16 Star177)
	(calibration_target instrument16 Star60)
	(calibration_target instrument16 GroundStation191)
	(calibration_target instrument16 GroundStation33)
	(calibration_target instrument16 Star55)
	(calibration_target instrument16 Star135)
	(calibration_target instrument16 GroundStation137)
	(calibration_target instrument16 GroundStation49)
	(calibration_target instrument16 GroundStation209)
	(calibration_target instrument16 GroundStation42)
	(calibration_target instrument16 Star44)
	(calibration_target instrument16 GroundStation160)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(on_board instrument16 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet350)
	(supports instrument17 thermograph1)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation170)
	(calibration_target instrument17 Star23)
	(calibration_target instrument17 GroundStation87)
	(calibration_target instrument17 Star216)
	(calibration_target instrument17 Star219)
	(calibration_target instrument17 Star94)
	(calibration_target instrument17 GroundStation38)
	(calibration_target instrument17 Star117)
	(calibration_target instrument17 Star37)
	(calibration_target instrument17 Star25)
	(calibration_target instrument17 Star67)
	(calibration_target instrument17 GroundStation40)
	(calibration_target instrument17 GroundStation111)
	(calibration_target instrument17 Star59)
	(calibration_target instrument17 GroundStation178)
	(calibration_target instrument17 GroundStation204)
	(calibration_target instrument17 GroundStation158)
	(calibration_target instrument17 Star86)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 Star130)
	(calibration_target instrument17 GroundStation70)
	(calibration_target instrument17 Star93)
	(calibration_target instrument17 Star151)
	(calibration_target instrument17 GroundStation109)
	(calibration_target instrument17 GroundStation149)
	(calibration_target instrument17 GroundStation77)
	(calibration_target instrument17 Star135)
	(calibration_target instrument17 GroundStation113)
	(calibration_target instrument17 Star107)
	(calibration_target instrument17 GroundStation131)
	(calibration_target instrument17 Star7)
	(supports instrument18 thermograph1)
	(calibration_target instrument18 GroundStation105)
	(calibration_target instrument18 GroundStation191)
	(calibration_target instrument18 Star215)
	(calibration_target instrument18 Star65)
	(calibration_target instrument18 GroundStation204)
	(calibration_target instrument18 GroundStation96)
	(calibration_target instrument18 Star181)
	(calibration_target instrument18 GroundStation72)
	(calibration_target instrument18 GroundStation73)
	(calibration_target instrument18 Star151)
	(calibration_target instrument18 GroundStation4)
	(calibration_target instrument18 GroundStation129)
	(calibration_target instrument18 GroundStation137)
	(calibration_target instrument18 GroundStation56)
	(calibration_target instrument18 Star193)
	(calibration_target instrument18 GroundStation24)
	(calibration_target instrument18 GroundStation188)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 GroundStation133)
	(calibration_target instrument18 Star17)
	(calibration_target instrument18 GroundStation1)
	(calibration_target instrument18 Star219)
	(calibration_target instrument18 Star69)
	(calibration_target instrument18 GroundStation20)
	(calibration_target instrument18 Star214)
	(calibration_target instrument18 Star139)
	(calibration_target instrument18 GroundStation125)
	(calibration_target instrument18 Star45)
	(calibration_target instrument18 GroundStation169)
	(calibration_target instrument18 GroundStation84)
	(calibration_target instrument18 Star95)
	(calibration_target instrument18 Star152)
	(calibration_target instrument18 GroundStation172)
	(calibration_target instrument18 GroundStation131)
	(calibration_target instrument18 GroundStation145)
	(calibration_target instrument18 GroundStation212)
	(calibration_target instrument18 Star205)
	(calibration_target instrument18 GroundStation121)
	(calibration_target instrument18 GroundStation149)
	(calibration_target instrument18 Star206)
	(calibration_target instrument18 GroundStation138)
	(calibration_target instrument18 Star23)
	(calibration_target instrument18 Star82)
	(calibration_target instrument18 Star9)
	(calibration_target instrument18 GroundStation173)
	(calibration_target instrument18 GroundStation49)
	(calibration_target instrument18 GroundStation179)
	(calibration_target instrument18 Star81)
	(calibration_target instrument18 GroundStation34)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation166)
	(calibration_target instrument18 GroundStation167)
	(calibration_target instrument18 GroundStation136)
	(calibration_target instrument18 Star128)
	(calibration_target instrument18 GroundStation40)
	(calibration_target instrument18 Star44)
	(calibration_target instrument18 GroundStation164)
	(calibration_target instrument18 Star196)
	(calibration_target instrument18 Star8)
	(calibration_target instrument18 GroundStation209)
	(calibration_target instrument18 GroundStation124)
	(calibration_target instrument18 GroundStation217)
	(calibration_target instrument18 Star165)
	(calibration_target instrument18 Star118)
	(calibration_target instrument18 GroundStation109)
	(calibration_target instrument18 Star14)
	(calibration_target instrument18 GroundStation168)
	(calibration_target instrument18 Star216)
	(calibration_target instrument18 Star190)
	(calibration_target instrument18 GroundStation99)
	(on_board instrument17 satellite5)
	(on_board instrument18 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation96)
	(supports instrument19 thermograph1)
	(calibration_target instrument19 GroundStation209)
	(calibration_target instrument19 GroundStation213)
	(calibration_target instrument19 Star196)
	(calibration_target instrument19 Star142)
	(calibration_target instrument19 Star128)
	(calibration_target instrument19 Star15)
	(calibration_target instrument19 Star190)
	(calibration_target instrument19 GroundStation1)
	(calibration_target instrument19 GroundStation211)
	(calibration_target instrument19 Star206)
	(calibration_target instrument19 GroundStation212)
	(calibration_target instrument19 Star74)
	(calibration_target instrument19 GroundStation121)
	(calibration_target instrument19 Star94)
	(calibration_target instrument19 Star18)
	(calibration_target instrument19 GroundStation83)
	(calibration_target instrument19 Star192)
	(calibration_target instrument19 Star134)
	(calibration_target instrument19 GroundStation24)
	(calibration_target instrument19 GroundStation22)
	(calibration_target instrument19 Star139)
	(calibration_target instrument19 Star135)
	(calibration_target instrument19 Star6)
	(calibration_target instrument19 GroundStation34)
	(calibration_target instrument19 GroundStation168)
	(calibration_target instrument19 GroundStation98)
	(calibration_target instrument19 Star43)
	(calibration_target instrument19 GroundStation100)
	(calibration_target instrument19 GroundStation102)
	(calibration_target instrument19 GroundStation75)
	(calibration_target instrument19 GroundStation170)
	(calibration_target instrument19 Star62)
	(calibration_target instrument19 Star61)
	(calibration_target instrument19 Star60)
	(calibration_target instrument19 GroundStation88)
	(calibration_target instrument19 GroundStation163)
	(calibration_target instrument19 Star122)
	(calibration_target instrument19 Star63)
	(calibration_target instrument19 Star140)
	(calibration_target instrument19 Star25)
	(calibration_target instrument19 Star219)
	(calibration_target instrument19 Star208)
	(calibration_target instrument19 Star207)
	(calibration_target instrument19 GroundStation124)
	(calibration_target instrument19 Star44)
	(calibration_target instrument19 Star107)
	(calibration_target instrument19 Star0)
	(calibration_target instrument19 GroundStation84)
	(calibration_target instrument19 GroundStation158)
	(supports instrument20 thermograph1)
	(supports instrument20 thermograph2)
	(supports instrument20 spectrograph6)
	(calibration_target instrument20 GroundStation121)
	(calibration_target instrument20 GroundStation38)
	(calibration_target instrument20 GroundStation141)
	(calibration_target instrument20 Star183)
	(calibration_target instrument20 GroundStation166)
	(calibration_target instrument20 GroundStation13)
	(calibration_target instrument20 Star219)
	(calibration_target instrument20 GroundStation175)
	(calibration_target instrument20 GroundStation126)
	(calibration_target instrument20 Star154)
	(calibration_target instrument20 Star117)
	(calibration_target instrument20 Star165)
	(calibration_target instrument20 GroundStation119)
	(calibration_target instrument20 GroundStation148)
	(calibration_target instrument20 Star25)
	(calibration_target instrument20 Star128)
	(calibration_target instrument20 Star112)
	(calibration_target instrument20 GroundStation41)
	(calibration_target instrument20 GroundStation105)
	(calibration_target instrument20 Star44)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star142)
	(calibration_target instrument20 GroundStation188)
	(calibration_target instrument20 Star29)
	(calibration_target instrument20 Star196)
	(calibration_target instrument20 Star161)
	(calibration_target instrument20 GroundStation58)
	(calibration_target instrument20 GroundStation75)
	(calibration_target instrument20 GroundStation39)
	(calibration_target instrument20 GroundStation91)
	(calibration_target instrument20 Star67)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 GroundStation124)
	(calibration_target instrument20 GroundStation145)
	(calibration_target instrument20 GroundStation133)
	(calibration_target instrument20 Star187)
	(calibration_target instrument20 Star114)
	(calibration_target instrument20 Star37)
	(calibration_target instrument20 Star69)
	(calibration_target instrument20 Star177)
	(calibration_target instrument20 Star74)
	(calibration_target instrument20 GroundStation16)
	(calibration_target instrument20 GroundStation168)
	(calibration_target instrument20 GroundStation42)
	(calibration_target instrument20 Star186)
	(calibration_target instrument20 Star5)
	(calibration_target instrument20 GroundStation150)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Planet365)
	(supports instrument21 image3)
	(supports instrument21 thermograph5)
	(calibration_target instrument21 GroundStation125)
	(calibration_target instrument21 Star47)
	(calibration_target instrument21 GroundStation24)
	(calibration_target instrument21 Star142)
	(calibration_target instrument21 Star25)
	(calibration_target instrument21 GroundStation20)
	(calibration_target instrument21 Star92)
	(calibration_target instrument21 Star139)
	(calibration_target instrument21 GroundStation199)
	(calibration_target instrument21 Star177)
	(calibration_target instrument21 GroundStation178)
	(calibration_target instrument21 GroundStation56)
	(calibration_target instrument21 Star174)
	(calibration_target instrument21 GroundStation198)
	(calibration_target instrument21 Star26)
	(calibration_target instrument21 GroundStation150)
	(calibration_target instrument21 GroundStation195)
	(calibration_target instrument21 GroundStation13)
	(calibration_target instrument21 Star140)
	(calibration_target instrument21 GroundStation211)
	(calibration_target instrument21 Star157)
	(calibration_target instrument21 GroundStation129)
	(calibration_target instrument21 Star61)
	(calibration_target instrument21 Star0)
	(calibration_target instrument21 GroundStation137)
	(calibration_target instrument21 GroundStation70)
	(calibration_target instrument21 Star18)
	(calibration_target instrument21 GroundStation141)
	(calibration_target instrument21 GroundStation124)
	(calibration_target instrument21 GroundStation16)
	(calibration_target instrument21 GroundStation100)
	(calibration_target instrument21 GroundStation77)
	(calibration_target instrument21 GroundStation80)
	(calibration_target instrument21 Star216)
	(calibration_target instrument21 Star71)
	(calibration_target instrument21 Star116)
	(calibration_target instrument21 GroundStation175)
	(calibration_target instrument21 GroundStation191)
	(calibration_target instrument21 GroundStation213)
	(calibration_target instrument21 Star32)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 Star132)
	(calibration_target instrument21 Star196)
	(calibration_target instrument21 Star186)
	(calibration_target instrument21 Star55)
	(calibration_target instrument21 Star31)
	(calibration_target instrument21 Star151)
	(calibration_target instrument21 GroundStation99)
	(calibration_target instrument21 GroundStation123)
	(calibration_target instrument21 Star79)
	(calibration_target instrument21 GroundStation176)
	(calibration_target instrument21 Star9)
	(calibration_target instrument21 GroundStation42)
	(on_board instrument21 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation41)
	(supports instrument22 infrared7)
	(supports instrument22 infrared4)
	(supports instrument22 thermograph5)
	(calibration_target instrument22 GroundStation56)
	(calibration_target instrument22 GroundStation108)
	(calibration_target instrument22 Star187)
	(calibration_target instrument22 GroundStation80)
	(calibration_target instrument22 GroundStation72)
	(calibration_target instrument22 Star67)
	(calibration_target instrument22 Star147)
	(calibration_target instrument22 Star181)
	(calibration_target instrument22 Star46)
	(calibration_target instrument22 Star214)
	(calibration_target instrument22 Star59)
	(calibration_target instrument22 Star76)
	(calibration_target instrument22 Star144)
	(calibration_target instrument22 Star151)
	(calibration_target instrument22 Star55)
	(calibration_target instrument22 Star65)
	(calibration_target instrument22 GroundStation78)
	(calibration_target instrument22 GroundStation27)
	(calibration_target instrument22 Star134)
	(calibration_target instrument22 GroundStation158)
	(calibration_target instrument22 Star208)
	(calibration_target instrument22 GroundStation70)
	(calibration_target instrument22 GroundStation167)
	(calibration_target instrument22 GroundStation141)
	(calibration_target instrument22 GroundStation188)
	(calibration_target instrument22 GroundStation198)
	(calibration_target instrument22 GroundStation77)
	(calibration_target instrument22 Star165)
	(calibration_target instrument22 GroundStation66)
	(calibration_target instrument22 Star135)
	(calibration_target instrument22 GroundStation149)
	(calibration_target instrument22 Star54)
	(calibration_target instrument22 GroundStation123)
	(calibration_target instrument22 GroundStation159)
	(calibration_target instrument22 Star0)
	(calibration_target instrument22 Star202)
	(calibration_target instrument22 Star161)
	(calibration_target instrument22 GroundStation218)
	(calibration_target instrument22 Star3)
	(calibration_target instrument22 Star132)
	(calibration_target instrument22 Star192)
	(calibration_target instrument22 Star142)
	(calibration_target instrument22 GroundStation137)
	(calibration_target instrument22 GroundStation83)
	(calibration_target instrument22 GroundStation38)
	(calibration_target instrument22 GroundStation75)
	(calibration_target instrument22 Star120)
	(calibration_target instrument22 GroundStation191)
	(calibration_target instrument22 Star216)
	(supports instrument23 infrared0)
	(calibration_target instrument23 Star144)
	(calibration_target instrument23 Star118)
	(calibration_target instrument23 Star151)
	(calibration_target instrument23 Star112)
	(calibration_target instrument23 Star184)
	(calibration_target instrument23 GroundStation80)
	(calibration_target instrument23 GroundStation159)
	(calibration_target instrument23 Star134)
	(calibration_target instrument23 Star0)
	(calibration_target instrument23 Star210)
	(calibration_target instrument23 Star152)
	(calibration_target instrument23 GroundStation57)
	(calibration_target instrument23 GroundStation168)
	(calibration_target instrument23 GroundStation185)
	(calibration_target instrument23 GroundStation218)
	(calibration_target instrument23 Star89)
	(calibration_target instrument23 Star30)
	(calibration_target instrument23 GroundStation111)
	(calibration_target instrument23 GroundStation158)
	(calibration_target instrument23 GroundStation27)
	(calibration_target instrument23 GroundStation49)
	(calibration_target instrument23 GroundStation179)
	(calibration_target instrument23 Star59)
	(calibration_target instrument23 Star48)
	(calibration_target instrument23 GroundStation11)
	(calibration_target instrument23 Star86)
	(calibration_target instrument23 Star17)
	(calibration_target instrument23 Star62)
	(calibration_target instrument23 Star94)
	(calibration_target instrument23 Star193)
	(calibration_target instrument23 Star153)
	(calibration_target instrument23 GroundStation163)
	(calibration_target instrument23 GroundStation121)
	(calibration_target instrument23 Star28)
	(calibration_target instrument23 Star65)
	(calibration_target instrument23 GroundStation124)
	(calibration_target instrument23 Star187)
	(calibration_target instrument23 GroundStation125)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 Star132)
	(calibration_target instrument23 GroundStation191)
	(calibration_target instrument23 GroundStation78)
	(calibration_target instrument23 Star54)
	(calibration_target instrument23 Star23)
	(calibration_target instrument23 Star68)
	(calibration_target instrument23 Star140)
	(calibration_target instrument23 Star5)
	(calibration_target instrument23 GroundStation109)
	(calibration_target instrument23 Star46)
	(supports instrument24 infrared4)
	(supports instrument24 spectrograph6)
	(supports instrument24 infrared0)
	(calibration_target instrument24 Star208)
	(calibration_target instrument24 GroundStation72)
	(calibration_target instrument24 GroundStation126)
	(calibration_target instrument24 GroundStation211)
	(calibration_target instrument24 Star15)
	(calibration_target instrument24 Star152)
	(calibration_target instrument24 GroundStation38)
	(calibration_target instrument24 GroundStation168)
	(calibration_target instrument24 GroundStation124)
	(calibration_target instrument24 GroundStation27)
	(calibration_target instrument24 Star214)
	(calibration_target instrument24 GroundStation145)
	(calibration_target instrument24 Star207)
	(calibration_target instrument24 GroundStation125)
	(calibration_target instrument24 Star202)
	(calibration_target instrument24 Star171)
	(calibration_target instrument24 GroundStation176)
	(calibration_target instrument24 Star90)
	(calibration_target instrument24 Star139)
	(calibration_target instrument24 GroundStation155)
	(calibration_target instrument24 Star47)
	(calibration_target instrument24 GroundStation34)
	(calibration_target instrument24 GroundStation21)
	(calibration_target instrument24 GroundStation1)
	(calibration_target instrument24 Star130)
	(calibration_target instrument24 GroundStation209)
	(calibration_target instrument24 GroundStation172)
	(calibration_target instrument24 Star89)
	(calibration_target instrument24 Star114)
	(calibration_target instrument24 GroundStation36)
	(calibration_target instrument24 Star37)
	(calibration_target instrument24 GroundStation33)
	(calibration_target instrument24 Star48)
	(calibration_target instrument24 Star28)
	(on_board instrument22 satellite8)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star130)
	(supports instrument25 thermograph1)
	(supports instrument25 infrared4)
	(calibration_target instrument25 GroundStation197)
	(calibration_target instrument25 GroundStation136)
	(calibration_target instrument25 Star97)
	(calibration_target instrument25 Star216)
	(calibration_target instrument25 GroundStation218)
	(calibration_target instrument25 GroundStation77)
	(calibration_target instrument25 Star154)
	(calibration_target instrument25 Star135)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 Star157)
	(calibration_target instrument25 Star190)
	(calibration_target instrument25 GroundStation49)
	(calibration_target instrument25 Star65)
	(calibration_target instrument25 Star31)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 Star28)
	(calibration_target instrument25 GroundStation148)
	(calibration_target instrument25 Star63)
	(calibration_target instrument25 GroundStation73)
	(calibration_target instrument25 Star52)
	(calibration_target instrument25 Star9)
	(calibration_target instrument25 Star48)
	(calibration_target instrument25 GroundStation24)
	(calibration_target instrument25 GroundStation42)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 GroundStation211)
	(calibration_target instrument25 Star68)
	(calibration_target instrument25 GroundStation80)
	(calibration_target instrument25 Star81)
	(calibration_target instrument25 GroundStation66)
	(calibration_target instrument25 GroundStation199)
	(calibration_target instrument25 GroundStation96)
	(calibration_target instrument25 GroundStation179)
	(calibration_target instrument25 GroundStation188)
	(calibration_target instrument25 GroundStation111)
	(calibration_target instrument25 GroundStation75)
	(calibration_target instrument25 GroundStation173)
	(calibration_target instrument25 Star53)
	(calibration_target instrument25 Star180)
	(calibration_target instrument25 Star54)
	(calibration_target instrument25 Star147)
	(calibration_target instrument25 GroundStation213)
	(calibration_target instrument25 GroundStation175)
	(calibration_target instrument25 GroundStation10)
	(calibration_target instrument25 GroundStation172)
	(calibration_target instrument25 GroundStation167)
	(calibration_target instrument25 GroundStation217)
	(calibration_target instrument25 GroundStation204)
	(calibration_target instrument25 Star130)
	(calibration_target instrument25 Star183)
	(calibration_target instrument25 GroundStation105)
	(calibration_target instrument25 Star3)
	(supports instrument26 thermograph1)
	(supports instrument26 infrared4)
	(supports instrument26 thermograph5)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 GroundStation145)
	(calibration_target instrument26 GroundStation110)
	(calibration_target instrument26 GroundStation159)
	(calibration_target instrument26 Star37)
	(calibration_target instrument26 GroundStation200)
	(calibration_target instrument26 Star51)
	(calibration_target instrument26 Star132)
	(calibration_target instrument26 GroundStation155)
	(calibration_target instrument26 GroundStation16)
	(calibration_target instrument26 Star101)
	(calibration_target instrument26 Star147)
	(calibration_target instrument26 Star214)
	(calibration_target instrument26 Star183)
	(calibration_target instrument26 Star14)
	(calibration_target instrument26 GroundStation195)
	(calibration_target instrument26 Star76)
	(calibration_target instrument26 GroundStation36)
	(calibration_target instrument26 GroundStation64)
	(calibration_target instrument26 GroundStation176)
	(on_board instrument25 satellite9)
	(on_board instrument26 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation198)
	(supports instrument27 thermograph2)
	(supports instrument27 thermograph5)
	(calibration_target instrument27 GroundStation88)
	(calibration_target instrument27 GroundStation34)
	(calibration_target instrument27 GroundStation72)
	(calibration_target instrument27 Star128)
	(calibration_target instrument27 Star25)
	(calibration_target instrument27 Star60)
	(calibration_target instrument27 Star6)
	(calibration_target instrument27 GroundStation127)
	(calibration_target instrument27 GroundStation33)
	(supports instrument28 thermograph1)
	(calibration_target instrument28 Star59)
	(calibration_target instrument28 Star93)
	(calibration_target instrument28 Star135)
	(calibration_target instrument28 GroundStation121)
	(calibration_target instrument28 GroundStation158)
	(calibration_target instrument28 GroundStation137)
	(calibration_target instrument28 Star14)
	(calibration_target instrument28 Star151)
	(calibration_target instrument28 GroundStation127)
	(calibration_target instrument28 Star194)
	(calibration_target instrument28 GroundStation75)
	(calibration_target instrument28 GroundStation21)
	(calibration_target instrument28 GroundStation175)
	(calibration_target instrument28 Star60)
	(calibration_target instrument28 Star51)
	(calibration_target instrument28 Star97)
	(calibration_target instrument28 Star122)
	(calibration_target instrument28 Star128)
	(calibration_target instrument28 GroundStation109)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 Star25)
	(calibration_target instrument28 Star153)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 GroundStation159)
	(calibration_target instrument28 Star139)
	(calibration_target instrument28 Star196)
	(calibration_target instrument28 Star147)
	(calibration_target instrument28 GroundStation73)
	(calibration_target instrument28 GroundStation209)
	(calibration_target instrument28 Star134)
	(calibration_target instrument28 GroundStation191)
	(calibration_target instrument28 Star146)
	(calibration_target instrument28 GroundStation126)
	(calibration_target instrument28 GroundStation100)
	(calibration_target instrument28 Star0)
	(calibration_target instrument28 GroundStation169)
	(calibration_target instrument28 GroundStation217)
	(calibration_target instrument28 Star181)
	(calibration_target instrument28 GroundStation10)
	(calibration_target instrument28 GroundStation38)
	(calibration_target instrument28 GroundStation108)
	(calibration_target instrument28 Star192)
	(calibration_target instrument28 GroundStation212)
	(calibration_target instrument28 GroundStation138)
	(calibration_target instrument28 GroundStation20)
	(calibration_target instrument28 Star95)
	(calibration_target instrument28 GroundStation88)
	(calibration_target instrument28 Star210)
	(calibration_target instrument28 GroundStation40)
	(supports instrument29 infrared7)
	(supports instrument29 infrared0)
	(supports instrument29 spectrograph6)
	(calibration_target instrument29 GroundStation80)
	(calibration_target instrument29 GroundStation126)
	(calibration_target instrument29 GroundStation33)
	(calibration_target instrument29 Star140)
	(calibration_target instrument29 Star28)
	(calibration_target instrument29 Star52)
	(calibration_target instrument29 GroundStation218)
	(calibration_target instrument29 Star54)
	(calibration_target instrument29 Star128)
	(calibration_target instrument29 GroundStation39)
	(calibration_target instrument29 GroundStation111)
	(calibration_target instrument29 Star107)
	(calibration_target instrument29 GroundStation162)
	(calibration_target instrument29 GroundStation49)
	(calibration_target instrument29 Star134)
	(calibration_target instrument29 GroundStation204)
	(calibration_target instrument29 Star214)
	(calibration_target instrument29 GroundStation109)
	(calibration_target instrument29 Star71)
	(calibration_target instrument29 GroundStation198)
	(calibration_target instrument29 GroundStation40)
	(calibration_target instrument29 Star26)
	(calibration_target instrument29 GroundStation84)
	(calibration_target instrument29 Star6)
	(calibration_target instrument29 GroundStation98)
	(calibration_target instrument29 Star177)
	(calibration_target instrument29 Star180)
	(calibration_target instrument29 Star165)
	(calibration_target instrument29 Star144)
	(calibration_target instrument29 Star12)
	(calibration_target instrument29 Star117)
	(calibration_target instrument29 GroundStation189)
	(calibration_target instrument29 Star48)
	(calibration_target instrument29 GroundStation137)
	(calibration_target instrument29 Star193)
	(calibration_target instrument29 Star116)
	(calibration_target instrument29 GroundStation211)
	(calibration_target instrument29 Star19)
	(calibration_target instrument29 GroundStation20)
	(calibration_target instrument29 Star208)
	(calibration_target instrument29 Star186)
	(calibration_target instrument29 Star5)
	(calibration_target instrument29 GroundStation13)
	(calibration_target instrument29 Star174)
	(calibration_target instrument29 Star135)
	(calibration_target instrument29 Star152)
	(calibration_target instrument29 Star192)
	(calibration_target instrument29 GroundStation195)
	(calibration_target instrument29 GroundStation57)
	(calibration_target instrument29 Star156)
	(calibration_target instrument29 GroundStation2)
	(calibration_target instrument29 Star44)
	(calibration_target instrument29 GroundStation70)
	(calibration_target instrument29 Star74)
	(calibration_target instrument29 Star194)
	(calibration_target instrument29 Star202)
	(calibration_target instrument29 Star89)
	(calibration_target instrument29 Star130)
	(calibration_target instrument29 GroundStation88)
	(calibration_target instrument29 Star147)
	(calibration_target instrument29 GroundStation129)
	(calibration_target instrument29 GroundStation158)
	(calibration_target instrument29 Star139)
	(calibration_target instrument29 GroundStation191)
	(calibration_target instrument29 GroundStation21)
	(calibration_target instrument29 Star61)
	(on_board instrument27 satellite10)
	(on_board instrument28 satellite10)
	(on_board instrument29 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation98)
	(supports instrument30 infrared7)
	(supports instrument30 thermograph1)
	(supports instrument30 image3)
	(calibration_target instrument30 Star14)
	(calibration_target instrument30 GroundStation16)
	(calibration_target instrument30 Star216)
	(calibration_target instrument30 GroundStation24)
	(calibration_target instrument30 Star94)
	(calibration_target instrument30 Star116)
	(calibration_target instrument30 Star9)
	(calibration_target instrument30 Star120)
	(calibration_target instrument30 Star0)
	(calibration_target instrument30 GroundStation111)
	(calibration_target instrument30 GroundStation185)
	(calibration_target instrument30 Star3)
	(calibration_target instrument30 Star193)
	(calibration_target instrument30 GroundStation176)
	(calibration_target instrument30 GroundStation141)
	(calibration_target instrument30 GroundStation83)
	(calibration_target instrument30 GroundStation125)
	(calibration_target instrument30 GroundStation127)
	(calibration_target instrument30 Star107)
	(calibration_target instrument30 Star165)
	(calibration_target instrument30 GroundStation197)
	(calibration_target instrument30 Star184)
	(calibration_target instrument30 Star135)
	(calibration_target instrument30 Star154)
	(calibration_target instrument30 GroundStation36)
	(calibration_target instrument30 Star112)
	(calibration_target instrument30 GroundStation123)
	(calibration_target instrument30 Star8)
	(calibration_target instrument30 Star201)
	(calibration_target instrument30 GroundStation179)
	(calibration_target instrument30 Star82)
	(calibration_target instrument30 Star61)
	(calibration_target instrument30 GroundStation198)
	(calibration_target instrument30 GroundStation108)
	(calibration_target instrument30 GroundStation22)
	(calibration_target instrument30 GroundStation166)
	(calibration_target instrument30 GroundStation96)
	(calibration_target instrument30 GroundStation38)
	(calibration_target instrument30 GroundStation213)
	(calibration_target instrument30 GroundStation33)
	(calibration_target instrument30 GroundStation200)
	(calibration_target instrument30 GroundStation121)
	(calibration_target instrument30 Star25)
	(calibration_target instrument30 Star171)
	(calibration_target instrument30 Star29)
	(calibration_target instrument30 Star117)
	(calibration_target instrument30 Star95)
	(calibration_target instrument30 Star76)
	(supports instrument31 thermograph5)
	(supports instrument31 spectrograph6)
	(supports instrument31 image3)
	(calibration_target instrument31 GroundStation102)
	(calibration_target instrument31 Star8)
	(calibration_target instrument31 GroundStation111)
	(calibration_target instrument31 GroundStation217)
	(calibration_target instrument31 Star139)
	(calibration_target instrument31 Star81)
	(calibration_target instrument31 GroundStation137)
	(calibration_target instrument31 Star128)
	(calibration_target instrument31 Star55)
	(calibration_target instrument31 Star183)
	(calibration_target instrument31 Star146)
	(calibration_target instrument31 Star37)
	(calibration_target instrument31 GroundStation133)
	(calibration_target instrument31 Star3)
	(calibration_target instrument31 Star140)
	(calibration_target instrument31 GroundStation188)
	(calibration_target instrument31 GroundStation204)
	(calibration_target instrument31 GroundStation57)
	(calibration_target instrument31 Star17)
	(calibration_target instrument31 GroundStation78)
	(calibration_target instrument31 Star135)
	(calibration_target instrument31 Star30)
	(calibration_target instrument31 Star122)
	(calibration_target instrument31 Star31)
	(calibration_target instrument31 GroundStation1)
	(calibration_target instrument31 Star206)
	(calibration_target instrument31 GroundStation113)
	(calibration_target instrument31 GroundStation209)
	(calibration_target instrument31 Star51)
	(calibration_target instrument31 GroundStation13)
	(calibration_target instrument31 Star161)
	(calibration_target instrument31 GroundStation70)
	(calibration_target instrument31 Star60)
	(calibration_target instrument31 Star79)
	(calibration_target instrument31 Star35)
	(calibration_target instrument31 Star143)
	(calibration_target instrument31 Star97)
	(calibration_target instrument31 Star6)
	(calibration_target instrument31 Star117)
	(calibration_target instrument31 Star144)
	(calibration_target instrument31 Star7)
	(calibration_target instrument31 Star118)
	(calibration_target instrument31 GroundStation164)
	(calibration_target instrument31 GroundStation149)
	(calibration_target instrument31 GroundStation56)
	(calibration_target instrument31 GroundStation22)
	(calibration_target instrument31 Star93)
	(calibration_target instrument31 Star107)
	(calibration_target instrument31 Star181)
	(calibration_target instrument31 GroundStation162)
	(calibration_target instrument31 GroundStation41)
	(calibration_target instrument31 GroundStation148)
	(calibration_target instrument31 Star120)
	(calibration_target instrument31 Star174)
	(calibration_target instrument31 GroundStation84)
	(supports instrument32 infrared7)
	(supports instrument32 image3)
	(calibration_target instrument32 Star202)
	(calibration_target instrument32 GroundStation155)
	(calibration_target instrument32 GroundStation22)
	(calibration_target instrument32 Star192)
	(calibration_target instrument32 GroundStation198)
	(calibration_target instrument32 Star37)
	(calibration_target instrument32 GroundStation178)
	(calibration_target instrument32 Star62)
	(calibration_target instrument32 Star5)
	(calibration_target instrument32 GroundStation179)
	(calibration_target instrument32 Star44)
	(calibration_target instrument32 GroundStation162)
	(calibration_target instrument32 Star46)
	(calibration_target instrument32 GroundStation211)
	(calibration_target instrument32 Star183)
	(calibration_target instrument32 GroundStation91)
	(calibration_target instrument32 GroundStation188)
	(calibration_target instrument32 Star174)
	(calibration_target instrument32 GroundStation163)
	(calibration_target instrument32 Star206)
	(calibration_target instrument32 Star130)
	(calibration_target instrument32 GroundStation75)
	(calibration_target instrument32 Star26)
	(calibration_target instrument32 GroundStation119)
	(calibration_target instrument32 Star25)
	(calibration_target instrument32 GroundStation42)
	(calibration_target instrument32 GroundStation176)
	(calibration_target instrument32 GroundStation173)
	(on_board instrument30 satellite11)
	(on_board instrument31 satellite11)
	(on_board instrument32 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star399)
	(supports instrument33 infrared7)
	(supports instrument33 spectrograph6)
	(calibration_target instrument33 GroundStation175)
	(calibration_target instrument33 Star214)
	(calibration_target instrument33 GroundStation150)
	(calibration_target instrument33 Star32)
	(calibration_target instrument33 GroundStation119)
	(calibration_target instrument33 Star183)
	(calibration_target instrument33 GroundStation16)
	(calibration_target instrument33 Star52)
	(calibration_target instrument33 GroundStation136)
	(calibration_target instrument33 GroundStation124)
	(calibration_target instrument33 Star47)
	(calibration_target instrument33 Star54)
	(calibration_target instrument33 GroundStation98)
	(calibration_target instrument33 Star5)
	(calibration_target instrument33 GroundStation197)
	(calibration_target instrument33 Star142)
	(calibration_target instrument33 Star207)
	(calibration_target instrument33 Star68)
	(calibration_target instrument33 GroundStation42)
	(calibration_target instrument33 GroundStation163)
	(calibration_target instrument33 GroundStation87)
	(calibration_target instrument33 Star156)
	(calibration_target instrument33 GroundStation75)
	(calibration_target instrument33 Star79)
	(calibration_target instrument33 GroundStation199)
	(calibration_target instrument33 GroundStation121)
	(calibration_target instrument33 GroundStation149)
	(calibration_target instrument33 Star116)
	(calibration_target instrument33 GroundStation80)
	(calibration_target instrument33 GroundStation21)
	(calibration_target instrument33 GroundStation191)
	(calibration_target instrument33 Star135)
	(calibration_target instrument33 GroundStation113)
	(calibration_target instrument33 Star177)
	(calibration_target instrument33 GroundStation173)
	(calibration_target instrument33 Star120)
	(calibration_target instrument33 Star89)
	(calibration_target instrument33 GroundStation108)
	(calibration_target instrument33 Star187)
	(calibration_target instrument33 GroundStation127)
	(calibration_target instrument33 Star118)
	(calibration_target instrument33 GroundStation138)
	(calibration_target instrument33 Star182)
	(calibration_target instrument33 Star67)
	(calibration_target instrument33 Star132)
	(calibration_target instrument33 Star9)
	(calibration_target instrument33 Star101)
	(calibration_target instrument33 Star186)
	(calibration_target instrument33 Star140)
	(calibration_target instrument33 Star23)
	(calibration_target instrument33 GroundStation159)
	(supports instrument34 image3)
	(supports instrument34 infrared4)
	(calibration_target instrument34 Star61)
	(calibration_target instrument34 GroundStation176)
	(calibration_target instrument34 GroundStation129)
	(calibration_target instrument34 Star165)
	(calibration_target instrument34 GroundStation27)
	(calibration_target instrument34 Star101)
	(calibration_target instrument34 Star202)
	(calibration_target instrument34 Star201)
	(calibration_target instrument34 GroundStation138)
	(calibration_target instrument34 GroundStation20)
	(calibration_target instrument34 Star48)
	(calibration_target instrument34 GroundStation41)
	(calibration_target instrument34 GroundStation164)
	(calibration_target instrument34 Star0)
	(calibration_target instrument34 GroundStation24)
	(calibration_target instrument34 GroundStation87)
	(calibration_target instrument34 GroundStation73)
	(calibration_target instrument34 GroundStation170)
	(calibration_target instrument34 Star147)
	(calibration_target instrument34 Star29)
	(calibration_target instrument34 GroundStation188)
	(calibration_target instrument34 Star193)
	(calibration_target instrument34 Star143)
	(calibration_target instrument34 Star62)
	(calibration_target instrument34 Star106)
	(calibration_target instrument34 Star135)
	(calibration_target instrument34 Star37)
	(calibration_target instrument34 GroundStation102)
	(calibration_target instrument34 Star122)
	(calibration_target instrument34 Star140)
	(calibration_target instrument34 Star107)
	(calibration_target instrument34 Star214)
	(calibration_target instrument34 GroundStation36)
	(calibration_target instrument34 GroundStation22)
	(calibration_target instrument34 Star82)
	(calibration_target instrument34 GroundStation70)
	(calibration_target instrument34 Star6)
	(calibration_target instrument34 GroundStation110)
	(calibration_target instrument34 Star52)
	(calibration_target instrument34 Star71)
	(calibration_target instrument34 Star216)
	(calibration_target instrument34 Star59)
	(calibration_target instrument34 Star177)
	(calibration_target instrument34 GroundStation150)
	(calibration_target instrument34 Star44)
	(calibration_target instrument34 GroundStation195)
	(calibration_target instrument34 GroundStation75)
	(calibration_target instrument34 Star47)
	(calibration_target instrument34 GroundStation49)
	(calibration_target instrument34 GroundStation105)
	(calibration_target instrument34 Star12)
	(calibration_target instrument34 Star45)
	(calibration_target instrument34 Star17)
	(calibration_target instrument34 GroundStation113)
	(calibration_target instrument34 Star23)
	(calibration_target instrument34 Star3)
	(calibration_target instrument34 Star26)
	(calibration_target instrument34 Star181)
	(calibration_target instrument34 GroundStation88)
	(calibration_target instrument34 GroundStation158)
	(calibration_target instrument34 Star151)
	(supports instrument35 infrared4)
	(supports instrument35 spectrograph6)
	(supports instrument35 infrared0)
	(calibration_target instrument35 GroundStation73)
	(calibration_target instrument35 Star26)
	(calibration_target instrument35 GroundStation56)
	(calibration_target instrument35 Star63)
	(supports instrument36 infrared0)
	(calibration_target instrument36 Star142)
	(calibration_target instrument36 GroundStation36)
	(calibration_target instrument36 GroundStation85)
	(calibration_target instrument36 Star65)
	(calibration_target instrument36 GroundStation204)
	(calibration_target instrument36 Star28)
	(calibration_target instrument36 Star9)
	(calibration_target instrument36 GroundStation160)
	(calibration_target instrument36 Star140)
	(calibration_target instrument36 GroundStation158)
	(calibration_target instrument36 GroundStation40)
	(calibration_target instrument36 GroundStation211)
	(calibration_target instrument36 GroundStation145)
	(calibration_target instrument36 GroundStation84)
	(calibration_target instrument36 Star46)
	(calibration_target instrument36 Star15)
	(calibration_target instrument36 GroundStation10)
	(calibration_target instrument36 Star53)
	(calibration_target instrument36 GroundStation141)
	(calibration_target instrument36 GroundStation189)
	(calibration_target instrument36 Star215)
	(calibration_target instrument36 Star18)
	(calibration_target instrument36 GroundStation80)
	(calibration_target instrument36 GroundStation4)
	(supports instrument37 infrared7)
	(supports instrument37 infrared4)
	(supports instrument37 infrared0)
	(calibration_target instrument37 Star51)
	(calibration_target instrument37 Star194)
	(calibration_target instrument37 Star90)
	(calibration_target instrument37 Star69)
	(calibration_target instrument37 Star115)
	(calibration_target instrument37 Star182)
	(calibration_target instrument37 GroundStation129)
	(calibration_target instrument37 Star79)
	(calibration_target instrument37 GroundStation109)
	(calibration_target instrument37 Star30)
	(calibration_target instrument37 Star26)
	(calibration_target instrument37 GroundStation189)
	(calibration_target instrument37 GroundStation145)
	(calibration_target instrument37 Star12)
	(calibration_target instrument37 GroundStation4)
	(calibration_target instrument37 GroundStation66)
	(calibration_target instrument37 GroundStation155)
	(calibration_target instrument37 Star82)
	(calibration_target instrument37 GroundStation158)
	(calibration_target instrument37 GroundStation127)
	(calibration_target instrument37 GroundStation168)
	(calibration_target instrument37 Star140)
	(calibration_target instrument37 Star201)
	(calibration_target instrument37 Star18)
	(calibration_target instrument37 GroundStation11)
	(calibration_target instrument37 Star139)
	(calibration_target instrument37 Star101)
	(calibration_target instrument37 Star187)
	(calibration_target instrument37 Star153)
	(calibration_target instrument37 GroundStation20)
	(calibration_target instrument37 GroundStation204)
	(calibration_target instrument37 GroundStation159)
	(calibration_target instrument37 Star50)
	(calibration_target instrument37 Star86)
	(calibration_target instrument37 GroundStation191)
	(calibration_target instrument37 Star43)
	(on_board instrument33 satellite12)
	(on_board instrument34 satellite12)
	(on_board instrument35 satellite12)
	(on_board instrument36 satellite12)
	(on_board instrument37 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Planet324)
)
(:goal (and
	(pointing satellite0 Star140)
	(pointing satellite5 GroundStation136)
	(pointing satellite6 Star241)
	(pointing satellite7 Phenomenon298)
	(pointing satellite8 Star0)
	(have_image Planet220 infrared4)
	(have_image Star221 infrared0)
	(have_image Phenomenon222 infrared0)
	(have_image Phenomenon222 infrared7)
	(have_image Planet223 image3)
	(have_image Planet224 thermograph2)
	(have_image Phenomenon225 thermograph5)
	(have_image Planet227 thermograph5)
	(have_image Planet227 thermograph2)
	(have_image Planet228 infrared0)
	(have_image Star230 thermograph5)
	(have_image Star230 infrared4)
	(have_image Star232 infrared0)
	(have_image Star233 image3)
	(have_image Star234 infrared4)
	(have_image Star234 thermograph2)
	(have_image Phenomenon235 infrared7)
	(have_image Phenomenon236 spectrograph6)
	(have_image Planet237 infrared0)
	(have_image Planet237 image3)
	(have_image Phenomenon238 thermograph2)
	(have_image Planet239 thermograph2)
	(have_image Star241 image3)
	(have_image Star241 thermograph2)
	(have_image Phenomenon242 infrared0)
	(have_image Star243 thermograph2)
	(have_image Phenomenon244 thermograph1)
	(have_image Planet245 infrared0)
	(have_image Planet245 thermograph5)
	(have_image Star246 spectrograph6)
	(have_image Star246 thermograph5)
	(have_image Star247 thermograph1)
	(have_image Star247 spectrograph6)
	(have_image Phenomenon248 image3)
	(have_image Planet249 thermograph5)
	(have_image Phenomenon250 infrared4)
	(have_image Phenomenon251 infrared7)
	(have_image Phenomenon251 infrared0)
	(have_image Phenomenon252 infrared7)
	(have_image Planet253 thermograph2)
	(have_image Planet253 thermograph1)
	(have_image Planet254 thermograph2)
	(have_image Planet255 spectrograph6)
	(have_image Planet255 thermograph2)
	(have_image Planet256 thermograph2)
	(have_image Planet256 thermograph5)
	(have_image Phenomenon258 spectrograph6)
	(have_image Phenomenon258 thermograph1)
	(have_image Planet259 infrared7)
	(have_image Star260 infrared4)
	(have_image Star260 image3)
	(have_image Star261 spectrograph6)
	(have_image Star262 spectrograph6)
	(have_image Star262 thermograph1)
	(have_image Phenomenon263 image3)
	(have_image Star264 image3)
	(have_image Star264 infrared4)
	(have_image Phenomenon265 spectrograph6)
	(have_image Planet266 image3)
	(have_image Planet266 thermograph5)
	(have_image Phenomenon267 thermograph1)
	(have_image Phenomenon268 thermograph1)
	(have_image Phenomenon268 infrared4)
	(have_image Planet269 infrared4)
	(have_image Planet269 thermograph2)
	(have_image Planet270 thermograph1)
	(have_image Phenomenon271 infrared7)
	(have_image Phenomenon273 image3)
	(have_image Star274 image3)
	(have_image Star274 spectrograph6)
	(have_image Planet275 infrared0)
	(have_image Phenomenon276 infrared7)
	(have_image Star277 image3)
	(have_image Star277 thermograph1)
	(have_image Planet278 image3)
	(have_image Phenomenon279 thermograph2)
	(have_image Phenomenon279 thermograph5)
	(have_image Phenomenon280 infrared7)
	(have_image Phenomenon280 thermograph2)
	(have_image Planet281 infrared0)
	(have_image Star282 infrared7)
	(have_image Planet283 image3)
	(have_image Planet283 thermograph2)
	(have_image Star284 spectrograph6)
	(have_image Phenomenon285 spectrograph6)
	(have_image Phenomenon285 infrared4)
	(have_image Star286 image3)
	(have_image Phenomenon287 thermograph2)
	(have_image Phenomenon287 infrared7)
	(have_image Star288 thermograph2)
	(have_image Star288 infrared4)
	(have_image Star289 thermograph2)
	(have_image Star290 infrared7)
	(have_image Star290 thermograph1)
	(have_image Planet291 thermograph2)
	(have_image Planet291 image3)
	(have_image Phenomenon292 infrared4)
	(have_image Phenomenon292 thermograph1)
	(have_image Phenomenon293 thermograph1)
	(have_image Phenomenon293 thermograph5)
	(have_image Planet294 infrared7)
	(have_image Star295 infrared4)
	(have_image Star296 thermograph2)
	(have_image Phenomenon297 thermograph2)
	(have_image Phenomenon297 thermograph5)
	(have_image Phenomenon298 infrared7)
	(have_image Phenomenon298 infrared0)
	(have_image Phenomenon299 thermograph5)
	(have_image Planet300 thermograph2)
	(have_image Planet301 spectrograph6)
	(have_image Planet301 infrared7)
	(have_image Phenomenon302 infrared0)
	(have_image Phenomenon302 infrared7)
	(have_image Star303 infrared0)
	(have_image Planet304 infrared0)
	(have_image Planet305 infrared7)
	(have_image Planet305 image3)
	(have_image Planet306 infrared7)
	(have_image Planet306 thermograph1)
	(have_image Phenomenon307 thermograph2)
	(have_image Star308 image3)
	(have_image Phenomenon309 spectrograph6)
	(have_image Phenomenon310 thermograph2)
	(have_image Star311 infrared4)
	(have_image Phenomenon312 spectrograph6)
	(have_image Phenomenon313 infrared7)
	(have_image Planet314 image3)
	(have_image Planet314 infrared0)
	(have_image Star315 infrared4)
	(have_image Phenomenon316 thermograph2)
	(have_image Phenomenon317 infrared7)
	(have_image Phenomenon317 thermograph5)
	(have_image Phenomenon319 thermograph1)
	(have_image Phenomenon319 infrared0)
	(have_image Planet321 thermograph5)
	(have_image Phenomenon322 infrared7)
	(have_image Phenomenon322 thermograph5)
	(have_image Phenomenon323 spectrograph6)
	(have_image Phenomenon323 infrared7)
	(have_image Planet324 image3)
	(have_image Planet325 thermograph5)
	(have_image Star326 image3)
	(have_image Star327 infrared4)
	(have_image Star327 thermograph1)
	(have_image Planet329 infrared7)
	(have_image Planet329 thermograph2)
	(have_image Planet330 thermograph5)
	(have_image Planet330 thermograph2)
	(have_image Planet331 thermograph1)
	(have_image Planet331 thermograph5)
	(have_image Star332 image3)
	(have_image Star333 infrared7)
	(have_image Star333 spectrograph6)
	(have_image Star334 spectrograph6)
	(have_image Star334 image3)
	(have_image Star335 thermograph1)
	(have_image Star335 infrared4)
	(have_image Phenomenon336 infrared4)
	(have_image Phenomenon336 image3)
	(have_image Phenomenon337 infrared4)
	(have_image Phenomenon337 spectrograph6)
	(have_image Phenomenon338 thermograph1)
	(have_image Planet339 image3)
	(have_image Planet339 infrared0)
	(have_image Planet340 infrared7)
	(have_image Planet340 thermograph5)
	(have_image Star341 infrared0)
	(have_image Star341 thermograph2)
	(have_image Star342 infrared0)
	(have_image Star342 spectrograph6)
	(have_image Star343 spectrograph6)
	(have_image Star343 image3)
	(have_image Star344 thermograph2)
	(have_image Star344 thermograph1)
	(have_image Phenomenon345 image3)
	(have_image Phenomenon345 infrared0)
	(have_image Planet346 thermograph5)
	(have_image Planet346 infrared4)
	(have_image Phenomenon347 infrared7)
	(have_image Phenomenon347 spectrograph6)
	(have_image Planet348 spectrograph6)
	(have_image Planet350 thermograph1)
	(have_image Planet350 infrared4)
	(have_image Phenomenon351 spectrograph6)
	(have_image Planet352 thermograph1)
	(have_image Phenomenon353 image3)
	(have_image Planet354 thermograph5)
	(have_image Planet355 infrared0)
	(have_image Planet355 image3)
	(have_image Star356 infrared7)
	(have_image Star358 infrared7)
	(have_image Phenomenon359 infrared4)
	(have_image Phenomenon359 infrared7)
	(have_image Planet361 infrared7)
	(have_image Planet361 image3)
	(have_image Star362 infrared4)
	(have_image Star363 spectrograph6)
	(have_image Star364 thermograph1)
	(have_image Star364 infrared7)
	(have_image Planet365 spectrograph6)
	(have_image Planet365 thermograph5)
	(have_image Planet366 spectrograph6)
	(have_image Phenomenon367 thermograph2)
	(have_image Phenomenon368 thermograph2)
	(have_image Phenomenon369 infrared0)
	(have_image Phenomenon369 spectrograph6)
	(have_image Planet370 spectrograph6)
	(have_image Planet371 thermograph2)
	(have_image Star372 image3)
	(have_image Phenomenon373 infrared7)
	(have_image Star374 thermograph5)
	(have_image Star375 thermograph1)
	(have_image Star375 infrared0)
	(have_image Planet376 infrared4)
	(have_image Planet377 image3)
	(have_image Planet377 infrared4)
	(have_image Phenomenon378 infrared7)
	(have_image Phenomenon378 thermograph1)
	(have_image Star379 thermograph2)
	(have_image Star380 infrared4)
	(have_image Phenomenon381 thermograph2)
	(have_image Phenomenon381 infrared7)
	(have_image Planet382 image3)
	(have_image Planet382 spectrograph6)
	(have_image Planet383 infrared4)
	(have_image Phenomenon384 thermograph2)
	(have_image Planet385 thermograph5)
	(have_image Phenomenon386 infrared4)
	(have_image Phenomenon386 spectrograph6)
	(have_image Phenomenon387 thermograph2)
	(have_image Phenomenon387 infrared4)
	(have_image Phenomenon388 thermograph2)
	(have_image Phenomenon389 image3)
	(have_image Phenomenon389 thermograph1)
	(have_image Planet390 infrared4)
	(have_image Planet390 infrared0)
	(have_image Phenomenon391 spectrograph6)
	(have_image Phenomenon391 infrared4)
	(have_image Star392 infrared0)
	(have_image Star392 infrared4)
	(have_image Star393 thermograph1)
	(have_image Planet394 infrared7)
	(have_image Planet394 image3)
	(have_image Planet395 thermograph1)
	(have_image Star396 spectrograph6)
	(have_image Star396 thermograph2)
	(have_image Star397 thermograph1)
	(have_image Star399 image3)
	(have_image Star400 infrared0)
	(have_image Phenomenon402 infrared0)
	(have_image Phenomenon402 infrared4)
	(have_image Phenomenon404 infrared0)
	(have_image Phenomenon404 thermograph5)
	(have_image Star405 image3)
	(have_image Star405 thermograph1)
	(have_image Star406 infrared0)
	(have_image Star406 spectrograph6)
	(have_image Planet407 infrared4)
	(have_image Planet408 image3)
	(have_image Planet408 infrared4)
	(have_image Star409 thermograph2)
	(have_image Star409 thermograph5)
	(have_image Phenomenon410 thermograph1)
	(have_image Star411 image3)
	(have_image Planet412 infrared7)
	(have_image Planet412 thermograph2)
	(have_image Star413 infrared7)
	(have_image Star414 spectrograph6)
	(have_image Star415 thermograph5)
	(have_image Star415 infrared4)
	(have_image Phenomenon416 infrared7)
	(have_image Planet417 image3)
	(have_image Planet418 infrared4)
	(have_image Planet418 infrared7)
	(have_image Planet419 infrared0)
	(have_image Planet420 thermograph2)
	(have_image Phenomenon421 thermograph2)
	(have_image Star422 infrared0)
	(have_image Star423 thermograph5)
	(have_image Phenomenon424 thermograph1)
	(have_image Phenomenon424 spectrograph6)
	(have_image Planet425 image3)
	(have_image Planet426 infrared4)
	(have_image Planet426 infrared0)
	(have_image Star427 thermograph2)
	(have_image Star427 spectrograph6)
	(have_image Planet429 infrared4)
	(have_image Planet429 spectrograph6)
	(have_image Phenomenon430 infrared7)
	(have_image Phenomenon430 spectrograph6)
	(have_image Planet431 thermograph5)
	(have_image Star432 image3)
	(have_image Star432 spectrograph6)
	(have_image Phenomenon433 image3)
	(have_image Phenomenon434 thermograph2)
	(have_image Phenomenon434 thermograph5)
	(have_image Phenomenon435 thermograph2)
	(have_image Star436 thermograph2)
	(have_image Star436 image3)
	(have_image Star437 thermograph2)
	(have_image Star437 spectrograph6)
	(have_image Planet438 thermograph2)
	(have_image Planet438 infrared7)
	(have_image Star439 thermograph2)
	(have_image Star439 infrared7)
))

)
