(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	satellite2 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	satellite5 - satellite
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	satellite8 - satellite
	instrument22 - instrument
	instrument23 - instrument
	instrument24 - instrument
	satellite9 - satellite
	instrument25 - instrument
	instrument26 - instrument
	satellite10 - satellite
	instrument27 - instrument
	instrument28 - instrument
	image0 - mode
	spectrograph2 - mode
	spectrograph5 - mode
	infrared4 - mode
	thermograph1 - mode
	infrared3 - mode
	Star209 - direction
	GroundStation218 - direction
	Star78 - direction
	GroundStation167 - direction
	Star196 - direction
	GroundStation68 - direction
	Star131 - direction
	GroundStation208 - direction
	GroundStation215 - direction
	GroundStation184 - direction
	Star144 - direction
	GroundStation202 - direction
	Star166 - direction
	Star4 - direction
	Star156 - direction
	Star34 - direction
	Star185 - direction
	GroundStation40 - direction
	GroundStation102 - direction
	GroundStation65 - direction
	Star27 - direction
	Star103 - direction
	Star168 - direction
	GroundStation111 - direction
	GroundStation183 - direction
	Star225 - direction
	Star169 - direction
	GroundStation207 - direction
	GroundStation97 - direction
	GroundStation198 - direction
	GroundStation182 - direction
	GroundStation31 - direction
	GroundStation21 - direction
	GroundStation90 - direction
	GroundStation222 - direction
	GroundStation59 - direction
	GroundStation127 - direction
	GroundStation99 - direction
	GroundStation194 - direction
	Star181 - direction
	Star170 - direction
	Star153 - direction
	GroundStation66 - direction
	GroundStation114 - direction
	Star192 - direction
	Star224 - direction
	GroundStation157 - direction
	Star210 - direction
	Star91 - direction
	Star197 - direction
	Star187 - direction
	Star108 - direction
	Star180 - direction
	GroundStation35 - direction
	GroundStation141 - direction
	GroundStation213 - direction
	Star61 - direction
	Star155 - direction
	GroundStation178 - direction
	GroundStation5 - direction
	GroundStation177 - direction
	GroundStation112 - direction
	GroundStation38 - direction
	GroundStation135 - direction
	GroundStation142 - direction
	Star1 - direction
	Star42 - direction
	Star79 - direction
	GroundStation211 - direction
	GroundStation205 - direction
	Star48 - direction
	GroundStation70 - direction
	GroundStation221 - direction
	GroundStation82 - direction
	Star45 - direction
	GroundStation162 - direction
	GroundStation195 - direction
	Star55 - direction
	Star175 - direction
	GroundStation92 - direction
	Star219 - direction
	GroundStation36 - direction
	GroundStation176 - direction
	GroundStation152 - direction
	Star52 - direction
	GroundStation226 - direction
	GroundStation87 - direction
	GroundStation124 - direction
	GroundStation159 - direction
	Star158 - direction
	Star95 - direction
	GroundStation13 - direction
	Star161 - direction
	Star15 - direction
	Star105 - direction
	Star46 - direction
	GroundStation37 - direction
	Star201 - direction
	GroundStation28 - direction
	GroundStation104 - direction
	Star203 - direction
	Star123 - direction
	GroundStation190 - direction
	GroundStation17 - direction
	GroundStation121 - direction
	Star23 - direction
	Star110 - direction
	Star151 - direction
	Star50 - direction
	GroundStation33 - direction
	Star77 - direction
	Star74 - direction
	Star11 - direction
	Star134 - direction
	GroundStation188 - direction
	Star149 - direction
	Star72 - direction
	GroundStation206 - direction
	Star146 - direction
	Star122 - direction
	GroundStation41 - direction
	Star116 - direction
	GroundStation193 - direction
	Star109 - direction
	GroundStation165 - direction
	Star130 - direction
	GroundStation171 - direction
	GroundStation133 - direction
	Star53 - direction
	GroundStation119 - direction
	GroundStation163 - direction
	Star57 - direction
	Star60 - direction
	Star63 - direction
	Star173 - direction
	Star189 - direction
	Star140 - direction
	Star39 - direction
	GroundStation220 - direction
	GroundStation174 - direction
	GroundStation160 - direction
	Star148 - direction
	Star89 - direction
	GroundStation6 - direction
	GroundStation147 - direction
	GroundStation94 - direction
	GroundStation58 - direction
	GroundStation10 - direction
	GroundStation29 - direction
	Star125 - direction
	GroundStation85 - direction
	Star143 - direction
	Star73 - direction
	GroundStation20 - direction
	Star200 - direction
	Star30 - direction
	GroundStation7 - direction
	GroundStation217 - direction
	Star191 - direction
	Star84 - direction
	Star199 - direction
	Star132 - direction
	Star9 - direction
	GroundStation25 - direction
	GroundStation49 - direction
	GroundStation107 - direction
	Star69 - direction
	GroundStation67 - direction
	GroundStation137 - direction
	Star16 - direction
	GroundStation101 - direction
	GroundStation86 - direction
	GroundStation8 - direction
	GroundStation118 - direction
	Star12 - direction
	Star129 - direction
	Star117 - direction
	Star139 - direction
	GroundStation113 - direction
	GroundStation18 - direction
	Star56 - direction
	Star120 - direction
	Star83 - direction
	Star164 - direction
	GroundStation128 - direction
	GroundStation26 - direction
	GroundStation71 - direction
	GroundStation24 - direction
	Star227 - direction
	GroundStation88 - direction
	GroundStation2 - direction
	GroundStation0 - direction
	GroundStation44 - direction
	Star64 - direction
	GroundStation115 - direction
	GroundStation47 - direction
	GroundStation145 - direction
	Star126 - direction
	GroundStation93 - direction
	GroundStation51 - direction
	GroundStation22 - direction
	GroundStation136 - direction
	GroundStation19 - direction
	GroundStation75 - direction
	GroundStation216 - direction
	GroundStation106 - direction
	GroundStation32 - direction
	GroundStation172 - direction
	Star43 - direction
	GroundStation154 - direction
	Star3 - direction
	GroundStation138 - direction
	Star150 - direction
	GroundStation100 - direction
	GroundStation81 - direction
	Star223 - direction
	GroundStation80 - direction
	GroundStation62 - direction
	Star214 - direction
	GroundStation204 - direction
	Star179 - direction
	Star14 - direction
	GroundStation212 - direction
	Star54 - direction
	GroundStation186 - direction
	GroundStation76 - direction
	GroundStation98 - direction
	Star96 - direction
	Phenomenon228 - direction
	Planet229 - direction
	Star230 - direction
	Phenomenon231 - direction
	Star232 - direction
	Phenomenon233 - direction
	Star234 - direction
	Planet235 - direction
	Planet236 - direction
	Star237 - direction
	Star238 - direction
	Phenomenon239 - direction
	Star240 - direction
	Planet241 - direction
	Planet242 - direction
	Phenomenon243 - direction
	Star244 - direction
	Star245 - direction
	Planet246 - direction
	Star247 - direction
	Planet248 - direction
	Phenomenon249 - direction
	Planet250 - direction
	Star251 - direction
	Phenomenon252 - direction
	Star253 - direction
	Phenomenon254 - direction
	Star255 - direction
	Planet256 - direction
	Star257 - direction
	Phenomenon258 - direction
	Phenomenon259 - direction
	Planet260 - direction
	Star261 - direction
	Planet262 - direction
	Planet263 - direction
	Star264 - direction
	Planet265 - direction
	Planet266 - direction
	Phenomenon267 - direction
	Planet268 - direction
	Star269 - direction
	Planet270 - direction
	Planet271 - direction
	Planet272 - direction
	Planet273 - direction
	Phenomenon274 - direction
	Star275 - direction
	Phenomenon276 - direction
	Star277 - direction
	Phenomenon278 - direction
	Planet279 - direction
	Phenomenon280 - direction
	Planet281 - direction
	Star282 - direction
	Planet283 - direction
	Star284 - direction
	Planet285 - direction
	Planet286 - direction
	Phenomenon287 - direction
	Star288 - direction
	Phenomenon289 - direction
	Star290 - direction
	Planet291 - direction
	Phenomenon292 - direction
	Planet293 - direction
	Planet294 - direction
	Star295 - direction
	Star296 - direction
	Phenomenon297 - direction
	Star298 - direction
	Phenomenon299 - direction
	Phenomenon300 - direction
	Phenomenon301 - direction
	Planet302 - direction
	Star303 - direction
	Phenomenon304 - direction
	Planet305 - direction
	Phenomenon306 - direction
	Planet307 - direction
	Phenomenon308 - direction
	Star309 - direction
	Phenomenon310 - direction
	Star311 - direction
	Star312 - direction
	Planet313 - direction
	Planet314 - direction
	Planet315 - direction
	Planet316 - direction
	Phenomenon317 - direction
	Planet318 - direction
	Planet319 - direction
	Planet320 - direction
	Star321 - direction
	Star322 - direction
	Star323 - direction
	Phenomenon324 - direction
	Phenomenon325 - direction
	Phenomenon326 - direction
	Star327 - direction
	Planet328 - direction
	Star329 - direction
	Planet330 - direction
	Phenomenon331 - direction
	Planet332 - direction
	Star333 - direction
	Planet334 - direction
	Phenomenon335 - direction
	Planet336 - direction
	Planet337 - direction
	Star338 - direction
	Planet339 - direction
	Star340 - direction
	Star341 - direction
	Planet342 - direction
	Phenomenon343 - direction
	Star344 - direction
	Star345 - direction
	Planet346 - direction
	Planet347 - direction
	Star348 - direction
	Star349 - direction
	Phenomenon350 - direction
	Star351 - direction
	Phenomenon352 - direction
	Phenomenon353 - direction
	Star354 - direction
	Star355 - direction
	Planet356 - direction
	Planet357 - direction
	Planet358 - direction
	Star359 - direction
	Star360 - direction
	Planet361 - direction
	Star362 - direction
	Phenomenon363 - direction
	Star364 - direction
	Planet365 - direction
	Star366 - direction
	Phenomenon367 - direction
	Star368 - direction
	Star369 - direction
	Star370 - direction
	Planet371 - direction
	Planet372 - direction
	Star373 - direction
	Star374 - direction
	Planet375 - direction
	Planet376 - direction
	Star377 - direction
	Planet378 - direction
	Phenomenon379 - direction
	Planet380 - direction
	Planet381 - direction
	Star382 - direction
	Phenomenon383 - direction
	Planet384 - direction
	Phenomenon385 - direction
	Planet386 - direction
	Star387 - direction
	Planet388 - direction
	Star389 - direction
	Star390 - direction
	Planet391 - direction
	Star392 - direction
	Star393 - direction
	Star394 - direction
	Phenomenon395 - direction
	Star396 - direction
	Planet397 - direction
	Planet398 - direction
	Phenomenon399 - direction
	Phenomenon400 - direction
	Star401 - direction
	Star402 - direction
	Star403 - direction
	Phenomenon404 - direction
	Star405 - direction
	Phenomenon406 - direction
	Phenomenon407 - direction
	Planet408 - direction
	Phenomenon409 - direction
	Phenomenon410 - direction
	Star411 - direction
	Star412 - direction
	Planet413 - direction
	Planet414 - direction
	Phenomenon415 - direction
	Phenomenon416 - direction
	Planet417 - direction
	Star418 - direction
	Star419 - direction
	Phenomenon420 - direction
	Phenomenon421 - direction
	Planet422 - direction
	Planet423 - direction
	Star424 - direction
	Phenomenon425 - direction
	Planet426 - direction
	Phenomenon427 - direction
	Star428 - direction
	Phenomenon429 - direction
	Star430 - direction
	Star431 - direction
	Star432 - direction
	Planet433 - direction
	Star434 - direction
	Star435 - direction
	Phenomenon436 - direction
	Phenomenon437 - direction
	Phenomenon438 - direction
	Phenomenon439 - direction
	Star440 - direction
	Phenomenon441 - direction
	Star442 - direction
	Phenomenon443 - direction
	Star444 - direction
	Star445 - direction
	Phenomenon446 - direction
	Star447 - direction
	Planet448 - direction
	Phenomenon449 - direction
	Star450 - direction
	Phenomenon451 - direction
	Star452 - direction
	Phenomenon453 - direction
	Star454 - direction
	Planet455 - direction
)
(:init
	(supports instrument0 image0)
	(supports instrument0 infrared3)
	(supports instrument0 thermograph1)
	(calibration_target instrument0 GroundStation67)
	(calibration_target instrument0 GroundStation135)
	(calibration_target instrument0 GroundStation29)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation82)
	(calibration_target instrument0 GroundStation154)
	(calibration_target instrument0 GroundStation35)
	(calibration_target instrument0 GroundStation47)
	(calibration_target instrument0 Star148)
	(calibration_target instrument0 GroundStation184)
	(calibration_target instrument0 GroundStation17)
	(calibration_target instrument0 Star73)
	(calibration_target instrument0 Star130)
	(calibration_target instrument0 GroundStation0)
	(calibration_target instrument0 Star175)
	(calibration_target instrument0 GroundStation112)
	(calibration_target instrument0 GroundStation183)
	(calibration_target instrument0 Star83)
	(calibration_target instrument0 GroundStation206)
	(calibration_target instrument0 Star108)
	(calibration_target instrument0 GroundStation101)
	(calibration_target instrument0 GroundStation212)
	(calibration_target instrument0 GroundStation202)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation22)
	(calibration_target instrument0 Star11)
	(calibration_target instrument0 Star173)
	(calibration_target instrument0 Star209)
	(calibration_target instrument0 Star197)
	(calibration_target instrument0 GroundStation75)
	(calibration_target instrument0 Star146)
	(calibration_target instrument0 GroundStation40)
	(calibration_target instrument0 Star210)
	(calibration_target instrument0 GroundStation176)
	(calibration_target instrument0 Star45)
	(calibration_target instrument0 Star63)
	(calibration_target instrument0 Star103)
	(calibration_target instrument0 GroundStation80)
	(calibration_target instrument0 Star110)
	(calibration_target instrument0 Star23)
	(calibration_target instrument0 Star34)
	(calibration_target instrument0 GroundStation127)
	(calibration_target instrument0 GroundStation94)
	(calibration_target instrument0 GroundStation163)
	(calibration_target instrument0 GroundStation128)
	(calibration_target instrument0 Star39)
	(calibration_target instrument0 GroundStation49)
	(calibration_target instrument0 GroundStation85)
	(calibration_target instrument0 GroundStation121)
	(calibration_target instrument0 GroundStation21)
	(calibration_target instrument0 GroundStation190)
	(calibration_target instrument0 Star219)
	(calibration_target instrument0 Star4)
	(calibration_target instrument0 Star164)
	(calibration_target instrument0 Star224)
	(calibration_target instrument0 Star27)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet248)
	(supports instrument1 spectrograph5)
	(calibration_target instrument1 GroundStation26)
	(calibration_target instrument1 Star153)
	(calibration_target instrument1 GroundStation58)
	(calibration_target instrument1 Star45)
	(calibration_target instrument1 GroundStation68)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star209)
	(calibration_target instrument1 GroundStation163)
	(calibration_target instrument1 Star56)
	(calibration_target instrument1 Star191)
	(calibration_target instrument1 Star123)
	(calibration_target instrument1 Star4)
	(calibration_target instrument1 Star199)
	(calibration_target instrument1 GroundStation114)
	(calibration_target instrument1 GroundStation165)
	(calibration_target instrument1 GroundStation159)
	(calibration_target instrument1 Star197)
	(calibration_target instrument1 Star203)
	(calibration_target instrument1 Star170)
	(calibration_target instrument1 Star134)
	(calibration_target instrument1 Star79)
	(calibration_target instrument1 GroundStation186)
	(calibration_target instrument1 GroundStation2)
	(calibration_target instrument1 Star96)
	(on_board instrument1 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation172)
	(supports instrument2 spectrograph2)
	(calibration_target instrument2 GroundStation207)
	(calibration_target instrument2 GroundStation62)
	(calibration_target instrument2 GroundStation186)
	(calibration_target instrument2 GroundStation172)
	(calibration_target instrument2 GroundStation38)
	(calibration_target instrument2 GroundStation195)
	(calibration_target instrument2 Star201)
	(calibration_target instrument2 GroundStation154)
	(calibration_target instrument2 Star150)
	(calibration_target instrument2 GroundStation190)
	(calibration_target instrument2 GroundStation178)
	(calibration_target instrument2 GroundStation51)
	(calibration_target instrument2 Star4)
	(calibration_target instrument2 GroundStation212)
	(calibration_target instrument2 Star77)
	(calibration_target instrument2 GroundStation68)
	(calibration_target instrument2 Star110)
	(calibration_target instrument2 GroundStation222)
	(calibration_target instrument2 Star185)
	(calibration_target instrument2 Star72)
	(calibration_target instrument2 GroundStation163)
	(calibration_target instrument2 GroundStation22)
	(calibration_target instrument2 GroundStation86)
	(calibration_target instrument2 Star39)
	(calibration_target instrument2 GroundStation100)
	(calibration_target instrument2 GroundStation47)
	(calibration_target instrument2 Star155)
	(calibration_target instrument2 GroundStation32)
	(calibration_target instrument2 GroundStation82)
	(calibration_target instrument2 Star11)
	(calibration_target instrument2 Star83)
	(calibration_target instrument2 Star156)
	(calibration_target instrument2 Star56)
	(calibration_target instrument2 GroundStation49)
	(calibration_target instrument2 GroundStation58)
	(calibration_target instrument2 GroundStation20)
	(calibration_target instrument2 GroundStation104)
	(calibration_target instrument2 GroundStation188)
	(calibration_target instrument2 Star197)
	(calibration_target instrument2 Star34)
	(calibration_target instrument2 Star89)
	(calibration_target instrument2 GroundStation145)
	(calibration_target instrument2 GroundStation5)
	(calibration_target instrument2 Star69)
	(calibration_target instrument2 GroundStation92)
	(calibration_target instrument2 GroundStation37)
	(calibration_target instrument2 Star64)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 Star103)
	(calibration_target instrument2 GroundStation128)
	(calibration_target instrument2 Star78)
	(calibration_target instrument2 GroundStation121)
	(calibration_target instrument2 GroundStation174)
	(calibration_target instrument2 Star144)
	(calibration_target instrument2 Star143)
	(calibration_target instrument2 GroundStation183)
	(supports instrument3 spectrograph5)
	(supports instrument3 infrared4)
	(supports instrument3 thermograph1)
	(calibration_target instrument3 Star61)
	(calibration_target instrument3 Star219)
	(calibration_target instrument3 GroundStation40)
	(calibration_target instrument3 GroundStation31)
	(calibration_target instrument3 GroundStation90)
	(calibration_target instrument3 Star199)
	(calibration_target instrument3 Star153)
	(calibration_target instrument3 GroundStation217)
	(calibration_target instrument3 Star27)
	(calibration_target instrument3 GroundStation100)
	(calibration_target instrument3 GroundStation211)
	(calibration_target instrument3 Star52)
	(calibration_target instrument3 Star89)
	(calibration_target instrument3 Star170)
	(calibration_target instrument3 Star166)
	(supports instrument4 spectrograph2)
	(calibration_target instrument4 Star103)
	(calibration_target instrument4 GroundStation220)
	(calibration_target instrument4 Star110)
	(calibration_target instrument4 GroundStation204)
	(calibration_target instrument4 GroundStation107)
	(calibration_target instrument4 Star161)
	(calibration_target instrument4 GroundStation90)
	(calibration_target instrument4 Star53)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 Star43)
	(calibration_target instrument4 GroundStation186)
	(calibration_target instrument4 Star210)
	(calibration_target instrument4 GroundStation221)
	(calibration_target instrument4 GroundStation98)
	(calibration_target instrument4 Star27)
	(calibration_target instrument4 Star140)
	(calibration_target instrument4 Star158)
	(calibration_target instrument4 Star83)
	(calibration_target instrument4 Star14)
	(calibration_target instrument4 GroundStation154)
	(calibration_target instrument4 Star199)
	(calibration_target instrument4 GroundStation33)
	(calibration_target instrument4 GroundStation76)
	(calibration_target instrument4 Star54)
	(calibration_target instrument4 Star48)
	(calibration_target instrument4 GroundStation59)
	(calibration_target instrument4 GroundStation177)
	(calibration_target instrument4 Star117)
	(calibration_target instrument4 Star126)
	(calibration_target instrument4 GroundStation188)
	(calibration_target instrument4 GroundStation190)
	(calibration_target instrument4 GroundStation40)
	(calibration_target instrument4 Star125)
	(calibration_target instrument4 Star69)
	(calibration_target instrument4 GroundStation208)
	(calibration_target instrument4 Star227)
	(calibration_target instrument4 GroundStation66)
	(calibration_target instrument4 GroundStation194)
	(calibration_target instrument4 Star130)
	(calibration_target instrument4 GroundStation100)
	(calibration_target instrument4 GroundStation94)
	(calibration_target instrument4 Star23)
	(calibration_target instrument4 Star63)
	(calibration_target instrument4 Star153)
	(calibration_target instrument4 GroundStation183)
	(calibration_target instrument4 Star225)
	(calibration_target instrument4 GroundStation137)
	(calibration_target instrument4 GroundStation24)
	(calibration_target instrument4 GroundStation138)
	(calibration_target instrument4 GroundStation152)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 Star131)
	(supports instrument5 image0)
	(calibration_target instrument5 GroundStation174)
	(calibration_target instrument5 GroundStation213)
	(calibration_target instrument5 Star151)
	(calibration_target instrument5 GroundStation215)
	(calibration_target instrument5 Star131)
	(calibration_target instrument5 GroundStation226)
	(calibration_target instrument5 GroundStation202)
	(calibration_target instrument5 Star197)
	(calibration_target instrument5 GroundStation5)
	(on_board instrument2 satellite2)
	(on_board instrument3 satellite2)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation13)
	(supports instrument6 spectrograph2)
	(calibration_target instrument6 Star224)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 Star151)
	(calibration_target instrument6 GroundStation98)
	(calibration_target instrument6 GroundStation127)
	(calibration_target instrument6 GroundStation142)
	(calibration_target instrument6 GroundStation157)
	(calibration_target instrument6 GroundStation93)
	(calibration_target instrument6 GroundStation32)
	(calibration_target instrument6 GroundStation178)
	(calibration_target instrument6 Star61)
	(calibration_target instrument6 GroundStation115)
	(calibration_target instrument6 Star78)
	(calibration_target instrument6 GroundStation68)
	(calibration_target instrument6 Star132)
	(calibration_target instrument6 GroundStation47)
	(calibration_target instrument6 Star56)
	(calibration_target instrument6 GroundStation118)
	(calibration_target instrument6 Star148)
	(calibration_target instrument6 GroundStation124)
	(calibration_target instrument6 GroundStation58)
	(calibration_target instrument6 GroundStation208)
	(calibration_target instrument6 GroundStation154)
	(calibration_target instrument6 Star179)
	(calibration_target instrument6 GroundStation202)
	(calibration_target instrument6 GroundStation65)
	(calibration_target instrument6 Star155)
	(calibration_target instrument6 Star69)
	(calibration_target instrument6 GroundStation101)
	(calibration_target instrument6 Star173)
	(calibration_target instrument6 GroundStation62)
	(calibration_target instrument6 GroundStation137)
	(calibration_target instrument6 Star175)
	(calibration_target instrument6 GroundStation195)
	(calibration_target instrument6 GroundStation212)
	(calibration_target instrument6 Star130)
	(calibration_target instrument6 Star43)
	(calibration_target instrument6 GroundStation221)
	(calibration_target instrument6 GroundStation22)
	(calibration_target instrument6 GroundStation114)
	(calibration_target instrument6 Star64)
	(calibration_target instrument6 Star185)
	(calibration_target instrument6 GroundStation207)
	(calibration_target instrument6 Star57)
	(calibration_target instrument6 GroundStation171)
	(calibration_target instrument6 GroundStation186)
	(calibration_target instrument6 GroundStation211)
	(calibration_target instrument6 Star14)
	(calibration_target instrument6 Star60)
	(calibration_target instrument6 GroundStation97)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 Star201)
	(calibration_target instrument6 Star103)
	(calibration_target instrument6 GroundStation5)
	(calibration_target instrument6 GroundStation220)
	(calibration_target instrument6 Star210)
	(calibration_target instrument6 GroundStation36)
	(calibration_target instrument6 Star144)
	(calibration_target instrument6 GroundStation31)
	(calibration_target instrument6 GroundStation35)
	(calibration_target instrument6 GroundStation204)
	(calibration_target instrument6 GroundStation75)
	(calibration_target instrument6 Star120)
	(calibration_target instrument6 GroundStation218)
	(calibration_target instrument6 Star50)
	(calibration_target instrument6 GroundStation177)
	(calibration_target instrument6 GroundStation99)
	(supports instrument7 image0)
	(supports instrument7 spectrograph5)
	(supports instrument7 infrared4)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star214)
	(calibration_target instrument7 Star83)
	(supports instrument8 infrared4)
	(supports instrument8 spectrograph2)
	(calibration_target instrument8 Star192)
	(calibration_target instrument8 Star4)
	(calibration_target instrument8 GroundStation212)
	(calibration_target instrument8 Star143)
	(calibration_target instrument8 GroundStation97)
	(calibration_target instrument8 Star73)
	(calibration_target instrument8 GroundStation176)
	(calibration_target instrument8 GroundStation101)
	(calibration_target instrument8 Star223)
	(calibration_target instrument8 GroundStation220)
	(calibration_target instrument8 GroundStation58)
	(calibration_target instrument8 GroundStation213)
	(calibration_target instrument8 GroundStation40)
	(calibration_target instrument8 GroundStation93)
	(calibration_target instrument8 GroundStation113)
	(calibration_target instrument8 Star109)
	(calibration_target instrument8 GroundStation5)
	(calibration_target instrument8 Star185)
	(calibration_target instrument8 GroundStation221)
	(calibration_target instrument8 Star96)
	(calibration_target instrument8 GroundStation195)
	(calibration_target instrument8 Star175)
	(calibration_target instrument8 GroundStation194)
	(calibration_target instrument8 GroundStation222)
	(calibration_target instrument8 Star166)
	(calibration_target instrument8 GroundStation172)
	(calibration_target instrument8 Star158)
	(calibration_target instrument8 GroundStation88)
	(calibration_target instrument8 GroundStation41)
	(calibration_target instrument8 Star196)
	(calibration_target instrument8 GroundStation62)
	(calibration_target instrument8 GroundStation80)
	(calibration_target instrument8 GroundStation177)
	(calibration_target instrument8 Star110)
	(calibration_target instrument8 GroundStation90)
	(calibration_target instrument8 GroundStation163)
	(calibration_target instrument8 Star214)
	(calibration_target instrument8 GroundStation178)
	(calibration_target instrument8 GroundStation67)
	(calibration_target instrument8 GroundStation193)
	(calibration_target instrument8 Star131)
	(calibration_target instrument8 GroundStation182)
	(calibration_target instrument8 Star61)
	(calibration_target instrument8 Star146)
	(calibration_target instrument8 GroundStation141)
	(calibration_target instrument8 GroundStation70)
	(calibration_target instrument8 GroundStation92)
	(calibration_target instrument8 GroundStation115)
	(calibration_target instrument8 Star179)
	(calibration_target instrument8 Star189)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 Star120)
	(calibration_target instrument8 GroundStation71)
	(calibration_target instrument8 Star173)
	(calibration_target instrument8 GroundStation167)
	(calibration_target instrument8 Star227)
	(calibration_target instrument8 Star191)
	(supports instrument9 thermograph1)
	(calibration_target instrument9 Star189)
	(calibration_target instrument9 GroundStation154)
	(calibration_target instrument9 GroundStation226)
	(calibration_target instrument9 Star91)
	(calibration_target instrument9 Star144)
	(calibration_target instrument9 Star173)
	(calibration_target instrument9 Star185)
	(calibration_target instrument9 Star168)
	(calibration_target instrument9 Star61)
	(calibration_target instrument9 Star143)
	(calibration_target instrument9 GroundStation111)
	(calibration_target instrument9 GroundStation147)
	(calibration_target instrument9 GroundStation159)
	(calibration_target instrument9 Star77)
	(calibration_target instrument9 GroundStation87)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 GroundStation186)
	(calibration_target instrument9 GroundStation88)
	(calibration_target instrument9 GroundStation136)
	(calibration_target instrument9 GroundStation162)
	(calibration_target instrument9 GroundStation142)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation38)
	(calibration_target instrument9 GroundStation99)
	(calibration_target instrument9 GroundStation157)
	(calibration_target instrument9 Star197)
	(calibration_target instrument9 GroundStation171)
	(calibration_target instrument9 GroundStation92)
	(calibration_target instrument9 Star132)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation51)
	(supports instrument10 spectrograph2)
	(calibration_target instrument10 GroundStation114)
	(calibration_target instrument10 GroundStation182)
	(calibration_target instrument10 Star179)
	(calibration_target instrument10 GroundStation19)
	(calibration_target instrument10 Star189)
	(calibration_target instrument10 GroundStation106)
	(calibration_target instrument10 GroundStation172)
	(calibration_target instrument10 GroundStation98)
	(calibration_target instrument10 Star43)
	(calibration_target instrument10 GroundStation204)
	(calibration_target instrument10 GroundStation99)
	(calibration_target instrument10 GroundStation87)
	(calibration_target instrument10 Star52)
	(calibration_target instrument10 GroundStation104)
	(calibration_target instrument10 Star16)
	(calibration_target instrument10 GroundStation111)
	(calibration_target instrument10 GroundStation44)
	(calibration_target instrument10 Star224)
	(calibration_target instrument10 GroundStation37)
	(calibration_target instrument10 GroundStation217)
	(calibration_target instrument10 GroundStation92)
	(calibration_target instrument10 Star23)
	(calibration_target instrument10 Star89)
	(calibration_target instrument10 GroundStation162)
	(calibration_target instrument10 Star191)
	(calibration_target instrument10 GroundStation93)
	(calibration_target instrument10 GroundStation188)
	(calibration_target instrument10 GroundStation68)
	(calibration_target instrument10 GroundStation171)
	(calibration_target instrument10 Star77)
	(calibration_target instrument10 Star74)
	(calibration_target instrument10 GroundStation76)
	(calibration_target instrument10 GroundStation127)
	(supports instrument11 thermograph1)
	(supports instrument11 infrared3)
	(calibration_target instrument11 GroundStation119)
	(calibration_target instrument11 Star77)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 GroundStation174)
	(calibration_target instrument11 Star179)
	(calibration_target instrument11 GroundStation215)
	(calibration_target instrument11 GroundStation38)
	(calibration_target instrument11 GroundStation102)
	(calibration_target instrument11 Star16)
	(calibration_target instrument11 GroundStation136)
	(calibration_target instrument11 Star161)
	(calibration_target instrument11 GroundStation186)
	(calibration_target instrument11 GroundStation195)
	(calibration_target instrument11 GroundStation21)
	(calibration_target instrument11 GroundStation10)
	(calibration_target instrument11 GroundStation208)
	(calibration_target instrument11 Star56)
	(calibration_target instrument11 Star84)
	(calibration_target instrument11 GroundStation212)
	(calibration_target instrument11 Star227)
	(calibration_target instrument11 Star189)
	(calibration_target instrument11 GroundStation111)
	(calibration_target instrument11 GroundStation80)
	(calibration_target instrument11 GroundStation100)
	(calibration_target instrument11 GroundStation97)
	(calibration_target instrument11 Star64)
	(calibration_target instrument11 Star123)
	(calibration_target instrument11 GroundStation8)
	(calibration_target instrument11 GroundStation184)
	(calibration_target instrument11 Star225)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 GroundStation49)
	(calibration_target instrument11 Star134)
	(calibration_target instrument11 GroundStation87)
	(calibration_target instrument11 GroundStation41)
	(calibration_target instrument11 GroundStation2)
	(calibration_target instrument11 Star48)
	(calibration_target instrument11 Star46)
	(calibration_target instrument11 GroundStation20)
	(calibration_target instrument11 GroundStation24)
	(calibration_target instrument11 GroundStation82)
	(calibration_target instrument11 Star158)
	(calibration_target instrument11 GroundStation198)
	(calibration_target instrument11 GroundStation98)
	(calibration_target instrument11 GroundStation147)
	(calibration_target instrument11 Star164)
	(calibration_target instrument11 Star155)
	(calibration_target instrument11 Star117)
	(calibration_target instrument11 Star203)
	(calibration_target instrument11 Star72)
	(calibration_target instrument11 GroundStation37)
	(calibration_target instrument11 GroundStation29)
	(calibration_target instrument11 Star45)
	(calibration_target instrument11 Star131)
	(calibration_target instrument11 Star151)
	(calibration_target instrument11 GroundStation182)
	(calibration_target instrument11 Star169)
	(calibration_target instrument11 Star73)
	(supports instrument12 infrared3)
	(calibration_target instrument12 Star64)
	(calibration_target instrument12 Star117)
	(calibration_target instrument12 GroundStation82)
	(calibration_target instrument12 Star72)
	(calibration_target instrument12 GroundStation6)
	(calibration_target instrument12 Star3)
	(calibration_target instrument12 Star179)
	(calibration_target instrument12 Star23)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 Star185)
	(calibration_target instrument12 GroundStation198)
	(calibration_target instrument12 Star149)
	(calibration_target instrument12 Star15)
	(calibration_target instrument12 Star164)
	(calibration_target instrument12 GroundStation102)
	(calibration_target instrument12 Star169)
	(calibration_target instrument12 GroundStation37)
	(calibration_target instrument12 GroundStation19)
	(calibration_target instrument12 GroundStation44)
	(calibration_target instrument12 GroundStation208)
	(calibration_target instrument12 GroundStation174)
	(calibration_target instrument12 GroundStation190)
	(calibration_target instrument12 GroundStation118)
	(calibration_target instrument12 Star225)
	(calibration_target instrument12 Star54)
	(supports instrument13 infrared4)
	(supports instrument13 spectrograph2)
	(calibration_target instrument13 Star153)
	(calibration_target instrument13 GroundStation10)
	(calibration_target instrument13 GroundStation138)
	(calibration_target instrument13 Star77)
	(calibration_target instrument13 GroundStation66)
	(calibration_target instrument13 Star43)
	(calibration_target instrument13 Star126)
	(calibration_target instrument13 Star169)
	(calibration_target instrument13 Star105)
	(calibration_target instrument13 Star83)
	(calibration_target instrument13 Star166)
	(calibration_target instrument13 GroundStation183)
	(calibration_target instrument13 GroundStation99)
	(calibration_target instrument13 Star161)
	(calibration_target instrument13 GroundStation202)
	(calibration_target instrument13 GroundStation204)
	(calibration_target instrument13 GroundStation7)
	(calibration_target instrument13 GroundStation17)
	(calibration_target instrument13 GroundStation220)
	(calibration_target instrument13 Star9)
	(calibration_target instrument13 GroundStation44)
	(calibration_target instrument13 GroundStation128)
	(calibration_target instrument13 Star144)
	(calibration_target instrument13 GroundStation5)
	(calibration_target instrument13 GroundStation226)
	(calibration_target instrument13 Star149)
	(calibration_target instrument13 GroundStation184)
	(calibration_target instrument13 GroundStation6)
	(calibration_target instrument13 GroundStation35)
	(calibration_target instrument13 GroundStation124)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation221)
	(calibration_target instrument13 GroundStation51)
	(calibration_target instrument13 Star3)
	(calibration_target instrument13 GroundStation32)
	(calibration_target instrument13 GroundStation193)
	(calibration_target instrument13 GroundStation92)
	(calibration_target instrument13 Star91)
	(calibration_target instrument13 Star130)
	(calibration_target instrument13 Star45)
	(calibration_target instrument13 Star23)
	(calibration_target instrument13 GroundStation97)
	(calibration_target instrument13 GroundStation190)
	(calibration_target instrument13 GroundStation188)
	(calibration_target instrument13 Star89)
	(calibration_target instrument13 Star27)
	(calibration_target instrument13 Star14)
	(calibration_target instrument13 Star129)
	(calibration_target instrument13 GroundStation71)
	(calibration_target instrument13 GroundStation212)
	(calibration_target instrument13 Star139)
	(calibration_target instrument13 Star103)
	(calibration_target instrument13 GroundStation82)
	(calibration_target instrument13 GroundStation162)
	(calibration_target instrument13 Star134)
	(calibration_target instrument13 Star4)
	(calibration_target instrument13 Star168)
	(calibration_target instrument13 GroundStation142)
	(calibration_target instrument13 Star132)
	(calibration_target instrument13 GroundStation215)
	(calibration_target instrument13 GroundStation37)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star189)
	(supports instrument14 infrared4)
	(calibration_target instrument14 Star4)
	(calibration_target instrument14 GroundStation163)
	(calibration_target instrument14 Star199)
	(calibration_target instrument14 GroundStation220)
	(supports instrument15 image0)
	(supports instrument15 spectrograph5)
	(calibration_target instrument15 Star108)
	(calibration_target instrument15 GroundStation160)
	(calibration_target instrument15 Star64)
	(calibration_target instrument15 Star146)
	(calibration_target instrument15 Star16)
	(calibration_target instrument15 GroundStation135)
	(calibration_target instrument15 GroundStation93)
	(calibration_target instrument15 Star191)
	(calibration_target instrument15 Star34)
	(supports instrument16 thermograph1)
	(calibration_target instrument16 GroundStation159)
	(calibration_target instrument16 GroundStation85)
	(calibration_target instrument16 Star34)
	(calibration_target instrument16 Star156)
	(calibration_target instrument16 Star55)
	(calibration_target instrument16 Star109)
	(calibration_target instrument16 Star130)
	(calibration_target instrument16 Star12)
	(calibration_target instrument16 GroundStation24)
	(calibration_target instrument16 GroundStation99)
	(calibration_target instrument16 GroundStation213)
	(calibration_target instrument16 Star227)
	(calibration_target instrument16 Star52)
	(calibration_target instrument16 GroundStation0)
	(calibration_target instrument16 GroundStation31)
	(calibration_target instrument16 Star168)
	(calibration_target instrument16 GroundStation86)
	(calibration_target instrument16 Star72)
	(calibration_target instrument16 GroundStation6)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 Star197)
	(supports instrument17 infrared3)
	(supports instrument17 thermograph1)
	(supports instrument17 infrared4)
	(calibration_target instrument17 GroundStation41)
	(calibration_target instrument17 Star227)
	(calibration_target instrument17 GroundStation138)
	(calibration_target instrument17 Star14)
	(calibration_target instrument17 GroundStation92)
	(calibration_target instrument17 Star169)
	(calibration_target instrument17 Star30)
	(calibration_target instrument17 Star16)
	(calibration_target instrument17 Star91)
	(calibration_target instrument17 GroundStation136)
	(calibration_target instrument17 Star148)
	(calibration_target instrument17 Star77)
	(calibration_target instrument17 GroundStation49)
	(calibration_target instrument17 GroundStation82)
	(calibration_target instrument17 Star52)
	(calibration_target instrument17 Star225)
	(calibration_target instrument17 Star39)
	(calibration_target instrument17 GroundStation13)
	(calibration_target instrument17 GroundStation104)
	(calibration_target instrument17 Star83)
	(calibration_target instrument17 GroundStation222)
	(calibration_target instrument17 Star53)
	(calibration_target instrument17 Star64)
	(calibration_target instrument17 GroundStation183)
	(calibration_target instrument17 Star46)
	(calibration_target instrument17 Star117)
	(calibration_target instrument17 Star189)
	(calibration_target instrument17 GroundStation111)
	(calibration_target instrument17 GroundStation147)
	(calibration_target instrument17 Star168)
	(calibration_target instrument17 Star61)
	(calibration_target instrument17 GroundStation85)
	(calibration_target instrument17 Star199)
	(calibration_target instrument17 GroundStation47)
	(calibration_target instrument17 Star103)
	(calibration_target instrument17 GroundStation174)
	(calibration_target instrument17 Star79)
	(calibration_target instrument17 Star27)
	(calibration_target instrument17 Star203)
	(calibration_target instrument17 GroundStation204)
	(calibration_target instrument17 GroundStation65)
	(calibration_target instrument17 GroundStation32)
	(calibration_target instrument17 GroundStation162)
	(calibration_target instrument17 GroundStation226)
	(calibration_target instrument17 GroundStation88)
	(calibration_target instrument17 GroundStation102)
	(calibration_target instrument17 GroundStation40)
	(calibration_target instrument17 GroundStation20)
	(calibration_target instrument17 Star1)
	(calibration_target instrument17 Star9)
	(calibration_target instrument17 GroundStation113)
	(calibration_target instrument17 GroundStation90)
	(calibration_target instrument17 Star109)
	(calibration_target instrument17 Star69)
	(calibration_target instrument17 GroundStation152)
	(calibration_target instrument17 Star151)
	(calibration_target instrument17 Star146)
	(calibration_target instrument17 Star89)
	(calibration_target instrument17 GroundStation81)
	(calibration_target instrument17 Star143)
	(calibration_target instrument17 Star185)
	(calibration_target instrument17 GroundStation171)
	(calibration_target instrument17 Star197)
	(calibration_target instrument17 Star48)
	(calibration_target instrument17 GroundStation188)
	(calibration_target instrument17 Star187)
	(supports instrument18 infrared3)
	(supports instrument18 spectrograph5)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 Star155)
	(calibration_target instrument18 GroundStation100)
	(calibration_target instrument18 Star153)
	(calibration_target instrument18 GroundStation24)
	(calibration_target instrument18 GroundStation198)
	(calibration_target instrument18 Star30)
	(calibration_target instrument18 GroundStation135)
	(calibration_target instrument18 Star89)
	(calibration_target instrument18 GroundStation58)
	(calibration_target instrument18 GroundStation97)
	(calibration_target instrument18 Star54)
	(calibration_target instrument18 Star227)
	(calibration_target instrument18 Star201)
	(calibration_target instrument18 GroundStation207)
	(calibration_target instrument18 Star60)
	(calibration_target instrument18 Star180)
	(calibration_target instrument18 GroundStation0)
	(supports instrument19 infrared3)
	(supports instrument19 spectrograph5)
	(supports instrument19 infrared4)
	(calibration_target instrument19 GroundStation101)
	(calibration_target instrument19 GroundStation136)
	(calibration_target instrument19 Star181)
	(calibration_target instrument19 Star223)
	(calibration_target instrument19 GroundStation165)
	(calibration_target instrument19 GroundStation194)
	(calibration_target instrument19 GroundStation142)
	(calibration_target instrument19 GroundStation94)
	(calibration_target instrument19 Star148)
	(calibration_target instrument19 GroundStation188)
	(calibration_target instrument19 GroundStation99)
	(calibration_target instrument19 GroundStation127)
	(calibration_target instrument19 GroundStation7)
	(calibration_target instrument19 GroundStation76)
	(calibration_target instrument19 GroundStation152)
	(calibration_target instrument19 GroundStation19)
	(calibration_target instrument19 Star3)
	(calibration_target instrument19 GroundStation59)
	(calibration_target instrument19 GroundStation177)
	(calibration_target instrument19 Star187)
	(calibration_target instrument19 GroundStation222)
	(calibration_target instrument19 Star74)
	(calibration_target instrument19 Star200)
	(calibration_target instrument19 GroundStation41)
	(calibration_target instrument19 GroundStation90)
	(calibration_target instrument19 GroundStation216)
	(calibration_target instrument19 GroundStation81)
	(calibration_target instrument19 GroundStation163)
	(calibration_target instrument19 Star116)
	(calibration_target instrument19 GroundStation121)
	(calibration_target instrument19 GroundStation70)
	(calibration_target instrument19 GroundStation106)
	(calibration_target instrument19 GroundStation58)
	(calibration_target instrument19 Star175)
	(calibration_target instrument19 Star161)
	(calibration_target instrument19 Star95)
	(calibration_target instrument19 GroundStation193)
	(calibration_target instrument19 Star60)
	(calibration_target instrument19 GroundStation75)
	(calibration_target instrument19 GroundStation21)
	(calibration_target instrument19 Star72)
	(calibration_target instrument19 GroundStation204)
	(calibration_target instrument19 GroundStation31)
	(calibration_target instrument19 GroundStation33)
	(calibration_target instrument19 Star155)
	(calibration_target instrument19 GroundStation182)
	(calibration_target instrument19 GroundStation5)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Phenomenon443)
	(supports instrument20 spectrograph5)
	(calibration_target instrument20 GroundStation141)
	(calibration_target instrument20 GroundStation124)
	(calibration_target instrument20 GroundStation41)
	(calibration_target instrument20 GroundStation66)
	(calibration_target instrument20 GroundStation213)
	(calibration_target instrument20 Star125)
	(calibration_target instrument20 GroundStation36)
	(calibration_target instrument20 GroundStation195)
	(calibration_target instrument20 GroundStation2)
	(calibration_target instrument20 GroundStation25)
	(calibration_target instrument20 GroundStation205)
	(calibration_target instrument20 Star153)
	(calibration_target instrument20 Star170)
	(supports instrument21 thermograph1)
	(calibration_target instrument21 GroundStation70)
	(calibration_target instrument21 GroundStation128)
	(calibration_target instrument21 GroundStation163)
	(calibration_target instrument21 GroundStation217)
	(calibration_target instrument21 GroundStation119)
	(calibration_target instrument21 GroundStation38)
	(calibration_target instrument21 GroundStation82)
	(calibration_target instrument21 GroundStation35)
	(calibration_target instrument21 GroundStation44)
	(calibration_target instrument21 GroundStation142)
	(calibration_target instrument21 Star180)
	(calibration_target instrument21 GroundStation17)
	(calibration_target instrument21 GroundStation101)
	(calibration_target instrument21 Star146)
	(calibration_target instrument21 Star108)
	(calibration_target instrument21 GroundStation220)
	(calibration_target instrument21 Star187)
	(calibration_target instrument21 GroundStation51)
	(calibration_target instrument21 Star69)
	(calibration_target instrument21 Star219)
	(calibration_target instrument21 GroundStation133)
	(calibration_target instrument21 Star53)
	(calibration_target instrument21 GroundStation85)
	(calibration_target instrument21 Star139)
	(calibration_target instrument21 Star12)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 GroundStation145)
	(calibration_target instrument21 GroundStation195)
	(calibration_target instrument21 Star197)
	(calibration_target instrument21 GroundStation87)
	(calibration_target instrument21 Star91)
	(calibration_target instrument21 Star56)
	(calibration_target instrument21 Star117)
	(calibration_target instrument21 GroundStation113)
	(calibration_target instrument21 GroundStation159)
	(calibration_target instrument21 Star200)
	(calibration_target instrument21 GroundStation24)
	(calibration_target instrument21 Star210)
	(calibration_target instrument21 GroundStation157)
	(calibration_target instrument21 GroundStation107)
	(calibration_target instrument21 GroundStation124)
	(calibration_target instrument21 Star3)
	(calibration_target instrument21 Star130)
	(calibration_target instrument21 Star223)
	(calibration_target instrument21 Star45)
	(calibration_target instrument21 Star116)
	(calibration_target instrument21 GroundStation71)
	(calibration_target instrument21 Star224)
	(calibration_target instrument21 Star192)
	(calibration_target instrument21 GroundStation193)
	(calibration_target instrument21 GroundStation186)
	(calibration_target instrument21 GroundStation114)
	(calibration_target instrument21 GroundStation86)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Planet380)
	(supports instrument22 thermograph1)
	(supports instrument22 spectrograph2)
	(calibration_target instrument22 GroundStation135)
	(calibration_target instrument22 GroundStation226)
	(calibration_target instrument22 GroundStation100)
	(calibration_target instrument22 GroundStation38)
	(calibration_target instrument22 GroundStation112)
	(calibration_target instrument22 GroundStation177)
	(calibration_target instrument22 GroundStation124)
	(calibration_target instrument22 GroundStation5)
	(calibration_target instrument22 GroundStation178)
	(calibration_target instrument22 Star155)
	(calibration_target instrument22 Star61)
	(calibration_target instrument22 GroundStation213)
	(calibration_target instrument22 GroundStation51)
	(calibration_target instrument22 GroundStation94)
	(calibration_target instrument22 GroundStation141)
	(calibration_target instrument22 GroundStation142)
	(calibration_target instrument22 Star9)
	(calibration_target instrument22 GroundStation28)
	(supports instrument23 infrared4)
	(calibration_target instrument23 Star48)
	(calibration_target instrument23 Star146)
	(calibration_target instrument23 GroundStation205)
	(calibration_target instrument23 GroundStation211)
	(calibration_target instrument23 Star117)
	(calibration_target instrument23 Star79)
	(calibration_target instrument23 GroundStation10)
	(calibration_target instrument23 Star223)
	(calibration_target instrument23 GroundStation71)
	(calibration_target instrument23 Star139)
	(calibration_target instrument23 Star69)
	(calibration_target instrument23 GroundStation62)
	(calibration_target instrument23 GroundStation76)
	(calibration_target instrument23 GroundStation206)
	(calibration_target instrument23 Star110)
	(calibration_target instrument23 Star42)
	(calibration_target instrument23 Star1)
	(calibration_target instrument23 GroundStation80)
	(calibration_target instrument23 GroundStation142)
	(calibration_target instrument23 GroundStation176)
	(supports instrument24 thermograph1)
	(supports instrument24 spectrograph2)
	(supports instrument24 spectrograph5)
	(calibration_target instrument24 GroundStation119)
	(calibration_target instrument24 Star95)
	(calibration_target instrument24 Star63)
	(calibration_target instrument24 Star117)
	(calibration_target instrument24 GroundStation0)
	(calibration_target instrument24 Star158)
	(calibration_target instrument24 GroundStation154)
	(calibration_target instrument24 GroundStation186)
	(calibration_target instrument24 Star126)
	(calibration_target instrument24 GroundStation159)
	(calibration_target instrument24 GroundStation121)
	(calibration_target instrument24 GroundStation124)
	(calibration_target instrument24 GroundStation217)
	(calibration_target instrument24 GroundStation172)
	(calibration_target instrument24 GroundStation87)
	(calibration_target instrument24 Star43)
	(calibration_target instrument24 GroundStation80)
	(calibration_target instrument24 GroundStation226)
	(calibration_target instrument24 GroundStation204)
	(calibration_target instrument24 Star52)
	(calibration_target instrument24 Star123)
	(calibration_target instrument24 GroundStation152)
	(calibration_target instrument24 Star109)
	(calibration_target instrument24 GroundStation212)
	(calibration_target instrument24 Star39)
	(calibration_target instrument24 GroundStation176)
	(calibration_target instrument24 GroundStation137)
	(calibration_target instrument24 Star214)
	(calibration_target instrument24 GroundStation36)
	(calibration_target instrument24 GroundStation19)
	(calibration_target instrument24 Star219)
	(calibration_target instrument24 Star201)
	(calibration_target instrument24 Star173)
	(calibration_target instrument24 GroundStation17)
	(calibration_target instrument24 GroundStation92)
	(calibration_target instrument24 GroundStation216)
	(calibration_target instrument24 Star110)
	(calibration_target instrument24 Star175)
	(calibration_target instrument24 Star149)
	(calibration_target instrument24 Star179)
	(calibration_target instrument24 Star55)
	(calibration_target instrument24 GroundStation195)
	(calibration_target instrument24 Star50)
	(calibration_target instrument24 GroundStation67)
	(calibration_target instrument24 GroundStation94)
	(calibration_target instrument24 GroundStation220)
	(calibration_target instrument24 GroundStation162)
	(calibration_target instrument24 GroundStation133)
	(calibration_target instrument24 Star45)
	(calibration_target instrument24 GroundStation82)
	(calibration_target instrument24 GroundStation221)
	(calibration_target instrument24 GroundStation70)
	(calibration_target instrument24 Star64)
	(on_board instrument22 satellite8)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Planet242)
	(supports instrument25 spectrograph5)
	(supports instrument25 thermograph1)
	(supports instrument25 infrared4)
	(calibration_target instrument25 Star146)
	(calibration_target instrument25 GroundStation101)
	(calibration_target instrument25 GroundStation206)
	(calibration_target instrument25 GroundStation71)
	(calibration_target instrument25 GroundStation160)
	(calibration_target instrument25 Star16)
	(calibration_target instrument25 GroundStation171)
	(calibration_target instrument25 GroundStation2)
	(calibration_target instrument25 Star72)
	(calibration_target instrument25 Star53)
	(calibration_target instrument25 Star96)
	(calibration_target instrument25 Star149)
	(calibration_target instrument25 GroundStation188)
	(calibration_target instrument25 Star134)
	(calibration_target instrument25 GroundStation220)
	(calibration_target instrument25 Star11)
	(calibration_target instrument25 Star74)
	(calibration_target instrument25 Star77)
	(calibration_target instrument25 GroundStation33)
	(calibration_target instrument25 Star50)
	(calibration_target instrument25 Star151)
	(calibration_target instrument25 Star110)
	(calibration_target instrument25 Star57)
	(calibration_target instrument25 Star23)
	(calibration_target instrument25 GroundStation6)
	(calibration_target instrument25 Star14)
	(calibration_target instrument25 GroundStation121)
	(calibration_target instrument25 GroundStation17)
	(calibration_target instrument25 GroundStation190)
	(calibration_target instrument25 GroundStation163)
	(calibration_target instrument25 GroundStation145)
	(calibration_target instrument25 Star123)
	(calibration_target instrument25 Star203)
	(calibration_target instrument25 GroundStation104)
	(calibration_target instrument25 GroundStation51)
	(calibration_target instrument25 GroundStation7)
	(calibration_target instrument25 GroundStation28)
	(calibration_target instrument25 Star201)
	(calibration_target instrument25 Star43)
	(calibration_target instrument25 GroundStation26)
	(calibration_target instrument25 Star148)
	(calibration_target instrument25 GroundStation119)
	(calibration_target instrument25 GroundStation216)
	(calibration_target instrument25 Star109)
	(calibration_target instrument25 GroundStation37)
	(calibration_target instrument25 GroundStation128)
	(calibration_target instrument25 GroundStation80)
	(calibration_target instrument25 GroundStation107)
	(calibration_target instrument25 Star126)
	(calibration_target instrument25 Star46)
	(calibration_target instrument25 Star89)
	(calibration_target instrument25 Star105)
	(calibration_target instrument25 Star15)
	(calibration_target instrument25 Star161)
	(calibration_target instrument25 GroundStation49)
	(calibration_target instrument25 GroundStation13)
	(calibration_target instrument25 GroundStation76)
	(supports instrument26 infrared4)
	(supports instrument26 infrared3)
	(calibration_target instrument26 Star199)
	(calibration_target instrument26 Star84)
	(calibration_target instrument26 Star191)
	(calibration_target instrument26 GroundStation217)
	(calibration_target instrument26 GroundStation7)
	(calibration_target instrument26 Star30)
	(calibration_target instrument26 GroundStation2)
	(calibration_target instrument26 GroundStation186)
	(calibration_target instrument26 Star200)
	(calibration_target instrument26 Star179)
	(calibration_target instrument26 GroundStation20)
	(calibration_target instrument26 Star227)
	(calibration_target instrument26 Star139)
	(calibration_target instrument26 Star73)
	(calibration_target instrument26 GroundStation49)
	(calibration_target instrument26 Star143)
	(calibration_target instrument26 GroundStation85)
	(calibration_target instrument26 GroundStation107)
	(calibration_target instrument26 Star125)
	(calibration_target instrument26 GroundStation113)
	(calibration_target instrument26 Star16)
	(calibration_target instrument26 GroundStation29)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 GroundStation58)
	(calibration_target instrument26 GroundStation94)
	(calibration_target instrument26 GroundStation147)
	(calibration_target instrument26 GroundStation6)
	(calibration_target instrument26 GroundStation118)
	(calibration_target instrument26 Star89)
	(calibration_target instrument26 Star132)
	(calibration_target instrument26 Star148)
	(calibration_target instrument26 GroundStation160)
	(calibration_target instrument26 GroundStation174)
	(calibration_target instrument26 GroundStation220)
	(calibration_target instrument26 Star39)
	(calibration_target instrument26 Star140)
	(calibration_target instrument26 Star189)
	(calibration_target instrument26 Star173)
	(calibration_target instrument26 Star63)
	(calibration_target instrument26 GroundStation67)
	(calibration_target instrument26 Star60)
	(calibration_target instrument26 Star57)
	(calibration_target instrument26 GroundStation163)
	(calibration_target instrument26 GroundStation119)
	(calibration_target instrument26 Star53)
	(calibration_target instrument26 GroundStation133)
	(calibration_target instrument26 GroundStation171)
	(calibration_target instrument26 Star130)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 GroundStation165)
	(calibration_target instrument26 Star109)
	(calibration_target instrument26 GroundStation193)
	(calibration_target instrument26 Star116)
	(calibration_target instrument26 GroundStation41)
	(calibration_target instrument26 Star214)
	(calibration_target instrument26 Star122)
	(on_board instrument25 satellite9)
	(on_board instrument26 satellite9)
	(power_avail satellite9)
	(pointing satellite9 GroundStation176)
	(supports instrument27 infrared4)
	(calibration_target instrument27 Star227)
	(calibration_target instrument27 GroundStation24)
	(calibration_target instrument27 GroundStation71)
	(calibration_target instrument27 GroundStation26)
	(calibration_target instrument27 GroundStation128)
	(calibration_target instrument27 Star164)
	(calibration_target instrument27 Star83)
	(calibration_target instrument27 GroundStation2)
	(calibration_target instrument27 Star120)
	(calibration_target instrument27 Star56)
	(calibration_target instrument27 GroundStation18)
	(calibration_target instrument27 GroundStation113)
	(calibration_target instrument27 Star139)
	(calibration_target instrument27 Star117)
	(calibration_target instrument27 GroundStation172)
	(calibration_target instrument27 Star129)
	(calibration_target instrument27 Star12)
	(calibration_target instrument27 GroundStation118)
	(calibration_target instrument27 GroundStation8)
	(calibration_target instrument27 GroundStation51)
	(calibration_target instrument27 GroundStation86)
	(calibration_target instrument27 GroundStation101)
	(calibration_target instrument27 Star16)
	(calibration_target instrument27 GroundStation32)
	(calibration_target instrument27 GroundStation137)
	(calibration_target instrument27 GroundStation67)
	(calibration_target instrument27 Star69)
	(calibration_target instrument27 GroundStation107)
	(calibration_target instrument27 GroundStation49)
	(calibration_target instrument27 GroundStation25)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 Star132)
	(supports instrument28 infrared3)
	(supports instrument28 thermograph1)
	(supports instrument28 infrared4)
	(calibration_target instrument28 Star96)
	(calibration_target instrument28 GroundStation98)
	(calibration_target instrument28 GroundStation76)
	(calibration_target instrument28 GroundStation186)
	(calibration_target instrument28 Star54)
	(calibration_target instrument28 GroundStation212)
	(calibration_target instrument28 Star14)
	(calibration_target instrument28 Star179)
	(calibration_target instrument28 GroundStation204)
	(calibration_target instrument28 Star214)
	(calibration_target instrument28 GroundStation62)
	(calibration_target instrument28 GroundStation80)
	(calibration_target instrument28 Star223)
	(calibration_target instrument28 GroundStation81)
	(calibration_target instrument28 GroundStation100)
	(calibration_target instrument28 Star150)
	(calibration_target instrument28 GroundStation138)
	(calibration_target instrument28 Star3)
	(calibration_target instrument28 GroundStation154)
	(calibration_target instrument28 Star43)
	(calibration_target instrument28 GroundStation172)
	(calibration_target instrument28 GroundStation32)
	(calibration_target instrument28 GroundStation106)
	(calibration_target instrument28 GroundStation216)
	(calibration_target instrument28 GroundStation75)
	(calibration_target instrument28 GroundStation19)
	(calibration_target instrument28 GroundStation136)
	(calibration_target instrument28 GroundStation22)
	(calibration_target instrument28 GroundStation51)
	(calibration_target instrument28 GroundStation93)
	(calibration_target instrument28 Star126)
	(calibration_target instrument28 GroundStation145)
	(calibration_target instrument28 GroundStation47)
	(calibration_target instrument28 GroundStation115)
	(calibration_target instrument28 Star64)
	(calibration_target instrument28 GroundStation44)
	(calibration_target instrument28 GroundStation0)
	(calibration_target instrument28 GroundStation2)
	(calibration_target instrument28 GroundStation88)
	(on_board instrument27 satellite10)
	(on_board instrument28 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Phenomenon292)
)
(:goal (and
	(pointing satellite3 Phenomenon267)
	(pointing satellite5 Star122)
	(pointing satellite8 Star354)
	(have_image Phenomenon228 image0)
	(have_image Planet229 infrared4)
	(have_image Planet229 image0)
	(have_image Star230 spectrograph2)
	(have_image Star230 spectrograph5)
	(have_image Phenomenon231 image0)
	(have_image Phenomenon231 spectrograph2)
	(have_image Star232 infrared4)
	(have_image Star232 image0)
	(have_image Phenomenon233 spectrograph2)
	(have_image Star234 infrared4)
	(have_image Star234 spectrograph2)
	(have_image Planet235 thermograph1)
	(have_image Planet235 infrared4)
	(have_image Planet236 infrared3)
	(have_image Star237 spectrograph5)
	(have_image Star237 image0)
	(have_image Star238 thermograph1)
	(have_image Phenomenon239 thermograph1)
	(have_image Phenomenon239 infrared4)
	(have_image Star240 spectrograph2)
	(have_image Planet241 spectrograph2)
	(have_image Planet242 image0)
	(have_image Phenomenon243 thermograph1)
	(have_image Star244 thermograph1)
	(have_image Star244 infrared4)
	(have_image Star245 spectrograph5)
	(have_image Star245 infrared4)
	(have_image Planet246 thermograph1)
	(have_image Star247 infrared4)
	(have_image Planet248 thermograph1)
	(have_image Planet250 image0)
	(have_image Planet250 thermograph1)
	(have_image Star251 thermograph1)
	(have_image Phenomenon252 infrared4)
	(have_image Star253 spectrograph2)
	(have_image Star253 infrared3)
	(have_image Phenomenon254 image0)
	(have_image Star255 thermograph1)
	(have_image Star255 image0)
	(have_image Planet256 infrared3)
	(have_image Star257 image0)
	(have_image Phenomenon258 infrared3)
	(have_image Phenomenon259 spectrograph2)
	(have_image Planet262 spectrograph5)
	(have_image Star264 spectrograph2)
	(have_image Star264 image0)
	(have_image Planet265 infrared4)
	(have_image Planet265 infrared3)
	(have_image Planet266 infrared4)
	(have_image Planet266 infrared3)
	(have_image Phenomenon267 spectrograph2)
	(have_image Phenomenon267 thermograph1)
	(have_image Planet268 infrared4)
	(have_image Star269 infrared3)
	(have_image Planet270 infrared3)
	(have_image Planet270 thermograph1)
	(have_image Planet271 thermograph1)
	(have_image Planet271 spectrograph2)
	(have_image Planet272 image0)
	(have_image Planet273 spectrograph2)
	(have_image Planet273 thermograph1)
	(have_image Phenomenon274 image0)
	(have_image Phenomenon274 infrared4)
	(have_image Star275 infrared3)
	(have_image Phenomenon276 infrared4)
	(have_image Phenomenon276 image0)
	(have_image Star277 spectrograph2)
	(have_image Star277 thermograph1)
	(have_image Phenomenon278 infrared3)
	(have_image Phenomenon278 spectrograph2)
	(have_image Planet279 spectrograph5)
	(have_image Planet279 spectrograph2)
	(have_image Phenomenon280 infrared3)
	(have_image Phenomenon280 image0)
	(have_image Planet281 image0)
	(have_image Planet281 spectrograph2)
	(have_image Star282 spectrograph5)
	(have_image Star282 spectrograph2)
	(have_image Planet283 thermograph1)
	(have_image Star284 thermograph1)
	(have_image Star284 infrared3)
	(have_image Planet285 spectrograph2)
	(have_image Planet285 thermograph1)
	(have_image Planet286 image0)
	(have_image Phenomenon287 infrared4)
	(have_image Phenomenon287 spectrograph5)
	(have_image Phenomenon289 thermograph1)
	(have_image Phenomenon289 spectrograph5)
	(have_image Star290 thermograph1)
	(have_image Planet291 infrared4)
	(have_image Planet291 infrared3)
	(have_image Phenomenon292 spectrograph2)
	(have_image Planet293 image0)
	(have_image Planet294 spectrograph2)
	(have_image Star295 infrared4)
	(have_image Star295 thermograph1)
	(have_image Star296 infrared4)
	(have_image Star296 infrared3)
	(have_image Star298 spectrograph2)
	(have_image Star298 image0)
	(have_image Phenomenon299 infrared3)
	(have_image Phenomenon299 spectrograph2)
	(have_image Phenomenon300 spectrograph2)
	(have_image Planet302 infrared4)
	(have_image Star303 infrared4)
	(have_image Star303 spectrograph2)
	(have_image Phenomenon304 spectrograph2)
	(have_image Planet305 spectrograph2)
	(have_image Phenomenon306 infrared4)
	(have_image Planet307 thermograph1)
	(have_image Phenomenon308 infrared3)
	(have_image Phenomenon308 thermograph1)
	(have_image Star309 image0)
	(have_image Phenomenon310 spectrograph5)
	(have_image Phenomenon310 image0)
	(have_image Star311 thermograph1)
	(have_image Star311 infrared3)
	(have_image Star312 thermograph1)
	(have_image Planet314 spectrograph2)
	(have_image Planet315 spectrograph5)
	(have_image Planet316 spectrograph5)
	(have_image Phenomenon317 infrared4)
	(have_image Phenomenon317 spectrograph2)
	(have_image Planet318 infrared3)
	(have_image Planet319 infrared4)
	(have_image Planet319 infrared3)
	(have_image Planet320 spectrograph2)
	(have_image Planet320 infrared4)
	(have_image Star321 spectrograph2)
	(have_image Star321 image0)
	(have_image Star322 image0)
	(have_image Star323 infrared3)
	(have_image Phenomenon324 infrared3)
	(have_image Phenomenon324 infrared4)
	(have_image Phenomenon325 infrared4)
	(have_image Phenomenon325 spectrograph2)
	(have_image Phenomenon326 infrared3)
	(have_image Planet328 thermograph1)
	(have_image Planet328 spectrograph5)
	(have_image Star329 spectrograph2)
	(have_image Planet330 thermograph1)
	(have_image Planet330 image0)
	(have_image Phenomenon331 infrared4)
	(have_image Phenomenon331 spectrograph5)
	(have_image Planet332 infrared4)
	(have_image Planet332 spectrograph5)
	(have_image Star333 infrared4)
	(have_image Planet334 infrared4)
	(have_image Phenomenon335 spectrograph5)
	(have_image Planet336 spectrograph2)
	(have_image Planet337 image0)
	(have_image Star338 thermograph1)
	(have_image Planet339 spectrograph2)
	(have_image Planet339 infrared4)
	(have_image Star340 spectrograph2)
	(have_image Planet342 image0)
	(have_image Planet342 infrared4)
	(have_image Phenomenon343 spectrograph5)
	(have_image Phenomenon343 thermograph1)
	(have_image Star344 spectrograph5)
	(have_image Star344 infrared3)
	(have_image Star345 thermograph1)
	(have_image Star345 image0)
	(have_image Planet346 spectrograph5)
	(have_image Planet347 image0)
	(have_image Planet347 infrared4)
	(have_image Star348 spectrograph2)
	(have_image Star349 spectrograph2)
	(have_image Phenomenon350 spectrograph2)
	(have_image Phenomenon350 thermograph1)
	(have_image Star351 spectrograph5)
	(have_image Phenomenon352 spectrograph5)
	(have_image Phenomenon352 image0)
	(have_image Phenomenon353 thermograph1)
	(have_image Phenomenon353 spectrograph5)
	(have_image Star354 image0)
	(have_image Star354 infrared3)
	(have_image Star355 thermograph1)
	(have_image Planet356 infrared4)
	(have_image Planet356 spectrograph5)
	(have_image Planet357 image0)
	(have_image Planet358 spectrograph5)
	(have_image Star359 infrared3)
	(have_image Star360 image0)
	(have_image Star360 thermograph1)
	(have_image Planet361 spectrograph2)
	(have_image Planet361 thermograph1)
	(have_image Star362 spectrograph2)
	(have_image Star362 infrared4)
	(have_image Phenomenon363 infrared4)
	(have_image Star364 thermograph1)
	(have_image Star364 image0)
	(have_image Star366 thermograph1)
	(have_image Star366 spectrograph2)
	(have_image Phenomenon367 infrared4)
	(have_image Star368 thermograph1)
	(have_image Star368 spectrograph5)
	(have_image Star369 spectrograph2)
	(have_image Star369 spectrograph5)
	(have_image Star370 thermograph1)
	(have_image Planet371 image0)
	(have_image Planet372 spectrograph2)
	(have_image Star373 thermograph1)
	(have_image Star374 image0)
	(have_image Star374 spectrograph5)
	(have_image Planet375 infrared3)
	(have_image Planet376 thermograph1)
	(have_image Star377 infrared4)
	(have_image Planet378 infrared3)
	(have_image Phenomenon379 infrared3)
	(have_image Planet380 spectrograph5)
	(have_image Planet380 infrared3)
	(have_image Planet381 infrared3)
	(have_image Phenomenon383 spectrograph5)
	(have_image Phenomenon383 infrared4)
	(have_image Planet384 image0)
	(have_image Phenomenon385 infrared3)
	(have_image Planet386 spectrograph2)
	(have_image Planet386 thermograph1)
	(have_image Star387 spectrograph2)
	(have_image Star387 image0)
	(have_image Planet388 spectrograph5)
	(have_image Planet388 thermograph1)
	(have_image Star389 infrared4)
	(have_image Star390 thermograph1)
	(have_image Star390 spectrograph5)
	(have_image Planet391 spectrograph5)
	(have_image Star392 spectrograph5)
	(have_image Star392 infrared3)
	(have_image Star393 image0)
	(have_image Star393 spectrograph2)
	(have_image Star394 infrared4)
	(have_image Phenomenon395 spectrograph5)
	(have_image Phenomenon395 image0)
	(have_image Star396 thermograph1)
	(have_image Planet397 spectrograph2)
	(have_image Planet398 image0)
	(have_image Planet398 thermograph1)
	(have_image Phenomenon399 spectrograph5)
	(have_image Phenomenon399 image0)
	(have_image Phenomenon400 infrared3)
	(have_image Star401 infrared4)
	(have_image Star402 infrared3)
	(have_image Star402 thermograph1)
	(have_image Star403 spectrograph5)
	(have_image Star403 image0)
	(have_image Phenomenon404 infrared3)
	(have_image Star405 spectrograph2)
	(have_image Star405 spectrograph5)
	(have_image Phenomenon406 spectrograph5)
	(have_image Phenomenon406 infrared4)
	(have_image Phenomenon407 spectrograph2)
	(have_image Planet408 thermograph1)
	(have_image Planet408 spectrograph5)
	(have_image Phenomenon409 infrared3)
	(have_image Phenomenon409 thermograph1)
	(have_image Phenomenon410 infrared4)
	(have_image Phenomenon410 spectrograph5)
	(have_image Star411 thermograph1)
	(have_image Star412 image0)
	(have_image Star412 spectrograph2)
	(have_image Planet413 spectrograph2)
	(have_image Planet413 spectrograph5)
	(have_image Planet414 infrared3)
	(have_image Planet414 infrared4)
	(have_image Phenomenon415 spectrograph2)
	(have_image Phenomenon416 image0)
	(have_image Star418 image0)
	(have_image Star418 spectrograph2)
	(have_image Star419 spectrograph5)
	(have_image Star419 thermograph1)
	(have_image Phenomenon420 spectrograph2)
	(have_image Phenomenon420 image0)
	(have_image Phenomenon421 spectrograph2)
	(have_image Planet422 spectrograph2)
	(have_image Planet423 thermograph1)
	(have_image Star424 infrared3)
	(have_image Star424 spectrograph5)
	(have_image Phenomenon425 thermograph1)
	(have_image Phenomenon425 spectrograph2)
	(have_image Planet426 infrared3)
	(have_image Phenomenon427 thermograph1)
	(have_image Star428 thermograph1)
	(have_image Phenomenon429 infrared3)
	(have_image Star430 infrared4)
	(have_image Star430 spectrograph5)
	(have_image Star432 infrared3)
	(have_image Star432 image0)
	(have_image Planet433 infrared4)
	(have_image Star434 image0)
	(have_image Star434 infrared3)
	(have_image Star435 spectrograph5)
	(have_image Star435 infrared4)
	(have_image Phenomenon436 spectrograph5)
	(have_image Phenomenon437 infrared4)
	(have_image Phenomenon438 spectrograph5)
	(have_image Phenomenon438 thermograph1)
	(have_image Phenomenon439 spectrograph2)
	(have_image Star440 infrared4)
	(have_image Star440 infrared3)
	(have_image Phenomenon441 infrared4)
	(have_image Star442 spectrograph2)
	(have_image Star442 infrared4)
	(have_image Phenomenon443 image0)
	(have_image Star444 spectrograph5)
	(have_image Star444 thermograph1)
	(have_image Star445 thermograph1)
	(have_image Phenomenon446 infrared4)
	(have_image Phenomenon446 image0)
	(have_image Star447 spectrograph2)
	(have_image Star447 spectrograph5)
	(have_image Planet448 spectrograph5)
	(have_image Planet448 infrared4)
	(have_image Phenomenon449 thermograph1)
	(have_image Phenomenon449 image0)
	(have_image Star450 thermograph1)
	(have_image Phenomenon451 thermograph1)
	(have_image Phenomenon453 spectrograph2)
	(have_image Star454 spectrograph2)
	(have_image Planet455 infrared3)
	(have_image Planet455 image0)
))

)
