(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	instrument6 - instrument
	satellite2 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite3 - satellite
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	satellite5 - satellite
	instrument16 - instrument
	satellite6 - satellite
	instrument17 - instrument
	instrument18 - instrument
	instrument19 - instrument
	satellite7 - satellite
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite8 - satellite
	instrument23 - instrument
	instrument24 - instrument
	satellite9 - satellite
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite10 - satellite
	instrument29 - instrument
	thermograph4 - mode
	infrared0 - mode
	infrared2 - mode
	spectrograph1 - mode
	image3 - mode
	image5 - mode
	GroundStation128 - direction
	GroundStation77 - direction
	GroundStation152 - direction
	GroundStation72 - direction
	GroundStation42 - direction
	GroundStation178 - direction
	GroundStation119 - direction
	Star111 - direction
	GroundStation18 - direction
	GroundStation138 - direction
	GroundStation53 - direction
	Star162 - direction
	Star64 - direction
	Star201 - direction
	Star181 - direction
	GroundStation88 - direction
	Star203 - direction
	Star225 - direction
	GroundStation141 - direction
	Star33 - direction
	Star189 - direction
	Star74 - direction
	GroundStation167 - direction
	Star109 - direction
	GroundStation78 - direction
	GroundStation233 - direction
	Star173 - direction
	Star102 - direction
	GroundStation158 - direction
	Star182 - direction
	Star209 - direction
	Star126 - direction
	Star38 - direction
	Star186 - direction
	Star149 - direction
	GroundStation43 - direction
	Star125 - direction
	Star108 - direction
	Star75 - direction
	GroundStation10 - direction
	GroundStation94 - direction
	GroundStation221 - direction
	GroundStation2 - direction
	GroundStation26 - direction
	Star219 - direction
	Star15 - direction
	Star68 - direction
	GroundStation232 - direction
	Star44 - direction
	GroundStation206 - direction
	Star91 - direction
	GroundStation226 - direction
	Star131 - direction
	GroundStation171 - direction
	Star123 - direction
	GroundStation84 - direction
	Star213 - direction
	GroundStation11 - direction
	Star172 - direction
	Star230 - direction
	GroundStation121 - direction
	Star222 - direction
	Star23 - direction
	Star29 - direction
	GroundStation218 - direction
	Star161 - direction
	Star101 - direction
	Star216 - direction
	Star223 - direction
	Star145 - direction
	GroundStation210 - direction
	Star112 - direction
	Star39 - direction
	GroundStation146 - direction
	Star103 - direction
	Star214 - direction
	Star24 - direction
	GroundStation70 - direction
	Star151 - direction
	GroundStation194 - direction
	GroundStation83 - direction
	Star164 - direction
	GroundStation115 - direction
	Star229 - direction
	GroundStation187 - direction
	Star58 - direction
	Star73 - direction
	GroundStation183 - direction
	GroundStation120 - direction
	Star31 - direction
	GroundStation133 - direction
	Star197 - direction
	GroundStation107 - direction
	GroundStation76 - direction
	GroundStation166 - direction
	Star134 - direction
	GroundStation144 - direction
	Star113 - direction
	GroundStation67 - direction
	GroundStation200 - direction
	Star137 - direction
	GroundStation177 - direction
	Star12 - direction
	Star153 - direction
	GroundStation143 - direction
	GroundStation71 - direction
	GroundStation129 - direction
	GroundStation179 - direction
	GroundStation191 - direction
	GroundStation6 - direction
	Star34 - direction
	GroundStation37 - direction
	Star235 - direction
	GroundStation198 - direction
	GroundStation154 - direction
	GroundStation3 - direction
	Star60 - direction
	GroundStation110 - direction
	GroundStation61 - direction
	Star50 - direction
	GroundStation56 - direction
	GroundStation1 - direction
	Star35 - direction
	Star170 - direction
	GroundStation196 - direction
	Star81 - direction
	Star100 - direction
	GroundStation148 - direction
	Star106 - direction
	GroundStation190 - direction
	GroundStation193 - direction
	GroundStation79 - direction
	Star165 - direction
	Star228 - direction
	Star30 - direction
	GroundStation51 - direction
	Star208 - direction
	GroundStation150 - direction
	Star9 - direction
	GroundStation63 - direction
	Star180 - direction
	GroundStation155 - direction
	Star14 - direction
	GroundStation217 - direction
	Star28 - direction
	Star205 - direction
	Star142 - direction
	GroundStation41 - direction
	Star69 - direction
	GroundStation199 - direction
	GroundStation104 - direction
	GroundStation22 - direction
	GroundStation90 - direction
	GroundStation127 - direction
	GroundStation36 - direction
	Star47 - direction
	GroundStation140 - direction
	GroundStation163 - direction
	Star184 - direction
	Star40 - direction
	GroundStation215 - direction
	GroundStation27 - direction
	Star25 - direction
	Star157 - direction
	GroundStation234 - direction
	GroundStation4 - direction
	Star227 - direction
	Star132 - direction
	GroundStation93 - direction
	Star80 - direction
	Star135 - direction
	GroundStation0 - direction
	Star20 - direction
	Star211 - direction
	GroundStation202 - direction
	GroundStation92 - direction
	Star105 - direction
	GroundStation212 - direction
	Star204 - direction
	GroundStation185 - direction
	Star86 - direction
	Star66 - direction
	GroundStation7 - direction
	GroundStation195 - direction
	GroundStation16 - direction
	Star124 - direction
	Star49 - direction
	GroundStation13 - direction
	GroundStation159 - direction
	Star136 - direction
	Star98 - direction
	GroundStation139 - direction
	GroundStation89 - direction
	Star54 - direction
	Star207 - direction
	Star48 - direction
	Star156 - direction
	Star122 - direction
	Star59 - direction
	GroundStation175 - direction
	Star174 - direction
	GroundStation97 - direction
	Star65 - direction
	Star85 - direction
	Star147 - direction
	Star118 - direction
	Star17 - direction
	Star52 - direction
	GroundStation55 - direction
	Star168 - direction
	Star19 - direction
	Star188 - direction
	GroundStation176 - direction
	Star95 - direction
	Star96 - direction
	Star21 - direction
	GroundStation220 - direction
	Star192 - direction
	Star5 - direction
	Star87 - direction
	GroundStation45 - direction
	GroundStation82 - direction
	Star117 - direction
	Star46 - direction
	GroundStation99 - direction
	GroundStation160 - direction
	GroundStation8 - direction
	GroundStation169 - direction
	Star130 - direction
	Star57 - direction
	GroundStation32 - direction
	GroundStation62 - direction
	Star224 - direction
	GroundStation231 - direction
	Star114 - direction
	Star116 - direction
	Phenomenon236 - direction
	Star237 - direction
	Star238 - direction
	Star239 - direction
	Star240 - direction
	Star241 - direction
	Planet242 - direction
	Planet243 - direction
	Planet244 - direction
	Star245 - direction
	Star246 - direction
	Planet247 - direction
	Phenomenon248 - direction
	Phenomenon249 - direction
	Phenomenon250 - direction
	Phenomenon251 - direction
	Phenomenon252 - direction
	Planet253 - direction
	Star254 - direction
	Star255 - direction
	Star256 - direction
	Planet257 - direction
	Phenomenon258 - direction
	Phenomenon259 - direction
	Star260 - direction
	Star261 - direction
	Star262 - direction
	Phenomenon263 - direction
	Planet264 - direction
	Star265 - direction
	Planet266 - direction
	Star267 - direction
	Star268 - direction
	Star269 - direction
	Phenomenon270 - direction
	Phenomenon271 - direction
	Phenomenon272 - direction
	Phenomenon273 - direction
	Planet274 - direction
	Phenomenon275 - direction
	Phenomenon276 - direction
	Planet277 - direction
	Star278 - direction
	Phenomenon279 - direction
	Star280 - direction
	Star281 - direction
	Phenomenon282 - direction
	Star283 - direction
	Planet284 - direction
	Phenomenon285 - direction
	Star286 - direction
	Star287 - direction
	Phenomenon288 - direction
	Phenomenon289 - direction
	Star290 - direction
	Planet291 - direction
	Planet292 - direction
	Phenomenon293 - direction
	Star294 - direction
	Planet295 - direction
	Phenomenon296 - direction
	Phenomenon297 - direction
	Planet298 - direction
	Star299 - direction
	Phenomenon300 - direction
	Phenomenon301 - direction
	Planet302 - direction
	Star303 - direction
	Phenomenon304 - direction
	Planet305 - direction
	Phenomenon306 - direction
	Star307 - direction
	Planet308 - direction
	Planet309 - direction
	Planet310 - direction
	Planet311 - direction
	Phenomenon312 - direction
	Planet313 - direction
	Planet314 - direction
	Planet315 - direction
	Planet316 - direction
	Phenomenon317 - direction
	Star318 - direction
	Planet319 - direction
	Phenomenon320 - direction
	Phenomenon321 - direction
	Star322 - direction
	Planet323 - direction
	Planet324 - direction
	Planet325 - direction
	Phenomenon326 - direction
	Phenomenon327 - direction
	Star328 - direction
	Planet329 - direction
	Star330 - direction
	Star331 - direction
	Planet332 - direction
	Star333 - direction
	Planet334 - direction
	Phenomenon335 - direction
	Planet336 - direction
	Planet337 - direction
	Phenomenon338 - direction
	Phenomenon339 - direction
	Planet340 - direction
	Star341 - direction
	Star342 - direction
	Planet343 - direction
	Star344 - direction
	Planet345 - direction
	Planet346 - direction
	Phenomenon347 - direction
	Star348 - direction
	Planet349 - direction
	Planet350 - direction
	Phenomenon351 - direction
	Star352 - direction
	Phenomenon353 - direction
	Phenomenon354 - direction
	Star355 - direction
	Phenomenon356 - direction
	Planet357 - direction
	Star358 - direction
	Phenomenon359 - direction
	Phenomenon360 - direction
	Planet361 - direction
	Planet362 - direction
	Star363 - direction
	Planet364 - direction
	Star365 - direction
	Phenomenon366 - direction
	Phenomenon367 - direction
	Star368 - direction
	Star369 - direction
	Star370 - direction
	Phenomenon371 - direction
	Phenomenon372 - direction
	Planet373 - direction
	Phenomenon374 - direction
	Planet375 - direction
	Phenomenon376 - direction
	Phenomenon377 - direction
	Phenomenon378 - direction
	Planet379 - direction
	Phenomenon380 - direction
	Star381 - direction
	Planet382 - direction
	Planet383 - direction
	Phenomenon384 - direction
	Phenomenon385 - direction
	Planet386 - direction
	Planet387 - direction
	Phenomenon388 - direction
	Planet389 - direction
	Phenomenon390 - direction
	Planet391 - direction
	Planet392 - direction
	Star393 - direction
	Planet394 - direction
	Star395 - direction
	Phenomenon396 - direction
	Phenomenon397 - direction
	Star398 - direction
	Star399 - direction
	Planet400 - direction
	Planet401 - direction
	Planet402 - direction
	Star403 - direction
	Planet404 - direction
	Planet405 - direction
	Star406 - direction
	Star407 - direction
	Phenomenon408 - direction
	Phenomenon409 - direction
	Star410 - direction
	Phenomenon411 - direction
	Star412 - direction
	Planet413 - direction
	Star414 - direction
	Phenomenon415 - direction
	Star416 - direction
	Phenomenon417 - direction
	Planet418 - direction
	Phenomenon419 - direction
	Planet420 - direction
	Phenomenon421 - direction
	Planet422 - direction
	Star423 - direction
	Star424 - direction
	Planet425 - direction
	Phenomenon426 - direction
	Phenomenon427 - direction
	Star428 - direction
	Planet429 - direction
	Phenomenon430 - direction
	Star431 - direction
	Phenomenon432 - direction
	Planet433 - direction
	Star434 - direction
	Star435 - direction
	Phenomenon436 - direction
	Star437 - direction
	Planet438 - direction
	Planet439 - direction
	Star440 - direction
	Planet441 - direction
	Star442 - direction
	Phenomenon443 - direction
	Planet444 - direction
	Star445 - direction
	Planet446 - direction
	Planet447 - direction
	Phenomenon448 - direction
	Star449 - direction
	Phenomenon450 - direction
	Planet451 - direction
	Planet452 - direction
	Phenomenon453 - direction
	Phenomenon454 - direction
	Planet455 - direction
	Planet456 - direction
	Planet457 - direction
	Planet458 - direction
	Planet459 - direction
	Planet460 - direction
	Planet461 - direction
	Phenomenon462 - direction
	Phenomenon463 - direction
	Planet464 - direction
	Star465 - direction
	Star466 - direction
	Planet467 - direction
	Phenomenon468 - direction
	Planet469 - direction
	Planet470 - direction
	Planet471 - direction
)
(:init
	(supports instrument0 image5)
	(supports instrument0 infrared2)
	(calibration_target instrument0 Star125)
	(calibration_target instrument0 Star189)
	(calibration_target instrument0 GroundStation159)
	(calibration_target instrument0 Star65)
	(calibration_target instrument0 GroundStation61)
	(calibration_target instrument0 Star49)
	(calibration_target instrument0 Star34)
	(calibration_target instrument0 Star111)
	(calibration_target instrument0 Star117)
	(calibration_target instrument0 GroundStation115)
	(calibration_target instrument0 Star91)
	(calibration_target instrument0 GroundStation183)
	(calibration_target instrument0 Star116)
	(calibration_target instrument0 GroundStation154)
	(calibration_target instrument0 Star182)
	(calibration_target instrument0 GroundStation198)
	(calibration_target instrument0 GroundStation141)
	(calibration_target instrument0 Star132)
	(calibration_target instrument0 Star48)
	(calibration_target instrument0 Star207)
	(calibration_target instrument0 Star52)
	(calibration_target instrument0 Star211)
	(calibration_target instrument0 Star165)
	(calibration_target instrument0 GroundStation76)
	(calibration_target instrument0 Star19)
	(calibration_target instrument0 Star188)
	(calibration_target instrument0 GroundStation233)
	(calibration_target instrument0 Star118)
	(calibration_target instrument0 GroundStation71)
	(calibration_target instrument0 Star113)
	(calibration_target instrument0 Star50)
	(calibration_target instrument0 GroundStation200)
	(calibration_target instrument0 Star68)
	(calibration_target instrument0 Star214)
	(calibration_target instrument0 GroundStation26)
	(calibration_target instrument0 GroundStation133)
	(calibration_target instrument0 Star23)
	(calibration_target instrument0 GroundStation63)
	(calibration_target instrument0 Star5)
	(calibration_target instrument0 Star145)
	(calibration_target instrument0 GroundStation179)
	(calibration_target instrument0 GroundStation97)
	(calibration_target instrument0 Star87)
	(calibration_target instrument0 Star57)
	(calibration_target instrument0 GroundStation13)
	(calibration_target instrument0 GroundStation32)
	(calibration_target instrument0 Star17)
	(calibration_target instrument0 GroundStation158)
	(calibration_target instrument0 Star168)
	(calibration_target instrument0 Star73)
	(calibration_target instrument0 GroundStation128)
	(calibration_target instrument0 GroundStation221)
	(calibration_target instrument0 GroundStation42)
	(calibration_target instrument0 Star54)
	(calibration_target instrument0 GroundStation62)
	(calibration_target instrument0 GroundStation70)
	(calibration_target instrument0 GroundStation4)
	(supports instrument1 image5)
	(supports instrument1 thermograph4)
	(supports instrument1 image3)
	(calibration_target instrument1 GroundStation97)
	(calibration_target instrument1 Star103)
	(calibration_target instrument1 GroundStation129)
	(calibration_target instrument1 Star5)
	(calibration_target instrument1 Star173)
	(calibration_target instrument1 GroundStation146)
	(calibration_target instrument1 GroundStation71)
	(calibration_target instrument1 GroundStation210)
	(calibration_target instrument1 Star17)
	(calibration_target instrument1 Star162)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star229)
	(calibration_target instrument1 GroundStation70)
	(calibration_target instrument1 Star181)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 Star21)
	(calibration_target instrument1 Star109)
	(calibration_target instrument1 Star19)
	(calibration_target instrument1 GroundStation148)
	(calibration_target instrument1 GroundStation84)
	(calibration_target instrument1 Star137)
	(calibration_target instrument1 GroundStation199)
	(calibration_target instrument1 GroundStation3)
	(calibration_target instrument1 Star116)
	(calibration_target instrument1 Star28)
	(calibration_target instrument1 Star170)
	(calibration_target instrument1 GroundStation193)
	(calibration_target instrument1 Star20)
	(calibration_target instrument1 Star30)
	(calibration_target instrument1 Star224)
	(calibration_target instrument1 Star184)
	(calibration_target instrument1 Star207)
	(calibration_target instrument1 GroundStation11)
	(calibration_target instrument1 GroundStation61)
	(calibration_target instrument1 Star230)
	(calibration_target instrument1 GroundStation178)
	(calibration_target instrument1 Star134)
	(calibration_target instrument1 GroundStation195)
	(calibration_target instrument1 Star81)
	(calibration_target instrument1 GroundStation78)
	(calibration_target instrument1 GroundStation43)
	(supports instrument2 thermograph4)
	(supports instrument2 image3)
	(calibration_target instrument2 Star19)
	(calibration_target instrument2 Star222)
	(calibration_target instrument2 GroundStation198)
	(calibration_target instrument2 Star64)
	(calibration_target instrument2 GroundStation194)
	(calibration_target instrument2 GroundStation138)
	(calibration_target instrument2 GroundStation71)
	(calibration_target instrument2 GroundStation127)
	(calibration_target instrument2 GroundStation129)
	(calibration_target instrument2 Star48)
	(calibration_target instrument2 GroundStation199)
	(calibration_target instrument2 GroundStation77)
	(calibration_target instrument2 GroundStation146)
	(calibration_target instrument2 Star44)
	(calibration_target instrument2 Star54)
	(calibration_target instrument2 Star161)
	(calibration_target instrument2 GroundStation169)
	(calibration_target instrument2 GroundStation67)
	(calibration_target instrument2 GroundStation178)
	(calibration_target instrument2 Star145)
	(calibration_target instrument2 Star130)
	(calibration_target instrument2 Star105)
	(calibration_target instrument2 GroundStation3)
	(calibration_target instrument2 Star204)
	(calibration_target instrument2 Star225)
	(calibration_target instrument2 Star219)
	(calibration_target instrument2 GroundStation97)
	(calibration_target instrument2 GroundStation90)
	(calibration_target instrument2 Star124)
	(calibration_target instrument2 Star165)
	(calibration_target instrument2 Star46)
	(calibration_target instrument2 GroundStation99)
	(calibration_target instrument2 Star131)
	(calibration_target instrument2 GroundStation193)
	(calibration_target instrument2 GroundStation160)
	(calibration_target instrument2 Star81)
	(calibration_target instrument2 Star98)
	(calibration_target instrument2 Star151)
	(calibration_target instrument2 Star74)
	(calibration_target instrument2 Star95)
	(calibration_target instrument2 Star58)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 Star174)
	(calibration_target instrument2 GroundStation51)
	(calibration_target instrument2 GroundStation92)
	(calibration_target instrument2 Star31)
	(calibration_target instrument2 Star223)
	(calibration_target instrument2 Star23)
	(calibration_target instrument2 GroundStation104)
	(calibration_target instrument2 Star172)
	(calibration_target instrument2 GroundStation150)
	(calibration_target instrument2 GroundStation4)
	(calibration_target instrument2 Star118)
	(calibration_target instrument2 Star114)
	(calibration_target instrument2 GroundStation55)
	(calibration_target instrument2 Star126)
	(calibration_target instrument2 Star30)
	(calibration_target instrument2 GroundStation53)
	(calibration_target instrument2 GroundStation218)
	(calibration_target instrument2 GroundStation88)
	(calibration_target instrument2 Star116)
	(calibration_target instrument2 Star214)
	(calibration_target instrument2 GroundStation196)
	(calibration_target instrument2 Star100)
	(calibration_target instrument2 GroundStation234)
	(calibration_target instrument2 GroundStation148)
	(calibration_target instrument2 Star33)
	(calibration_target instrument2 GroundStation61)
	(calibration_target instrument2 Star123)
	(calibration_target instrument2 GroundStation119)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet394)
	(supports instrument3 image3)
	(calibration_target instrument3 Star222)
	(calibration_target instrument3 GroundStation193)
	(calibration_target instrument3 GroundStation97)
	(calibration_target instrument3 GroundStation133)
	(calibration_target instrument3 Star204)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation127)
	(calibration_target instrument3 GroundStation63)
	(calibration_target instrument3 Star170)
	(calibration_target instrument3 GroundStation154)
	(calibration_target instrument3 Star87)
	(calibration_target instrument3 GroundStation72)
	(calibration_target instrument3 Star188)
	(calibration_target instrument3 GroundStation7)
	(calibration_target instrument3 GroundStation77)
	(calibration_target instrument3 GroundStation163)
	(calibration_target instrument3 GroundStation84)
	(calibration_target instrument3 GroundStation196)
	(calibration_target instrument3 Star113)
	(calibration_target instrument3 GroundStation18)
	(calibration_target instrument3 Star17)
	(calibration_target instrument3 GroundStation233)
	(calibration_target instrument3 GroundStation79)
	(calibration_target instrument3 Star235)
	(calibration_target instrument3 GroundStation8)
	(calibration_target instrument3 GroundStation42)
	(calibration_target instrument3 Star201)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star173)
	(calibration_target instrument3 Star75)
	(calibration_target instrument3 GroundStation215)
	(supports instrument4 infrared2)
	(supports instrument4 spectrograph1)
	(calibration_target instrument4 Star157)
	(calibration_target instrument4 GroundStation43)
	(calibration_target instrument4 GroundStation67)
	(calibration_target instrument4 GroundStation61)
	(calibration_target instrument4 GroundStation76)
	(calibration_target instrument4 Star65)
	(calibration_target instrument4 Star91)
	(calibration_target instrument4 Star125)
	(calibration_target instrument4 Star31)
	(calibration_target instrument4 GroundStation206)
	(calibration_target instrument4 GroundStation11)
	(calibration_target instrument4 GroundStation120)
	(calibration_target instrument4 Star64)
	(calibration_target instrument4 GroundStation176)
	(calibration_target instrument4 Star112)
	(calibration_target instrument4 GroundStation158)
	(calibration_target instrument4 Star151)
	(calibration_target instrument4 Star223)
	(calibration_target instrument4 GroundStation56)
	(calibration_target instrument4 GroundStation234)
	(calibration_target instrument4 GroundStation144)
	(calibration_target instrument4 GroundStation152)
	(calibration_target instrument4 Star75)
	(calibration_target instrument4 Star124)
	(calibration_target instrument4 Star35)
	(calibration_target instrument4 GroundStation155)
	(calibration_target instrument4 GroundStation92)
	(calibration_target instrument4 Star181)
	(calibration_target instrument4 Star103)
	(calibration_target instrument4 Star113)
	(calibration_target instrument4 Star149)
	(calibration_target instrument4 GroundStation129)
	(calibration_target instrument4 Star57)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 Star132)
	(calibration_target instrument4 GroundStation198)
	(calibration_target instrument4 Star224)
	(calibration_target instrument4 GroundStation84)
	(calibration_target instrument4 Star216)
	(calibration_target instrument4 GroundStation143)
	(calibration_target instrument4 GroundStation166)
	(calibration_target instrument4 Star9)
	(calibration_target instrument4 GroundStation32)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 GroundStation93)
	(calibration_target instrument4 GroundStation119)
	(calibration_target instrument4 GroundStation195)
	(calibration_target instrument4 Star201)
	(calibration_target instrument4 GroundStation187)
	(calibration_target instrument4 Star33)
	(calibration_target instrument4 Star49)
	(calibration_target instrument4 GroundStation78)
	(calibration_target instrument4 GroundStation199)
	(supports instrument5 thermograph4)
	(calibration_target instrument5 Star111)
	(calibration_target instrument5 Star122)
	(calibration_target instrument5 Star153)
	(calibration_target instrument5 Star186)
	(calibration_target instrument5 Star20)
	(calibration_target instrument5 GroundStation143)
	(calibration_target instrument5 Star137)
	(calibration_target instrument5 GroundStation152)
	(calibration_target instrument5 GroundStation183)
	(calibration_target instrument5 Star147)
	(calibration_target instrument5 Star117)
	(calibration_target instrument5 Star50)
	(calibration_target instrument5 Star102)
	(calibration_target instrument5 GroundStation79)
	(calibration_target instrument5 GroundStation43)
	(calibration_target instrument5 GroundStation82)
	(calibration_target instrument5 GroundStation220)
	(calibration_target instrument5 Star34)
	(calibration_target instrument5 Star38)
	(calibration_target instrument5 GroundStation61)
	(calibration_target instrument5 GroundStation206)
	(calibration_target instrument5 Star168)
	(calibration_target instrument5 GroundStation140)
	(calibration_target instrument5 Star25)
	(calibration_target instrument5 GroundStation63)
	(calibration_target instrument5 GroundStation77)
	(calibration_target instrument5 GroundStation76)
	(calibration_target instrument5 Star149)
	(calibration_target instrument5 Star188)
	(supports instrument6 infrared2)
	(supports instrument6 spectrograph1)
	(calibration_target instrument6 Star65)
	(calibration_target instrument6 GroundStation226)
	(calibration_target instrument6 GroundStation231)
	(calibration_target instrument6 GroundStation175)
	(calibration_target instrument6 GroundStation191)
	(calibration_target instrument6 Star165)
	(calibration_target instrument6 Star25)
	(calibration_target instrument6 Star39)
	(calibration_target instrument6 Star96)
	(calibration_target instrument6 Star124)
	(calibration_target instrument6 GroundStation26)
	(calibration_target instrument6 GroundStation45)
	(calibration_target instrument6 Star64)
	(calibration_target instrument6 GroundStation177)
	(calibration_target instrument6 GroundStation10)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 Star229)
	(calibration_target instrument6 Star207)
	(calibration_target instrument6 GroundStation127)
	(calibration_target instrument6 Star219)
	(calibration_target instrument6 GroundStation42)
	(calibration_target instrument6 GroundStation72)
	(calibration_target instrument6 GroundStation176)
	(calibration_target instrument6 GroundStation140)
	(calibration_target instrument6 GroundStation13)
	(calibration_target instrument6 Star149)
	(calibration_target instrument6 Star197)
	(calibration_target instrument6 Star117)
	(calibration_target instrument6 Star170)
	(calibration_target instrument6 GroundStation76)
	(calibration_target instrument6 Star113)
	(calibration_target instrument6 Star46)
	(calibration_target instrument6 GroundStation121)
	(calibration_target instrument6 GroundStation36)
	(calibration_target instrument6 Star49)
	(calibration_target instrument6 Star28)
	(calibration_target instrument6 GroundStation169)
	(calibration_target instrument6 Star19)
	(calibration_target instrument6 Star100)
	(calibration_target instrument6 GroundStation133)
	(calibration_target instrument6 Star116)
	(calibration_target instrument6 Star204)
	(calibration_target instrument6 GroundStation32)
	(calibration_target instrument6 Star213)
	(calibration_target instrument6 GroundStation158)
	(calibration_target instrument6 Star216)
	(calibration_target instrument6 Star203)
	(calibration_target instrument6 GroundStation167)
	(calibration_target instrument6 Star40)
	(calibration_target instrument6 Star91)
	(calibration_target instrument6 GroundStation199)
	(calibration_target instrument6 GroundStation163)
	(calibration_target instrument6 Star98)
	(calibration_target instrument6 GroundStation90)
	(calibration_target instrument6 Star145)
	(calibration_target instrument6 GroundStation11)
	(calibration_target instrument6 Star214)
	(calibration_target instrument6 GroundStation84)
	(calibration_target instrument6 Star75)
	(calibration_target instrument6 GroundStation37)
	(calibration_target instrument6 Star17)
	(calibration_target instrument6 GroundStation71)
	(calibration_target instrument6 Star54)
	(calibration_target instrument6 GroundStation129)
	(calibration_target instrument6 GroundStation18)
	(calibration_target instrument6 GroundStation62)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(on_board instrument6 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star39)
	(supports instrument7 image3)
	(calibration_target instrument7 GroundStation144)
	(calibration_target instrument7 Star19)
	(calibration_target instrument7 Star74)
	(calibration_target instrument7 Star192)
	(calibration_target instrument7 Star50)
	(calibration_target instrument7 Star205)
	(calibration_target instrument7 Star168)
	(calibration_target instrument7 GroundStation218)
	(calibration_target instrument7 GroundStation159)
	(calibration_target instrument7 Star116)
	(calibration_target instrument7 Star214)
	(calibration_target instrument7 Star184)
	(supports instrument8 infrared0)
	(supports instrument8 spectrograph1)
	(supports instrument8 image3)
	(calibration_target instrument8 Star100)
	(calibration_target instrument8 Star50)
	(calibration_target instrument8 GroundStation158)
	(calibration_target instrument8 Star34)
	(calibration_target instrument8 Star81)
	(calibration_target instrument8 Star165)
	(calibration_target instrument8 Star114)
	(calibration_target instrument8 GroundStation166)
	(calibration_target instrument8 GroundStation56)
	(calibration_target instrument8 GroundStation206)
	(calibration_target instrument8 Star91)
	(calibration_target instrument8 GroundStation178)
	(calibration_target instrument8 GroundStation99)
	(calibration_target instrument8 GroundStation2)
	(calibration_target instrument8 GroundStation37)
	(calibration_target instrument8 Star19)
	(supports instrument9 image3)
	(supports instrument9 thermograph4)
	(calibration_target instrument9 GroundStation195)
	(calibration_target instrument9 GroundStation71)
	(calibration_target instrument9 GroundStation115)
	(calibration_target instrument9 Star29)
	(calibration_target instrument9 GroundStation88)
	(calibration_target instrument9 Star165)
	(calibration_target instrument9 GroundStation154)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 Star34)
	(calibration_target instrument9 Star180)
	(calibration_target instrument9 Star111)
	(calibration_target instrument9 GroundStation206)
	(calibration_target instrument9 GroundStation79)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 Star33)
	(calibration_target instrument9 GroundStation146)
	(calibration_target instrument9 Star208)
	(calibration_target instrument9 GroundStation150)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star188)
	(calibration_target instrument9 Star207)
	(calibration_target instrument9 Star112)
	(calibration_target instrument9 Star142)
	(calibration_target instrument9 GroundStation36)
	(calibration_target instrument9 Star168)
	(calibration_target instrument9 GroundStation175)
	(calibration_target instrument9 GroundStation119)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 Star235)
	(calibration_target instrument9 GroundStation127)
	(calibration_target instrument9 Star81)
	(calibration_target instrument9 Star25)
	(calibration_target instrument9 Star59)
	(calibration_target instrument9 GroundStation200)
	(calibration_target instrument9 Star116)
	(calibration_target instrument9 GroundStation169)
	(calibration_target instrument9 GroundStation221)
	(calibration_target instrument9 Star174)
	(calibration_target instrument9 GroundStation215)
	(calibration_target instrument9 GroundStation217)
	(calibration_target instrument9 GroundStation93)
	(calibration_target instrument9 Star60)
	(calibration_target instrument9 GroundStation171)
	(calibration_target instrument9 Star86)
	(calibration_target instrument9 GroundStation10)
	(calibration_target instrument9 GroundStation43)
	(calibration_target instrument9 GroundStation187)
	(calibration_target instrument9 GroundStation158)
	(calibration_target instrument9 Star184)
	(calibration_target instrument9 Star201)
	(calibration_target instrument9 Star125)
	(calibration_target instrument9 GroundStation167)
	(calibration_target instrument9 Star14)
	(calibration_target instrument9 Star75)
	(calibration_target instrument9 GroundStation78)
	(calibration_target instrument9 Star205)
	(supports instrument10 infrared2)
	(supports instrument10 image3)
	(calibration_target instrument10 Star25)
	(calibration_target instrument10 Star38)
	(calibration_target instrument10 GroundStation89)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(on_board instrument9 satellite2)
	(on_board instrument10 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet433)
	(supports instrument11 image5)
	(supports instrument11 infrared0)
	(supports instrument11 thermograph4)
	(calibration_target instrument11 GroundStation11)
	(calibration_target instrument11 Star188)
	(calibration_target instrument11 Star164)
	(calibration_target instrument11 Star24)
	(calibration_target instrument11 Star125)
	(calibration_target instrument11 GroundStation89)
	(calibration_target instrument11 Star75)
	(calibration_target instrument11 GroundStation41)
	(calibration_target instrument11 Star157)
	(calibration_target instrument11 GroundStation7)
	(calibration_target instrument11 GroundStation97)
	(calibration_target instrument11 GroundStation120)
	(calibration_target instrument11 GroundStation198)
	(calibration_target instrument11 Star123)
	(calibration_target instrument11 GroundStation127)
	(calibration_target instrument11 GroundStation67)
	(calibration_target instrument11 Star204)
	(calibration_target instrument11 Star29)
	(calibration_target instrument11 GroundStation183)
	(calibration_target instrument11 Star227)
	(calibration_target instrument11 GroundStation146)
	(calibration_target instrument11 GroundStation138)
	(supports instrument12 image5)
	(supports instrument12 image3)
	(supports instrument12 infrared2)
	(calibration_target instrument12 GroundStation158)
	(calibration_target instrument12 GroundStation163)
	(calibration_target instrument12 Star59)
	(calibration_target instrument12 Star80)
	(calibration_target instrument12 GroundStation231)
	(calibration_target instrument12 Star165)
	(calibration_target instrument12 GroundStation169)
	(calibration_target instrument12 Star126)
	(calibration_target instrument12 GroundStation127)
	(calibration_target instrument12 Star64)
	(calibration_target instrument12 GroundStation110)
	(calibration_target instrument12 Star213)
	(calibration_target instrument12 GroundStation166)
	(calibration_target instrument12 Star186)
	(calibration_target instrument12 Star157)
	(calibration_target instrument12 Star34)
	(calibration_target instrument12 Star112)
	(calibration_target instrument12 Star30)
	(calibration_target instrument12 Star101)
	(calibration_target instrument12 Star24)
	(calibration_target instrument12 GroundStation84)
	(calibration_target instrument12 Star19)
	(calibration_target instrument12 Star98)
	(calibration_target instrument12 Star135)
	(calibration_target instrument12 Star91)
	(calibration_target instrument12 Star9)
	(calibration_target instrument12 Star180)
	(calibration_target instrument12 GroundStation140)
	(calibration_target instrument12 GroundStation26)
	(calibration_target instrument12 GroundStation104)
	(calibration_target instrument12 GroundStation220)
	(calibration_target instrument12 GroundStation0)
	(calibration_target instrument12 Star205)
	(calibration_target instrument12 Star162)
	(calibration_target instrument12 Star103)
	(calibration_target instrument12 GroundStation233)
	(calibration_target instrument12 Star136)
	(calibration_target instrument12 GroundStation179)
	(calibration_target instrument12 GroundStation121)
	(calibration_target instrument12 GroundStation1)
	(calibration_target instrument12 GroundStation187)
	(calibration_target instrument12 Star229)
	(calibration_target instrument12 Star28)
	(calibration_target instrument12 GroundStation63)
	(calibration_target instrument12 Star15)
	(calibration_target instrument12 GroundStation90)
	(calibration_target instrument12 Star130)
	(calibration_target instrument12 Star208)
	(calibration_target instrument12 Star114)
	(calibration_target instrument12 GroundStation193)
	(calibration_target instrument12 Star207)
	(calibration_target instrument12 Star52)
	(calibration_target instrument12 Star75)
	(calibration_target instrument12 GroundStation194)
	(calibration_target instrument12 GroundStation53)
	(calibration_target instrument12 GroundStation37)
	(calibration_target instrument12 GroundStation159)
	(calibration_target instrument12 GroundStation139)
	(calibration_target instrument12 Star118)
	(calibration_target instrument12 GroundStation51)
	(calibration_target instrument12 GroundStation196)
	(calibration_target instrument12 GroundStation218)
	(calibration_target instrument12 GroundStation176)
	(calibration_target instrument12 Star125)
	(calibration_target instrument12 GroundStation36)
	(calibration_target instrument12 GroundStation195)
	(calibration_target instrument12 Star173)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet460)
	(supports instrument13 spectrograph1)
	(supports instrument13 image3)
	(calibration_target instrument13 GroundStation210)
	(calibration_target instrument13 Star189)
	(calibration_target instrument13 Star201)
	(calibration_target instrument13 GroundStation93)
	(calibration_target instrument13 GroundStation2)
	(calibration_target instrument13 GroundStation155)
	(calibration_target instrument13 GroundStation177)
	(calibration_target instrument13 Star186)
	(calibration_target instrument13 Star131)
	(calibration_target instrument13 Star219)
	(calibration_target instrument13 GroundStation232)
	(calibration_target instrument13 Star102)
	(calibration_target instrument13 Star54)
	(calibration_target instrument13 GroundStation194)
	(calibration_target instrument13 GroundStation1)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 GroundStation27)
	(calibration_target instrument13 GroundStation71)
	(calibration_target instrument13 Star46)
	(calibration_target instrument13 GroundStation171)
	(calibration_target instrument13 GroundStation83)
	(calibration_target instrument13 GroundStation196)
	(calibration_target instrument13 Star149)
	(calibration_target instrument13 Star197)
	(calibration_target instrument13 Star80)
	(calibration_target instrument13 GroundStation158)
	(calibration_target instrument13 GroundStation140)
	(calibration_target instrument13 GroundStation154)
	(calibration_target instrument13 GroundStation190)
	(calibration_target instrument13 Star5)
	(calibration_target instrument13 Star151)
	(calibration_target instrument13 Star44)
	(calibration_target instrument13 Star123)
	(calibration_target instrument13 GroundStation139)
	(calibration_target instrument13 Star173)
	(calibration_target instrument13 Star21)
	(calibration_target instrument13 GroundStation231)
	(calibration_target instrument13 Star109)
	(calibration_target instrument13 Star209)
	(calibration_target instrument13 GroundStation3)
	(calibration_target instrument13 GroundStation215)
	(calibration_target instrument13 Star23)
	(calibration_target instrument13 GroundStation99)
	(calibration_target instrument13 GroundStation187)
	(calibration_target instrument13 Star98)
	(calibration_target instrument13 Star147)
	(calibration_target instrument13 Star229)
	(calibration_target instrument13 Star19)
	(calibration_target instrument13 GroundStation26)
	(calibration_target instrument13 Star161)
	(calibration_target instrument13 Star39)
	(supports instrument14 infrared2)
	(calibration_target instrument14 GroundStation200)
	(calibration_target instrument14 GroundStation71)
	(calibration_target instrument14 Star74)
	(calibration_target instrument14 Star116)
	(calibration_target instrument14 Star81)
	(calibration_target instrument14 GroundStation159)
	(calibration_target instrument14 Star118)
	(calibration_target instrument14 Star20)
	(calibration_target instrument14 Star157)
	(calibration_target instrument14 GroundStation233)
	(calibration_target instrument14 Star189)
	(calibration_target instrument14 GroundStation8)
	(calibration_target instrument14 Star130)
	(calibration_target instrument14 Star33)
	(calibration_target instrument14 Star30)
	(calibration_target instrument14 GroundStation70)
	(calibration_target instrument14 Star126)
	(calibration_target instrument14 Star47)
	(calibration_target instrument14 GroundStation191)
	(calibration_target instrument14 GroundStation141)
	(calibration_target instrument14 Star28)
	(calibration_target instrument14 Star73)
	(calibration_target instrument14 Star225)
	(calibration_target instrument14 GroundStation163)
	(calibration_target instrument14 GroundStation76)
	(calibration_target instrument14 Star85)
	(calibration_target instrument14 Star142)
	(calibration_target instrument14 Star35)
	(calibration_target instrument14 Star203)
	(calibration_target instrument14 GroundStation26)
	(calibration_target instrument14 GroundStation22)
	(calibration_target instrument14 GroundStation0)
	(calibration_target instrument14 Star135)
	(calibration_target instrument14 GroundStation183)
	(calibration_target instrument14 GroundStation6)
	(calibration_target instrument14 GroundStation160)
	(calibration_target instrument14 GroundStation148)
	(calibration_target instrument14 GroundStation104)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 Star109)
	(calibration_target instrument14 GroundStation56)
	(calibration_target instrument14 GroundStation175)
	(calibration_target instrument14 GroundStation177)
	(calibration_target instrument14 Star186)
	(calibration_target instrument14 GroundStation154)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 Star182)
	(calibration_target instrument14 Star208)
	(calibration_target instrument14 Star91)
	(calibration_target instrument14 GroundStation217)
	(calibration_target instrument14 Star101)
	(calibration_target instrument14 Star192)
	(calibration_target instrument14 GroundStation88)
	(calibration_target instrument14 GroundStation231)
	(calibration_target instrument14 Star172)
	(calibration_target instrument14 Star165)
	(calibration_target instrument14 GroundStation139)
	(calibration_target instrument14 GroundStation97)
	(calibration_target instrument14 GroundStation27)
	(calibration_target instrument14 GroundStation55)
	(calibration_target instrument14 GroundStation45)
	(calibration_target instrument14 Star211)
	(calibration_target instrument14 Star39)
	(calibration_target instrument14 Star69)
	(calibration_target instrument14 GroundStation36)
	(calibration_target instrument14 Star44)
	(calibration_target instrument14 Star224)
	(calibration_target instrument14 GroundStation179)
	(calibration_target instrument14 GroundStation198)
	(calibration_target instrument14 Star164)
	(calibration_target instrument14 Star38)
	(calibration_target instrument14 GroundStation140)
	(calibration_target instrument14 GroundStation155)
	(calibration_target instrument14 GroundStation13)
	(calibration_target instrument14 Star21)
	(calibration_target instrument14 Star173)
	(calibration_target instrument14 Star181)
	(supports instrument15 spectrograph1)
	(supports instrument15 infrared0)
	(calibration_target instrument15 Star223)
	(calibration_target instrument15 GroundStation36)
	(calibration_target instrument15 Star25)
	(calibration_target instrument15 GroundStation16)
	(on_board instrument13 satellite4)
	(on_board instrument14 satellite4)
	(on_board instrument15 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star117)
	(supports instrument16 thermograph4)
	(supports instrument16 spectrograph1)
	(calibration_target instrument16 GroundStation187)
	(calibration_target instrument16 GroundStation177)
	(calibration_target instrument16 Star21)
	(calibration_target instrument16 GroundStation78)
	(calibration_target instrument16 GroundStation13)
	(calibration_target instrument16 Star109)
	(calibration_target instrument16 Star57)
	(calibration_target instrument16 Star131)
	(calibration_target instrument16 Star227)
	(calibration_target instrument16 Star182)
	(calibration_target instrument16 Star85)
	(calibration_target instrument16 GroundStation11)
	(calibration_target instrument16 GroundStation191)
	(calibration_target instrument16 GroundStation158)
	(calibration_target instrument16 Star44)
	(calibration_target instrument16 GroundStation127)
	(calibration_target instrument16 GroundStation232)
	(calibration_target instrument16 Star197)
	(calibration_target instrument16 Star46)
	(calibration_target instrument16 GroundStation104)
	(calibration_target instrument16 Star101)
	(calibration_target instrument16 Star156)
	(calibration_target instrument16 GroundStation139)
	(calibration_target instrument16 Star132)
	(calibration_target instrument16 Star207)
	(calibration_target instrument16 GroundStation99)
	(calibration_target instrument16 GroundStation167)
	(calibration_target instrument16 Star30)
	(calibration_target instrument16 GroundStation3)
	(calibration_target instrument16 GroundStation199)
	(on_board instrument16 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation51)
	(supports instrument17 image5)
	(supports instrument17 image3)
	(supports instrument17 thermograph4)
	(calibration_target instrument17 GroundStation226)
	(calibration_target instrument17 GroundStation41)
	(calibration_target instrument17 Star209)
	(calibration_target instrument17 Star182)
	(calibration_target instrument17 GroundStation171)
	(calibration_target instrument17 Star117)
	(calibration_target instrument17 GroundStation37)
	(calibration_target instrument17 GroundStation218)
	(calibration_target instrument17 Star98)
	(calibration_target instrument17 GroundStation155)
	(calibration_target instrument17 GroundStation158)
	(calibration_target instrument17 Star157)
	(calibration_target instrument17 Star102)
	(calibration_target instrument17 GroundStation55)
	(calibration_target instrument17 Star173)
	(calibration_target instrument17 GroundStation92)
	(calibration_target instrument17 GroundStation140)
	(calibration_target instrument17 GroundStation221)
	(calibration_target instrument17 Star65)
	(calibration_target instrument17 GroundStation6)
	(calibration_target instrument17 Star184)
	(calibration_target instrument17 Star34)
	(calibration_target instrument17 GroundStation233)
	(calibration_target instrument17 Star49)
	(calibration_target instrument17 GroundStation4)
	(calibration_target instrument17 Star54)
	(calibration_target instrument17 Star132)
	(supports instrument18 infrared2)
	(supports instrument18 spectrograph1)
	(supports instrument18 image3)
	(calibration_target instrument18 Star207)
	(calibration_target instrument18 Star112)
	(calibration_target instrument18 GroundStation70)
	(calibration_target instrument18 GroundStation217)
	(calibration_target instrument18 Star5)
	(calibration_target instrument18 Star126)
	(calibration_target instrument18 Star52)
	(calibration_target instrument18 Star48)
	(calibration_target instrument18 GroundStation177)
	(calibration_target instrument18 Star123)
	(calibration_target instrument18 GroundStation212)
	(calibration_target instrument18 Star39)
	(calibration_target instrument18 Star113)
	(calibration_target instrument18 GroundStation55)
	(calibration_target instrument18 Star228)
	(calibration_target instrument18 GroundStation110)
	(calibration_target instrument18 GroundStation194)
	(supports instrument19 image5)
	(supports instrument19 infrared2)
	(supports instrument19 infrared0)
	(calibration_target instrument19 GroundStation221)
	(calibration_target instrument19 GroundStation179)
	(calibration_target instrument19 Star149)
	(calibration_target instrument19 Star19)
	(calibration_target instrument19 Star130)
	(calibration_target instrument19 Star24)
	(calibration_target instrument19 GroundStation196)
	(calibration_target instrument19 Star105)
	(calibration_target instrument19 GroundStation92)
	(calibration_target instrument19 Star186)
	(calibration_target instrument19 Star21)
	(calibration_target instrument19 Star38)
	(calibration_target instrument19 Star106)
	(calibration_target instrument19 Star17)
	(calibration_target instrument19 GroundStation110)
	(calibration_target instrument19 Star95)
	(calibration_target instrument19 GroundStation190)
	(calibration_target instrument19 Star68)
	(calibration_target instrument19 GroundStation140)
	(calibration_target instrument19 Star131)
	(calibration_target instrument19 GroundStation63)
	(calibration_target instrument19 GroundStation90)
	(calibration_target instrument19 GroundStation166)
	(calibration_target instrument19 GroundStation2)
	(calibration_target instrument19 Star60)
	(calibration_target instrument19 Star118)
	(calibration_target instrument19 Star170)
	(calibration_target instrument19 GroundStation154)
	(calibration_target instrument19 GroundStation8)
	(calibration_target instrument19 Star50)
	(calibration_target instrument19 Star39)
	(calibration_target instrument19 GroundStation97)
	(on_board instrument17 satellite6)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star57)
	(supports instrument20 infrared2)
	(supports instrument20 infrared0)
	(supports instrument20 image5)
	(calibration_target instrument20 Star98)
	(calibration_target instrument20 Star54)
	(calibration_target instrument20 GroundStation171)
	(supports instrument21 infrared0)
	(calibration_target instrument21 GroundStation62)
	(calibration_target instrument21 Star87)
	(calibration_target instrument21 Star113)
	(calibration_target instrument21 Star122)
	(calibration_target instrument21 Star21)
	(calibration_target instrument21 GroundStation107)
	(calibration_target instrument21 GroundStation176)
	(calibration_target instrument21 GroundStation41)
	(calibration_target instrument21 Star34)
	(calibration_target instrument21 Star40)
	(calibration_target instrument21 Star108)
	(calibration_target instrument21 Star147)
	(calibration_target instrument21 Star125)
	(calibration_target instrument21 GroundStation94)
	(calibration_target instrument21 GroundStation220)
	(calibration_target instrument21 GroundStation226)
	(calibration_target instrument21 Star101)
	(calibration_target instrument21 GroundStation43)
	(supports instrument22 image5)
	(supports instrument22 infrared2)
	(supports instrument22 image3)
	(calibration_target instrument22 GroundStation11)
	(calibration_target instrument22 GroundStation177)
	(calibration_target instrument22 GroundStation107)
	(calibration_target instrument22 Star85)
	(calibration_target instrument22 GroundStation234)
	(calibration_target instrument22 Star5)
	(calibration_target instrument22 GroundStation121)
	(calibration_target instrument22 GroundStation115)
	(calibration_target instrument22 Star180)
	(calibration_target instrument22 GroundStation191)
	(calibration_target instrument22 GroundStation32)
	(calibration_target instrument22 GroundStation2)
	(calibration_target instrument22 Star123)
	(calibration_target instrument22 GroundStation155)
	(calibration_target instrument22 Star86)
	(calibration_target instrument22 GroundStation218)
	(calibration_target instrument22 GroundStation110)
	(calibration_target instrument22 Star207)
	(calibration_target instrument22 GroundStation221)
	(calibration_target instrument22 Star184)
	(calibration_target instrument22 Star57)
	(calibration_target instrument22 GroundStation67)
	(calibration_target instrument22 GroundStation16)
	(calibration_target instrument22 GroundStation215)
	(calibration_target instrument22 GroundStation3)
	(calibration_target instrument22 GroundStation45)
	(calibration_target instrument22 Star87)
	(calibration_target instrument22 Star188)
	(calibration_target instrument22 Star21)
	(calibration_target instrument22 Star172)
	(calibration_target instrument22 GroundStation94)
	(calibration_target instrument22 GroundStation139)
	(calibration_target instrument22 Star14)
	(calibration_target instrument22 Star98)
	(calibration_target instrument22 GroundStation195)
	(calibration_target instrument22 GroundStation206)
	(calibration_target instrument22 Star65)
	(calibration_target instrument22 Star35)
	(calibration_target instrument22 Star164)
	(calibration_target instrument22 Star147)
	(calibration_target instrument22 Star216)
	(calibration_target instrument22 GroundStation160)
	(calibration_target instrument22 GroundStation70)
	(calibration_target instrument22 Star131)
	(calibration_target instrument22 GroundStation10)
	(calibration_target instrument22 Star19)
	(calibration_target instrument22 Star81)
	(calibration_target instrument22 Star113)
	(calibration_target instrument22 Star49)
	(calibration_target instrument22 GroundStation148)
	(calibration_target instrument22 GroundStation4)
	(calibration_target instrument22 Star151)
	(calibration_target instrument22 Star227)
	(calibration_target instrument22 Star75)
	(calibration_target instrument22 GroundStation127)
	(calibration_target instrument22 GroundStation51)
	(calibration_target instrument22 Star46)
	(on_board instrument20 satellite7)
	(on_board instrument21 satellite7)
	(on_board instrument22 satellite7)
	(power_avail satellite7)
	(pointing satellite7 Star30)
	(supports instrument23 image3)
	(calibration_target instrument23 GroundStation218)
	(calibration_target instrument23 GroundStation196)
	(calibration_target instrument23 GroundStation16)
	(calibration_target instrument23 Star66)
	(calibration_target instrument23 Star29)
	(calibration_target instrument23 Star164)
	(calibration_target instrument23 GroundStation234)
	(calibration_target instrument23 Star9)
	(calibration_target instrument23 GroundStation176)
	(calibration_target instrument23 GroundStation32)
	(calibration_target instrument23 GroundStation90)
	(calibration_target instrument23 GroundStation159)
	(calibration_target instrument23 GroundStation127)
	(calibration_target instrument23 Star23)
	(calibration_target instrument23 Star40)
	(calibration_target instrument23 GroundStation107)
	(calibration_target instrument23 Star168)
	(calibration_target instrument23 Star20)
	(calibration_target instrument23 Star222)
	(calibration_target instrument23 GroundStation121)
	(calibration_target instrument23 GroundStation41)
	(calibration_target instrument23 Star117)
	(calibration_target instrument23 Star230)
	(calibration_target instrument23 Star47)
	(calibration_target instrument23 Star49)
	(calibration_target instrument23 Star172)
	(calibration_target instrument23 GroundStation11)
	(calibration_target instrument23 Star213)
	(calibration_target instrument23 Star114)
	(calibration_target instrument23 GroundStation37)
	(calibration_target instrument23 GroundStation84)
	(calibration_target instrument23 Star235)
	(calibration_target instrument23 Star80)
	(calibration_target instrument23 Star174)
	(calibration_target instrument23 GroundStation150)
	(calibration_target instrument23 Star28)
	(calibration_target instrument23 Star123)
	(calibration_target instrument23 GroundStation144)
	(calibration_target instrument23 GroundStation171)
	(calibration_target instrument23 GroundStation179)
	(calibration_target instrument23 GroundStation129)
	(calibration_target instrument23 Star142)
	(calibration_target instrument23 Star204)
	(calibration_target instrument23 Star147)
	(calibration_target instrument23 Star50)
	(calibration_target instrument23 Star188)
	(calibration_target instrument23 Star131)
	(calibration_target instrument23 GroundStation226)
	(calibration_target instrument23 Star91)
	(calibration_target instrument23 GroundStation206)
	(calibration_target instrument23 Star130)
	(calibration_target instrument23 GroundStation133)
	(calibration_target instrument23 GroundStation71)
	(calibration_target instrument23 GroundStation220)
	(calibration_target instrument23 Star44)
	(calibration_target instrument23 Star161)
	(calibration_target instrument23 Star170)
	(calibration_target instrument23 GroundStation232)
	(calibration_target instrument23 GroundStation36)
	(calibration_target instrument23 Star19)
	(calibration_target instrument23 GroundStation61)
	(calibration_target instrument23 GroundStation140)
	(calibration_target instrument23 GroundStation110)
	(calibration_target instrument23 GroundStation198)
	(calibration_target instrument23 GroundStation51)
	(calibration_target instrument23 Star145)
	(calibration_target instrument23 Star68)
	(calibration_target instrument23 Star101)
	(calibration_target instrument23 Star15)
	(calibration_target instrument23 GroundStation163)
	(calibration_target instrument23 GroundStation99)
	(calibration_target instrument23 Star219)
	(calibration_target instrument23 Star34)
	(calibration_target instrument23 GroundStation217)
	(calibration_target instrument23 Star96)
	(calibration_target instrument23 GroundStation26)
	(calibration_target instrument23 GroundStation187)
	(calibration_target instrument23 Star184)
	(supports instrument24 infrared2)
	(supports instrument24 image5)
	(supports instrument24 spectrograph1)
	(calibration_target instrument24 GroundStation82)
	(calibration_target instrument24 Star208)
	(calibration_target instrument24 Star184)
	(calibration_target instrument24 GroundStation107)
	(calibration_target instrument24 GroundStation193)
	(calibration_target instrument24 GroundStation146)
	(calibration_target instrument24 Star39)
	(calibration_target instrument24 Star112)
	(calibration_target instrument24 GroundStation210)
	(calibration_target instrument24 Star48)
	(calibration_target instrument24 Star69)
	(calibration_target instrument24 Star145)
	(calibration_target instrument24 GroundStation187)
	(calibration_target instrument24 GroundStation200)
	(calibration_target instrument24 Star86)
	(calibration_target instrument24 GroundStation92)
	(calibration_target instrument24 Star223)
	(calibration_target instrument24 Star197)
	(calibration_target instrument24 GroundStation231)
	(calibration_target instrument24 GroundStation63)
	(calibration_target instrument24 Star5)
	(calibration_target instrument24 GroundStation133)
	(calibration_target instrument24 GroundStation51)
	(calibration_target instrument24 Star216)
	(calibration_target instrument24 Star101)
	(calibration_target instrument24 Star103)
	(calibration_target instrument24 Star135)
	(calibration_target instrument24 Star132)
	(calibration_target instrument24 Star161)
	(calibration_target instrument24 GroundStation160)
	(on_board instrument23 satellite8)
	(on_board instrument24 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star246)
	(supports instrument25 spectrograph1)
	(calibration_target instrument25 GroundStation176)
	(calibration_target instrument25 GroundStation83)
	(calibration_target instrument25 GroundStation71)
	(calibration_target instrument25 GroundStation56)
	(calibration_target instrument25 GroundStation194)
	(calibration_target instrument25 Star54)
	(calibration_target instrument25 Star165)
	(calibration_target instrument25 Star48)
	(calibration_target instrument25 Star151)
	(calibration_target instrument25 GroundStation70)
	(calibration_target instrument25 GroundStation41)
	(calibration_target instrument25 GroundStation51)
	(calibration_target instrument25 Star24)
	(calibration_target instrument25 Star106)
	(calibration_target instrument25 Star214)
	(calibration_target instrument25 Star103)
	(supports instrument26 image5)
	(supports instrument26 infrared2)
	(calibration_target instrument26 GroundStation79)
	(calibration_target instrument26 Star9)
	(calibration_target instrument26 GroundStation32)
	(calibration_target instrument26 GroundStation191)
	(calibration_target instrument26 GroundStation104)
	(calibration_target instrument26 GroundStation198)
	(calibration_target instrument26 GroundStation4)
	(calibration_target instrument26 GroundStation179)
	(calibration_target instrument26 Star48)
	(calibration_target instrument26 GroundStation3)
	(calibration_target instrument26 GroundStation99)
	(calibration_target instrument26 GroundStation129)
	(calibration_target instrument26 GroundStation63)
	(calibration_target instrument26 GroundStation27)
	(calibration_target instrument26 GroundStation71)
	(calibration_target instrument26 GroundStation199)
	(calibration_target instrument26 GroundStation143)
	(calibration_target instrument26 Star204)
	(calibration_target instrument26 Star65)
	(calibration_target instrument26 Star106)
	(calibration_target instrument26 Star153)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 Star20)
	(calibration_target instrument26 Star130)
	(calibration_target instrument26 GroundStation177)
	(calibration_target instrument26 Star40)
	(calibration_target instrument26 Star137)
	(calibration_target instrument26 Star124)
	(calibration_target instrument26 Star227)
	(calibration_target instrument26 Star142)
	(calibration_target instrument26 GroundStation200)
	(calibration_target instrument26 GroundStation67)
	(calibration_target instrument26 Star113)
	(calibration_target instrument26 GroundStation144)
	(calibration_target instrument26 Star134)
	(calibration_target instrument26 GroundStation37)
	(calibration_target instrument26 Star25)
	(calibration_target instrument26 Star81)
	(calibration_target instrument26 GroundStation166)
	(calibration_target instrument26 GroundStation76)
	(calibration_target instrument26 Star208)
	(calibration_target instrument26 GroundStation107)
	(calibration_target instrument26 Star197)
	(calibration_target instrument26 GroundStation159)
	(calibration_target instrument26 GroundStation89)
	(calibration_target instrument26 GroundStation133)
	(calibration_target instrument26 Star31)
	(calibration_target instrument26 GroundStation93)
	(calibration_target instrument26 Star207)
	(calibration_target instrument26 Star21)
	(calibration_target instrument26 GroundStation120)
	(calibration_target instrument26 Star34)
	(calibration_target instrument26 Star147)
	(calibration_target instrument26 Star135)
	(calibration_target instrument26 GroundStation183)
	(calibration_target instrument26 Star73)
	(calibration_target instrument26 GroundStation36)
	(calibration_target instrument26 Star116)
	(calibration_target instrument26 GroundStation13)
	(calibration_target instrument26 Star58)
	(calibration_target instrument26 GroundStation187)
	(calibration_target instrument26 Star229)
	(calibration_target instrument26 GroundStation115)
	(calibration_target instrument26 Star52)
	(calibration_target instrument26 Star164)
	(supports instrument27 infrared2)
	(supports instrument27 image5)
	(supports instrument27 spectrograph1)
	(calibration_target instrument27 GroundStation215)
	(calibration_target instrument27 Star168)
	(calibration_target instrument27 GroundStation160)
	(calibration_target instrument27 Star207)
	(calibration_target instrument27 Star40)
	(calibration_target instrument27 Star54)
	(calibration_target instrument27 Star184)
	(calibration_target instrument27 GroundStation163)
	(calibration_target instrument27 GroundStation140)
	(calibration_target instrument27 Star47)
	(calibration_target instrument27 GroundStation36)
	(calibration_target instrument27 GroundStation127)
	(calibration_target instrument27 GroundStation90)
	(calibration_target instrument27 GroundStation22)
	(calibration_target instrument27 Star52)
	(calibration_target instrument27 GroundStation104)
	(calibration_target instrument27 GroundStation93)
	(calibration_target instrument27 GroundStation199)
	(calibration_target instrument27 Star69)
	(calibration_target instrument27 Star25)
	(calibration_target instrument27 GroundStation41)
	(calibration_target instrument27 Star142)
	(calibration_target instrument27 Star205)
	(calibration_target instrument27 Star117)
	(calibration_target instrument27 GroundStation82)
	(calibration_target instrument27 Star28)
	(calibration_target instrument27 Star188)
	(calibration_target instrument27 GroundStation217)
	(calibration_target instrument27 Star14)
	(calibration_target instrument27 GroundStation155)
	(calibration_target instrument27 Star180)
	(calibration_target instrument27 GroundStation176)
	(calibration_target instrument27 GroundStation63)
	(calibration_target instrument27 Star9)
	(calibration_target instrument27 GroundStation150)
	(calibration_target instrument27 Star208)
	(calibration_target instrument27 GroundStation51)
	(calibration_target instrument27 Star30)
	(calibration_target instrument27 Star228)
	(calibration_target instrument27 Star211)
	(calibration_target instrument27 Star165)
	(calibration_target instrument27 GroundStation79)
	(calibration_target instrument27 GroundStation193)
	(calibration_target instrument27 GroundStation190)
	(calibration_target instrument27 Star192)
	(calibration_target instrument27 Star85)
	(calibration_target instrument27 GroundStation8)
	(calibration_target instrument27 Star106)
	(calibration_target instrument27 GroundStation148)
	(calibration_target instrument27 Star130)
	(calibration_target instrument27 Star116)
	(calibration_target instrument27 Star100)
	(calibration_target instrument27 Star147)
	(calibration_target instrument27 Star81)
	(calibration_target instrument27 GroundStation196)
	(calibration_target instrument27 Star170)
	(calibration_target instrument27 Star35)
	(calibration_target instrument27 GroundStation1)
	(calibration_target instrument27 Star124)
	(calibration_target instrument27 GroundStation56)
	(calibration_target instrument27 Star50)
	(calibration_target instrument27 Star17)
	(calibration_target instrument27 GroundStation61)
	(calibration_target instrument27 GroundStation110)
	(calibration_target instrument27 Star60)
	(calibration_target instrument27 GroundStation3)
	(calibration_target instrument27 GroundStation154)
	(calibration_target instrument27 GroundStation198)
	(calibration_target instrument27 GroundStation0)
	(calibration_target instrument27 Star235)
	(calibration_target instrument27 Star59)
	(calibration_target instrument27 GroundStation37)
	(calibration_target instrument27 Star174)
	(calibration_target instrument27 Star34)
	(calibration_target instrument27 GroundStation175)
	(calibration_target instrument27 GroundStation231)
	(calibration_target instrument27 GroundStation6)
	(supports instrument28 image3)
	(supports instrument28 spectrograph1)
	(calibration_target instrument28 Star117)
	(calibration_target instrument28 GroundStation82)
	(calibration_target instrument28 GroundStation45)
	(calibration_target instrument28 Star87)
	(calibration_target instrument28 Star5)
	(calibration_target instrument28 Star192)
	(calibration_target instrument28 GroundStation220)
	(calibration_target instrument28 Star21)
	(calibration_target instrument28 Star96)
	(calibration_target instrument28 Star95)
	(calibration_target instrument28 GroundStation176)
	(calibration_target instrument28 Star188)
	(calibration_target instrument28 Star19)
	(calibration_target instrument28 Star168)
	(calibration_target instrument28 GroundStation55)
	(calibration_target instrument28 Star52)
	(calibration_target instrument28 Star46)
	(calibration_target instrument28 Star17)
	(calibration_target instrument28 Star118)
	(calibration_target instrument28 Star147)
	(calibration_target instrument28 Star85)
	(calibration_target instrument28 Star65)
	(calibration_target instrument28 GroundStation97)
	(calibration_target instrument28 Star174)
	(calibration_target instrument28 GroundStation175)
	(calibration_target instrument28 Star59)
	(calibration_target instrument28 Star122)
	(calibration_target instrument28 Star156)
	(calibration_target instrument28 GroundStation169)
	(calibration_target instrument28 Star48)
	(calibration_target instrument28 Star207)
	(calibration_target instrument28 Star54)
	(calibration_target instrument28 GroundStation89)
	(calibration_target instrument28 GroundStation139)
	(calibration_target instrument28 Star98)
	(calibration_target instrument28 GroundStation160)
	(calibration_target instrument28 Star136)
	(calibration_target instrument28 GroundStation159)
	(calibration_target instrument28 GroundStation13)
	(calibration_target instrument28 Star49)
	(calibration_target instrument28 Star124)
	(calibration_target instrument28 GroundStation16)
	(calibration_target instrument28 GroundStation195)
	(calibration_target instrument28 GroundStation7)
	(calibration_target instrument28 Star66)
	(calibration_target instrument28 Star86)
	(calibration_target instrument28 GroundStation185)
	(calibration_target instrument28 Star204)
	(calibration_target instrument28 GroundStation212)
	(calibration_target instrument28 Star105)
	(calibration_target instrument28 GroundStation92)
	(calibration_target instrument28 GroundStation202)
	(calibration_target instrument28 Star211)
	(calibration_target instrument28 Star20)
	(calibration_target instrument28 GroundStation0)
	(calibration_target instrument28 Star135)
	(calibration_target instrument28 Star80)
	(calibration_target instrument28 GroundStation93)
	(calibration_target instrument28 GroundStation32)
	(calibration_target instrument28 Star132)
	(calibration_target instrument28 Star227)
	(calibration_target instrument28 GroundStation4)
	(calibration_target instrument28 GroundStation234)
	(calibration_target instrument28 Star157)
	(calibration_target instrument28 Star25)
	(calibration_target instrument28 GroundStation27)
	(on_board instrument25 satellite9)
	(on_board instrument26 satellite9)
	(on_board instrument27 satellite9)
	(on_board instrument28 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Star52)
	(supports instrument29 image5)
	(calibration_target instrument29 Star116)
	(calibration_target instrument29 Star114)
	(calibration_target instrument29 GroundStation231)
	(calibration_target instrument29 Star224)
	(calibration_target instrument29 GroundStation62)
	(calibration_target instrument29 GroundStation32)
	(calibration_target instrument29 Star57)
	(calibration_target instrument29 Star130)
	(calibration_target instrument29 GroundStation169)
	(calibration_target instrument29 GroundStation8)
	(calibration_target instrument29 GroundStation160)
	(calibration_target instrument29 GroundStation99)
	(calibration_target instrument29 Star46)
	(on_board instrument29 satellite10)
	(power_avail satellite10)
	(pointing satellite10 Star211)
)
(:goal (and
	(pointing satellite0 Phenomenon259)
	(pointing satellite1 Phenomenon353)
	(pointing satellite2 Star85)
	(pointing satellite3 Star240)
	(pointing satellite4 Phenomenon320)
	(have_image Phenomenon236 image5)
	(have_image Star237 image3)
	(have_image Star237 infrared0)
	(have_image Star238 image3)
	(have_image Star238 image5)
	(have_image Star240 image5)
	(have_image Planet242 thermograph4)
	(have_image Planet242 spectrograph1)
	(have_image Planet243 thermograph4)
	(have_image Planet244 spectrograph1)
	(have_image Planet244 thermograph4)
	(have_image Planet247 thermograph4)
	(have_image Phenomenon248 spectrograph1)
	(have_image Phenomenon249 spectrograph1)
	(have_image Phenomenon249 thermograph4)
	(have_image Phenomenon250 infrared0)
	(have_image Phenomenon251 spectrograph1)
	(have_image Phenomenon252 thermograph4)
	(have_image Planet253 infrared0)
	(have_image Star254 spectrograph1)
	(have_image Star254 image3)
	(have_image Star255 image3)
	(have_image Star256 image3)
	(have_image Star256 thermograph4)
	(have_image Phenomenon258 infrared2)
	(have_image Phenomenon259 thermograph4)
	(have_image Star260 thermograph4)
	(have_image Star261 infrared0)
	(have_image Star261 thermograph4)
	(have_image Phenomenon263 image3)
	(have_image Planet264 spectrograph1)
	(have_image Planet266 image3)
	(have_image Star267 image3)
	(have_image Star268 infrared2)
	(have_image Star268 image3)
	(have_image Star269 image5)
	(have_image Star269 spectrograph1)
	(have_image Phenomenon270 image3)
	(have_image Phenomenon270 infrared0)
	(have_image Phenomenon271 image5)
	(have_image Phenomenon272 image3)
	(have_image Phenomenon273 infrared0)
	(have_image Phenomenon275 image5)
	(have_image Phenomenon276 image5)
	(have_image Phenomenon276 infrared0)
	(have_image Planet277 image5)
	(have_image Star278 thermograph4)
	(have_image Star280 infrared0)
	(have_image Star280 infrared2)
	(have_image Phenomenon282 thermograph4)
	(have_image Star283 infrared2)
	(have_image Planet284 image5)
	(have_image Phenomenon285 thermograph4)
	(have_image Star287 spectrograph1)
	(have_image Phenomenon288 infrared2)
	(have_image Phenomenon288 infrared0)
	(have_image Phenomenon289 image3)
	(have_image Star290 infrared2)
	(have_image Planet291 infrared2)
	(have_image Planet291 image5)
	(have_image Planet292 infrared0)
	(have_image Phenomenon293 infrared0)
	(have_image Phenomenon293 image5)
	(have_image Phenomenon296 image5)
	(have_image Phenomenon296 spectrograph1)
	(have_image Phenomenon297 infrared2)
	(have_image Planet298 thermograph4)
	(have_image Star299 infrared2)
	(have_image Phenomenon300 infrared2)
	(have_image Phenomenon300 thermograph4)
	(have_image Phenomenon301 thermograph4)
	(have_image Planet302 thermograph4)
	(have_image Planet302 infrared0)
	(have_image Star303 infrared0)
	(have_image Star303 image3)
	(have_image Phenomenon304 image3)
	(have_image Planet305 spectrograph1)
	(have_image Phenomenon306 image5)
	(have_image Phenomenon306 spectrograph1)
	(have_image Star307 infrared2)
	(have_image Planet308 spectrograph1)
	(have_image Planet309 image5)
	(have_image Planet309 infrared0)
	(have_image Planet310 image3)
	(have_image Planet310 infrared2)
	(have_image Phenomenon312 infrared0)
	(have_image Planet313 thermograph4)
	(have_image Planet313 infrared2)
	(have_image Planet314 thermograph4)
	(have_image Planet314 infrared0)
	(have_image Planet315 thermograph4)
	(have_image Planet316 infrared2)
	(have_image Phenomenon317 infrared2)
	(have_image Star318 infrared2)
	(have_image Star318 thermograph4)
	(have_image Planet319 thermograph4)
	(have_image Planet319 image3)
	(have_image Phenomenon320 thermograph4)
	(have_image Phenomenon320 image5)
	(have_image Phenomenon321 thermograph4)
	(have_image Phenomenon321 infrared0)
	(have_image Star322 infrared2)
	(have_image Star322 spectrograph1)
	(have_image Planet323 infrared2)
	(have_image Planet324 thermograph4)
	(have_image Phenomenon326 image5)
	(have_image Phenomenon327 infrared2)
	(have_image Phenomenon327 thermograph4)
	(have_image Star328 spectrograph1)
	(have_image Planet329 image3)
	(have_image Star330 image5)
	(have_image Star330 image3)
	(have_image Star331 thermograph4)
	(have_image Star331 infrared0)
	(have_image Planet332 infrared0)
	(have_image Planet332 image5)
	(have_image Star333 infrared0)
	(have_image Planet334 image3)
	(have_image Phenomenon335 infrared0)
	(have_image Planet336 infrared0)
	(have_image Planet337 infrared2)
	(have_image Planet337 image5)
	(have_image Phenomenon338 infrared2)
	(have_image Phenomenon339 image5)
	(have_image Star341 infrared0)
	(have_image Star341 thermograph4)
	(have_image Star342 spectrograph1)
	(have_image Star342 infrared2)
	(have_image Planet343 image5)
	(have_image Planet343 infrared2)
	(have_image Star344 image5)
	(have_image Planet345 image5)
	(have_image Planet345 infrared0)
	(have_image Planet346 image5)
	(have_image Planet346 image3)
	(have_image Phenomenon347 infrared0)
	(have_image Phenomenon347 spectrograph1)
	(have_image Star348 image5)
	(have_image Planet349 spectrograph1)
	(have_image Phenomenon351 image3)
	(have_image Star352 image5)
	(have_image Phenomenon353 infrared0)
	(have_image Phenomenon353 image5)
	(have_image Phenomenon354 infrared2)
	(have_image Star355 infrared0)
	(have_image Star355 image3)
	(have_image Phenomenon356 thermograph4)
	(have_image Phenomenon356 infrared0)
	(have_image Planet357 infrared2)
	(have_image Planet357 thermograph4)
	(have_image Star358 image5)
	(have_image Star358 infrared2)
	(have_image Phenomenon359 image3)
	(have_image Phenomenon360 infrared2)
	(have_image Planet361 infrared0)
	(have_image Planet361 image3)
	(have_image Planet362 spectrograph1)
	(have_image Star363 infrared0)
	(have_image Star363 infrared2)
	(have_image Planet364 spectrograph1)
	(have_image Star365 infrared0)
	(have_image Star365 image5)
	(have_image Phenomenon366 infrared2)
	(have_image Phenomenon367 infrared2)
	(have_image Phenomenon367 image5)
	(have_image Star368 thermograph4)
	(have_image Star369 infrared0)
	(have_image Phenomenon371 thermograph4)
	(have_image Phenomenon371 infrared0)
	(have_image Phenomenon372 image3)
	(have_image Phenomenon372 spectrograph1)
	(have_image Planet373 image5)
	(have_image Planet373 infrared2)
	(have_image Phenomenon374 thermograph4)
	(have_image Planet375 thermograph4)
	(have_image Phenomenon376 image5)
	(have_image Phenomenon377 image3)
	(have_image Phenomenon378 spectrograph1)
	(have_image Planet379 infrared2)
	(have_image Planet379 spectrograph1)
	(have_image Phenomenon380 infrared2)
	(have_image Star381 image3)
	(have_image Star381 infrared2)
	(have_image Planet382 infrared0)
	(have_image Planet382 infrared2)
	(have_image Planet383 spectrograph1)
	(have_image Planet383 image5)
	(have_image Phenomenon384 image3)
	(have_image Phenomenon384 spectrograph1)
	(have_image Phenomenon385 image5)
	(have_image Planet386 image3)
	(have_image Planet386 thermograph4)
	(have_image Planet387 spectrograph1)
	(have_image Planet387 thermograph4)
	(have_image Phenomenon388 infrared0)
	(have_image Planet389 image3)
	(have_image Phenomenon390 infrared2)
	(have_image Planet391 image3)
	(have_image Planet392 thermograph4)
	(have_image Star393 spectrograph1)
	(have_image Planet394 infrared0)
	(have_image Planet394 image5)
	(have_image Phenomenon396 spectrograph1)
	(have_image Phenomenon397 infrared0)
	(have_image Star398 spectrograph1)
	(have_image Planet400 image3)
	(have_image Planet401 image3)
	(have_image Planet401 thermograph4)
	(have_image Planet402 image3)
	(have_image Star403 image5)
	(have_image Star403 thermograph4)
	(have_image Planet404 image3)
	(have_image Planet405 thermograph4)
	(have_image Planet405 image3)
	(have_image Star406 image5)
	(have_image Star406 infrared0)
	(have_image Phenomenon408 image5)
	(have_image Phenomenon408 infrared0)
	(have_image Phenomenon409 image5)
	(have_image Star410 image3)
	(have_image Phenomenon411 spectrograph1)
	(have_image Phenomenon411 image5)
	(have_image Star412 image5)
	(have_image Star412 infrared2)
	(have_image Planet413 image3)
	(have_image Planet413 infrared2)
	(have_image Star414 image5)
	(have_image Phenomenon415 spectrograph1)
	(have_image Phenomenon415 image3)
	(have_image Star416 infrared0)
	(have_image Star416 image3)
	(have_image Phenomenon417 spectrograph1)
	(have_image Phenomenon417 image5)
	(have_image Planet418 infrared2)
	(have_image Planet418 spectrograph1)
	(have_image Phenomenon419 image5)
	(have_image Phenomenon419 infrared0)
	(have_image Planet420 spectrograph1)
	(have_image Planet420 thermograph4)
	(have_image Planet422 spectrograph1)
	(have_image Star423 infrared2)
	(have_image Star424 infrared0)
	(have_image Planet425 image3)
	(have_image Phenomenon426 thermograph4)
	(have_image Phenomenon427 infrared0)
	(have_image Star428 image5)
	(have_image Planet429 thermograph4)
	(have_image Phenomenon430 image3)
	(have_image Star431 infrared2)
	(have_image Phenomenon432 infrared2)
	(have_image Planet433 spectrograph1)
	(have_image Planet433 image3)
	(have_image Star435 image5)
	(have_image Phenomenon436 thermograph4)
	(have_image Star437 infrared2)
	(have_image Star437 spectrograph1)
	(have_image Planet438 image5)
	(have_image Planet439 image5)
	(have_image Planet439 spectrograph1)
	(have_image Star440 image3)
	(have_image Star440 thermograph4)
	(have_image Planet441 spectrograph1)
	(have_image Planet441 image3)
	(have_image Star442 thermograph4)
	(have_image Star442 image3)
	(have_image Phenomenon443 thermograph4)
	(have_image Planet444 spectrograph1)
	(have_image Planet444 infrared0)
	(have_image Star445 thermograph4)
	(have_image Planet446 thermograph4)
	(have_image Planet447 image3)
	(have_image Planet447 spectrograph1)
	(have_image Star449 spectrograph1)
	(have_image Phenomenon450 image3)
	(have_image Phenomenon450 thermograph4)
	(have_image Planet451 image5)
	(have_image Planet451 thermograph4)
	(have_image Planet452 image5)
	(have_image Phenomenon453 image3)
	(have_image Phenomenon454 infrared2)
	(have_image Planet455 infrared2)
	(have_image Planet457 infrared0)
	(have_image Planet458 image3)
	(have_image Planet458 infrared2)
	(have_image Planet459 image5)
	(have_image Planet459 infrared0)
	(have_image Planet461 image5)
	(have_image Planet461 spectrograph1)
	(have_image Phenomenon462 infrared2)
	(have_image Phenomenon463 thermograph4)
	(have_image Phenomenon463 image3)
	(have_image Planet464 infrared2)
	(have_image Planet464 image3)
	(have_image Star466 infrared0)
	(have_image Planet467 image5)
	(have_image Planet467 spectrograph1)
	(have_image Phenomenon468 infrared0)
	(have_image Planet469 infrared2)
	(have_image Planet470 thermograph4)
	(have_image Planet470 image5)
	(have_image Planet471 spectrograph1)
))

)
