(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	satellite4 - satellite
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite5 - satellite
	instrument13 - instrument
	instrument14 - instrument
	instrument15 - instrument
	instrument16 - instrument
	instrument17 - instrument
	satellite6 - satellite
	instrument18 - instrument
	instrument19 - instrument
	instrument20 - instrument
	instrument21 - instrument
	instrument22 - instrument
	satellite7 - satellite
	instrument23 - instrument
	satellite8 - satellite
	instrument24 - instrument
	instrument25 - instrument
	instrument26 - instrument
	instrument27 - instrument
	instrument28 - instrument
	satellite9 - satellite
	instrument29 - instrument
	instrument30 - instrument
	satellite10 - satellite
	instrument31 - instrument
	instrument32 - instrument
	instrument33 - instrument
	instrument34 - instrument
	instrument35 - instrument
	satellite11 - satellite
	instrument36 - instrument
	instrument37 - instrument
	satellite12 - satellite
	instrument38 - instrument
	image7 - mode
	spectrograph0 - mode
	spectrograph1 - mode
	spectrograph6 - mode
	thermograph4 - mode
	infrared5 - mode
	spectrograph2 - mode
	infrared3 - mode
	Star168 - direction
	Star1 - direction
	Star181 - direction
	GroundStation205 - direction
	Star75 - direction
	Star179 - direction
	GroundStation218 - direction
	Star191 - direction
	GroundStation43 - direction
	Star17 - direction
	GroundStation137 - direction
	Star162 - direction
	Star32 - direction
	GroundStation16 - direction
	Star233 - direction
	Star20 - direction
	GroundStation193 - direction
	GroundStation100 - direction
	GroundStation183 - direction
	GroundStation213 - direction
	Star175 - direction
	GroundStation208 - direction
	GroundStation158 - direction
	GroundStation97 - direction
	Star36 - direction
	Star180 - direction
	GroundStation186 - direction
	GroundStation225 - direction
	GroundStation163 - direction
	Star227 - direction
	GroundStation190 - direction
	Star12 - direction
	GroundStation126 - direction
	GroundStation25 - direction
	GroundStation10 - direction
	GroundStation169 - direction
	Star110 - direction
	GroundStation70 - direction
	GroundStation124 - direction
	GroundStation177 - direction
	GroundStation101 - direction
	Star9 - direction
	GroundStation98 - direction
	Star202 - direction
	Star90 - direction
	GroundStation145 - direction
	Star74 - direction
	GroundStation55 - direction
	GroundStation40 - direction
	GroundStation69 - direction
	GroundStation132 - direction
	GroundStation39 - direction
	GroundStation104 - direction
	Star156 - direction
	GroundStation117 - direction
	Star182 - direction
	Star231 - direction
	Star73 - direction
	GroundStation5 - direction
	Star224 - direction
	GroundStation56 - direction
	GroundStation164 - direction
	Star107 - direction
	Star61 - direction
	Star114 - direction
	GroundStation41 - direction
	Star160 - direction
	Star120 - direction
	GroundStation172 - direction
	GroundStation108 - direction
	GroundStation138 - direction
	Star222 - direction
	GroundStation146 - direction
	Star14 - direction
	Star0 - direction
	Star192 - direction
	Star68 - direction
	Star2 - direction
	Star105 - direction
	GroundStation226 - direction
	Star139 - direction
	Star106 - direction
	Star44 - direction
	GroundStation171 - direction
	Star133 - direction
	GroundStation209 - direction
	GroundStation15 - direction
	GroundStation86 - direction
	Star135 - direction
	GroundStation161 - direction
	Star11 - direction
	GroundStation113 - direction
	Star141 - direction
	GroundStation174 - direction
	Star155 - direction
	GroundStation230 - direction
	Star24 - direction
	Star78 - direction
	Star144 - direction
	GroundStation170 - direction
	Star80 - direction
	Star211 - direction
	Star99 - direction
	GroundStation26 - direction
	Star93 - direction
	Star176 - direction
	Star13 - direction
	Star122 - direction
	Star142 - direction
	GroundStation28 - direction
	Star83 - direction
	Star129 - direction
	Star157 - direction
	Star150 - direction
	GroundStation207 - direction
	Star33 - direction
	Star52 - direction
	GroundStation204 - direction
	Star200 - direction
	Star228 - direction
	Star66 - direction
	Star3 - direction
	GroundStation188 - direction
	GroundStation30 - direction
	GroundStation214 - direction
	GroundStation219 - direction
	GroundStation65 - direction
	GroundStation221 - direction
	Star203 - direction
	Star217 - direction
	Star140 - direction
	Star194 - direction
	Star134 - direction
	Star198 - direction
	GroundStation165 - direction
	GroundStation81 - direction
	GroundStation51 - direction
	Star46 - direction
	Star53 - direction
	GroundStation112 - direction
	GroundStation92 - direction
	GroundStation47 - direction
	GroundStation19 - direction
	GroundStation42 - direction
	Star31 - direction
	Star195 - direction
	GroundStation48 - direction
	GroundStation196 - direction
	Star223 - direction
	Star103 - direction
	Star38 - direction
	Star199 - direction
	Star37 - direction
	Star87 - direction
	Star7 - direction
	Star116 - direction
	GroundStation58 - direction
	GroundStation159 - direction
	GroundStation27 - direction
	GroundStation77 - direction
	Star166 - direction
	Star96 - direction
	Star91 - direction
	GroundStation23 - direction
	Star229 - direction
	GroundStation235 - direction
	GroundStation149 - direction
	Star128 - direction
	GroundStation62 - direction
	Star85 - direction
	Star215 - direction
	Star151 - direction
	GroundStation234 - direction
	GroundStation121 - direction
	GroundStation29 - direction
	GroundStation102 - direction
	Star94 - direction
	Star95 - direction
	Star153 - direction
	GroundStation125 - direction
	GroundStation197 - direction
	GroundStation173 - direction
	Star189 - direction
	Star119 - direction
	GroundStation79 - direction
	GroundStation45 - direction
	Star4 - direction
	GroundStation64 - direction
	Star127 - direction
	Star67 - direction
	Star59 - direction
	Star152 - direction
	GroundStation57 - direction
	GroundStation21 - direction
	GroundStation72 - direction
	GroundStation115 - direction
	GroundStation71 - direction
	GroundStation167 - direction
	Star201 - direction
	GroundStation18 - direction
	Star6 - direction
	Star8 - direction
	Star89 - direction
	Star131 - direction
	Star35 - direction
	GroundStation212 - direction
	GroundStation216 - direction
	Star34 - direction
	GroundStation232 - direction
	Star88 - direction
	Star210 - direction
	GroundStation178 - direction
	GroundStation143 - direction
	GroundStation185 - direction
	Star111 - direction
	GroundStation220 - direction
	GroundStation118 - direction
	Star148 - direction
	GroundStation206 - direction
	Star184 - direction
	GroundStation154 - direction
	GroundStation63 - direction
	Star60 - direction
	GroundStation136 - direction
	Star130 - direction
	GroundStation49 - direction
	Star147 - direction
	GroundStation76 - direction
	GroundStation123 - direction
	GroundStation82 - direction
	Star84 - direction
	Star109 - direction
	GroundStation22 - direction
	GroundStation50 - direction
	Star187 - direction
	Star54 - direction
	Phenomenon236 - direction
	Star237 - direction
	Phenomenon238 - direction
	Phenomenon239 - direction
	Star240 - direction
	Planet241 - direction
	Star242 - direction
	Star243 - direction
	Planet244 - direction
	Phenomenon245 - direction
	Phenomenon246 - direction
	Planet247 - direction
	Phenomenon248 - direction
	Planet249 - direction
	Phenomenon250 - direction
	Phenomenon251 - direction
	Planet252 - direction
	Planet253 - direction
	Star254 - direction
	Star255 - direction
	Star256 - direction
	Planet257 - direction
	Phenomenon258 - direction
	Phenomenon259 - direction
	Phenomenon260 - direction
	Star261 - direction
	Planet262 - direction
	Star263 - direction
	Phenomenon264 - direction
	Planet265 - direction
	Planet266 - direction
	Star267 - direction
	Planet268 - direction
	Phenomenon269 - direction
	Phenomenon270 - direction
	Planet271 - direction
	Star272 - direction
	Planet273 - direction
	Star274 - direction
	Phenomenon275 - direction
	Star276 - direction
	Phenomenon277 - direction
	Star278 - direction
	Star279 - direction
	Planet280 - direction
	Phenomenon281 - direction
	Phenomenon282 - direction
	Planet283 - direction
	Star284 - direction
	Planet285 - direction
	Planet286 - direction
	Star287 - direction
	Planet288 - direction
	Planet289 - direction
	Planet290 - direction
	Phenomenon291 - direction
	Star292 - direction
	Planet293 - direction
	Phenomenon294 - direction
	Star295 - direction
	Phenomenon296 - direction
	Star297 - direction
	Phenomenon298 - direction
	Planet299 - direction
	Planet300 - direction
	Planet301 - direction
	Phenomenon302 - direction
	Star303 - direction
	Phenomenon304 - direction
	Star305 - direction
	Phenomenon306 - direction
	Phenomenon307 - direction
	Phenomenon308 - direction
	Phenomenon309 - direction
	Phenomenon310 - direction
	Star311 - direction
	Phenomenon312 - direction
	Phenomenon313 - direction
	Planet314 - direction
	Phenomenon315 - direction
	Phenomenon316 - direction
	Star317 - direction
	Planet318 - direction
	Star319 - direction
	Star320 - direction
	Star321 - direction
	Planet322 - direction
	Star323 - direction
	Phenomenon324 - direction
	Planet325 - direction
	Planet326 - direction
	Star327 - direction
	Planet328 - direction
	Planet329 - direction
	Phenomenon330 - direction
	Star331 - direction
	Phenomenon332 - direction
	Planet333 - direction
	Phenomenon334 - direction
	Star335 - direction
	Star336 - direction
	Star337 - direction
	Phenomenon338 - direction
	Planet339 - direction
	Planet340 - direction
	Star341 - direction
	Phenomenon342 - direction
	Star343 - direction
	Phenomenon344 - direction
	Planet345 - direction
	Planet346 - direction
	Phenomenon347 - direction
	Star348 - direction
	Star349 - direction
	Phenomenon350 - direction
	Planet351 - direction
	Star352 - direction
	Phenomenon353 - direction
	Planet354 - direction
	Planet355 - direction
	Star356 - direction
	Phenomenon357 - direction
	Star358 - direction
	Phenomenon359 - direction
	Planet360 - direction
	Star361 - direction
	Phenomenon362 - direction
	Phenomenon363 - direction
	Star364 - direction
	Phenomenon365 - direction
	Star366 - direction
	Planet367 - direction
	Planet368 - direction
	Star369 - direction
	Star370 - direction
	Phenomenon371 - direction
	Phenomenon372 - direction
	Phenomenon373 - direction
	Planet374 - direction
	Star375 - direction
	Phenomenon376 - direction
	Phenomenon377 - direction
	Star378 - direction
	Phenomenon379 - direction
	Phenomenon380 - direction
	Planet381 - direction
	Planet382 - direction
	Phenomenon383 - direction
	Star384 - direction
	Phenomenon385 - direction
	Star386 - direction
	Phenomenon387 - direction
	Phenomenon388 - direction
	Phenomenon389 - direction
	Star390 - direction
	Planet391 - direction
	Star392 - direction
	Planet393 - direction
	Planet394 - direction
	Phenomenon395 - direction
	Star396 - direction
	Star397 - direction
	Planet398 - direction
	Planet399 - direction
	Planet400 - direction
	Star401 - direction
	Phenomenon402 - direction
	Star403 - direction
	Star404 - direction
	Phenomenon405 - direction
	Planet406 - direction
	Star407 - direction
	Star408 - direction
	Planet409 - direction
	Star410 - direction
	Phenomenon411 - direction
	Planet412 - direction
	Star413 - direction
	Star414 - direction
	Star415 - direction
	Star416 - direction
	Planet417 - direction
	Planet418 - direction
	Star419 - direction
	Star420 - direction
	Star421 - direction
	Phenomenon422 - direction
	Phenomenon423 - direction
	Planet424 - direction
	Star425 - direction
	Star426 - direction
	Phenomenon427 - direction
	Phenomenon428 - direction
	Phenomenon429 - direction
	Star430 - direction
	Phenomenon431 - direction
	Phenomenon432 - direction
	Planet433 - direction
	Star434 - direction
	Star435 - direction
	Planet436 - direction
	Star437 - direction
	Planet438 - direction
	Planet439 - direction
	Phenomenon440 - direction
	Planet441 - direction
	Star442 - direction
	Star443 - direction
	Phenomenon444 - direction
	Star445 - direction
	Phenomenon446 - direction
	Phenomenon447 - direction
	Planet448 - direction
	Phenomenon449 - direction
	Star450 - direction
	Star451 - direction
	Planet452 - direction
	Star453 - direction
	Planet454 - direction
	Star455 - direction
	Phenomenon456 - direction
	Star457 - direction
	Star458 - direction
	Star459 - direction
	Star460 - direction
	Star461 - direction
	Phenomenon462 - direction
	Planet463 - direction
	Phenomenon464 - direction
	Planet465 - direction
	Planet466 - direction
	Phenomenon467 - direction
	Planet468 - direction
	Planet469 - direction
	Planet470 - direction
	Star471 - direction
)
(:init
	(supports instrument0 spectrograph2)
	(calibration_target instrument0 GroundStation196)
	(calibration_target instrument0 Star85)
	(calibration_target instrument0 GroundStation169)
	(calibration_target instrument0 GroundStation171)
	(calibration_target instrument0 Star228)
	(supports instrument1 spectrograph6)
	(calibration_target instrument1 Star166)
	(calibration_target instrument1 GroundStation172)
	(calibration_target instrument1 GroundStation43)
	(calibration_target instrument1 Star147)
	(calibration_target instrument1 GroundStation124)
	(calibration_target instrument1 GroundStation113)
	(calibration_target instrument1 Star184)
	(calibration_target instrument1 GroundStation234)
	(calibration_target instrument1 Star35)
	(calibration_target instrument1 Star67)
	(calibration_target instrument1 Star153)
	(calibration_target instrument1 GroundStation29)
	(calibration_target instrument1 Star198)
	(calibration_target instrument1 Star85)
	(calibration_target instrument1 GroundStation138)
	(calibration_target instrument1 GroundStation169)
	(calibration_target instrument1 Star155)
	(calibration_target instrument1 Star151)
	(calibration_target instrument1 Star199)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 Star84)
	(calibration_target instrument1 Star128)
	(calibration_target instrument1 GroundStation171)
	(calibration_target instrument1 Star187)
	(calibration_target instrument1 Star31)
	(calibration_target instrument1 GroundStation136)
	(calibration_target instrument1 GroundStation56)
	(calibration_target instrument1 Star215)
	(calibration_target instrument1 GroundStation214)
	(calibration_target instrument1 Star7)
	(calibration_target instrument1 GroundStation77)
	(calibration_target instrument1 Star140)
	(calibration_target instrument1 GroundStation177)
	(calibration_target instrument1 GroundStation117)
	(supports instrument2 thermograph4)
	(supports instrument2 infrared3)
	(supports instrument2 image7)
	(calibration_target instrument2 GroundStation232)
	(calibration_target instrument2 Star74)
	(calibration_target instrument2 Star3)
	(calibration_target instrument2 Star201)
	(calibration_target instrument2 GroundStation100)
	(calibration_target instrument2 GroundStation154)
	(calibration_target instrument2 GroundStation65)
	(calibration_target instrument2 GroundStation81)
	(calibration_target instrument2 Star38)
	(calibration_target instrument2 GroundStation41)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet360)
	(supports instrument3 infrared5)
	(supports instrument3 image7)
	(supports instrument3 infrared3)
	(calibration_target instrument3 GroundStation171)
	(calibration_target instrument3 GroundStation235)
	(calibration_target instrument3 Star192)
	(calibration_target instrument3 Star68)
	(calibration_target instrument3 Star105)
	(calibration_target instrument3 Star153)
	(calibration_target instrument3 Star157)
	(calibration_target instrument3 Star144)
	(calibration_target instrument3 Star17)
	(calibration_target instrument3 Star93)
	(calibration_target instrument3 Star61)
	(calibration_target instrument3 Star198)
	(calibration_target instrument3 GroundStation213)
	(calibration_target instrument3 Star24)
	(calibration_target instrument3 Star195)
	(calibration_target instrument3 GroundStation193)
	(calibration_target instrument3 Star8)
	(calibration_target instrument3 Star116)
	(calibration_target instrument3 Star129)
	(calibration_target instrument3 Star182)
	(calibration_target instrument3 Star187)
	(calibration_target instrument3 Star181)
	(calibration_target instrument3 GroundStation39)
	(calibration_target instrument3 Star83)
	(calibration_target instrument3 Star53)
	(calibration_target instrument3 Star156)
	(calibration_target instrument3 GroundStation81)
	(calibration_target instrument3 Star87)
	(calibration_target instrument3 Star32)
	(calibration_target instrument3 Star222)
	(calibration_target instrument3 GroundStation69)
	(calibration_target instrument3 Star201)
	(calibration_target instrument3 Star162)
	(calibration_target instrument3 Star85)
	(calibration_target instrument3 GroundStation62)
	(calibration_target instrument3 GroundStation124)
	(calibration_target instrument3 GroundStation196)
	(calibration_target instrument3 Star223)
	(calibration_target instrument3 GroundStation123)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 GroundStation25)
	(calibration_target instrument3 Star191)
	(calibration_target instrument3 GroundStation226)
	(calibration_target instrument3 GroundStation77)
	(calibration_target instrument3 GroundStation218)
	(calibration_target instrument3 GroundStation125)
	(calibration_target instrument3 GroundStation137)
	(calibration_target instrument3 Star227)
	(calibration_target instrument3 Star128)
	(calibration_target instrument3 Star38)
	(calibration_target instrument3 Star110)
	(calibration_target instrument3 GroundStation207)
	(calibration_target instrument3 GroundStation164)
	(calibration_target instrument3 GroundStation149)
	(calibration_target instrument3 Star9)
	(calibration_target instrument3 Star224)
	(calibration_target instrument3 GroundStation23)
	(calibration_target instrument3 Star74)
	(calibration_target instrument3 Star20)
	(calibration_target instrument3 GroundStation58)
	(calibration_target instrument3 Star210)
	(calibration_target instrument3 Star90)
	(calibration_target instrument3 Star52)
	(calibration_target instrument3 Star88)
	(calibration_target instrument3 GroundStation63)
	(calibration_target instrument3 GroundStation115)
	(calibration_target instrument3 GroundStation70)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 GroundStation51)
	(calibration_target instrument3 Star200)
	(calibration_target instrument3 GroundStation234)
	(calibration_target instrument3 GroundStation86)
	(calibration_target instrument3 Star103)
	(calibration_target instrument3 GroundStation204)
	(supports instrument4 spectrograph0)
	(calibration_target instrument4 GroundStation193)
	(calibration_target instrument4 GroundStation138)
	(calibration_target instrument4 GroundStation48)
	(calibration_target instrument4 GroundStation97)
	(calibration_target instrument4 Star155)
	(calibration_target instrument4 GroundStation159)
	(calibration_target instrument4 Star59)
	(calibration_target instrument4 Star175)
	(calibration_target instrument4 Star88)
	(calibration_target instrument4 Star52)
	(calibration_target instrument4 GroundStation101)
	(calibration_target instrument4 GroundStation124)
	(calibration_target instrument4 Star83)
	(calibration_target instrument4 Star148)
	(calibration_target instrument4 GroundStation42)
	(calibration_target instrument4 Star152)
	(calibration_target instrument4 Star195)
	(calibration_target instrument4 GroundStation113)
	(calibration_target instrument4 Star130)
	(calibration_target instrument4 GroundStation177)
	(calibration_target instrument4 GroundStation143)
	(calibration_target instrument4 GroundStation164)
	(calibration_target instrument4 Star32)
	(calibration_target instrument4 Star215)
	(calibration_target instrument4 GroundStation216)
	(calibration_target instrument4 GroundStation19)
	(calibration_target instrument4 Star95)
	(calibration_target instrument4 Star141)
	(calibration_target instrument4 GroundStation28)
	(calibration_target instrument4 GroundStation108)
	(calibration_target instrument4 GroundStation22)
	(calibration_target instrument4 Star2)
	(calibration_target instrument4 Star156)
	(calibration_target instrument4 Star80)
	(calibration_target instrument4 Star106)
	(calibration_target instrument4 GroundStation212)
	(calibration_target instrument4 GroundStation136)
	(calibration_target instrument4 GroundStation170)
	(calibration_target instrument4 Star116)
	(calibration_target instrument4 GroundStation126)
	(calibration_target instrument4 GroundStation47)
	(calibration_target instrument4 GroundStation72)
	(calibration_target instrument4 GroundStation64)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 Star233)
	(calibration_target instrument4 GroundStation118)
	(calibration_target instrument4 Star176)
	(calibration_target instrument4 GroundStation206)
	(calibration_target instrument4 Star187)
	(calibration_target instrument4 GroundStation63)
	(calibration_target instrument4 GroundStation15)
	(calibration_target instrument4 Star119)
	(calibration_target instrument4 Star217)
	(calibration_target instrument4 Star8)
	(calibration_target instrument4 Star85)
	(calibration_target instrument4 Star1)
	(supports instrument5 spectrograph1)
	(supports instrument5 spectrograph6)
	(supports instrument5 infrared5)
	(calibration_target instrument5 Star181)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Star341)
	(supports instrument6 image7)
	(supports instrument6 spectrograph0)
	(calibration_target instrument6 Star229)
	(calibration_target instrument6 Star103)
	(calibration_target instrument6 Star139)
	(calibration_target instrument6 GroundStation82)
	(calibration_target instrument6 Star231)
	(calibration_target instrument6 Star147)
	(calibration_target instrument6 GroundStation235)
	(calibration_target instrument6 Star223)
	(calibration_target instrument6 Star227)
	(calibration_target instrument6 Star110)
	(calibration_target instrument6 Star144)
	(calibration_target instrument6 Star20)
	(calibration_target instrument6 GroundStation219)
	(calibration_target instrument6 GroundStation81)
	(calibration_target instrument6 Star191)
	(calibration_target instrument6 GroundStation25)
	(calibration_target instrument6 Star140)
	(calibration_target instrument6 GroundStation123)
	(calibration_target instrument6 GroundStation174)
	(calibration_target instrument6 GroundStation124)
	(calibration_target instrument6 Star129)
	(calibration_target instrument6 Star116)
	(calibration_target instrument6 GroundStation161)
	(calibration_target instrument6 GroundStation71)
	(calibration_target instrument6 Star74)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 GroundStation112)
	(calibration_target instrument6 GroundStation102)
	(calibration_target instrument6 Star11)
	(calibration_target instrument6 Star24)
	(calibration_target instrument6 Star141)
	(calibration_target instrument6 GroundStation230)
	(calibration_target instrument6 Star107)
	(calibration_target instrument6 GroundStation55)
	(calibration_target instrument6 Star90)
	(calibration_target instrument6 GroundStation207)
	(calibration_target instrument6 Star9)
	(calibration_target instrument6 Star168)
	(calibration_target instrument6 Star127)
	(calibration_target instrument6 Star96)
	(calibration_target instrument6 GroundStation164)
	(calibration_target instrument6 GroundStation101)
	(calibration_target instrument6 Star85)
	(calibration_target instrument6 Star160)
	(calibration_target instrument6 GroundStation77)
	(calibration_target instrument6 Star203)
	(calibration_target instrument6 GroundStation177)
	(calibration_target instrument6 GroundStation18)
	(calibration_target instrument6 GroundStation193)
	(calibration_target instrument6 GroundStation121)
	(calibration_target instrument6 Star155)
	(calibration_target instrument6 Star182)
	(calibration_target instrument6 GroundStation26)
	(calibration_target instrument6 GroundStation158)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation232)
	(supports instrument7 thermograph4)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared3)
	(calibration_target instrument7 Star200)
	(calibration_target instrument7 GroundStation232)
	(calibration_target instrument7 Star89)
	(calibration_target instrument7 GroundStation123)
	(calibration_target instrument7 GroundStation101)
	(calibration_target instrument7 Star168)
	(calibration_target instrument7 GroundStation167)
	(calibration_target instrument7 Star34)
	(calibration_target instrument7 GroundStation30)
	(calibration_target instrument7 Star24)
	(calibration_target instrument7 GroundStation43)
	(calibration_target instrument7 GroundStation25)
	(calibration_target instrument7 GroundStation45)
	(calibration_target instrument7 GroundStation22)
	(calibration_target instrument7 GroundStation125)
	(calibration_target instrument7 Star61)
	(calibration_target instrument7 GroundStation185)
	(calibration_target instrument7 Star189)
	(calibration_target instrument7 GroundStation126)
	(calibration_target instrument7 GroundStation235)
	(calibration_target instrument7 GroundStation214)
	(calibration_target instrument7 GroundStation172)
	(calibration_target instrument7 Star60)
	(supports instrument8 spectrograph6)
	(calibration_target instrument8 GroundStation219)
	(calibration_target instrument8 GroundStation209)
	(calibration_target instrument8 GroundStation71)
	(calibration_target instrument8 GroundStation183)
	(calibration_target instrument8 GroundStation154)
	(calibration_target instrument8 Star93)
	(calibration_target instrument8 GroundStation143)
	(calibration_target instrument8 GroundStation30)
	(calibration_target instrument8 Star89)
	(calibration_target instrument8 GroundStation163)
	(calibration_target instrument8 GroundStation132)
	(calibration_target instrument8 GroundStation193)
	(calibration_target instrument8 Star44)
	(calibration_target instrument8 Star90)
	(calibration_target instrument8 Star144)
	(calibration_target instrument8 GroundStation27)
	(calibration_target instrument8 Star184)
	(calibration_target instrument8 Star116)
	(calibration_target instrument8 GroundStation81)
	(calibration_target instrument8 Star73)
	(calibration_target instrument8 GroundStation124)
	(calibration_target instrument8 Star181)
	(calibration_target instrument8 GroundStation158)
	(calibration_target instrument8 GroundStation186)
	(calibration_target instrument8 Star192)
	(calibration_target instrument8 GroundStation137)
	(calibration_target instrument8 GroundStation221)
	(calibration_target instrument8 Star85)
	(calibration_target instrument8 GroundStation216)
	(calibration_target instrument8 Star187)
	(calibration_target instrument8 Star211)
	(calibration_target instrument8 Star157)
	(calibration_target instrument8 GroundStation230)
	(calibration_target instrument8 GroundStation57)
	(calibration_target instrument8 GroundStation97)
	(calibration_target instrument8 Star109)
	(calibration_target instrument8 GroundStation118)
	(calibration_target instrument8 GroundStation41)
	(calibration_target instrument8 Star78)
	(calibration_target instrument8 GroundStation206)
	(supports instrument9 spectrograph6)
	(supports instrument9 thermograph4)
	(supports instrument9 spectrograph2)
	(calibration_target instrument9 GroundStation209)
	(calibration_target instrument9 GroundStation172)
	(calibration_target instrument9 GroundStation18)
	(calibration_target instrument9 GroundStation29)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Planet252)
	(supports instrument10 thermograph4)
	(calibration_target instrument10 GroundStation51)
	(calibration_target instrument10 GroundStation193)
	(calibration_target instrument10 GroundStation121)
	(calibration_target instrument10 Star105)
	(calibration_target instrument10 Star180)
	(calibration_target instrument10 Star14)
	(calibration_target instrument10 GroundStation216)
	(calibration_target instrument10 Star87)
	(calibration_target instrument10 GroundStation81)
	(calibration_target instrument10 Star61)
	(calibration_target instrument10 Star162)
	(calibration_target instrument10 GroundStation219)
	(calibration_target instrument10 GroundStation101)
	(calibration_target instrument10 GroundStation196)
	(calibration_target instrument10 Star103)
	(calibration_target instrument10 Star8)
	(calibration_target instrument10 GroundStation164)
	(calibration_target instrument10 GroundStation27)
	(calibration_target instrument10 GroundStation220)
	(calibration_target instrument10 GroundStation174)
	(calibration_target instrument10 GroundStation123)
	(calibration_target instrument10 Star140)
	(calibration_target instrument10 GroundStation226)
	(calibration_target instrument10 GroundStation170)
	(calibration_target instrument10 Star152)
	(calibration_target instrument10 GroundStation126)
	(calibration_target instrument10 GroundStation63)
	(calibration_target instrument10 Star94)
	(calibration_target instrument10 GroundStation183)
	(calibration_target instrument10 GroundStation169)
	(calibration_target instrument10 GroundStation137)
	(calibration_target instrument10 Star67)
	(calibration_target instrument10 GroundStation197)
	(calibration_target instrument10 Star80)
	(calibration_target instrument10 Star12)
	(calibration_target instrument10 Star53)
	(calibration_target instrument10 GroundStation28)
	(calibration_target instrument10 GroundStation42)
	(calibration_target instrument10 GroundStation185)
	(calibration_target instrument10 Star153)
	(calibration_target instrument10 GroundStation86)
	(calibration_target instrument10 Star111)
	(calibration_target instrument10 GroundStation213)
	(calibration_target instrument10 GroundStation104)
	(calibration_target instrument10 Star106)
	(calibration_target instrument10 Star122)
	(calibration_target instrument10 Star52)
	(calibration_target instrument10 Star91)
	(calibration_target instrument10 Star46)
	(calibration_target instrument10 GroundStation22)
	(calibration_target instrument10 Star34)
	(calibration_target instrument10 GroundStation221)
	(calibration_target instrument10 GroundStation64)
	(calibration_target instrument10 Star135)
	(calibration_target instrument10 Star38)
	(calibration_target instrument10 GroundStation209)
	(calibration_target instrument10 GroundStation158)
	(calibration_target instrument10 GroundStation43)
	(calibration_target instrument10 GroundStation92)
	(calibration_target instrument10 Star211)
	(calibration_target instrument10 GroundStation49)
	(calibration_target instrument10 GroundStation29)
	(supports instrument11 infrared3)
	(supports instrument11 image7)
	(calibration_target instrument11 GroundStation15)
	(calibration_target instrument11 GroundStation19)
	(calibration_target instrument11 GroundStation159)
	(calibration_target instrument11 Star184)
	(calibration_target instrument11 Star52)
	(calibration_target instrument11 GroundStation117)
	(calibration_target instrument11 GroundStation235)
	(calibration_target instrument11 Star4)
	(calibration_target instrument11 Star93)
	(calibration_target instrument11 Star9)
	(calibration_target instrument11 GroundStation178)
	(calibration_target instrument11 GroundStation25)
	(calibration_target instrument11 GroundStation55)
	(calibration_target instrument11 Star3)
	(calibration_target instrument11 Star110)
	(calibration_target instrument11 Star95)
	(calibration_target instrument11 GroundStation188)
	(calibration_target instrument11 GroundStation121)
	(calibration_target instrument11 Star68)
	(calibration_target instrument11 GroundStation58)
	(calibration_target instrument11 GroundStation193)
	(calibration_target instrument11 GroundStation205)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star157)
	(calibration_target instrument11 Star122)
	(supports instrument12 infrared5)
	(calibration_target instrument12 GroundStation26)
	(calibration_target instrument12 Star135)
	(calibration_target instrument12 Star14)
	(calibration_target instrument12 Star67)
	(calibration_target instrument12 GroundStation118)
	(calibration_target instrument12 GroundStation62)
	(calibration_target instrument12 Star78)
	(on_board instrument10 satellite4)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star74)
	(supports instrument13 spectrograph1)
	(supports instrument13 infrared5)
	(supports instrument13 spectrograph6)
	(calibration_target instrument13 GroundStation159)
	(calibration_target instrument13 Star88)
	(calibration_target instrument13 Star194)
	(calibration_target instrument13 GroundStation16)
	(calibration_target instrument13 Star191)
	(supports instrument14 infrared5)
	(supports instrument14 spectrograph1)
	(calibration_target instrument14 Star231)
	(calibration_target instrument14 GroundStation136)
	(calibration_target instrument14 GroundStation206)
	(calibration_target instrument14 GroundStation51)
	(calibration_target instrument14 GroundStation15)
	(calibration_target instrument14 GroundStation27)
	(calibration_target instrument14 Star90)
	(calibration_target instrument14 Star14)
	(calibration_target instrument14 GroundStation76)
	(calibration_target instrument14 Star142)
	(calibration_target instrument14 GroundStation125)
	(calibration_target instrument14 Star68)
	(calibration_target instrument14 GroundStation58)
	(calibration_target instrument14 Star111)
	(calibration_target instrument14 GroundStation226)
	(calibration_target instrument14 GroundStation47)
	(calibration_target instrument14 GroundStation183)
	(calibration_target instrument14 Star12)
	(calibration_target instrument14 GroundStation92)
	(calibration_target instrument14 GroundStation188)
	(calibration_target instrument14 GroundStation169)
	(calibration_target instrument14 Star131)
	(calibration_target instrument14 GroundStation77)
	(calibration_target instrument14 Star20)
	(calibration_target instrument14 Star160)
	(calibration_target instrument14 GroundStation221)
	(calibration_target instrument14 GroundStation104)
	(calibration_target instrument14 GroundStation62)
	(calibration_target instrument14 Star60)
	(calibration_target instrument14 Star46)
	(calibration_target instrument14 GroundStation112)
	(calibration_target instrument14 GroundStation235)
	(calibration_target instrument14 GroundStation16)
	(calibration_target instrument14 Star52)
	(calibration_target instrument14 Star152)
	(calibration_target instrument14 Star9)
	(calibration_target instrument14 GroundStation185)
	(calibration_target instrument14 Star215)
	(supports instrument15 spectrograph6)
	(supports instrument15 spectrograph1)
	(supports instrument15 infrared5)
	(calibration_target instrument15 GroundStation30)
	(calibration_target instrument15 Star67)
	(calibration_target instrument15 GroundStation171)
	(calibration_target instrument15 GroundStation28)
	(calibration_target instrument15 GroundStation115)
	(calibration_target instrument15 Star90)
	(calibration_target instrument15 Star74)
	(calibration_target instrument15 GroundStation72)
	(calibration_target instrument15 Star140)
	(calibration_target instrument15 Star80)
	(calibration_target instrument15 GroundStation50)
	(calibration_target instrument15 Star93)
	(calibration_target instrument15 GroundStation118)
	(calibration_target instrument15 GroundStation178)
	(calibration_target instrument15 Star9)
	(calibration_target instrument15 GroundStation193)
	(calibration_target instrument15 GroundStation41)
	(calibration_target instrument15 GroundStation197)
	(calibration_target instrument15 GroundStation98)
	(calibration_target instrument15 Star37)
	(calibration_target instrument15 Star222)
	(calibration_target instrument15 Star184)
	(calibration_target instrument15 GroundStation27)
	(calibration_target instrument15 Star85)
	(calibration_target instrument15 GroundStation185)
	(calibration_target instrument15 GroundStation15)
	(calibration_target instrument15 GroundStation234)
	(calibration_target instrument15 Star181)
	(calibration_target instrument15 GroundStation19)
	(calibration_target instrument15 Star120)
	(calibration_target instrument15 Star223)
	(calibration_target instrument15 GroundStation138)
	(calibration_target instrument15 Star60)
	(calibration_target instrument15 Star94)
	(calibration_target instrument15 Star68)
	(calibration_target instrument15 Star133)
	(calibration_target instrument15 GroundStation213)
	(calibration_target instrument15 Star182)
	(calibration_target instrument15 Star59)
	(calibration_target instrument15 Star156)
	(calibration_target instrument15 Star142)
	(calibration_target instrument15 Star107)
	(calibration_target instrument15 Star99)
	(calibration_target instrument15 GroundStation121)
	(calibration_target instrument15 Star151)
	(calibration_target instrument15 Star20)
	(calibration_target instrument15 GroundStation163)
	(calibration_target instrument15 GroundStation22)
	(calibration_target instrument15 GroundStation154)
	(calibration_target instrument15 GroundStation158)
	(calibration_target instrument15 GroundStation137)
	(calibration_target instrument15 Star110)
	(calibration_target instrument15 Star141)
	(calibration_target instrument15 Star91)
	(calibration_target instrument15 Star217)
	(calibration_target instrument15 Star128)
	(calibration_target instrument15 Star38)
	(calibration_target instrument15 Star24)
	(calibration_target instrument15 GroundStation81)
	(calibration_target instrument15 Star227)
	(calibration_target instrument15 GroundStation124)
	(calibration_target instrument15 GroundStation208)
	(calibration_target instrument15 Star122)
	(calibration_target instrument15 Star11)
	(calibration_target instrument15 GroundStation25)
	(calibration_target instrument15 GroundStation196)
	(calibration_target instrument15 GroundStation167)
	(calibration_target instrument15 GroundStation161)
	(calibration_target instrument15 Star36)
	(calibration_target instrument15 GroundStation117)
	(calibration_target instrument15 Star8)
	(supports instrument16 thermograph4)
	(supports instrument16 image7)
	(calibration_target instrument16 GroundStation177)
	(calibration_target instrument16 GroundStation186)
	(calibration_target instrument16 Star78)
	(calibration_target instrument16 Star93)
	(calibration_target instrument16 GroundStation72)
	(calibration_target instrument16 Star66)
	(calibration_target instrument16 Star107)
	(calibration_target instrument16 Star128)
	(calibration_target instrument16 Star151)
	(calibration_target instrument16 GroundStation221)
	(calibration_target instrument16 Star210)
	(calibration_target instrument16 Star14)
	(calibration_target instrument16 GroundStation79)
	(calibration_target instrument16 Star95)
	(calibration_target instrument16 Star75)
	(calibration_target instrument16 Star31)
	(calibration_target instrument16 GroundStation208)
	(calibration_target instrument16 GroundStation205)
	(calibration_target instrument16 GroundStation163)
	(supports instrument17 image7)
	(calibration_target instrument17 Star175)
	(calibration_target instrument17 Star157)
	(calibration_target instrument17 GroundStation221)
	(calibration_target instrument17 Star156)
	(calibration_target instrument17 Star191)
	(calibration_target instrument17 GroundStation173)
	(calibration_target instrument17 Star4)
	(calibration_target instrument17 GroundStation165)
	(calibration_target instrument17 GroundStation193)
	(calibration_target instrument17 Star153)
	(calibration_target instrument17 Star78)
	(calibration_target instrument17 Star94)
	(calibration_target instrument17 GroundStation137)
	(calibration_target instrument17 GroundStation118)
	(calibration_target instrument17 Star215)
	(calibration_target instrument17 Star8)
	(calibration_target instrument17 GroundStation220)
	(calibration_target instrument17 Star227)
	(calibration_target instrument17 GroundStation30)
	(calibration_target instrument17 GroundStation126)
	(calibration_target instrument17 Star166)
	(calibration_target instrument17 Star53)
	(calibration_target instrument17 GroundStation213)
	(calibration_target instrument17 Star150)
	(calibration_target instrument17 GroundStation28)
	(calibration_target instrument17 GroundStation56)
	(calibration_target instrument17 Star114)
	(calibration_target instrument17 Star195)
	(calibration_target instrument17 Star119)
	(calibration_target instrument17 Star85)
	(calibration_target instrument17 GroundStation218)
	(calibration_target instrument17 GroundStation49)
	(calibration_target instrument17 Star187)
	(calibration_target instrument17 Star35)
	(calibration_target instrument17 Star198)
	(calibration_target instrument17 Star222)
	(calibration_target instrument17 Star17)
	(calibration_target instrument17 Star231)
	(calibration_target instrument17 Star90)
	(calibration_target instrument17 GroundStation10)
	(calibration_target instrument17 GroundStation225)
	(calibration_target instrument17 Star80)
	(calibration_target instrument17 Star60)
	(calibration_target instrument17 Star68)
	(calibration_target instrument17 Star20)
	(calibration_target instrument17 Star144)
	(calibration_target instrument17 GroundStation101)
	(calibration_target instrument17 Star96)
	(calibration_target instrument17 Star134)
	(calibration_target instrument17 Star211)
	(calibration_target instrument17 Star36)
	(calibration_target instrument17 GroundStation39)
	(calibration_target instrument17 GroundStation19)
	(calibration_target instrument17 Star103)
	(calibration_target instrument17 Star83)
	(calibration_target instrument17 Star38)
	(calibration_target instrument17 Star152)
	(calibration_target instrument17 GroundStation102)
	(calibration_target instrument17 GroundStation208)
	(calibration_target instrument17 GroundStation25)
	(calibration_target instrument17 Star202)
	(calibration_target instrument17 Star179)
	(calibration_target instrument17 Star84)
	(calibration_target instrument17 Star34)
	(calibration_target instrument17 Star233)
	(calibration_target instrument17 Star129)
	(calibration_target instrument17 Star139)
	(calibration_target instrument17 GroundStation57)
	(calibration_target instrument17 GroundStation178)
	(calibration_target instrument17 Star201)
	(calibration_target instrument17 Star73)
	(calibration_target instrument17 Star75)
	(on_board instrument13 satellite5)
	(on_board instrument14 satellite5)
	(on_board instrument15 satellite5)
	(on_board instrument16 satellite5)
	(on_board instrument17 satellite5)
	(power_avail satellite5)
	(pointing satellite5 GroundStation28)
	(supports instrument18 thermograph4)
	(supports instrument18 spectrograph0)
	(supports instrument18 spectrograph2)
	(calibration_target instrument18 Star34)
	(calibration_target instrument18 Star122)
	(calibration_target instrument18 Star140)
	(calibration_target instrument18 GroundStation100)
	(calibration_target instrument18 Star88)
	(calibration_target instrument18 GroundStation42)
	(calibration_target instrument18 Star109)
	(calibration_target instrument18 Star78)
	(calibration_target instrument18 Star87)
	(calibration_target instrument18 GroundStation48)
	(calibration_target instrument18 Star12)
	(calibration_target instrument18 GroundStation51)
	(calibration_target instrument18 Star210)
	(calibration_target instrument18 Star6)
	(calibration_target instrument18 Star231)
	(calibration_target instrument18 Star202)
	(calibration_target instrument18 Star110)
	(calibration_target instrument18 GroundStation65)
	(calibration_target instrument18 Star228)
	(calibration_target instrument18 GroundStation132)
	(calibration_target instrument18 GroundStation117)
	(calibration_target instrument18 Star107)
	(calibration_target instrument18 Star0)
	(calibration_target instrument18 GroundStation23)
	(calibration_target instrument18 GroundStation18)
	(calibration_target instrument18 Star166)
	(calibration_target instrument18 Star114)
	(calibration_target instrument18 GroundStation21)
	(calibration_target instrument18 Star175)
	(calibration_target instrument18 GroundStation137)
	(calibration_target instrument18 Star111)
	(calibration_target instrument18 Star233)
	(supports instrument19 spectrograph1)
	(supports instrument19 image7)
	(supports instrument19 infrared3)
	(calibration_target instrument19 GroundStation43)
	(calibration_target instrument19 Star35)
	(calibration_target instrument19 GroundStation158)
	(calibration_target instrument19 Star160)
	(calibration_target instrument19 GroundStation56)
	(calibration_target instrument19 Star44)
	(calibration_target instrument19 Star31)
	(calibration_target instrument19 GroundStation25)
	(calibration_target instrument19 GroundStation19)
	(calibration_target instrument19 GroundStation55)
	(calibration_target instrument19 GroundStation79)
	(calibration_target instrument19 GroundStation71)
	(calibration_target instrument19 Star106)
	(calibration_target instrument19 Star110)
	(calibration_target instrument19 GroundStation161)
	(calibration_target instrument19 GroundStation214)
	(calibration_target instrument19 GroundStation47)
	(calibration_target instrument19 Star53)
	(calibration_target instrument19 GroundStation100)
	(calibration_target instrument19 Star83)
	(calibration_target instrument19 GroundStation143)
	(calibration_target instrument19 GroundStation193)
	(calibration_target instrument19 GroundStation132)
	(calibration_target instrument19 GroundStation40)
	(calibration_target instrument19 Star11)
	(calibration_target instrument19 Star201)
	(supports instrument20 thermograph4)
	(supports instrument20 spectrograph1)
	(calibration_target instrument20 GroundStation209)
	(calibration_target instrument20 Star153)
	(calibration_target instrument20 GroundStation126)
	(calibration_target instrument20 Star194)
	(calibration_target instrument20 GroundStation173)
	(calibration_target instrument20 Star233)
	(calibration_target instrument20 Star66)
	(calibration_target instrument20 GroundStation163)
	(calibration_target instrument20 GroundStation26)
	(calibration_target instrument20 GroundStation207)
	(calibration_target instrument20 GroundStation146)
	(calibration_target instrument20 Star83)
	(calibration_target instrument20 GroundStation16)
	(calibration_target instrument20 GroundStation86)
	(calibration_target instrument20 Star3)
	(calibration_target instrument20 Star119)
	(calibration_target instrument20 GroundStation40)
	(calibration_target instrument20 Star156)
	(calibration_target instrument20 GroundStation226)
	(calibration_target instrument20 GroundStation178)
	(calibration_target instrument20 GroundStation10)
	(calibration_target instrument20 Star2)
	(calibration_target instrument20 GroundStation177)
	(calibration_target instrument20 GroundStation206)
	(calibration_target instrument20 Star231)
	(calibration_target instrument20 GroundStation64)
	(calibration_target instrument20 GroundStation63)
	(calibration_target instrument20 Star133)
	(calibration_target instrument20 GroundStation221)
	(calibration_target instrument20 GroundStation5)
	(calibration_target instrument20 GroundStation154)
	(calibration_target instrument20 GroundStation214)
	(calibration_target instrument20 GroundStation23)
	(calibration_target instrument20 Star176)
	(calibration_target instrument20 GroundStation29)
	(calibration_target instrument20 GroundStation57)
	(calibration_target instrument20 Star210)
	(calibration_target instrument20 GroundStation28)
	(calibration_target instrument20 Star199)
	(calibration_target instrument20 GroundStation113)
	(calibration_target instrument20 GroundStation117)
	(calibration_target instrument20 GroundStation69)
	(calibration_target instrument20 GroundStation158)
	(calibration_target instrument20 Star32)
	(calibration_target instrument20 Star52)
	(calibration_target instrument20 Star135)
	(calibration_target instrument20 Star4)
	(calibration_target instrument20 Star200)
	(calibration_target instrument20 Star44)
	(calibration_target instrument20 GroundStation149)
	(calibration_target instrument20 Star187)
	(calibration_target instrument20 Star144)
	(calibration_target instrument20 GroundStation232)
	(calibration_target instrument20 Star180)
	(calibration_target instrument20 Star106)
	(calibration_target instrument20 GroundStation71)
	(calibration_target instrument20 GroundStation138)
	(calibration_target instrument20 GroundStation97)
	(calibration_target instrument20 GroundStation22)
	(calibration_target instrument20 Star192)
	(calibration_target instrument20 Star162)
	(calibration_target instrument20 Star227)
	(calibration_target instrument20 GroundStation212)
	(calibration_target instrument20 Star31)
	(calibration_target instrument20 GroundStation137)
	(calibration_target instrument20 GroundStation104)
	(calibration_target instrument20 Star93)
	(calibration_target instrument20 Star211)
	(calibration_target instrument20 GroundStation100)
	(calibration_target instrument20 Star129)
	(calibration_target instrument20 GroundStation49)
	(calibration_target instrument20 GroundStation118)
	(calibration_target instrument20 GroundStation39)
	(calibration_target instrument20 Star17)
	(calibration_target instrument20 Star0)
	(calibration_target instrument20 GroundStation51)
	(supports instrument21 image7)
	(supports instrument21 infrared5)
	(supports instrument21 spectrograph0)
	(calibration_target instrument21 GroundStation23)
	(calibration_target instrument21 Star8)
	(calibration_target instrument21 GroundStation154)
	(calibration_target instrument21 GroundStation79)
	(calibration_target instrument21 GroundStation76)
	(calibration_target instrument21 Star187)
	(calibration_target instrument21 GroundStation62)
	(calibration_target instrument21 GroundStation183)
	(calibration_target instrument21 Star130)
	(calibration_target instrument21 Star229)
	(calibration_target instrument21 Star182)
	(calibration_target instrument21 Star150)
	(calibration_target instrument21 Star142)
	(calibration_target instrument21 Star156)
	(calibration_target instrument21 GroundStation204)
	(calibration_target instrument21 Star228)
	(calibration_target instrument21 GroundStation232)
	(calibration_target instrument21 Star95)
	(calibration_target instrument21 Star60)
	(calibration_target instrument21 GroundStation65)
	(calibration_target instrument21 Star217)
	(calibration_target instrument21 Star151)
	(calibration_target instrument21 GroundStation5)
	(calibration_target instrument21 GroundStation10)
	(calibration_target instrument21 Star4)
	(calibration_target instrument21 GroundStation212)
	(calibration_target instrument21 GroundStation100)
	(calibration_target instrument21 Star166)
	(calibration_target instrument21 Star133)
	(calibration_target instrument21 Star203)
	(calibration_target instrument21 GroundStation121)
	(calibration_target instrument21 Star31)
	(calibration_target instrument21 Star202)
	(calibration_target instrument21 GroundStation123)
	(calibration_target instrument21 GroundStation208)
	(calibration_target instrument21 GroundStation97)
	(calibration_target instrument21 GroundStation177)
	(calibration_target instrument21 Star12)
	(calibration_target instrument21 GroundStation146)
	(calibration_target instrument21 Star83)
	(calibration_target instrument21 GroundStation193)
	(calibration_target instrument21 GroundStation125)
	(calibration_target instrument21 Star36)
	(calibration_target instrument21 Star176)
	(calibration_target instrument21 GroundStation164)
	(calibration_target instrument21 Star80)
	(calibration_target instrument21 Star38)
	(calibration_target instrument21 GroundStation206)
	(calibration_target instrument21 Star106)
	(calibration_target instrument21 GroundStation113)
	(calibration_target instrument21 Star20)
	(calibration_target instrument21 Star54)
	(calibration_target instrument21 GroundStation92)
	(calibration_target instrument21 GroundStation197)
	(calibration_target instrument21 GroundStation40)
	(supports instrument22 thermograph4)
	(supports instrument22 spectrograph6)
	(calibration_target instrument22 GroundStation216)
	(calibration_target instrument22 Star187)
	(calibration_target instrument22 GroundStation230)
	(calibration_target instrument22 GroundStation29)
	(calibration_target instrument22 Star142)
	(calibration_target instrument22 GroundStation190)
	(calibration_target instrument22 GroundStation197)
	(calibration_target instrument22 GroundStation97)
	(calibration_target instrument22 GroundStation158)
	(calibration_target instrument22 GroundStation69)
	(calibration_target instrument22 GroundStation18)
	(calibration_target instrument22 Star35)
	(calibration_target instrument22 Star111)
	(calibration_target instrument22 Star189)
	(calibration_target instrument22 Star114)
	(calibration_target instrument22 Star150)
	(calibration_target instrument22 Star84)
	(calibration_target instrument22 GroundStation115)
	(calibration_target instrument22 GroundStation15)
	(calibration_target instrument22 GroundStation206)
	(calibration_target instrument22 GroundStation50)
	(calibration_target instrument22 Star144)
	(calibration_target instrument22 GroundStation21)
	(calibration_target instrument22 GroundStation19)
	(calibration_target instrument22 Star180)
	(calibration_target instrument22 Star129)
	(calibration_target instrument22 GroundStation204)
	(calibration_target instrument22 GroundStation79)
	(calibration_target instrument22 GroundStation174)
	(calibration_target instrument22 GroundStation23)
	(calibration_target instrument22 Star66)
	(calibration_target instrument22 Star99)
	(calibration_target instrument22 Star130)
	(calibration_target instrument22 Star38)
	(calibration_target instrument22 GroundStation208)
	(calibration_target instrument22 Star151)
	(calibration_target instrument22 GroundStation164)
	(calibration_target instrument22 Star44)
	(calibration_target instrument22 GroundStation126)
	(calibration_target instrument22 Star88)
	(calibration_target instrument22 GroundStation186)
	(calibration_target instrument22 Star223)
	(calibration_target instrument22 Star33)
	(calibration_target instrument22 Star2)
	(calibration_target instrument22 GroundStation171)
	(calibration_target instrument22 Star175)
	(calibration_target instrument22 GroundStation117)
	(calibration_target instrument22 GroundStation39)
	(calibration_target instrument22 GroundStation221)
	(calibration_target instrument22 Star31)
	(calibration_target instrument22 Star222)
	(calibration_target instrument22 GroundStation65)
	(calibration_target instrument22 Star201)
	(calibration_target instrument22 Star153)
	(calibration_target instrument22 Star6)
	(calibration_target instrument22 Star61)
	(calibration_target instrument22 Star134)
	(calibration_target instrument22 GroundStation213)
	(calibration_target instrument22 Star89)
	(calibration_target instrument22 Star107)
	(on_board instrument18 satellite6)
	(on_board instrument19 satellite6)
	(on_board instrument20 satellite6)
	(on_board instrument21 satellite6)
	(on_board instrument22 satellite6)
	(power_avail satellite6)
	(pointing satellite6 Star327)
	(supports instrument23 image7)
	(calibration_target instrument23 Star140)
	(calibration_target instrument23 Star106)
	(calibration_target instrument23 GroundStation177)
	(calibration_target instrument23 GroundStation45)
	(calibration_target instrument23 GroundStation164)
	(calibration_target instrument23 Star33)
	(calibration_target instrument23 Star180)
	(calibration_target instrument23 Star36)
	(calibration_target instrument23 GroundStation47)
	(calibration_target instrument23 GroundStation226)
	(calibration_target instrument23 GroundStation57)
	(calibration_target instrument23 Star7)
	(calibration_target instrument23 Star99)
	(calibration_target instrument23 GroundStation204)
	(calibration_target instrument23 Star12)
	(calibration_target instrument23 GroundStation42)
	(calibration_target instrument23 GroundStation28)
	(calibration_target instrument23 Star182)
	(calibration_target instrument23 GroundStation58)
	(calibration_target instrument23 Star8)
	(calibration_target instrument23 GroundStation146)
	(calibration_target instrument23 Star73)
	(calibration_target instrument23 Star13)
	(calibration_target instrument23 GroundStation221)
	(calibration_target instrument23 GroundStation178)
	(calibration_target instrument23 Star150)
	(calibration_target instrument23 Star119)
	(calibration_target instrument23 Star133)
	(calibration_target instrument23 Star187)
	(calibration_target instrument23 GroundStation27)
	(calibration_target instrument23 Star105)
	(calibration_target instrument23 Star157)
	(calibration_target instrument23 Star201)
	(on_board instrument23 satellite7)
	(power_avail satellite7)
	(pointing satellite7 GroundStation101)
	(supports instrument24 spectrograph1)
	(supports instrument24 infrared5)
	(supports instrument24 infrared3)
	(calibration_target instrument24 Star31)
	(calibration_target instrument24 GroundStation5)
	(calibration_target instrument24 GroundStation92)
	(calibration_target instrument24 GroundStation10)
	(calibration_target instrument24 GroundStation40)
	(calibration_target instrument24 Star8)
	(calibration_target instrument24 GroundStation163)
	(calibration_target instrument24 GroundStation225)
	(calibration_target instrument24 Star142)
	(calibration_target instrument24 GroundStation161)
	(calibration_target instrument24 GroundStation173)
	(calibration_target instrument24 GroundStation149)
	(calibration_target instrument24 Star37)
	(calibration_target instrument24 GroundStation226)
	(calibration_target instrument24 GroundStation188)
	(calibration_target instrument24 GroundStation132)
	(calibration_target instrument24 Star67)
	(calibration_target instrument24 GroundStation86)
	(calibration_target instrument24 Star187)
	(calibration_target instrument24 GroundStation82)
	(calibration_target instrument24 Star93)
	(calibration_target instrument24 GroundStation186)
	(calibration_target instrument24 Star120)
	(calibration_target instrument24 GroundStation102)
	(calibration_target instrument24 Star160)
	(calibration_target instrument24 Star224)
	(calibration_target instrument24 GroundStation47)
	(calibration_target instrument24 GroundStation117)
	(calibration_target instrument24 GroundStation125)
	(supports instrument25 spectrograph2)
	(supports instrument25 spectrograph6)
	(supports instrument25 infrared5)
	(calibration_target instrument25 GroundStation159)
	(calibration_target instrument25 Star210)
	(calibration_target instrument25 Star116)
	(calibration_target instrument25 Star80)
	(calibration_target instrument25 GroundStation125)
	(calibration_target instrument25 Star227)
	(calibration_target instrument25 GroundStation81)
	(calibration_target instrument25 Star198)
	(calibration_target instrument25 GroundStation145)
	(calibration_target instrument25 Star87)
	(calibration_target instrument25 GroundStation163)
	(calibration_target instrument25 Star12)
	(calibration_target instrument25 GroundStation138)
	(calibration_target instrument25 GroundStation57)
	(calibration_target instrument25 Star8)
	(calibration_target instrument25 Star66)
	(calibration_target instrument25 Star96)
	(calibration_target instrument25 GroundStation108)
	(supports instrument26 spectrograph1)
	(supports instrument26 spectrograph2)
	(calibration_target instrument26 Star93)
	(calibration_target instrument26 GroundStation188)
	(calibration_target instrument26 Star3)
	(calibration_target instrument26 Star195)
	(calibration_target instrument26 Star105)
	(calibration_target instrument26 Star199)
	(calibration_target instrument26 Star120)
	(calibration_target instrument26 GroundStation10)
	(calibration_target instrument26 GroundStation214)
	(calibration_target instrument26 Star106)
	(calibration_target instrument26 Star160)
	(calibration_target instrument26 Star141)
	(calibration_target instrument26 GroundStation143)
	(calibration_target instrument26 Star133)
	(calibration_target instrument26 Star66)
	(calibration_target instrument26 Star103)
	(calibration_target instrument26 Star61)
	(calibration_target instrument26 Star153)
	(calibration_target instrument26 GroundStation234)
	(calibration_target instrument26 Star89)
	(calibration_target instrument26 GroundStation145)
	(calibration_target instrument26 GroundStation25)
	(calibration_target instrument26 Star88)
	(calibration_target instrument26 GroundStation42)
	(calibration_target instrument26 Star217)
	(calibration_target instrument26 Star131)
	(calibration_target instrument26 Star60)
	(calibration_target instrument26 Star127)
	(calibration_target instrument26 Star35)
	(calibration_target instrument26 GroundStation64)
	(calibration_target instrument26 GroundStation126)
	(calibration_target instrument26 GroundStation154)
	(calibration_target instrument26 Star78)
	(calibration_target instrument26 GroundStation138)
	(calibration_target instrument26 Star201)
	(calibration_target instrument26 Star12)
	(calibration_target instrument26 Star0)
	(calibration_target instrument26 GroundStation171)
	(calibration_target instrument26 Star187)
	(calibration_target instrument26 Star84)
	(calibration_target instrument26 GroundStation63)
	(calibration_target instrument26 GroundStation190)
	(calibration_target instrument26 GroundStation146)
	(supports instrument27 infrared5)
	(calibration_target instrument27 Star116)
	(calibration_target instrument27 Star135)
	(calibration_target instrument27 Star68)
	(calibration_target instrument27 GroundStation77)
	(calibration_target instrument27 GroundStation216)
	(calibration_target instrument27 GroundStation165)
	(calibration_target instrument27 GroundStation51)
	(calibration_target instrument27 Star157)
	(calibration_target instrument27 Star85)
	(calibration_target instrument27 GroundStation173)
	(calibration_target instrument27 Star14)
	(calibration_target instrument27 GroundStation70)
	(calibration_target instrument27 Star78)
	(calibration_target instrument27 Star46)
	(calibration_target instrument27 Star114)
	(calibration_target instrument27 GroundStation5)
	(calibration_target instrument27 Star150)
	(calibration_target instrument27 GroundStation23)
	(calibration_target instrument27 Star54)
	(calibration_target instrument27 GroundStation143)
	(calibration_target instrument27 Star228)
	(calibration_target instrument27 Star128)
	(calibration_target instrument27 Star110)
	(calibration_target instrument27 Star87)
	(calibration_target instrument27 GroundStation41)
	(calibration_target instrument27 GroundStation102)
	(calibration_target instrument27 Star109)
	(calibration_target instrument27 GroundStation169)
	(calibration_target instrument27 GroundStation146)
	(supports instrument28 spectrograph6)
	(supports instrument28 spectrograph0)
	(supports instrument28 image7)
	(calibration_target instrument28 GroundStation219)
	(calibration_target instrument28 Star66)
	(calibration_target instrument28 GroundStation214)
	(calibration_target instrument28 GroundStation86)
	(calibration_target instrument28 GroundStation177)
	(calibration_target instrument28 Star201)
	(calibration_target instrument28 Star60)
	(calibration_target instrument28 Star119)
	(calibration_target instrument28 GroundStation76)
	(calibration_target instrument28 GroundStation124)
	(calibration_target instrument28 GroundStation50)
	(calibration_target instrument28 Star199)
	(calibration_target instrument28 Star222)
	(calibration_target instrument28 GroundStation5)
	(on_board instrument24 satellite8)
	(on_board instrument25 satellite8)
	(on_board instrument26 satellite8)
	(on_board instrument27 satellite8)
	(on_board instrument28 satellite8)
	(power_avail satellite8)
	(pointing satellite8 Star450)
	(supports instrument29 spectrograph2)
	(supports instrument29 infrared3)
	(calibration_target instrument29 GroundStation63)
	(calibration_target instrument29 GroundStation104)
	(calibration_target instrument29 GroundStation204)
	(calibration_target instrument29 Star7)
	(calibration_target instrument29 Star37)
	(supports instrument30 spectrograph0)
	(calibration_target instrument30 Star95)
	(calibration_target instrument30 GroundStation63)
	(calibration_target instrument30 GroundStation82)
	(calibration_target instrument30 GroundStation212)
	(calibration_target instrument30 Star127)
	(calibration_target instrument30 GroundStation69)
	(calibration_target instrument30 Star14)
	(calibration_target instrument30 GroundStation15)
	(calibration_target instrument30 GroundStation40)
	(calibration_target instrument30 Star96)
	(calibration_target instrument30 GroundStation49)
	(calibration_target instrument30 GroundStation117)
	(calibration_target instrument30 GroundStation55)
	(calibration_target instrument30 GroundStation149)
	(calibration_target instrument30 Star74)
	(calibration_target instrument30 Star13)
	(calibration_target instrument30 GroundStation145)
	(calibration_target instrument30 GroundStation48)
	(calibration_target instrument30 GroundStation56)
	(calibration_target instrument30 GroundStation5)
	(calibration_target instrument30 GroundStation138)
	(calibration_target instrument30 Star131)
	(calibration_target instrument30 Star182)
	(calibration_target instrument30 Star90)
	(calibration_target instrument30 Star202)
	(calibration_target instrument30 GroundStation174)
	(calibration_target instrument30 GroundStation230)
	(calibration_target instrument30 GroundStation28)
	(calibration_target instrument30 GroundStation27)
	(calibration_target instrument30 GroundStation98)
	(calibration_target instrument30 Star148)
	(calibration_target instrument30 GroundStation102)
	(calibration_target instrument30 Star9)
	(calibration_target instrument30 GroundStation161)
	(calibration_target instrument30 GroundStation101)
	(calibration_target instrument30 GroundStation146)
	(calibration_target instrument30 GroundStation170)
	(calibration_target instrument30 GroundStation104)
	(calibration_target instrument30 Star231)
	(on_board instrument29 satellite9)
	(on_board instrument30 satellite9)
	(power_avail satellite9)
	(pointing satellite9 Planet268)
	(supports instrument31 infrared3)
	(supports instrument31 infrared5)
	(calibration_target instrument31 Star93)
	(calibration_target instrument31 GroundStation132)
	(calibration_target instrument31 GroundStation204)
	(calibration_target instrument31 Star141)
	(supports instrument32 spectrograph0)
	(supports instrument32 spectrograph1)
	(calibration_target instrument32 GroundStation174)
	(calibration_target instrument32 Star7)
	(calibration_target instrument32 GroundStation42)
	(calibration_target instrument32 GroundStation209)
	(calibration_target instrument32 GroundStation22)
	(calibration_target instrument32 GroundStation48)
	(calibration_target instrument32 Star66)
	(calibration_target instrument32 GroundStation86)
	(calibration_target instrument32 Star14)
	(calibration_target instrument32 Star231)
	(calibration_target instrument32 Star182)
	(calibration_target instrument32 Star120)
	(calibration_target instrument32 GroundStation117)
	(calibration_target instrument32 Star11)
	(calibration_target instrument32 Star31)
	(calibration_target instrument32 Star156)
	(calibration_target instrument32 GroundStation104)
	(calibration_target instrument32 GroundStation56)
	(calibration_target instrument32 GroundStation39)
	(calibration_target instrument32 GroundStation92)
	(calibration_target instrument32 GroundStation115)
	(supports instrument33 infrared3)
	(supports instrument33 thermograph4)
	(calibration_target instrument33 GroundStation115)
	(calibration_target instrument33 GroundStation63)
	(calibration_target instrument33 GroundStation48)
	(calibration_target instrument33 Star83)
	(calibration_target instrument33 Star73)
	(supports instrument34 image7)
	(supports instrument34 infrared5)
	(supports instrument34 thermograph4)
	(calibration_target instrument34 GroundStation92)
	(calibration_target instrument34 Star87)
	(calibration_target instrument34 GroundStation79)
	(calibration_target instrument34 GroundStation22)
	(calibration_target instrument34 GroundStation216)
	(calibration_target instrument34 Star88)
	(calibration_target instrument34 Star31)
	(calibration_target instrument34 Star61)
	(calibration_target instrument34 Star103)
	(calibration_target instrument34 GroundStation149)
	(calibration_target instrument34 Star107)
	(calibration_target instrument34 Star80)
	(calibration_target instrument34 GroundStation164)
	(calibration_target instrument34 GroundStation56)
	(calibration_target instrument34 Star217)
	(calibration_target instrument34 Star198)
	(calibration_target instrument34 GroundStation138)
	(calibration_target instrument34 Star224)
	(calibration_target instrument34 Star142)
	(calibration_target instrument34 GroundStation196)
	(calibration_target instrument34 GroundStation5)
	(supports instrument35 spectrograph6)
	(calibration_target instrument35 GroundStation51)
	(calibration_target instrument35 GroundStation188)
	(calibration_target instrument35 Star131)
	(calibration_target instrument35 GroundStation185)
	(calibration_target instrument35 Star155)
	(calibration_target instrument35 GroundStation82)
	(calibration_target instrument35 GroundStation174)
	(calibration_target instrument35 Star141)
	(calibration_target instrument35 GroundStation113)
	(calibration_target instrument35 GroundStation121)
	(calibration_target instrument35 Star119)
	(calibration_target instrument35 Star95)
	(calibration_target instrument35 Star189)
	(calibration_target instrument35 Star109)
	(calibration_target instrument35 Star11)
	(calibration_target instrument35 Star194)
	(calibration_target instrument35 GroundStation161)
	(calibration_target instrument35 Star13)
	(calibration_target instrument35 Star201)
	(calibration_target instrument35 GroundStation207)
	(calibration_target instrument35 Star135)
	(calibration_target instrument35 GroundStation86)
	(calibration_target instrument35 Star176)
	(calibration_target instrument35 GroundStation159)
	(calibration_target instrument35 GroundStation23)
	(calibration_target instrument35 GroundStation15)
	(calibration_target instrument35 Star122)
	(calibration_target instrument35 Star46)
	(calibration_target instrument35 GroundStation209)
	(calibration_target instrument35 GroundStation26)
	(calibration_target instrument35 Star133)
	(calibration_target instrument35 GroundStation171)
	(calibration_target instrument35 GroundStation27)
	(calibration_target instrument35 Star44)
	(calibration_target instrument35 Star106)
	(calibration_target instrument35 GroundStation28)
	(calibration_target instrument35 Star139)
	(calibration_target instrument35 GroundStation226)
	(calibration_target instrument35 Star105)
	(calibration_target instrument35 Star2)
	(calibration_target instrument35 Star68)
	(calibration_target instrument35 Star203)
	(calibration_target instrument35 Star152)
	(calibration_target instrument35 Star31)
	(calibration_target instrument35 Star96)
	(calibration_target instrument35 Star198)
	(calibration_target instrument35 Star192)
	(calibration_target instrument35 Star0)
	(calibration_target instrument35 GroundStation214)
	(calibration_target instrument35 Star14)
	(calibration_target instrument35 GroundStation76)
	(calibration_target instrument35 Star111)
	(calibration_target instrument35 GroundStation146)
	(calibration_target instrument35 GroundStation48)
	(calibration_target instrument35 GroundStation212)
	(calibration_target instrument35 Star38)
	(calibration_target instrument35 Star222)
	(calibration_target instrument35 GroundStation138)
	(calibration_target instrument35 Star142)
	(calibration_target instrument35 Star35)
	(calibration_target instrument35 GroundStation220)
	(calibration_target instrument35 GroundStation108)
	(calibration_target instrument35 GroundStation172)
	(calibration_target instrument35 Star120)
	(calibration_target instrument35 GroundStation102)
	(calibration_target instrument35 Star160)
	(calibration_target instrument35 GroundStation41)
	(calibration_target instrument35 Star93)
	(calibration_target instrument35 GroundStation79)
	(calibration_target instrument35 Star34)
	(calibration_target instrument35 GroundStation30)
	(calibration_target instrument35 Star114)
	(calibration_target instrument35 GroundStation206)
	(on_board instrument31 satellite10)
	(on_board instrument32 satellite10)
	(on_board instrument33 satellite10)
	(on_board instrument34 satellite10)
	(on_board instrument35 satellite10)
	(power_avail satellite10)
	(pointing satellite10 GroundStation172)
	(supports instrument36 spectrograph1)
	(supports instrument36 spectrograph6)
	(supports instrument36 spectrograph0)
	(calibration_target instrument36 GroundStation42)
	(calibration_target instrument36 GroundStation19)
	(calibration_target instrument36 GroundStation47)
	(calibration_target instrument36 Star151)
	(calibration_target instrument36 GroundStation92)
	(calibration_target instrument36 GroundStation58)
	(calibration_target instrument36 Star195)
	(calibration_target instrument36 GroundStation112)
	(calibration_target instrument36 Star53)
	(calibration_target instrument36 GroundStation220)
	(calibration_target instrument36 GroundStation64)
	(calibration_target instrument36 Star46)
	(calibration_target instrument36 GroundStation51)
	(calibration_target instrument36 GroundStation81)
	(calibration_target instrument36 GroundStation165)
	(calibration_target instrument36 Star198)
	(calibration_target instrument36 Star134)
	(calibration_target instrument36 Star194)
	(calibration_target instrument36 Star60)
	(calibration_target instrument36 GroundStation123)
	(calibration_target instrument36 Star140)
	(calibration_target instrument36 Star217)
	(calibration_target instrument36 Star184)
	(calibration_target instrument36 Star153)
	(calibration_target instrument36 Star203)
	(calibration_target instrument36 GroundStation221)
	(calibration_target instrument36 Star166)
	(calibration_target instrument36 Star59)
	(calibration_target instrument36 GroundStation65)
	(calibration_target instrument36 GroundStation219)
	(calibration_target instrument36 GroundStation136)
	(calibration_target instrument36 GroundStation214)
	(calibration_target instrument36 GroundStation30)
	(calibration_target instrument36 Star210)
	(calibration_target instrument36 GroundStation188)
	(calibration_target instrument36 Star3)
	(calibration_target instrument36 Star66)
	(calibration_target instrument36 Star228)
	(calibration_target instrument36 GroundStation143)
	(calibration_target instrument36 GroundStation22)
	(calibration_target instrument36 Star200)
	(calibration_target instrument36 GroundStation212)
	(calibration_target instrument36 GroundStation204)
	(calibration_target instrument36 Star52)
	(calibration_target instrument36 Star94)
	(calibration_target instrument36 GroundStation185)
	(calibration_target instrument36 Star201)
	(calibration_target instrument36 Star33)
	(calibration_target instrument36 GroundStation207)
	(calibration_target instrument36 Star150)
	(calibration_target instrument36 Star157)
	(calibration_target instrument36 Star129)
	(calibration_target instrument36 GroundStation167)
	(calibration_target instrument36 Star148)
	(calibration_target instrument36 Star83)
	(calibration_target instrument36 GroundStation28)
	(calibration_target instrument36 Star35)
	(calibration_target instrument36 Star142)
	(calibration_target instrument36 Star122)
	(calibration_target instrument36 Star13)
	(calibration_target instrument36 Star223)
	(calibration_target instrument36 Star176)
	(calibration_target instrument36 Star93)
	(calibration_target instrument36 GroundStation26)
	(calibration_target instrument36 GroundStation18)
	(calibration_target instrument36 GroundStation79)
	(calibration_target instrument36 Star99)
	(calibration_target instrument36 Star96)
	(calibration_target instrument36 Star211)
	(calibration_target instrument36 Star80)
	(calibration_target instrument36 GroundStation170)
	(calibration_target instrument36 Star144)
	(calibration_target instrument36 Star78)
	(calibration_target instrument36 Star24)
	(calibration_target instrument36 GroundStation154)
	(calibration_target instrument36 GroundStation230)
	(calibration_target instrument36 GroundStation235)
	(supports instrument37 thermograph4)
	(supports instrument37 spectrograph2)
	(supports instrument37 spectrograph6)
	(calibration_target instrument37 GroundStation115)
	(calibration_target instrument37 GroundStation72)
	(calibration_target instrument37 GroundStation21)
	(calibration_target instrument37 GroundStation57)
	(calibration_target instrument37 GroundStation178)
	(calibration_target instrument37 Star152)
	(calibration_target instrument37 Star59)
	(calibration_target instrument37 Star67)
	(calibration_target instrument37 Star127)
	(calibration_target instrument37 GroundStation64)
	(calibration_target instrument37 Star4)
	(calibration_target instrument37 Star210)
	(calibration_target instrument37 GroundStation45)
	(calibration_target instrument37 GroundStation136)
	(calibration_target instrument37 GroundStation79)
	(calibration_target instrument37 GroundStation18)
	(calibration_target instrument37 Star119)
	(calibration_target instrument37 Star189)
	(calibration_target instrument37 GroundStation173)
	(calibration_target instrument37 GroundStation197)
	(calibration_target instrument37 Star6)
	(calibration_target instrument37 GroundStation125)
	(calibration_target instrument37 Star153)
	(calibration_target instrument37 Star95)
	(calibration_target instrument37 Star94)
	(calibration_target instrument37 GroundStation76)
	(calibration_target instrument37 GroundStation102)
	(calibration_target instrument37 GroundStation29)
	(calibration_target instrument37 GroundStation121)
	(calibration_target instrument37 GroundStation234)
	(calibration_target instrument37 Star151)
	(calibration_target instrument37 Star215)
	(calibration_target instrument37 Star85)
	(calibration_target instrument37 GroundStation62)
	(calibration_target instrument37 Star128)
	(calibration_target instrument37 GroundStation149)
	(calibration_target instrument37 GroundStation235)
	(calibration_target instrument37 Star229)
	(calibration_target instrument37 GroundStation23)
	(calibration_target instrument37 Star91)
	(calibration_target instrument37 GroundStation71)
	(calibration_target instrument37 Star96)
	(calibration_target instrument37 Star166)
	(calibration_target instrument37 GroundStation77)
	(calibration_target instrument37 GroundStation27)
	(calibration_target instrument37 GroundStation159)
	(calibration_target instrument37 GroundStation58)
	(calibration_target instrument37 Star89)
	(calibration_target instrument37 Star54)
	(calibration_target instrument37 Star116)
	(calibration_target instrument37 GroundStation63)
	(calibration_target instrument37 Star7)
	(calibration_target instrument37 Star87)
	(calibration_target instrument37 Star37)
	(calibration_target instrument37 Star147)
	(calibration_target instrument37 Star199)
	(calibration_target instrument37 GroundStation185)
	(calibration_target instrument37 Star38)
	(calibration_target instrument37 Star103)
	(calibration_target instrument37 Star34)
	(calibration_target instrument37 Star223)
	(calibration_target instrument37 GroundStation196)
	(calibration_target instrument37 GroundStation48)
	(calibration_target instrument37 Star195)
	(calibration_target instrument37 Star31)
	(on_board instrument36 satellite11)
	(on_board instrument37 satellite11)
	(power_avail satellite11)
	(pointing satellite11 Star319)
	(supports instrument38 infrared3)
	(supports instrument38 spectrograph2)
	(supports instrument38 infrared5)
	(calibration_target instrument38 Star54)
	(calibration_target instrument38 Star187)
	(calibration_target instrument38 GroundStation50)
	(calibration_target instrument38 GroundStation22)
	(calibration_target instrument38 Star109)
	(calibration_target instrument38 Star84)
	(calibration_target instrument38 GroundStation82)
	(calibration_target instrument38 GroundStation123)
	(calibration_target instrument38 GroundStation76)
	(calibration_target instrument38 Star147)
	(calibration_target instrument38 GroundStation49)
	(calibration_target instrument38 Star130)
	(calibration_target instrument38 GroundStation136)
	(calibration_target instrument38 Star60)
	(calibration_target instrument38 GroundStation63)
	(calibration_target instrument38 GroundStation154)
	(calibration_target instrument38 Star184)
	(calibration_target instrument38 GroundStation206)
	(calibration_target instrument38 Star148)
	(calibration_target instrument38 GroundStation118)
	(calibration_target instrument38 GroundStation220)
	(calibration_target instrument38 Star111)
	(calibration_target instrument38 GroundStation185)
	(calibration_target instrument38 GroundStation143)
	(calibration_target instrument38 GroundStation178)
	(calibration_target instrument38 Star210)
	(calibration_target instrument38 Star88)
	(calibration_target instrument38 GroundStation232)
	(calibration_target instrument38 Star34)
	(calibration_target instrument38 GroundStation216)
	(calibration_target instrument38 GroundStation212)
	(calibration_target instrument38 Star35)
	(calibration_target instrument38 Star131)
	(calibration_target instrument38 Star89)
	(calibration_target instrument38 Star8)
	(calibration_target instrument38 Star6)
	(calibration_target instrument38 GroundStation18)
	(calibration_target instrument38 Star201)
	(calibration_target instrument38 GroundStation167)
	(calibration_target instrument38 GroundStation71)
	(on_board instrument38 satellite12)
	(power_avail satellite12)
	(pointing satellite12 Star68)
)
(:goal (and
	(pointing satellite3 Star263)
	(pointing satellite4 Planet436)
	(pointing satellite10 GroundStation143)
	(pointing satellite11 GroundStation23)
	(have_image Phenomenon236 spectrograph6)
	(have_image Phenomenon236 spectrograph1)
	(have_image Star237 spectrograph6)
	(have_image Star237 thermograph4)
	(have_image Phenomenon238 spectrograph6)
	(have_image Phenomenon238 thermograph4)
	(have_image Phenomenon239 infrared3)
	(have_image Star240 infrared5)
	(have_image Planet241 spectrograph2)
	(have_image Planet241 thermograph4)
	(have_image Star242 spectrograph0)
	(have_image Star243 infrared3)
	(have_image Star243 infrared5)
	(have_image Planet244 infrared5)
	(have_image Phenomenon245 infrared3)
	(have_image Planet247 thermograph4)
	(have_image Planet247 spectrograph1)
	(have_image Phenomenon248 spectrograph6)
	(have_image Phenomenon248 image7)
	(have_image Phenomenon250 infrared5)
	(have_image Phenomenon251 spectrograph6)
	(have_image Phenomenon251 infrared5)
	(have_image Planet252 spectrograph0)
	(have_image Planet252 image7)
	(have_image Planet253 thermograph4)
	(have_image Planet253 spectrograph1)
	(have_image Star254 image7)
	(have_image Star254 spectrograph2)
	(have_image Star255 infrared5)
	(have_image Star256 infrared5)
	(have_image Planet257 infrared5)
	(have_image Planet257 spectrograph1)
	(have_image Phenomenon258 spectrograph0)
	(have_image Phenomenon258 infrared3)
	(have_image Phenomenon259 image7)
	(have_image Phenomenon260 infrared3)
	(have_image Phenomenon260 spectrograph6)
	(have_image Star261 image7)
	(have_image Star261 infrared3)
	(have_image Planet262 thermograph4)
	(have_image Star263 infrared5)
	(have_image Phenomenon264 infrared5)
	(have_image Phenomenon264 image7)
	(have_image Planet265 thermograph4)
	(have_image Planet265 spectrograph1)
	(have_image Planet266 spectrograph0)
	(have_image Planet266 infrared3)
	(have_image Planet268 spectrograph1)
	(have_image Planet268 spectrograph2)
	(have_image Phenomenon269 infrared3)
	(have_image Phenomenon270 infrared3)
	(have_image Planet271 spectrograph6)
	(have_image Star272 spectrograph6)
	(have_image Planet273 image7)
	(have_image Star274 spectrograph0)
	(have_image Star274 image7)
	(have_image Phenomenon275 infrared5)
	(have_image Phenomenon275 spectrograph1)
	(have_image Star276 infrared3)
	(have_image Phenomenon277 infrared3)
	(have_image Phenomenon277 spectrograph0)
	(have_image Star278 spectrograph0)
	(have_image Star278 spectrograph1)
	(have_image Star279 image7)
	(have_image Star279 spectrograph2)
	(have_image Phenomenon281 spectrograph1)
	(have_image Phenomenon281 infrared5)
	(have_image Planet283 spectrograph2)
	(have_image Star284 spectrograph6)
	(have_image Star284 spectrograph0)
	(have_image Planet285 spectrograph0)
	(have_image Planet285 image7)
	(have_image Planet286 spectrograph1)
	(have_image Star287 spectrograph6)
	(have_image Star287 spectrograph0)
	(have_image Planet288 thermograph4)
	(have_image Planet290 infrared3)
	(have_image Planet290 image7)
	(have_image Phenomenon291 thermograph4)
	(have_image Phenomenon291 spectrograph1)
	(have_image Star292 spectrograph6)
	(have_image Planet293 infrared3)
	(have_image Planet293 image7)
	(have_image Phenomenon294 infrared3)
	(have_image Star295 spectrograph2)
	(have_image Star295 image7)
	(have_image Phenomenon296 thermograph4)
	(have_image Phenomenon296 spectrograph2)
	(have_image Star297 thermograph4)
	(have_image Phenomenon298 spectrograph6)
	(have_image Planet299 infrared5)
	(have_image Planet300 spectrograph1)
	(have_image Planet300 infrared3)
	(have_image Planet301 spectrograph1)
	(have_image Planet301 spectrograph0)
	(have_image Phenomenon302 spectrograph0)
	(have_image Star303 spectrograph6)
	(have_image Phenomenon304 spectrograph1)
	(have_image Star305 spectrograph0)
	(have_image Phenomenon306 spectrograph6)
	(have_image Phenomenon306 thermograph4)
	(have_image Phenomenon307 spectrograph2)
	(have_image Phenomenon307 image7)
	(have_image Phenomenon308 image7)
	(have_image Phenomenon308 spectrograph2)
	(have_image Phenomenon309 spectrograph0)
	(have_image Phenomenon310 spectrograph6)
	(have_image Phenomenon310 infrared5)
	(have_image Star311 spectrograph0)
	(have_image Star311 infrared3)
	(have_image Phenomenon312 spectrograph6)
	(have_image Phenomenon313 infrared3)
	(have_image Phenomenon313 image7)
	(have_image Phenomenon315 spectrograph2)
	(have_image Phenomenon315 spectrograph1)
	(have_image Phenomenon316 infrared3)
	(have_image Star317 thermograph4)
	(have_image Star317 spectrograph6)
	(have_image Planet318 spectrograph0)
	(have_image Star319 spectrograph0)
	(have_image Star319 infrared3)
	(have_image Star320 spectrograph2)
	(have_image Star320 infrared3)
	(have_image Star321 infrared3)
	(have_image Star321 spectrograph1)
	(have_image Planet322 spectrograph6)
	(have_image Phenomenon324 infrared3)
	(have_image Phenomenon324 spectrograph6)
	(have_image Planet325 spectrograph1)
	(have_image Planet325 thermograph4)
	(have_image Planet326 image7)
	(have_image Star327 spectrograph1)
	(have_image Planet328 image7)
	(have_image Planet328 spectrograph2)
	(have_image Phenomenon330 spectrograph1)
	(have_image Planet333 spectrograph2)
	(have_image Phenomenon334 spectrograph6)
	(have_image Star336 spectrograph6)
	(have_image Star336 image7)
	(have_image Star337 spectrograph2)
	(have_image Phenomenon338 spectrograph1)
	(have_image Planet339 image7)
	(have_image Planet340 infrared5)
	(have_image Star341 spectrograph1)
	(have_image Star341 infrared3)
	(have_image Star343 spectrograph2)
	(have_image Star343 spectrograph0)
	(have_image Phenomenon344 spectrograph1)
	(have_image Planet345 spectrograph6)
	(have_image Planet346 image7)
	(have_image Planet346 infrared5)
	(have_image Phenomenon347 spectrograph6)
	(have_image Star348 thermograph4)
	(have_image Star348 infrared5)
	(have_image Star349 spectrograph1)
	(have_image Phenomenon350 thermograph4)
	(have_image Phenomenon350 infrared5)
	(have_image Planet351 spectrograph6)
	(have_image Phenomenon353 spectrograph2)
	(have_image Planet354 spectrograph0)
	(have_image Planet354 spectrograph6)
	(have_image Planet355 infrared3)
	(have_image Star356 spectrograph1)
	(have_image Star358 spectrograph2)
	(have_image Phenomenon359 infrared5)
	(have_image Planet360 spectrograph1)
	(have_image Planet360 spectrograph2)
	(have_image Star361 image7)
	(have_image Star361 infrared5)
	(have_image Phenomenon362 spectrograph0)
	(have_image Phenomenon362 spectrograph2)
	(have_image Phenomenon363 spectrograph0)
	(have_image Star364 infrared5)
	(have_image Star364 image7)
	(have_image Star366 spectrograph6)
	(have_image Planet367 thermograph4)
	(have_image Planet368 image7)
	(have_image Star369 spectrograph0)
	(have_image Star369 infrared5)
	(have_image Star370 image7)
	(have_image Star370 spectrograph6)
	(have_image Phenomenon371 thermograph4)
	(have_image Phenomenon372 infrared5)
	(have_image Phenomenon372 spectrograph0)
	(have_image Phenomenon373 infrared5)
	(have_image Phenomenon373 spectrograph1)
	(have_image Planet374 spectrograph2)
	(have_image Star375 spectrograph6)
	(have_image Phenomenon376 spectrograph0)
	(have_image Phenomenon376 spectrograph1)
	(have_image Phenomenon377 infrared3)
	(have_image Phenomenon377 spectrograph6)
	(have_image Star378 spectrograph0)
	(have_image Star378 thermograph4)
	(have_image Phenomenon379 thermograph4)
	(have_image Phenomenon380 image7)
	(have_image Phenomenon380 spectrograph2)
	(have_image Planet381 spectrograph6)
	(have_image Planet382 spectrograph1)
	(have_image Planet382 spectrograph0)
	(have_image Phenomenon383 spectrograph6)
	(have_image Star384 image7)
	(have_image Phenomenon385 thermograph4)
	(have_image Star386 spectrograph0)
	(have_image Star386 infrared3)
	(have_image Phenomenon387 thermograph4)
	(have_image Phenomenon388 spectrograph1)
	(have_image Phenomenon388 spectrograph0)
	(have_image Phenomenon389 infrared3)
	(have_image Planet391 image7)
	(have_image Planet391 spectrograph2)
	(have_image Star392 spectrograph6)
	(have_image Star392 image7)
	(have_image Planet393 infrared3)
	(have_image Planet393 thermograph4)
	(have_image Planet394 spectrograph6)
	(have_image Planet394 spectrograph2)
	(have_image Phenomenon395 infrared3)
	(have_image Phenomenon395 spectrograph6)
	(have_image Star396 infrared3)
	(have_image Star396 spectrograph0)
	(have_image Star397 spectrograph1)
	(have_image Star397 spectrograph0)
	(have_image Planet398 infrared5)
	(have_image Planet398 spectrograph0)
	(have_image Planet399 spectrograph6)
	(have_image Planet399 spectrograph0)
	(have_image Planet400 spectrograph0)
	(have_image Star401 spectrograph2)
	(have_image Star401 thermograph4)
	(have_image Phenomenon402 spectrograph2)
	(have_image Star403 spectrograph0)
	(have_image Star404 spectrograph2)
	(have_image Star404 infrared5)
	(have_image Phenomenon405 spectrograph2)
	(have_image Planet406 image7)
	(have_image Planet406 infrared5)
	(have_image Star407 image7)
	(have_image Star408 spectrograph0)
	(have_image Planet409 spectrograph1)
	(have_image Planet409 image7)
	(have_image Star410 spectrograph1)
	(have_image Star410 thermograph4)
	(have_image Planet412 infrared3)
	(have_image Star413 infrared3)
	(have_image Star413 spectrograph1)
	(have_image Star414 infrared5)
	(have_image Star415 spectrograph1)
	(have_image Star415 infrared5)
	(have_image Star416 image7)
	(have_image Star416 spectrograph1)
	(have_image Planet417 infrared3)
	(have_image Planet418 spectrograph0)
	(have_image Star419 spectrograph0)
	(have_image Star419 infrared3)
	(have_image Star420 infrared3)
	(have_image Star420 spectrograph2)
	(have_image Star421 infrared5)
	(have_image Star421 image7)
	(have_image Phenomenon422 infrared5)
	(have_image Phenomenon423 spectrograph1)
	(have_image Planet424 infrared5)
	(have_image Planet424 thermograph4)
	(have_image Star425 thermograph4)
	(have_image Star426 spectrograph2)
	(have_image Star426 spectrograph6)
	(have_image Phenomenon428 spectrograph0)
	(have_image Phenomenon428 image7)
	(have_image Phenomenon429 infrared3)
	(have_image Phenomenon429 image7)
	(have_image Star430 image7)
	(have_image Star430 infrared3)
	(have_image Phenomenon431 image7)
	(have_image Phenomenon432 spectrograph1)
	(have_image Planet433 spectrograph0)
	(have_image Star434 spectrograph6)
	(have_image Planet436 spectrograph0)
	(have_image Planet436 infrared3)
	(have_image Star437 spectrograph6)
	(have_image Star437 infrared5)
	(have_image Planet438 spectrograph2)
	(have_image Planet438 infrared3)
	(have_image Planet439 thermograph4)
	(have_image Phenomenon440 image7)
	(have_image Planet441 spectrograph6)
	(have_image Star442 spectrograph0)
	(have_image Star443 spectrograph6)
	(have_image Star443 image7)
	(have_image Phenomenon444 spectrograph2)
	(have_image Phenomenon444 spectrograph0)
	(have_image Star445 spectrograph0)
	(have_image Phenomenon446 thermograph4)
	(have_image Phenomenon446 infrared3)
	(have_image Phenomenon447 image7)
	(have_image Phenomenon447 infrared3)
	(have_image Planet448 infrared3)
	(have_image Phenomenon449 image7)
	(have_image Planet452 spectrograph0)
	(have_image Planet452 image7)
	(have_image Star453 spectrograph1)
	(have_image Planet454 spectrograph1)
	(have_image Planet454 image7)
	(have_image Star455 thermograph4)
	(have_image Phenomenon456 spectrograph2)
	(have_image Star457 spectrograph0)
	(have_image Star457 spectrograph6)
	(have_image Star458 thermograph4)
	(have_image Star458 image7)
	(have_image Star459 spectrograph2)
	(have_image Star459 spectrograph6)
	(have_image Star460 infrared3)
	(have_image Star461 image7)
	(have_image Phenomenon462 infrared3)
	(have_image Phenomenon462 spectrograph6)
	(have_image Planet463 spectrograph2)
	(have_image Phenomenon464 image7)
	(have_image Planet465 image7)
	(have_image Planet465 infrared3)
	(have_image Planet466 spectrograph1)
	(have_image Phenomenon467 image7)
	(have_image Planet468 spectrograph0)
	(have_image Planet469 spectrograph1)
	(have_image Planet470 spectrograph2)
	(have_image Planet470 infrared3)
	(have_image Star471 spectrograph6)
	(have_image Star471 spectrograph1)
))

)
